### ISSUE TITLE
GE try-it truncating URL

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#1021]
@georgend encountered this issue

**Describe the bug**
Try-it experience is truncating URL resulting in an unexpected filter form which comes back as a 400.

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#example-2-get-a-user-account-using-a-sign-in-name
2. Click on try-it
3. Run the sample
4. See error in the response

I observe the following URL emitted in try-it
`GET /svc?url=https%3A%2F%2Fgraph.microsoft.com%2Fv1.0%2Fusers%3F%24select%3DdisplayName%2Cid%26%24filter%3Didentities%2Fany(c%3Ac%2FissuerAssignedId`

I observe the following URL emitted in GE
`GET /svc?url=https%3A%2F%2Fgraph.microsoft.com%2Fv1.0%2Fusers%3F%24select%3DdisplayName%2Cid%26%24filter%3Didentities%2Fany(c%3Ac%2FissuerAssignedId%20eq%20%27j.smith%40yahoo.com%27%20and%20c%2Fissuer%20eq%20%27contoso.onmicrosoft.com%27)`

**Expected behavior**
It should just work. Take the same query and run in full GE and it will work. I also expect to see the error result in the response pane.

**Screenshots**
![image](https://user-images.githubusercontent.com/8527305/125502013-22de92a4-4627-4b25-99ba-44d335afc7b5.png)

**Desktop (please complete the following information):**
 - Browser: Edge

 
[AB#10203](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10203)

**Comment by thewahome** [comment]
This has been escalated to the docs team

**Comment by FaithOmbongi** [comment]
Hi @thewahome , we're still seeing this issue in the docs. Kindly confirm.

**Comment by thewahome** [comment]
Hello @FaithOmbongi this should be in the next release
