### ISSUE TITLE
Query with expanding manager does not return manager itself

### ISSUE THREAD

**Issue by sven5** [microsoftgraph/microsoft-graph-explorer-v4#1029]
I'm not sure if this is a bug with Graph explorer or MS Graph API itself.

**Describe the bug**
When querying users with `$expand=manager` the manager's user object is not returned.

**To Reproduce**
1. Query `https://graph.microsoft.com/v1.0/users?$select=id&$expand=manager($levels=1;$select=id,displayName)`
2. Result is:
```
{
            "@odata.id": "https://graph.microsoft.com/v2/d9e30361-69c3-4740-b391-c56653a0aabf/directoryObjects/11122233-5b47-43c2-8261-e67b9ef5f835/Microsoft.DirectoryServices.User",
            "id": "11122233-5b47-43c2-8261-e67b9ef5f835",
            "manager": {
                "@odata.type": "#microsoft.graph.user",
                "@odata.id": "https://graph.microsoft.com/v2/d9e30361-69c3-4740-b391-c56653a0aabf/directoryObjects/33344455-59a8-47c7-8a28-ba8c8cbb65c6/Microsoft.DirectoryServices.User",
                "id": "33344455-59a8-47c7-8a28-ba8c8cbb65c6",
                "displayName": "manager"
            }
        },
```

the manager is returned below the user. However, manager object itself is not returned as user.

**Expected behavior**
I expect that the manager's user object is also in the result list.
Example:

```
{
            "@odata.id": "https://graph.microsoft.com/v2/d9e30361-69c3-4740-b391-c56653a0aabf/directoryObjects/11122233-5b47-43c2-8261-e67b9ef5f835/Microsoft.DirectoryServices.User",
            "id": "11122233-5b47-43c2-8261-e67b9ef5f835",
            "manager": {
                "@odata.type": "#microsoft.graph.user",
                "@odata.id": "https://graph.microsoft.com/v2/d9e30361-69c3-4740-b391-c56653a0aabf/directoryObjects/33344455-59a8-47c7-8a28-ba8c8cbb65c6/Microsoft.DirectoryServices.User",
                "id": "33344455-59a8-47c7-8a28-ba8c8cbb65c6",
                "displayName": "manager"
            }
        },
        {
            "@odata.id": "https://graph.microsoft.com/v2/d9e30361-69c3-4740-b391-c56653a0aabf/directoryObjects/33344455-59a8-47c7-8a28-ba8c8cbb65c6/Microsoft.DirectoryServices.User",
            "id": "33344455-59a8-47c7-8a28-ba8c8cbb65c6"
        },
```
 
[AB#10228](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10228)

**Comment by ElinorW** [comment]
Hi @sven5,
I believe the manager is also returned as a user.

Running this query `https://graph.microsoft.com/v1.0/users?$select=id,displayName&$expand=manager($levels=1;$select=id,displayName)`
**I have added the display name for explanation purposes**

Returns an object where users whose id, display name and level 1 manager's id and display name are listed
![image](https://user-images.githubusercontent.com/18407044/125788878-06b4ac52-ef98-4ddb-b9bd-b55c9195f27f.png)

From the example image I have shared, the user 'Debra Berger' has a manager named 'Diego Siciliani'
And we can see the user object of 'Diego Siciliani' also exists in the results. 

Is this what you meant?

**Comment by sven5** [comment]
Hi @ElinorW 

Thanks. Correct, this is what I meant. 
However, I'm running the query against an AAD B2C directory. Perhaps there is an issue or it's not supported?

**Comment by Licantrop0** [comment]
Hi @sven5, expanding managers' chain is part of the [Advanced Query Capabilities](https://docs.microsoft.com/en-us/graph/aad-advanced-queries), and unfortunately is currently not supported on B2C tenants.

**Comment by thewahome** [comment]
Thanks @Licantrop0 for adding this detail. Closing this
