### ISSUE TITLE
Permissions panel fails to load

### ISSUE THREAD

**Issue by OrangeDog** [microsoftgraph/microsoft-graph-explorer-v4#1034]
**Describe the bug**
Trying to load the permissions tab hangs for a while, then fails with 500 Internal Server Error, which is then blocked by CORS. The "open the permissions panel" link (https://graphexplorerapi.azurewebsites.net/permissions) also hangs and then fails in the same way.

[HAR log](https://gist.github.com/OrangeDog/68d5622f206ccc4fdaef1047c0b0b1c6)

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Log in with MS account (@cam.ac.uk)
3. Click on 'Modify permissions (preview)'
4. Wait 2+ minutes
5. Click on 'open the permissions panel'
6. Wait 2+ minutes

**Expected behavior**
Content should load correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/675056/126359640-8fe09705-2da8-456a-9f79-d6923b8668a3.png)

![image](https://user-images.githubusercontent.com/675056/126361386-6cf8f2d3-5fbf-4d7f-b936-c70c699b416c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 20H2 (OS Build 19042.1110)
 - Browser Firefox
 - Version 89.0.2
 
[AB#10304](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10304)

**Comment by OrangeDog** [comment]
The issue seems to have been resolved now.

**Comment by ElinorW** [comment]
Closing this as issue is resolved.
