### ISSUE TITLE
Seeing message about signed in to a sample account while I'm being auto signed in

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#1036]
When GE is loaded it is automatically loading the message below.  However sign in is being performed so there is no action for me to take.  I should only see this message if it is fully determined that I am not signed in or transitioning to being signed in.

_You are currently using a sample account. Sign in to access your own data._ 
[AB#10399](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10399)

**Comment by adhiambovivian** [comment]
Covered by header work #1656
