### ISSUE TITLE
Graph Explorer not returning OneDrive root/Children data

### ISSUE THREAD

**Issue by lisataka-uw** [microsoftgraph/microsoft-graph-explorer-v4#1038]
**Describe the bug**
I am attempting to read OneDrive data with Graph Explorer and finding that the following does not return Children data/
https://graph.microsoft.com/beta/users/<userID>/drive/root/children
https://graph.microsoft.com/beta/drives/<driveID/root/children
The above 2 calls does not fail - just no data. 

I am not a Global Admin, but have Files.ReadWrite.All and Sites.ReadWrite.All permissions.
Are there other required permissions? 

BTW -  https://graph.microsoft.com/beta/users/<userID>/drive/root returns expected data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51681097/126685503-494d7428-266f-4771-b1f7-081eed429d5a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge, Chrome

**Additional context**
 
[AB#10369](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10369)

**Comment by millicentachieng** [comment]
Hello @lisataka-uw

Thank you for reporting your concern. Unfortunately, we in the Graph Explorer team do not have any ownership of the APIs that are causing you issues. If you report this issue in the Microsoft Q&A forum, it will get routed to the appropriate team for them to triage.

https://aka.ms/askgraph
