### ISSUE TITLE
Set up click analytics telemetry auto-collection plugin 

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/microsoft-graph-explorer-v4#1045]
We are currently manually tracking clicks on specific UI components. Each time a new component is added we have to add new code to capture usage telemetry on it.

Application Insights now has a [plugin](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-click-analytics-plugin) that enables auto-collection of clicks analytics. 

This task is for investigating how the plugin will work for us while maintaining the telemetry schema already established and if feasible, proceed with implementation. 
 
[AB#10483](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10483)

**Comment by thewahome** [comment]
Can we have a discussion to see whether there is duplication of effort with the Portal team?

**Comment by adhiambovivian** [comment]
Closing this one - Portals team collects this data.
