### ISSUE TITLE
Ability to clear consents already granted

### ISSUE THREAD

**Issue by mostverydoge** [microsoftgraph/microsoft-graph-explorer-v4#1047]
**Is your feature request related to a problem? Please describe.**
When checking which attributes are released, I'm unable to specify the consents requested when I sign into my enterprise account, and cannot clear the consents I don't wish to grant, after logging in. When I authenticate in order to retrieve my own data, I'm logged in with User.Read graph permission. If I then fetch /oidc/userinfo I receive the email address attribute as well as Name, Surname, Given name, and Photo. I don't wish to grant email permission, but the authenticated permission User.Read grants access to the email address attribute and the oidc/userinfo endpoint treats this as equivalent to the OpenID.Email permission.

**Describe the solution you'd like**
A login flow which checks which Graph permissions should be requested, prior to authentication.

**Describe alternatives you've considered**
An extension to the Permissions panel allowing a right-click to clear a granted permission.

**Additional context**

 
[AB#10506](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10506)

**Comment by thewahome** [comment]
Hello @mostverydoge ,

> **Describe alternatives you've considered**
> An extension to the Permissions panel allowing a right-click to clear a granted permission.
> 

Sadly, you can't remove permissions by using the Graph Explorer UI however you can still un-consent to permissions by removing the application consent [as described in this article](https://www.shawntabrizi.com/aad/revoking-consent-azure-active-directory-applications/) and then re-consenting to the permissions you want.


> **Describe the solution you'd like**
> A login flow which checks which Graph permissions should be requested, prior to authentication.
> 

I am not quite sure I understand the statement here. On first login, we request only for these permissions: 'openid profile User.Read' all other scopes are requested when the user needs to consent to them. Are you saying that you do not want the User.Read permission to expose your email address?
