### ISSUE TITLE
No able to create event via Graph API

### ISSUE THREAD

**Issue by wildestcat01** [microsoftgraph/microsoft-graph-explorer-v4#1061]
On Creating the Event giving below error

{
    "error": {
        "code": "ErrorItemNotFound",
        "message": "The specified object was not found in the store.",
        "innerError": {
            "date": "2021-08-23T06:12:16",
            "request-id": "3c2e0d92-3a86-4558-b201-418fc6a36994",
            "client-request-id": "91a6d4c4-e656-cb3b-1381-716b88b75b6a"
        }
    }
} 
[AB#10809](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10809)

**Comment by millicentachieng** [comment]
Hello @wildestcat01

Thank you for reporting your concern. Unfortunately, we in the Graph Explorer team do not have any ownership of the APIs that are causing you issues. If you report this issue in the Microsoft Q&A forum, it will get routed to the appropriate team for them to triage.

https://aka.ms/askgraph
