### ISSUE TITLE
Request header ConsistencyLevel eventual is not sent correctly

### ISSUE THREAD

**Issue by Licantrop0** [microsoftgraph/microsoft-graph-explorer-v4#1063]
Sending [Advanced queries](https://docs.microsoft.com/en-us/graph/aad-advanced-queries) with graph explorer sometimes fails because `ConsistencyLevel: eventual` header is not sent:

![image](https://user-images.githubusercontent.com/2388430/130453483-af7b201f-264a-48c6-bf4c-17edd65147e3.png)

**To Reproduce**
Try here: https://developer.microsoft.com/en-us/graph/graph-explorer?request=applications%3F%24search%3D%22displayName%3ABrowser%22&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d

**Comment by Licantrop0** [comment]
yes, it happen when I'm logged in.

**Comment by Onokaev** [comment]
This issue was consistent with the previous API sandbox. 
It is currently being planned for as a feature request

**Comment by Licantrop0** [comment]
@Onokaev now it happens when I'm **NOT logged in**, see (missing @odata.count):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2388430/143865436-1dd3b0ac-959c-42e5-a833-9cae527a96be.png)

Instead, when I'm logged in I can see the count:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2388430/143865495-9bab0bf6-dece-4420-953b-399375aa3b33.png)

Before July/August, Graph Explorer was working fine with the [Advanced Query Capabilities](https://docs.microsoft.com/en-us/graph/aad-advanced-queries)
