### ISSUE TITLE
Deliver the ability to view Graph changes from Graph Explorer

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#1066]
- [x] #1174
- [ ] #1175
- [x] #869 

[AB#10822](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10822)

**Comment by RabebOthmani** [comment]
Will close this epic and open a new one in due time with spec and more details
