### ISSUE TITLE
Remain Accessibility Compliant

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#1067]
- [x] #1145
 - [x] #1146
 - [x] #1147
 - [ ] #1148
 - [ ] #1149
 - [x] #1150
 - [ ] #1151
 - [ ] #1102 

[AB#10823](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10823)

**Comment by RabebOthmani** [comment]
@ElinorW  @adhiambovivian  since we will always have accessibility tickets to look at, should we close this epic?

**Comment by adhiambovivian** [comment]
yap @RabebOthmani
