### ISSUE TITLE
Status messages missing for unauthenticated users

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#1078]
**Describe the bug**
When an unauthenticated user runs a query and it returns a successful or error response, the status messages are missing. E.g OK, Bad Request, Unauthorized... etc

**To Reproduce**
1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
2. Click on 'Run Query' button
3. Observe -200 message (Only status code is displayed)
4. See missing 'OK' message

**Expected behavior**
The status message should be displayed and not just the status code. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18407044/130943513-55068dda-84ac-4f0f-ab4c-6b7c6b52688b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: All

**Additional context**
This problem is not reproduced in cases where a user is authenticated.
 
[AB#10874](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10874)

**Comment by adhiambovivian** [comment]
To be fixed on API-Sandbox side
