### ISSUE TITLE
Boilerplate Teams POST send channel message posts to Teams, but returns 400 Bad Request

### ISSUE THREAD

**Issue by mharrisn** [microsoftgraph/microsoft-graph-explorer-v4#1079]
**Describe the bug**
Boilerplate Teams POST send channel message posts to Teams, but returns 400 Bad Request. Again, the channel message IS POSTED, but the Graph API returns a 400 status. An example of the response is below

**To Reproduce**
1. https://developer.microsoft.com/en-us/graph/graph-explorer
2. If needed, Sign In to Explorer
3. Scroll down to 'Microsoft Teams' and expand list
4. Scroll down to 'POST' send channel message
5. Consent to permissions under 'Modify Permissions' tab, if necessary
6. Replace Team ID and Channel ID with valid values
7. Run Query

**Expected behavior**
API would return 201 Status with the chatMessage response, and that the "Hello world" message it posted to the appropriate channel.

**Screenshots**
```
{
    "error": {
        "code": "BadRequest",
        "message": "Bad Request",
        "innerError": {
            "date": "2021-08-26T14:17:05",
            "request-id": "d9a11c4e-12f4-4ba1-ab80-c348dc738c35",
            "client-request-id": "d9a11c4e-12f4-4ba1-ab80-c348dc738c35"
        }
    }
}
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Browser Chrome
 - Version 92.0.4515.159

**Additional context**
The error response is not descriptive enough to determine any other root cause.
 
[AB#10878](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10878)

**Comment by millicentachieng** [comment]
Hello @mharrisn 

Thank you for reporting your concern. Unfortunately, we in the Graph Explorer team do not have any ownership of the APIs that are causing you issues. If you report this issue in the Microsoft Q&A forum, it will get routed to the appropriate team for them to triage.

https://aka.ms/askgraph
