### ISSUE TITLE
Address customer pain points from OCV

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#1081]
This is a bucket topic to cover work we can do for customer feedback points we are receiving. 
[AB#10879](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10879)

**Comment by adhiambovivian** [comment]
Most of the paint-points fall under permissions - there is upcoming investment(s) in permissions area. Closing this epic.
