### ISSUE TITLE
odata.nextLink containing filter doesn't work

### ISSUE THREAD

**Issue by williamscs** [microsoftgraph/microsoft-graph-explorer-v4#1082]
**Describe the bug**
If an API request was created containing a `$filter` parameter, the '@odata.nextLink' value will not work in a subsequent request.

**To Reproduce**
Perform a GET request with a filter: `https://graph.microsoft.com/v1.0/users?$filter=accountEnabled eq true`
Should have a response like:
```json
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users",
  "@odata.nextLink": "https://graph.microsoft.com/v1.0/users?$filter=accountEnabled+eq+true&$skiptoken=RFNwdAoAAQAAAAAAAAAAFAAAAJtOSvz52nxApH5XfVRmVjwBAAAAAAAAAAAAAAAAAAAXMS4yLjg0MC4xMTM1NTYuMS40LjIzMzEGAAAAAAABMJZSI_m8aECg6iZQykCENAEbAAAAAQAAAAA",
  …
}
```
> Note the spaces in the original filter are switched to a `+`

If you attempt to use the full odata.nextLink, you will receive an HTTP 400.
```json
{
  "error": {
    "code": "BadRequest",
    "message": "Invalid filter clause",
    "innerError": {
      "date": "2021-08-25T16:51:41",
      "request-id": "6a1bd9e8-07a5-4439-b171-c8295ee79e41",
      "client-request-id": "6a1bd9e8-07a5-4439-b171-c8295ee79e41"
    }
  }
}
```

Manually changing the `+` characters to spaces fixes the issue.

**Expected behavior**
Should be able to use the nextLink without modification.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.4
 - Browser: Insomnia REST Client (similar to Postman)

**Additional context**
This ticket was originally submitted to Microsoft Support and was directed here. 
[AB#10886](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10886)

**Comment by lbermudezch** [comment]
@thewahome any update here?
