### ISSUE TITLE
Filtering on appOwnerOrganizationId results in a BadRequest (Invalid filter clause)

### ISSUE THREAD

**Issue by JTeeuwissen** [microsoftgraph/microsoft-graph-explorer-v4#1085]
**Describe the bug**
Using the appOwnerOrganizationId eq filter on the serviceprincipals resource causes a bad request

**To Reproduce**
1. Go to `https://developer.microsoft.com/en-us/graph/graph-explorer`
2. Make sure to have the Application.Read.All permission
3. Enter `https://graph.microsoft.com/v1.0/serviceprincipals?$count=true&$filter=appOwnerOrganizationId eq '(my tenant id)'` as query.
4. Run

**Expected behavior**
A list of service principals with a matching appOwnerOrganizationId.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/15076530/131229417-af62526b-7d0c-4c96-a9fc-8070d5b48e2e.PNG)

**Desktop (please complete the following information):**
Win 10, opera, 78.0.4093.147

**Additional context**
Same error using postman and javascript api.
 
[AB#10910](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10910)

**Comment by ElinorW** [comment]
Hey @JTeeuwissen, 
Assuming you are including the `''`  I suggest you try inputting your tenent id without the quotation marks....
e,g `https://graph.microsoft.com/v1.0/serviceprincipals?$count=true&$filter=appOwnerOrganizationId eq (my tenant id)`

**Comment by JTeeuwissen** [comment]
@ElinorW Thank you for the response, this resolved my problem. I don't know why I did not try this before, so thank you.
