### ISSUE TITLE
Chrome Around Graph Explorer doesn't respect System Theme. 

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/microsoft-graph-explorer-v4#1096]
**Describe the bug**
Graph Explorer dark them gets set quite nicely based on Windows theme which is pretty cool!!!. However, it seems that the chrome around Graph Explorer doesn't respect the System Theme (Dark theme) and breaks the experience. 

**To Reproduce**
Set OS theme to dark mode. 
Graph Explorer adapts to the theme accordingly, however the chrome around stays white. 

**Expected behavior**
I expected that when the theme changes, all components in the window would change accordingly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1641829/131857193-317bed29-a405-4fef-b055-4d2968201839.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider
 - Browser: Edge
 - Version: latest

**Comment by adhiambovivian** [comment]
Has external dependency
