### ISSUE TITLE
sign in with tenant query param

### ISSUE THREAD

**Issue by michiproep** [microsoftgraph/microsoft-graph-explorer-v4#1106]
**Describe the bug**
When I start GraphExplorer using my tenant name as queryparameter and then try to sign in, the sign-in-popup just stays empty.
I tryed different browsers, also in-private windows

**To Reproduce**
1. See description

**Expected behavior**
The sign-in UI should be provided.

**Screenshots**

**Comment by Onokaev** [comment]
Hey @michiproep. Sorry about this. 
Are you still experiencing this issue? 
Which laptop were you using at the time you experienced this? It was a known issue with Macs, but it was sorted out with a new release.
