### ISSUE TITLE
Update 'Getting Started' webpage for GraphExplorer

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#1113]
**Is your feature request related to a problem? Please describe.**
The current GE documentation has stale information. It needs to be updated to capture what's new in Graph Explorer and also we need to have a cadence for long-term strategy for ensuring the site is up to date.

**what's currently on the GE docs**
![image](https://user-images.githubusercontent.com/9458079/172633687-1054dd5d-3f18-4d1d-81fd-648b2a3e7b45.png)

**How GE currently looks**

![image](https://user-images.githubusercontent.com/9458079/172633891-7e194546-e6c8-4e48-919a-d766ef440d90.png)

**Other improvements to the GE docs:**

- Update to have other information such as the FAQs around permissions
- Have the GE docs as a separate node similar to MGT, SDK etc in the Graph docs tree to improve discoverability

![image](https://user-images.githubusercontent.com/9458079/172634846-b1ac8c3e-eefc-4495-9dc7-a74f52a0aec5.png)

**Comment by ElinorW** [comment]
Closing this as the site has been updated
