### ISSUE TITLE
In dark mode, the share URL isn't visible

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/microsoft-graph-explorer-v4#1119]
**Describe the bug**

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Change Theme to dark mode if not already changed.
3. Click on Share Query 
![image](https://user-images.githubusercontent.com/6464005/133210654-08b6db35-8567-47c1-9127-3e525323484a.png)
4. Share Query URL is not visible(as below)
![image](https://user-images.githubusercontent.com/6464005/133210799-0b28da14-feca-46ca-b7e5-0e6bca0a5728.png)

Changing theme to light mode makes the query visible.

**Expected behavior**
Query should ideally be visible as one is unsure if there is something to be copied.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Chrome and Edge

**Comment by Onokaev** [comment]
#1152
