### ISSUE TITLE
Login failed with Graph Tester

### ISSUE THREAD

**Issue by firektl** [microsoftgraph/microsoft-graph-explorer-v4#1124]
**Describe the bug**

I am trying to develop an application in power apps, to manage Office 365 users (only update password, update name, create user) but when trying to test the POST methods of Microsoft Graph they ask me to log in; but when specifying the credentials it gives me an error:

Request Id: f083c31c-b657-451d-a1f6-443cf4eaea00
Correlation Id: a803255a-db60-402b-86b5-891b17325b1c
Timestamp: 2021-09-15T21:32:24Z
Message: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'de8bc8b5-d9f9-48b1-a8ad-b748da725064'.

**To Reproduce**
1.- Enter the URL: https://developer.microsoft.com/es-es/graph/graph-explorer/preview
2.- I press the button "Login to the Graph Tester"
3.- A pop-up window is displayed requesting the username and password; but it produces the indicated error

**Expected behavior**
I expected the login to be successful to access the information, this in order to create a custom connector in powerapps.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Microsoft Edge
Version: 93.0.961.47 (Official Build) (64-bit)

**Additional context**
I did a search for the error on the web; where they indicated a series of steps to do it in Azure; But when I try it, it tells me that the configuration is not available for Graph Explorer because it is a multi-tenant application. The steps were as follows:
1.- Enter the Azure portal
2.- Go to Azure Active Directory
3.- Go to business applications.
4.- Search Graph Explorer; go to Single sign-on. At this point I can't do the configuration.

Please if you could help me, I would be very grateful.

**Comment by thewahome** [comment]
Hello @firektl please use the production url:  https://developer.microsoft.com/es-es/graph/graph-explorer . It should allow you to log in properly
