### ISSUE TITLE
how to add https protocl in this sample?

### ISSUE THREAD

**Issue by leapyear1969** [microsoftgraph/microsoft-graph-explorer-v4#1127]
hello everyone, 

i am trying to transplant the Graph Explorer to my local enviroment, i want to use 'https protocl' to show it, it should look like https://www.localgraph.com , where should i add the 'https' request and my cert information in this sample?

thanks in advance.

**Comment by leapyear1969** [comment]
i tried to add "https" option in "*\node_modules\browser-sync\dist\default-config.js", it works in my test project,but not in this sample.

**Comment by Onokaev** [comment]
Hey @leapyear1969. Were you able to solve this problem?

**Comment by leapyear1969** [comment]
> he 'https' request and my cert information in this sample?

hello there, yes i fixed this issue by configure the browser sync configuration file.

```

Path\liteproject\node_modules\browser-sync\dist\```default-config.js```

```

in the default-config.js we can add https cert information, such as key and cert

![image](https://user-images.githubusercontent.com/18607988/174418845-d45423d5-6c02-41cc-ac2a-1d484db62d5d.png)
