### ISSUE TITLE
Bad performance for graph api

### ISSUE THREAD

**Issue by assalahav** [microsoftgraph/microsoft-graph-explorer-v4#1157]
**The bug**:
When using MS Graph API to scrape users and groups deltas and there's a lot of data to fetch, each response (containing the  deltaLink) contains much less than 1000 entries. 
For users request we get fixed size of 200 entries per response. 
For groups request we get varying number of entries in the response, startung from ~200 and decreases each time until it gets to 1 entry in each response. After quite a few of such responses it gets back to around 200 entries per result, and continue decreasing in next reponses. 
We see the same behaviour when using the Azure portal.

**Steps to reproduce the behaviour**:
Use 'https://graph.microsoft.com/v1.0/xxx/users/delta' or 'https://graph.microsoft.com/v1.0/xxx/Groups/delta' when there are a lot of users and groups. Use the url in the deltaLink in the result for your next request, and check how many entries are in the 'data' field.

**Expected behavior**
'data' field in the response shall contain 1000 entries, except for last batch.

**Screenshots**
Not available due to the size of the response.

**Desktop (please complete the following information):**
Not relevant. API problem that was verified from code as well as from Microsoft Graph portal. 

**Additional context**
We experience this problem with few different tenants of our customers.

**Comment by darrelmiller** [comment]
Hi @assalahav 

Thank you for reporting your concern.  Unfortunately, we in the Graph Explorer team do not have any ownership of the APIs that are causing you issues.  If you report this issue in the Microsoft Graph TechCommunity forum, it will get routed to the appropriate team for them to triage.  https://techcommunity.microsoft.com/t5/microsoft-graph/bd-p/OfficeGraph

**Comment by assalahav** [comment]
Thanks.
Issue reported: https://docs.microsoft.com/en-us/answers/questions/656446/bad-performance-for-graph-api.html
