### ISSUE TITLE
Retrieve a list of plannertask objects assigned to a User.

### ISSUE THREAD

**Issue by samikhwaireh** [microsoftgraph/microsoft-graph-explorer-v4#1161]
Forbidden - 403 - 810ms. You need to consent to the permissions on the Modify permissions (Preview) tab
![graph](https://user-images.githubusercontent.com/43380298/136903701-8a948e00-a8a4-469c-ba72-1aeb727fe2fe.png)

**Comment by samikhwaireh** [comment]
> Forbidden - 403 - 810ms. You need to consent to the permissions on the Modify permissions (Preview) tab ![graph](https://user-images.githubusercontent.com/43380298/136903701-8a948e00-a8a4-469c-ba72-1aeb727fe2fe.png)

I have a problem in retrieving the list of planner tasks for user, I gave all required permissions to the user, but didn't worked, any suggestions?

**Comment by thewahome** [comment]
@samikhwaireh I have reproduced this error. 

@darrelmiller / @irvinesunday who is a contact to reach out to for the correct permissions? I have consented to all `Task` related permissions with no luck

**Comment by RabebOthmani** [comment]
@samikhwaireh  @thewahome  looking at the documentation https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0&tabs=http looks like a work or school account is required. Were you using a personal account?

**Comment by samikhwaireh** [comment]
> @samikhwaireh @thewahome looking at the documentation https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0&tabs=http looks like a work or school account is required. Were you using a personal account?

I already use a work account

**Comment by samikhwaireh** [comment]
> @samikhwaireh @thewahome looking at the documentation https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0&tabs=http looks like a work or school account is required. Were you using a personal account?

I already use a work account

**Comment by Onokaev** [comment]
Hey @samikhwaireh @thewahome. I've just tested this endpoint, and it seems to be working
<img width="700" alt="image" src="https://user-images.githubusercontent.com/45680252/173094971-29afdd39-f02d-4fe7-b431-790d04025ae9.png">

Help me confirm if it's working on your end

**Comment by Onokaev** [comment]
I got a little confused with the exact query that you were running @samikhwaireh. The issue is still there.
Here's the query for reference:
https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%2F%7Buser-id%7D%2Fplanner%2Ftasks&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

Let me find the other permissions that we need to make calls to this endpoint

**Comment by Onokaev** [comment]
Hey @samikhwaireh. This issue is related to this other issue that was raised here: https://github.com/microsoftgraph/microsoft-graph-docs/issues/4766. 
From this, the endpoint does not support viewing tasks assigned to other users. You can only view your own tasks.
