### ISSUE TITLE
Is it possible to assign/ sent invitation of delegation for outlook mail using graph explore?

### ISSUE THREAD

**Issue by saif177** [microsoftgraph/microsoft-graph-explorer-v4#1162]
I am trying to send delegate invitation for outlook mail to someone (within organization) . there is API for changing delegation permission but I could find any API to assign delegate for outlook calendar . 

is there any API for that? if yes can anyone please refer me. thank you

**Comment by ElinorW** [comment]
Hey @saif177 
Were you able to get a solution to this? 

If not, you could post this on the Ms Graph Q&A page, https://docs.microsoft.com/en-us/answers/products/graph
Where someone with better expertise regarding this query may be able to answer you.
