### ISSUE TITLE
MS Graph Explorer should not show "Device.ReadWrite.All" as a permission to be consented

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-explorer-v4#1169]
**Describe the bug**
per the following documentation:  https://docs.microsoft.com/en-us/graph/permissions-reference#device-permissions
The only valid delegated permissions for Device are either Device.Read or Device.Read.All.  The MS Graph Explorer tool shows these 3 permissions:  Device.Read, Device.Read.All, and Device.ReadWrite.All.  If the user selects the permission Device.ReadWrite.All they will fail to consent with the consent popup appearing and going away.  In the Fiddler trace it shows the following error:  
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://developer.microsoft.com/en-us/graph/graph-explorer#error=invalid_client&amp;error_description=AADSTS650053%3a+The+application+%27Graph+Explorer%27+asked+for+scope+%27Device.ReadWrite.All%27+that+doesn%27t+exist+on+the+resource+%2700000003-0000-0000-c000-000000000000%27.+Contact+the+app+vendor.%0d%0aTrace+ID%3a+e689c8cf-9c13-456d-96b2-810598587b00%0d%0aCorrelation+ID%3a+2da03233-ac64-48b8-9984-d9be6914960d%0d%0aTimestamp%3a+2021-10-20+18%3a36%3a04Z&amp;state=eyJpZCI6ImY1YTIxMTA1LTVlNDYtNGZiOS1hNjcwLTAwOTZkNzhlOTJiOSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0%3d">here</a>.</h2>
</body></html>

However this error is never shown to the user.  The end result is that the user is not able to consent to the permission without seeing a valid error.  In the UI it may show this error text:  invalid scope

**To Reproduce**
1. Sign in to MS Graph explorer (https://aka.ms/ge)
2. Click on the  '....' to the right of sign in and select "Select permissions"
3. In the flyout window try selecting "Device.ReadWrite.All" and go through the Consent experience
4.
or you cans see the same bug this way:
1) sign in to MS graph explorer tool
2) do a GET on https://graph.microsoft.com/v1.0/devices"
3) click on "Modify permissions" tab under the request and try  to consent to Device.ReadWrite.All

**Expected behavior**
Consent to permission should complete sucessfully.  Intead of popup appears and goes away quickly.  it does not give you a chance to click on the 'Aceept" button.  Isssue reproduce on all platforms

Based on the above docs, Device.ReadWrite.All is only valid for Application permission.  It does not exist for Delegated permisisons

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by millicentachieng** [comment]
@bachoang, "Device.ReadWrite.All" permission isn't available on Graph Explorer. 

You can also look at [API documentation](https://docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&tabs=http) to get the specific permissions to use for an endpoint.
