### ISSUE TITLE
Search API Endpoints returning Bad Request 400

### ISSUE THREAD

**Issue by marinoscar** [microsoftgraph/microsoft-graph-explorer-v4#1170]
**Describe the bug**
Unable to use the Graph API Search Endpoints from the Graph Explorer

**To Reproduce**
1. Graph Explorer
2. Authenticate account to receive a token
3. Select the search api from the left menu
4. Click on search drive items
5. Enable the following permissions enable Files.Read.All, Sites.Read.All, Files.ReadWrite.All, Sites.ReadWrite.All
6. Click on run query

**Expected behavior**
A response should be expected but the Graph Explorer returns 400 Bad Request

**Screenshots**
Video recording of the issue
https://user-images.githubusercontent.com/581497/138792172-070e9228-c658-4d2d-a955-3f94a48223b6.mp4

**Comment by Onokaev** [comment]
Hey @marinoscar. 
Was this helpful?

**Comment by marinoscar** [comment]
Yes, thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
