### ISSUE TITLE
Fix the capability to export query history as HAR file

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#1182]

**Comment by gavinbarron** [comment]
@RabebOthmani we have this already:
![Image](https://user-images.githubusercontent.com/7122716/191570205-02d6a89b-0490-4a86-82bf-31a292993e73.png)

But as I was trying it today the HAR file that exported is not valid, it won't import into either PostMan or Fiddler

**Comment by ElinorW** [comment]
@gavinbarron , I've seen the HAR isn't valid
I guess the history item can be exported as a postman collection instead

**Comment by gavinbarron** [comment]
@ElinorW  HAR, when correctly created is a valid thing to import into PostMan and Fidder. 
HAR has the advantage of being an open format as opposed to be a vendor specific format.

**Comment by ElinorW** [comment]
Ah okay that's a great point @gavinbarron 
I'll look into resolving this
