### ISSUE TITLE
Cannot consent and post event to calendar on Graph API

### ISSUE THREAD

**Issue by dillardd** [microsoftgraph/microsoft-graph-explorer-v4#1205]
**Describe the bug**
After consenting to the required permissions on Graph Explorer, the request fails with 403 Forbidden and advises "You need to consent to the permissions on the Modify Permissions (Preview) tab". When click on the Modify Permissions (Preview) tab, all permissions are already consented to.

**To Reproduce**
1. Go to 'Graph Explorer'
2. Sign in
3. Scroll down to 'Outlook Calendar'
4. Click on 'Schedule a Meeting'
5. POST to https://graph.microsoft.com/v1.0/users/user@domain.com/events
6. Consent to required permissions
7. Click 'Run Query'

**Expected behavior**
Event created on user@domain.com calendar

**Screenshots**
![2021-11-10 12_29_02-Graph Explorer - Microsoft Graph and 6 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/62298501/141172389-d4d7de4c-a0e0-4042-821a-2d79715158ee.png)
Included

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge

**Comment by ElinorW** [comment]
Hey @dillardd, 
I'm unable to reproduce this. Could you please confirm if this is still the response you're getting after running the query?

**Comment by dillardd** [comment]
I also was not able to reproduce it when I logged in with a different account. I would consider the issue resolved.
