### ISSUE TITLE
Graph Explorer sign in does not work

### ISSUE THREAD

**Issue by RobVeldkamp-TomTom** [microsoftgraph/microsoft-graph-explorer-v4#1239]
**Describe the bug**
Unable to sign in to Graph Explorer using my company account.

**To Reproduce**
1. Go to Graph Explorer
2. Click on 'Sign in to Graph Explorer'
3. Fill in credentials
4. Watch the loading icon spin without end

**Expected behavior**
Either a clear error message that tells me what is wrong, or a working sign in. It shouldn't just keep spinning.

**Screenshots**
The console shows the following error:

<img width="1402" alt="Screenshot 2021-11-18 at 17 48 28" src="https://user-images.githubusercontent.com/66615366/142459610-86832ad5-a7aa-4fcb-8437-badea1975f9f.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6
 - Browser Chrome
 - Version 96.0.4664.45 (Official Build) (x86_64)

**Comment by adhiambovivian** [comment]
@Onokaev  this one is for you

**Comment by Onokaev** [comment]
Hey @RobVeldkamp-TomTom. I'm very sorry about this.
Are you still experiencing this issue? 
We released a new version of Graph Explorer which may have fixed this.

**Comment by RobVeldkamp-TomTom** [comment]
Hi, it seems the new version has fixed this issue. Thanks!

**Comment by Onokaev** [comment]
I am closing this issue as it was resolved by the new release
