### ISSUE TITLE
Restore the ability to collapse "Request" section in Graph Explorer

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-explorer-v4#1272]
I used to be able to completely reduce, towards the "Request" side, the section divider that separates the "Request" and the "Response" sections in Graph Explorer. This has not been possible in the last ~2 weeks with the "Request" section now of fixed minimum width.

Sometimes I just want to see the response body elements without using the "Expand" feature. Previously, I was able to completely minimize the request box section, especially when there's nothing useful I need to view simultaneously with the response body.

Please restore this useful feature. Or, add a button for complete collapse.

**To Reproduce**
1. Go to Graph Explorer
2. Place the mouse pointer on the divider between the "Request" and "Response" sections
3. See that you can expand the request box down, but can't reduce the section beyond a set width

<img width="858" alt="image" src="https://user-images.githubusercontent.com/14026935/143865297-566c75ed-f581-419f-979f-d2cf2e2495cb.png">

**Comment by Onokaev** [comment]
Hi @FaithOmbongi. This behavior has been restored. You can check it out here: https://jolly-sand-0ac78c710-1292.centralus.azurestaticapps.net/

It will be live on the next release

**Comment by FaithOmbongi** [comment]
Appreciate it! Thanks, @Onokaev !
