### ISSUE TITLE
A small bug when getting messages in a channel

### ISSUE THREAD

**Issue by Zhang-Xinrui** [microsoftgraph/microsoft-graph-explorer-v4#1309]
**Describe the bug**
There is a typo error about the tip box of the "Sample queries" -> "messages in a channel".

**To Reproduce**
1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
2. Click on "Sample queries" on the left, then click "Microsoft Teams(beta)"
3. Scroll down to "messages in a channel"
4. See a tip box on the right.
5. According to the suggestions in the tip box, first get your joined teams, second get channels of a team you joined.

**Expected behavior**
You will get a http error when requesting "https://graph.microsoft.com/beta/groups/{group-id-for-teams}/channels" when requesting channels of a team you have joined before. Replace the request to "https://graph.microsoft.com/beta/teams/{group-id-for-teams}/channels" and you will see everything goes well.

**Screenshots**
![image](https://user-images.githubusercontent.com/42544168/145547338-50384ffa-7954-436c-958e-d7f156ac60b9.png)
![image](https://user-images.githubusercontent.com/42544168/145547427-11df68a4-f0e2-4748-89b3-e8946bb9e77f.png)

**Comment by millicentachieng** [comment]
Hi @Zhang-Xinrui,

Thank you for catching that. The tip has been updated.
