### ISSUE TITLE
[Resource Explorer] Need the ability to add to collection an action or function in Resource Explorer

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#1321]
![image](https://user-images.githubusercontent.com/447694/146781851-61abdbcf-2de4-4789-b47d-ec279dc16977.png)

**Comment by RabebOthmani** [comment]
As a user, when I am on Resources Explorer and I click 'more actions' on a function
I want to see an 'Add to collection' option
So I can add the function to my collection 

**Acceptance Criteria**
<img width="538" alt="add action to collection " src="https://user-images.githubusercontent.com/5781590/146976491-f0f4700f-9dee-419d-be3f-05136a4b5cf3.png">
