### ISSUE TITLE
[Sign-in] token is being cached?

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1327]
It's been reported that a user signed in to Graph Explorer but the token making the call to the API belonged to another user.
We need to investigate this behavior and check if the token gets cached at any point.

**Comment by millicentachieng** [comment]
This issue is caused by one user signing in and then using a different account to consent to permissions. The UI isn't updated until the page is reloaded. The fix will be to update the profile image and email address once a different account is used to consent to permissions.
