### ISSUE TITLE
not seeing permissions in search API

### ISSUE THREAD

**Issue by legendvi** [microsoftgraph/microsoft-graph-explorer-v4#1329]
**Describe the bug**

**To Reproduce**

**Expected behavior**
it should show the permissions I should consent but it is showing permissions cannot be showed

**Screenshots**
![image](https://user-images.githubusercontent.com/41253273/147631055-f64589e9-f633-4c29-99f6-763bbadbf558.png)

**Desktop (please complete the following information):**
 - OS: windowns 10
 -  - Browser - chrome - 
 - latest

**Additional context**
please help

**Comment by RabebOthmani** [comment]
Hi @legendvi ,
I'm unable to repro the bug. I can see the list of permissions for the query mentioned on your screenshot. 
Could you please confirm you are still seeing the issue and provide more details? Thank you.

**Comment by legendvi** [comment]
Hi,
Yes Actually I was wondering where I can learn to know how to edit
permissions to graph API to query correctly. Please let me know how to
proceed.

Thanks,
Vignesh Kumar

**Comment by RabebOthmani** [comment]
@legendvi under the permissions tab, you should see what permissions to consent to. And you can always refer to the [documentation ](https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0) to see what permissions are required for each API.
