### ISSUE TITLE
 登录不了 Graph explore 

### ISSUE THREAD

**Issue by bjsy2022** [microsoftgraph/microsoft-graph-explorer-v4#1332]
使用正确的用户名和密码也无法登录！
![image](https://user-images.githubusercontent.com/97160626/148196877-a06a8aa3-c5e2-42a3-9cf0-4dabf094b298.png)

**Comment by Onokaev** [comment]
Hi @bjsy2022. Sorry about this.
Could you send a screenshot of the information displayed on the popup after you have attempted to sign in.

**Comment by bjsy2022** [comment]
It has been solved ,  no more actions are needed, Thanks!



***@***.***
 
发件人： EvansA
发送时间： 2022-01-19 14:39
收件人： microsoftgraph/microsoft-graph-explorer-v4
抄送： bjsy2022; Mention
主题： Re: [microsoftgraph/microsoft-graph-explorer-v4] 登录不了 Graph explore (Issue #1332)
Hi @bjsy2022. Sorry about this.
Could you send a screenshot of the information displayed on the popup after you have attempted to sign in.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Onokaev** [comment]
Sounds good!
