### ISSUE TITLE
SendMail through AAD App with Client Secret

### ISSUE THREAD

**Issue by wd21sos** [microsoftgraph/microsoft-graph-explorer-v4#1336]
**Describe the bug**
I want to send an email via graph api through Azure Active Directory App authorization. The app in aad does have all the necessary api permissions which would be needed for that request. I create an bearer token through postman which is used for authorization to send the mail. The Token is generated through https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token and does include all api permissions. With this I want to access the Graph API https://graph.microsoft.com/v1.0/users/<userid>/sendMail. However, when calling the API I get the following error: _The property 'subject' does not exist on type 'Microsoft.OutlookServices.Message'. Make sure to only use property names that are defined by the type or mark the type as open type. REST APIs for this mailbox are currently in preview. You can find more information about the preview REST APIs at https://dev.outlook.com/."_
If I use the token which is generated in graph explorer in my postman request it works just fine. The authorization is done through a client secret in postman.

**To Reproduce**
1. Open Postman
2. Create Environment with Client Secret to AAD
3. Create Bearer Token
4. Create GET Request to SendMail
5. Send Request

**Expected behavior**
{
    "error": {
        "code": "RequestBodyRead",
        "message": "The property 'subject' does not exist on type 'Microsoft.OutlookServices.Message'. Make sure to only use property names that are defined by the type or mark the type as open type. REST APIs for this mailbox are currently in preview. You can find more information about the preview REST APIs at https://dev.outlook.com/.",
        "innerError": {
            "date": "2022-01-11T14:42:45",
            "request-id": "5aa0b96c-6537-420b-94df-50ef811f90a0",
            "client-request-id": "5aa0b96c-6537-420b-94df-50ef811f90a0"
        }
    }
}

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser MS Edge
 - Version 97.0.1072.55

**Comment by RabebOthmani** [comment]
Hi @wd21sos , 
This is an API issue not a Graph Explorer one. I'm pinging the relevant team internally, in the meanwhile I recommend you post the question on [Microsoft Q&A ](https://docs.microsoft.com/en-us/answers/index.html)
