### ISSUE TITLE
Getting 504 when using Search API

### ISSUE THREAD

**Issue by ReiSuzuki** [microsoftgraph/microsoft-graph-explorer-v4#1361]
**When using the search API, I get a Gateway Timeout 504**
I had been successfully using the Graph Explorer to test the search API. 
`https://graph.microsoft.com/v1.0/search/query`
However, today I started to get a 504 gateway timeout with the following response:
`{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2022-01-21T16:58:20",
            "request-id": "e9ed93de-a625-4749-871d-eaae3f7a4860",
            "client-request-id": "253b74fa-3c81-4c65-b61c-35b3452c3c83"
        }
    }
}`

My Request body is:
`{
    "requests": [
        {
            "entityTypes": [
                "driveItem"
            ],
            "query": {
                "queryString": "contoso"
            }
        }
    ]
}`
<img width="1122" alt="Screen Shot 2022-01-21 at 10 00 04" src="https://user-images.githubusercontent.com/38015344/150568695-47b8902c-5253-4f92-8983-86b7f6419f32.png">

**Device:**
 - OS: macOS 12.1
 - Browser Microsoft Edge 
 - Version 97.0.1072.62

**Comment by Onokaev** [comment]
Hi @ReiSuzuki, are you still experiencing this issue? 
I have tested it and it seems to work fine. 

I have used the query and request body in your ticket: https://developer.microsoft.com/en-us/graph/graph-explorer?request=search%2Fquery&method=POST&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=eyJyZXF1ZXN0cyI6W3siZW50aXR5VHlwZXMiOlsiZHJpdmVJdGVtIl0sInF1ZXJ5Ijp7InF1ZXJ5U3RyaW5nIjoiY29udG9zbyJ9fV19&headers=W3sibmFtZSI6IkNvbnRlbnQtVHlwZSIsInZhbHVlIjoiYXBwbGljYXRpb24vanNvbiJ9XQ==

**Comment by ReiSuzuki** [comment]
Hi @Onokaev, Yes it seems that I still am experiencing this issue. I sometimes get a 503, and sometimes a 504.

`{
    "error": {
        "code": "ServiceUnavailable",
        "message": " The call failed, please try again. The call failed, please try again. The call failed, please try again. The call failed, please try again. The call failed, please try again. The call failed, please try again. The call failed, please try again. The call failed, please try again.",
        "innerError": {
            "date": "2022-01-24T18:01:41",
            "request-id": "dc32d7ad-70fa-41c8-942f-b97a90cdca65",
            "client-request-id": "d28a0b98-c67c-20b7-563d-866a2492d84f"
        }
    }
}`
<img width="871" alt="Screen Shot 2022-01-24 at 11 04 53" src="https://user-images.githubusercontent.com/38015344/150839126-aab4bdad-4aba-4408-8796-e4124cf80746.png">

**Comment by Onokaev** [comment]
Hey @ReiSuzuki. I could not reproduce this error on my end. 
Try pressing 'shift+reload' on the page for a hard refresh.

If this doesn't solve the problem, post it on the Graph community page. There are devs who work on the Graph endpoints who will be able to guide you better.

**Comment by ReiSuzuki** [comment]
It looks to be a Graph issue as it has been intermittent. I'll close this out, thanks!
