### ISSUE TITLE
Suggestion: change documentation link icon against sample queries to a more intuitive icon

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/microsoft-graph-explorer-v4#1366]
**Is your feature request related to a problem? Please describe.**
Telemetry data indicate that the number of documentation link clicks compared to sample query runs is very low.

**Describe the solution you'd like**
Update documentation link icon to something more intuitive.
<img width="268" alt="image" src="https://user-images.githubusercontent.com/25274795/150840279-3a50e3d8-a169-428b-9c04-cc470c6fbc9e.png">

**Describe alternatives you've considered**
A different icon.
<img width="268" alt="image" src="https://user-images.githubusercontent.com/25274795/150840702-c3b7db3a-a74c-4d60-b44e-0f3e6577d5f5.png">

**Comment by millicentachieng** [comment]
@RabebOthmani, @adhiambovivian  Thoughts on this?

**Comment by adhiambovivian** [comment]
looks good to me @millicentachieng
