### ISSUE TITLE
[Resource Explorer] Add confirmation that a resource item has been added to the Postman collection

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/microsoft-graph-explorer-v4#1394]
Add confirmation that a resource item has been added to the Postman collection which would also help users who navigate with a screen reader.

Also, add an icon to show that an item has already been added to the Postman collection and remove the 'Add to collection' command.

**Comment by adhiambovivian** [comment]
@RabebOthmani  any thoughts on this one?

**Comment by darrelmiller** [comment]
I don't think there is a need for a confirmation.  The count of items in the collection gets updated when new items are added. I believe this is sufficient feedback.

**Comment by millicentachieng** [comment]
You are right, @darrelmiller.
