### ISSUE TITLE
[UI] Ensure Graph Explorer is responsive on common screen sizes 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1412]
As a user, I want an optimal UI experience no matter what device I'm using 
So I can fully take advantage of the tool and focus on my learning experience 

**Acceptance Criteria**

- [x] Define list of most used devices for Graph Explorer
- [x] Define list of common screen sizes
- [x] Produce design stylesheet covering all responsiveness scenarios ( resize, shrink, enlarge, hide, etc)
- [x] #1531
- [x] #1532

**Design Resources**
- [Fluent UI Type Ramp](https://www.figma.com/file/F5BN2yodUyHlOfpL4KJCFK/Fluent-Web?node-id=3252%3A0) 
- [Grid layout guidance](https://www.figma.com/file/clQChsWqYgK97iNEiSTajT/MADS-Guidance?node-id=1%3A2)
- [nav controls](https://admincontrolsdemoapps.blob.core.windows.net/release/admin-controls/46.0.5/index.html#/examples/nav)

**Comment by ElinorW** [comment]
- Common devices used include: phones, tablets, laptops and desktop monitors. 
- Screen sizes according to [this](https://www.figma.com/file/F5BN2yodUyHlOfpL4KJCFK/Fluent-Web?node-id=3252%3A0) would be: 
: 1920px for very large screens
: 1366px - 1919px for extra extra large screens
: 1024px - 1365px for extra large screens
: 640px - 1023px for large screens
: 480px - 639px - for medium screens

- We use bootstrap which already comes with the a set stylesheet covering all responsive scenarios.

**Comment by ElinorW** [comment]
Some screenshots to support this 
![image](https://user-images.githubusercontent.com/18407044/155296381-7e23d0ac-767d-4a5b-97b4-7a49425fb6bd.png)
_The full page is contained in the bootstrap container that comes with a grid stylesheet_

**Comment by RabebOthmani** [comment]
Hi @ElinorW @thewahome , I'll leave it to you to make the technical decision. Here are some of the things I saw that led me to assume it is maybe related to responsiveness. 
For example, the permission tab is not rendering properly and behaves differently between Edge and Chrome on the same machine. (cc @Onokaev ) 
The pane that contains the response, code snippets etc is not showing me all tabs on a 15" screen which is a very common screen . Also when you start zooming in/out, scrolling and expanding panes, a lot of the elements on the screen won't render properly (text boxes, button, etc) 
![permissions on chrome](https://user-images.githubusercontent.com/5781590/155968042-f26f7ce0-46aa-4639-9d80-98d7c9c36807.png)
![permissions on edge ](https://user-images.githubusercontent.com/5781590/155968072-77b6d21a-d855-414d-97ba-546b4dabeb08.png)
![resize](https://user-images.githubusercontent.com/5781590/155968333-c6ae853e-cce4-4c0c-9324-2901efd31e3d.png)

![feedback on zoom](https://user-images.githubusercontent.com/5781590/155968136-9ccf63d2-66d0-48a4-b2b4-2530f24178bf.png)

**Comment by RabebOthmani** [comment]
The recommendation from the UX team is to use 1873W x 947H 
More details here https://gs.statcounter.com/screen-resolution-stats

**Comment by gavinbarron** [comment]
@RabebOthmani @adhiambovivian @ElinorW this is a great discussion to be having and an area that we can improve on.
One thing that can make responsive design even more challenging is that Windows will set a default zoom level on high resolution screens that can cause your screen to render the page as though it were much smaller.
e.g. 
![image](https://user-images.githubusercontent.com/7122716/182446020-ab2ffb0d-35c3-47f6-b23e-1fa7a2960719.png)
Causes the GE page to render on my screen as though it were only ~1200px wide:
![image](https://user-images.githubusercontent.com/7122716/182446519-09fa01d5-6cc2-485f-980f-ceba30ba234b.png)

Given this it's really important that we ensure that we look at the effective resolution when raising this kind of issue.

**Comment by ElinorW** [comment]
This is completed now
