### ISSUE TITLE
[UI] Share button to move next to query

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1413]
As a user, I want the ability to copy my query url 
so that I can easily add it to my apps or use it with other tooling 

**Acceptance Criteria**

- Remove the Share button and replace it with copy icon (similar to what's on the snippets tab) 
- Add copy icon next to the query box
- Copy button should behave in same way as copy code snippet
- Both copy and doc icons should move outside the URL box.

**Expected UI**

<img width="838" alt="copy url" src="https://user-images.githubusercontent.com/5781590/152332929-f00b9bc7-95d5-4aaa-8a15-78de1c82771b.png">

This is an illustration of the desired outcome but not a final design.

**Comment by RabebOthmani** [comment]
@Onokaev  apologies for not following with this properly. How did we end up with a result way different from the initial requirement? Can you explain to me again why this button is on the right? And why it is so big? The idea was to have something similar to the info icon, small and crisp.

**Comment by Onokaev** [comment]
@RabebOthmani it's okay. 
We discussed it with you during the sprint check-in. We engaged the UX team and presented their suggestion during our mid-sprint check-in.
