### ISSUE TITLE
[UI] Ensure a consistent experience across browsers and OS

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1414]
As a PM, I want to ensure we have a consistence experience across browsers and operating systems
So that the users have a seamlessly experience

**Acceptance Criteria** 

- Conduct a thorough testing on the most used browsers and OS ( check dashboard telemetry for most used browsers) 
- Depending on findings, triage and work on fixes.

**Comment by adhiambovivian** [comment]
Moving to the next milestone as we improve our testing coverage & automation

**Comment by Onokaev** [comment]
When resizing the screen, the Query Runner and Response sections do not resize properly
![image](https://user-images.githubusercontent.com/45680252/158765363-17aa6aba-0481-427e-932c-f2cdab0a19f5.png)

**Comment by Onokaev** [comment]
#1561 This was on all browsers and has been fixed

**Comment by Onokaev** [comment]
![image](https://user-images.githubusercontent.com/45680252/161261914-13534711-f6e0-4324-b15c-be3e4487a6be.png)
Sidebar grey color is not consistent through out the whole sidebar length. This is intermittent in all browsers

**Comment by Onokaev** [comment]
![image](https://user-images.githubusercontent.com/45680252/161489091-78177ffb-a04b-4a87-8622-62559ccbb109.png)
Resizing the request section makes the response section overflow to the rest of the page
