### ISSUE TITLE
[UI] Replace documentation icon

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1419]
As a user, I want to have an intuitive UI 
so that I can navigate easily to documentation

**Acceptance Criteria**

- replace current documentation icon with [this icon](https://iconcloud.design/search/documentation/4fee22fb0-c4094e9ea)

- replace info icon next to query url with the[ documentation icon](https://iconcloud.design/search/documentation/4fee22fb0-c4094e9ea)

**Comment by millicentachieng** [comment]
Related to #1366

**Comment by millicentachieng** [comment]
We have the below icon for documentation.
<img width="148" alt="image" src="https://user-images.githubusercontent.com/25274795/154067102-5d91a6f1-91bc-4f55-b8e6-fc93521ef0b1.png">

The above icon seems more appropriate than the below.
<img width="197" alt="image" src="https://user-images.githubusercontent.com/25274795/154067506-34e3c0a3-9e2a-449b-ba4b-1dc35c1a4ad0.png">

**Comment by millicentachieng** [comment]
Also, for the info icon, are we planning on adding any other info other than documentation? I want to think that's why the documentation details are in the callout. If not, I suggest that we do away with the callout and link straight to documentation.
