### ISSUE TITLE
Custom Properties for Microsoft 365 Profile Card API in Microsoft Graph will not publish

### ISSUE THREAD

**Issue by jrodriguezLSI** [microsoftgraph/microsoft-graph-explorer-v4#1420]
Wanted to add custom field to MS365 profile card, ran the code and got an OK status, 24 hours later shows no change on our tenants profile cards. Trying to run the code again throws a 409 conflict error

https://docs.microsoft.com/en-us/graph/add-properties-profilecard

Expected custom attribute to be added to all my users profile cards, as shown in documentation

![image](https://user-images.githubusercontent.com/98982901/152419527-df9482c4-4d00-452b-9c91-a2a7857d47c3.png)

 - OS: Windows 10 Pro
 - Browser: Edge
 - Version: Version 97.0.1072.76

**Comment by jrodriguezLSI** [comment]
Has been some time, any guidance on this?

**Comment by millicentachieng** [comment]
Hello @jrodriguezLSI 

Thank you for reporting your concern. Unfortunately, we in the Graph Explorer team do not have any ownership of the APIs that are causing you issues. If you report this issue in the Microsoft Q&A forum, it will get routed to the appropriate team for them to triage.

https://aka.ms/askgraph
