### ISSUE TITLE
[Resource Explorer] Kebab menu style

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1424]
There is a weird behavior on the kebab menu, after clicking on it. It stays selected. It shouldn't. 

<img width="311" alt="selection on 3 dots " src="https://user-images.githubusercontent.com/5781590/152578440-a43cd612-d7de-4fb6-9d45-a5f2a73900ed.png">

**Comment by millicentachieng** [comment]
@RabebOthmani The blue border is an accessibility attribute that provides a visual cue when the button is in focus. This is especially essential for keyboard users to help them navigate the site. All clickable components on Graph Explorer have this behaviour. 

For now, I want to think that the best option is to only update the border to fit the area as in the screenshot below.
![image](https://user-images.githubusercontent.com/25274795/153778807-846c650c-6b6a-4024-9bbf-a1a49bf24b19.png)

Let me know your thoughts.

**Comment by RabebOthmani** [comment]
Hi @millicentachieng , could you please point me out to the accessibility guidelines, there must be a neater way to achieve this. Thanks

**Comment by millicentachieng** [comment]
Here's the [link](https://microsoft.sharepoint.com/sites/accessibility/SitePages/MAS-2.4.7-Focus-Visible-Guide.aspx?xsdata=MDN8MDF8fDEzMjFmMzJlZDViYzRhZTliMmE4MzgwY2MxOGNhOTdkfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2Mzc4MDUyNzc4NTU3Mzg5MzN8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT0%3D&sdata=R1hpYzVsN0RsbFNUUEhLUm00K0dtMm9hT2l5aFRnK3g2bHB3TGlPa212QT0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cmiachien%40microsoft.com&OR=Teams-HL&CT=1644931000720&sourceId=&params=%7B%22AppName%22%3A%22Teams-Desktop%22%2C%22AppVersion%22%3A%2227%2F22010300409%22%7D) to the guidelines.

**Comment by RabebOthmani** [comment]
@millicentachieng I consulted with the UX team. Are we using Fluent or Fast component here? It does look like the 'on selection' behavior is not what comes out of the box with the component. Could you please confirm? 
https://uifabric.azurewebsites.net/#/
https://explore.fast.design/components/fast-tabs

**Comment by millicentachieng** [comment]
@RabebOthmani, we are using Fluent.
