### ISSUE TITLE
[Resource Explorer] Search capability for all nodes of the tree

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1426]
Currently Search on resources only works on parents nodes, we should be able to search the entire tree. 

**Example**

<img width="218" alt="SA node" src="https://user-images.githubusercontent.com/5781590/152584447-ac2ebb73-7b13-4bbf-b878-53872812a5b8.png">

ServiceAnnouncement is available under Admin , if I search for it. I don't get any results. Expected behavior is to see the node in the search results 
<img width="272" alt="search result" src="https://user-images.githubusercontent.com/5781590/152584623-baf7ed47-c37b-4ce1-b544-3801f5bf5184.png">

**Comment by RabebOthmani** [comment]
@millicentachieng is this available for testing now? I can't see it on the Resource Explorer testing instance. Thanks

**Comment by millicentachieng** [comment]
@RabebOthmani, it's ready.

**Comment by RabebOthmani** [comment]
I tested. It looks good. This is going to be super useful and appreciated by the users. Great work @millicentachieng and @thewahome !

**Comment by millicentachieng** [comment]
Done. Awaiting deployment.
