### ISSUE TITLE
[Resource Explorer] Search box style 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1427]
Currently the search box looks like it has double border , interior border should go. 
<img width="272" alt="search box" src="https://user-images.githubusercontent.com/5781590/152584979-ed47a98b-9060-4dff-96cf-392914c5794f.png">

**Comment by RabebOthmani** [comment]
@Onokaev tested on sample queries using the test instance provided , it looks fine. I'm assuming it would behave in the same way with Resource Explorer.

**Comment by Onokaev** [comment]
Yes @Rabeb. The searchbox is the same on the sample queries and resources as well
