### ISSUE TITLE
[Bug] Toolkit tab is not working 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1429]
When you go to the Toolkit tab, this error appears. 
<img width="821" alt="toolkit" src="https://user-images.githubusercontent.com/5781590/152768292-f49e3a2d-61e4-4ccf-9f34-add0b5a34d8e.png">

**Comment by sebastienlevert** [comment]
Is fixed now. https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1516

**Comment by millicentachieng** [comment]
Issue resolved by MGT team.
