### ISSUE TITLE
Exporting History

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#144]
This is the download button under the history component on the side bar. When a user clicks this button, it triggers downloading of all the history of the queries this particular user has been querying in .har files.

![image](https://user-images.githubusercontent.com/4668452/64519465-d5149c00-d2fc-11e9-8cf4-b8f0c4d72805.png)

**Comment by thewahome** [comment]
We should think about having two options:
1. One at a time
2. Bulk export
