### ISSUE TITLE
Telemetry pipeline streaming errors 

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#1440]
**Describe the bug**
We are currently getting sev4 alerts related to GE telemetry pipeline streaming alerts. In the past, this has caused timeouts especially when it comes to updating the GE powerBI dashboards. Currently, these alerts are causing alert fatigue to the on-call devs
**To Reproduce**
I mostly get the alerts from IcM for this issue

**Screenshots**
![image](https://user-images.githubusercontent.com/9458079/153181657-e2692d47-c925-463c-92e8-6996d7357728.png)

**Desktop (please complete the following information):**
Not applicable

**Comment by millicentachieng** [comment]
The following actions were taken:
- Set alert sensitivity to low to reduce the number of alerts being sent out
- Increase the evaluation period from 5 minutes to 1 hour
- Create a new action group, GE action group local,  that doesn't send alerts to IcM but sends an email to local engineers. Failures are not business-critical and can be addressed at a later time without loss of data.
