### ISSUE TITLE
[Code Snippets Tab] Add more useful information to the sample 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1449]
As a user, when I'm looking at a code sample
I would like to see documentation links 
So I can easily access everything I need to build my apps 

**Acceptance Criteria** 

- The code snippet should include comments. 
- Comments to add : // Leverage the power of our client libraries. Download the <language> client library here <url> 
                                  // To read more about our SDKs, go to the documentation page at <url> 

- All URLs should be shortened ( aka.ms/ ) 

![snippet example](https://user-images.githubusercontent.com/5781590/153435582-94d3e51a-8356-45a0-87e0-d4bf0fbc3fe5.png)

**Comment by Onokaev** [comment]
Currently waiting for help on shortening links on the aka/ms tool
