### ISSUE TITLE
Cannot use Graph Explorer when I have MFA

### ISSUE THREAD

**Issue by i-m-batman** [microsoftgraph/microsoft-graph-explorer-v4#1450]
**Describe the bug**
Does not do MFA - so deniced access

**To Reproduce**
1. Log in with an Azure AD account that has MFA turned on
2. Try to run a Graph API

**Expected behavior**
Prompt for MFA when logging in to Graph Explorer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97

**Additional context**
results returned (404)
    "error": {
        "code": "Unauthorized",
        "message": "Additional claims required {\"access_token\":{\"capolids\":{\"essential\":true,\"values\":[\"d5f8fe6b-0605-40b8-9e25-e37a364553f3\"]}}}",
        "innerError": {
            "date": "2022-02-10T15:36:43",
            "request-id": "859efc1f-7a89-48be-b658-864a93702632",
            "client-request-id": "c04cf16c-53e9-f96c-6902-795bdff01915"
        }
    }

**Comment by Onokaev** [comment]
Hey @i-m-batman, sorry about this. 
Were you able to log in?
The error response you have included suggests you logged in but couldn't access some resources in your tenant because of permissions restrictions. Which query did you run when you got this error?

Please add some screenshots for more context

**Comment by i-m-batman** [comment]
I was able to get in later, but not sure why it happened (sorry). Should know better and have snagged screenshots.

I will update if it happens again (with pictures)

thanks for getting back to me.
