### ISSUE TITLE
Faulty display on Adaptive cards 

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#1452]
**Describe the bug**
Adaptive Cards isn't displaying a user's data

**To Reproduce**
1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
2. Click on 'GET my profile'
3. Click on 'Adaptive Cards' tab

**Expected behavior**
Adaptive cards should show the users info

**Screenshots**
![image](https://user-images.githubusercontent.com/18407044/153565754-6d8b2276-b360-4f65-acca-d89bed827053.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Edge

**Additional Notes**
Problem is consistent on all queries that have an adaptive card response available

**Comment by sebastienlevert** [comment]
A PR was sent to the Adaptive Cards team to update to the latest templating engine. https://github.com/microsoft/adaptivecards-templates/pull/296

**Comment by ElinorW** [comment]
Issue resolved by the Adaptive Cards team.
