### ISSUE TITLE
Reset password with beta java SDK

### ISSUE THREAD

**Issue by jsandeepm** [microsoftgraph/microsoft-graph-explorer-v4#1453]
Reset password with beta java SDK giving error:

I got same error from Java code.

https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%2F4265d44b-9513-4c2c-860d-3b0996ebcc0c%2Fauthentication%2FpasswordMethods%2F4265d44b-9513-4c2c-860d-3b0996ebcc0c%2FresetPassword&method=POST&version=beta&GraphUrl=https://graph.microsoft.com&requestBody=eyJuZXdQYXNzd29yZCI6Im5ld1Bhc3N3b3JkLXZhbHVlIn0=&headers=W3sibmFtZSI6IkNvbnRlbnQtdHlwZSIsInZhbHVlIjoiYXBwbGljYXRpb24vanNvbiJ9XQ==

Screenshot of Graph explorer:
![image](https://user-images.githubusercontent.com/9821180/153600837-2f69e4ea-63e3-4913-9cd4-86eaeab5f91c.png)

**Comment by ElinorW** [comment]
Hi @jsandeepm, 

Looks like you are using a personal account, but you can correct me if I'm wrong.
This type of query is currently not supported on personal accounts, only work and school accounts are supported at the moment. 
You can find this information in the docs here: [passwordAuthenticationMethod: resetPassword](https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http)

**Comment by jsandeepm** [comment]
Thank you for clarifying the doubt. I will work with my Work account.

you can close the ticket.
