### ISSUE TITLE
[Telemetry] Investigate success/fail rates for Autocomplete 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1460]
As a team, we need to understand how the different endpoints are behaving 
so we can better serve our customers

**Acceptance Criteria**

- Investigate the reasons behind the high failure % with Autocomplete. 
- Determine set of actions based on the investigation results.

![image](https://user-images.githubusercontent.com/9458079/156524489-0cdb9789-3532-4064-a566-9571f65626a4.png)

![image](https://user-images.githubusercontent.com/9458079/156524562-e5514539-ac6d-448e-b3e9-cffba0102ad5.png)

**Comment by thewahome** [comment]
Closing this as a document has been provided with the results of the investigation
