### ISSUE TITLE
Speed up autocomplete suggestions

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#1465]
**Is your feature request related to a problem? Please describe.**
For the resource explorer to work, the application fetches a links only subset of the open-API description. We can leverage this since it is local and can reduce the calls made to the api

**Describe the solution you'd like**
Only check the API for query parameters since they do not come in with the open-API description loaded on page load. Since the links are already available, simply check in state to get the next part of the url. e.g. `me/` should yield a list straight from the state and not from a network call

**Describe alternatives you've considered**
Keeping it as is. No complaints have been made so far about the number of network calls

**Additional context**
Reducing network dependency would make autocomplete search faster

**Comment by thewahome** [comment]
This implementation would change the endpoint from autocomplete to openapitree . Closing it as it limits the functionalities we can receive from the autocomplete endpoint

**Comment by adhiambovivian** [comment]
@thewahome  what's our current autocomplete performance and what's our target baseline performance?

**Comment by thewahome** [comment]
I've seen calls take 400ms. With this method we can get them down to 0
