### ISSUE TITLE
Graph Explorer reports error when requesting the /me/calendarView with set time zones.

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/microsoft-graph-explorer-v4#1470]
**Describe the bug**
Graph Explorer reports error when requesting the /me/calendarView with set time zones.

**To Reproduce**
1. Go to https://aka.ms/ge
2. Enter the following query : https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=2020-01-01T19:00:00+05:30&endDateTime=2022-01-01T19:00:00+05:30
3. See error

**Expected behavior**
The URL should have been encoded and should return a similar response to the following :

```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('{id}')/calendarView",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=2020-02-01T19%3a00%3a00%2b05%3a30&endDateTime=2022-03-01T19%3a00%3a00%2b05%3a30&$skip=10",
    "value": [
      //...
    ]
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7620955/154722247-4182eea4-f32a-4f7c-9e50-04afe3cb9b80.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Latest

**Comment by sebastienlevert** [comment]
Would be related to the following SDK issue : https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/529

**Comment by Onokaev** [comment]
The endpoint does not recognize plus signs. All plus signs are converted to spaces as seen in the postman call below
![image](https://user-images.githubusercontent.com/45680252/156533798-1af2a153-b9b7-4b70-b464-9402db5e2d80.png)

Encoding the plus signs before making the API call works
![image](https://user-images.githubusercontent.com/45680252/156533875-0e51eaf1-f57e-46e2-bb9a-eda9f3f2f7af.png)

This is therefore not an SDK issue, but a service issue

**Comment by adhiambovivian** [comment]
@darrelmiller  any thoughts here?

**Comment by Onokaev** [comment]
> @adhiambovivian, I really feel a Graph Developer should be able to get any http calls and use Graph Explorer to get their data. In this specific case, it doesn't allow a developer use this endpoint with these filters. @RabebOthmani, thoughts?
> 
> Encoding shouldn't be left to the devs, especially in Graph Explorer...

Hey @sebastienlevert. This issue is specific to a service. I think the best course of action would be to track down the service owners and have them fix it on their end.

**Comment by Onokaev** [comment]
We currently expect developers to encode parameters that require encoding. Until we can have a decision on where exactly to encode parameters (client, sdk), we will close this issue.
