### ISSUE TITLE
Microsoft Graph API mailboxsettings not working with MailboxSettings.Read permissions in Exchange Hybrid

### ISSUE THREAD

**Issue by kogniewski** [microsoftgraph/microsoft-graph-explorer-v4#1478]
**Describe the bug**
Microsoft Graph API mailboxsettings not working with MailboxSettings.Read permissions in Exchange Hybrid. Works ok with Exchange Online, but in Hybrid environment works only with MailboxSettings.ReadWrite permissions.

**To Reproduce**
1. Go to Graph Explorer and log in to a tenant in Hybrid configuration.  
2. Run query: https://graph.microsoft.com/v1.0/me/mailboxsettings with MailboxSettings.Read permissions
3. See error: Forbidden 403. You need to consent to the permissions on the Modify permissions (preview) tab:
"ErrorAccessDenied","Access is denied. Check credentials and try again. REST APIs for this mailbox are currently in preview. You can find more information about the preview REST APIs at https://dev.outlook.com/."

**Expected behavior**
You should view settings in json format, just like when connecting to non-Hybrid instance:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('4bb9ee0b-ttt-422c-tttt-c516f91b22ac')/mailboxSettings",
    "archiveFolder": "AAMkADNiOGMyMDk0LWY3NTQtNDkyttttYjZmLWZlZmI4NjgyYmEzZQAuttttAABPF9miwsdIQ4rhf22EFWVlAQCqxa32onW-QJmttttwRCAvAAE5B5LSAAA=",
    "timeZone": "Central European Standard Time",
    "delegateMeetingMessageDeliveryOptions": "sendToDelegateOnly",
    "dateFormat": "",
    "timeFormat": "",
    "userPurpose": "user",
    "automaticRepliesSetting": {
        [...]
    },
    "language": {
        "locale": "pl-PL",
        "displayName": "Polish (Poland)"
    },
    [...]
}

**Screenshots**

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
@kogniewski it looks like this is resolved.
When you open the modify permissions tab and click consent on the `MailboxSettings.Read` permissions, you will be able to run this call successfully. 

Please confirm if that is not the case for you
