### ISSUE TITLE
GE returning 400 for some user profile queries

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#1491]
When user profile data is requested against GE (for some users) the request runs successfully from the network tab, but GE returns a 400 error to the user without displaying query results.
**_Query to test:_** 
https://graph.microsoft.com/beta/users/**SomeUser**@microsoft.com/profile

_**From network tab the query is successful**_
![image](https://user-images.githubusercontent.com/9458079/155378068-4789e9f9-7fd4-45f4-b9fd-35854980a5af.png)

_**From GE page, the query returns 400**_

![image](https://user-images.githubusercontent.com/9458079/155378418-57762dd3-87da-41c2-ac68-1f14725877b8.png)

**Comment by thewahome** [comment]
We triaged and troubleshot this. 
Should it be closed @adhiambovivian ?

**Comment by adhiambovivian** [comment]
works now both on Postman & GE
