### ISSUE TITLE
Replace language headers with icons (instead of text , let's use the language icon) using Fluent UI icons.

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#1493]

**Comment by ElinorW** [comment]
@RabebOthmani I have a few questions/concerns about this issue. 

1. Would the tab only have the icons without the text? or would they be alongside each other?
2. Also, some languages (e.g Objective-C) don't really have an official icon
3. Objective-C and Go icons don't exist in the Fluent UI documentation. In this case, should we just leave the text?

**Comment by RabebOthmani** [comment]
Hi @ElinorW ,
1/ the icons would replace the text so we save on space and make more beautiful. Let me know if you need me to share a screenshot from other documentation portals.
2/What's the process to request icons? Is that something we can do? If not, can we get approval to use the official language icon available online?

**Comment by ElinorW** [comment]
> Hi @ElinorW , 1/ the icons would replace the text so we save on space and make more beautiful. Let me know if you need me to share a screenshot from other documentation portals. 2/What's the process to request icons? Is that something we can do? If not, can we get approval to use the official language icon available online?

Okay, thanks. 
I haven't seen any provisions on how one can request icons, their documentation doesn't provide that. Perhaps we may need to get in touch with someone from the team

**Comment by bruceburge** [comment]
Please do not do this, icons are not an effectively replacement for text description, having usability should likely trump "beauty" in a utility that is often needed for rapid prototyping and API exploration.  I doubt most users want to have to attempt to figure out what each icon means, and its functionality.

**Comment by adhiambovivian** [comment]
Thank you @bruceburge  for your feedback on this one. Tagging our PM, @RabebOthmani

**Comment by adhiambovivian** [comment]
+1 @bruceburge on this one. @RabebOthmani  it's generally mentally tasking to figure out what icons mean. I have seen other tools use both text and icon which captures the best of both worlds
![image](https://user-images.githubusercontent.com/9458079/171607825-ac7cfbf5-1289-4f59-8178-9b876fd56b1a.png)
