### ISSUE TITLE
Add Telemetry to V2

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#150]
We currently have the following two options for adding telemetry: 
1. 1DS
2. JSLL

@jobala implemented telemetry in GE classic using JSLL but since the long term plan is to move all telemetry work to 1DS, we are going to start implementation of telemetry in V2 using 1DS. 

The telemetry should capture the following data: 

1. Errors
2. Track queries are frequently called. 
3. Track reception of the new features e.g. integration to code snippets and adaptive cards.
4. For code snippets, track if users copy the code and what code snippet is frequently copied.
5. For adaptive cards, track if users click on the link taking them to the adaptive cards design page

**Comment by thewahome** [comment]
Closing because we renamed to v4 :-)

#150
