### ISSUE TITLE
Modify error message banner for 403 Forbidden

### ISSUE THREAD

**Issue by Jackson-Woods** [microsoftgraph/microsoft-graph-explorer-v4#1518]
**Is your feature request related to a problem? Please describe.**
Request to change the error message that appears when the user receives a 403. The error message tells the user to consent additional permissions for Graph Explorer (the client app), but many 403s are the result of failed checks on the signed-in user's privileges, so no consent can solve the issue.

**Describe the solution you'd like**
Modify the error message text as follows:

"You need to consent to the permissions on the Modify permissions (preview) tab" --> "Either the signed-in user does not have sufficient privileges, or you need to consent to one of the permissions on the Modify permissions (preview) tab"

**Describe alternatives you've considered**
N/A

**Additional context**
![GE-403-screenshot](https://user-images.githubusercontent.com/34143250/156512834-d4117ebe-8630-4c7d-be07-6b09b255519b.png)

**Comment by RabebOthmani** [comment]
@thewahome @darrelmiller can you please explain to me how's the error message implemented here? I'd like to know whether @Jackson-Woods suggested fix would be enough or if more work is needed

**Comment by darrelmiller** [comment]
Yes, changing that message should be sufficient.

**Comment by RabebOthmani** [comment]
@adhiambovivian  just want to confirm that we are working on this ticket? I see it's still assigned to me
