### ISSUE TITLE
Add a warning if User Consent has been blocked

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#152]
Jeremy pointed out that while looking at NPS OCV dashboard 

https://ocv.azurewebsites.net/#/triage/?filters=%7B%22OcvAreas.IdPath%22:%5B%223cfe4d8d-be46-4267-bf83-444fdc9824ff%22%5D,%22ActionabilityScore.raw%22:%5B%22High%22,%22Medium%22,%22Low%22%5D,%22OcvAreas.LabelState.raw%22:%5B%22Unreviewed%22%5D%7D&offset=-29&q=&relDateType=day&searchtype=OcvItems&t=Actionable%20Feedback%20To%20Review

1 out of 10 votes with "Never works... always get permission errors (requestdenied) despite having permission granted." unfortunately they didn't leave their contact details. Darrel Miller suggested it may be MSIT tenant folks.  may be we should showing a warning when people use their microsoft.com accounts with Graph Explorer to say MSIT block it?

Darrel:    It would be great if we could in general detect if User Consent has been blocked so that we can warn people GE is going to be fairly useless.
(1 liked)<https://teams.microsoft.com/l/message/19:a710d75161804aecaf3ef3bc3239b1e6@thread.skype/1566939514954?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=1fc2aa55-29ee-4d2e-90cc-4b2ffa6c4f7e&amp;parentMessageId=1566939514954&amp;teamName=Graph Client Tooling&amp;channelName=Graph Explorer&amp;createdTime=1566939514954>

some companies prevent permissions from being consented. SIgn into Graph Explorer and try and get Graph Explorer to do any of the write permission scopes, you won't be able to consent them. 
[AB#7518](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7518)

**Comment by Onokaev** [comment]
#1060
