### ISSUE TITLE
Adjust the current pipeline to send the build drop to the portal team

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#1523]
Utilise azure pipeline  to share built code with the team

**Comment by ddyett** [comment]
@thewahome what's the block on this?

**Comment by thewahome** [comment]
We need to migrate to torus. @MIchaelMainer has a document that describes the steps we need to take and the repercussions of what the compliance team needs from us. Like moving to AzDo
