### ISSUE TITLE
[Resource Explorer] Not all tabs are showing 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1524]
When I go to Graph Explorer, I don't see all the tabs on the left side (sample queries, resources, history) 
This was a requirement on https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1411 
When the user first arrive to Graph Explorer, we should make it easy for them to notice all the features available to them 
![missing tab ](https://user-images.githubusercontent.com/5781590/156604335-f5dfd873-aee6-45a9-b5f9-456ec57946ef.png)

**Comment by thewahome** [comment]
Hello @RabebOthmani this is an expected experience for people with one or a combination of smaller screens / large zoom fonts / low resolution. The page resizes itself to fit the screen settings of the user and adds the "three dots" to allow someone to pick more of the items that can not be immediately displayed.

**Comment by RabebOthmani** [comment]
As discussed @thewahome  , I'm happy to tackle this as new feature/requirement.

**Comment by ddyett** [comment]
treating as new feature request rather than blocked as discussed above.

**Comment by gavinbarron** [comment]
Looks like the overflow case for the left-hand pane occurs when the screen is < 1500px wide.
I think our best course of action here is to get some telemetry about what resolutions our users are viewing the site in to help guide our effort and determine if this is a widespread issue or one that's simply impacting a user who has great influence on the work being done.

**Comment by ElinorW** [comment]
@gavinbarron telemetry suggests a large number of users use devices >=1366px wide.
Therefore I believe we can address this issue
