### ISSUE TITLE
Unable to query organization branding

### ISSUE THREAD

**Issue by MubDubs** [microsoftgraph/microsoft-graph-explorer-v4#1528]
**Describe the bug**
When attempting to query my organization branding from resource graph, it gives an error stating: "Request_ResourceNotFound". 

**To Reproduce**
1. Go to Resource Graph Explorer
2. Type in https://graph.microsoft.com/v1.0/organization/ID/branding
3. Scroll down to "Response Preview"

Note: I'm able to query "https://graph.microsoft.com/v1.0/organization/" fine

**Expected behavior**
The expected behavior is that the response should provide details on my current branding. 

**Screenshots**
![2022-03-04 09_01_05-Graph Explorer - Microsoft Graph — Mozilla Firefox](https://user-images.githubusercontent.com/75283373/156777148-564feb72-c589-44fc-9526-4c74ad80208e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 97.0.1 64-bit

**Comment by darrelmiller** [comment]
According to the documentation, if branding has not been setup, then a 404 will be returned,

```
If successful, this method returns a 200 OK response code and an [organizationalBranding](https://docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-1.0) object in the response body. If no default branding object exists, this method returns a 404 Not Found response code.
```
https://docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-1.0&tabs=http

I would suggest doing a PATCH/PUT to branding to try setting values and then see if you can retrieve them.

**Comment by ElinorW** [comment]
Hey @darrelmiller 
I tried running a PATCH to update the details but I still got the same error where it appears that the resource isn't found.

**Comment by ranok** [comment]
@ElinorW You need to create the OrganizationalBranding object before you can change it. If you have a specific localization in mind, you can use [these instructions](https://learn.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-1.0&tabs=http) to create it. If you are trying to create the default (0) localization, you cannot specify that as an `id`, but if you omit the `id` entirely it will create the default one, then you can use PUT/PATCH to update/add stream objects.
