### ISSUE TITLE
401 on /places/microsoft.graph.room

### ISSUE THREAD

**Issue by matiasdevin** [microsoftgraph/microsoft-graph-explorer-v4#1529]
QUERY: https://graph.microsoft.com/v1.0/places/microsoft.graph.room

Exceuted in Graph Explorer Loggedin with a global admin account

when performing the query it returns 401
"error": {
        "code": "UnknownError",
        "message": "{\"code\":\"Unauthorized\",\"message\":\"There was a problem calling the proxy call\"}",

The strange thing about this is that 2 days ago it worked perfectly

**Comment by ElinorW** [comment]
Hey @matiasdevin,
I am unable to reproduce this as it returns a 200-Ok on my side. 
Could you confirm if this is still the behavior?
