### ISSUE TITLE
Exported Postman Collection from Resource Explorer creates a two level hierarchy

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#1536]
Previously, the exported Postman Collection created a flat list of request objects.  It has since been changed to create a grouping based on the first path segment.  This caused Hidi to stop being able to parse the Postman Collection.

The Postman collection should reflect the UI experience and as that is currently a flat list, so should the Postman collection.

We should discuss whether both the UX and the Postman collection should introduce some level of nesting and how much?

**Comment by thewahome** [comment]
As agreed offline, we will export a flat list until the need for nesting arises
