### ISSUE TITLE
Graph Example title is misleading

### ISSUE THREAD

**Issue by bruceburge** [microsoftgraph/microsoft-graph-explorer-v4#1550]
**Describe the bug**
The example is titled "all the items in my drive" what it is doing "List children in the root of the current user's drive"

The example would be far more useful, and far less confusing, if it did actually return all items. 

**To Reproduce**
1) goto graph explorer
2) click on "all the items in my drive"

**Expected behavior**
get "all the items in my drive"

**Additional context**
I know the easiest answer would be to change the name of the example, but if you want these examples to be meaningful, including more complex results would be better.

**Comment by RabebOthmani** [comment]
@adhiambovivian Please correct me if my assumptions are wrong. But the samples get populated by the workloads

**Comment by MaryannGitonga** [comment]
@bruceburge, the behavior you’re noting with the sample query is the one documented here [https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#response](https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#response).

For performance reasons, the response will return a batch of 200 items but you can access the rest of the items by following the @odata.nexLink property in the response. Therefore, in effect, the sample query provides all the drive items. With that said, I appreciate your point that this is not the clearest. So, changes will be made to rename the name of the endpoint from "all the items in my drive" to "list items in my drive".
