### ISSUE TITLE
https://graph.microsoft.com/v1.0/reports/getEmailActivityUserCounts(period='D7') does not work in MS Graph Explorer

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-explorer-v4#1575]
**Describe the bug**
When making the following call using MS Graph Explorer its trying to redirect to download the report. It looks like MS Graph Explorer is not doing the redirect.
GET https://graph.microsoft.com/v1.0/reports/getEmailActivityUserCounts(period='D7')

https://docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityusercounts?view=graph-rest-1.0#response
If successful, this method returns a 302 Found response that redirects to a preauthenticated download URL for the report. That URL can be found in the Location header in the response.

**Expected behavior**
MS Graph Explorer to perform the redirect and download the report (CSV)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Issue occurs in both Edge and Chrome
 - Version 99.0.1150.39 

**Additional context**
There is also an issue with loading the "Modify Permissions" for "https://graph.microsoft.com/v1.0/reports/getEmailActivityUserCounts(period='D7')"

Workaround is to use "https://graph.microsoft.com/v1.0/reports/getEmailActivityUserCounts" to load the Modify Permissions

**Comment by millicentachieng** [comment]
@irvinesunday Please see permissions problem mentioned in this issue.

**Comment by millicentachieng** [comment]
@willfiddes,

Queries that result in a redirect to a download URL do not work on Graph Explorer due CORS policy. The query will however work in a backend service or API client like Postman. For now, Graph Explorer will only display this information when such a query is encountered.

Also, thank you for reporting the permissions problem. We have a fix that is being tracked here: https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/948
