### ISSUE TITLE
Request headers info isn't present on code snippets

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#1657]
**Describe the bug**
In cases where queries have some request headers, the code snippets don't display some header information

**To Reproduce**
1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
2. Click on the **Applications** group
3. Scroll down to 
![image](https://user-images.githubusercontent.com/18407044/162921173-982eae22-6731-4f2a-940a-0e0b1316ca8b.png)
5. Click on the **code snippets** tab and view _CSharp_ tab
6. See missing header information

**Expected behavior**
Some of the snippets e.g the CSharp one should show information about the headers

**Screenshots**
This is how it appears on the snippets
![image](https://user-images.githubusercontent.com/18407044/162920617-4cc34d1e-9bf6-402d-875c-42f57c9acc67.png)

This is how it should appear (according to the [docs](https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=csharp#code-try-13)) --> **Notice the missing header**
![image](https://user-images.githubusercontent.com/18407044/162920923-6fd0a5b3-07d8-4f2b-9cc5-fc9d154984fe.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: MS Edge

**Additional context**

**Comment by RabebOthmani** [comment]
@ElinorW @adhiambovivian upon conversations with Darrel, we should be showing the headers info.

**Comment by millicentachieng** [comment]
Please note that some headers, e.g. `Authorization`, may contain sensitive data and their values should be redacted prior to calling DevX API for snippets.

**Comment by darrelmiller** [comment]
@millicentachieng None of the HTTP snippets will ever include the Authorization header.  If there are extra headers shown in the HTTP snippet then we should include them in the code snippet.   However, headers like Content-Type and Content-Length can be ignored in most cases.
