### ISSUE TITLE
Invalid URL - sample queries

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1660]
While doing some testing, I found out that one of the sample queries has an invalid URL. 
Do we validate URLs on the GE side or DevX API? What and how do we validate? 
![invalid url space](https://user-images.githubusercontent.com/5781590/162991894-30cd05a3-8f56-4dc1-8f2d-220ca2726302.png)

**Comment by Onokaev** [comment]
We do it on the GE side. It displays this error if there is space within the the url. Spaces are only allowed on the search parameters, leading part of the url ( *space*https://... ) and trailing part of the url as long as there are no search parameters (https:... (*space*)).

**Comment by Onokaev** [comment]
This particular url is triggering that error message because there is space between 'id', '|' and 'userPrincipalName.

**Comment by Onokaev** [comment]
https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/949
