### ISSUE TITLE
Property "phones" of orgContact on GraphAPI can't be selected

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/microsoft-graph-explorer-v4#1666]
**Describe the bug**
When trying to select the property "phones" the graph does not return anything besides the odata info

**To Reproduce**
1. Create orgContact
2. Give orgContact phone number
3. Try to select phone number of orgContact

**Expected behavior**
phones property should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/45571948/163335173-3883ea48-14f4-4c40-9aa7-79a608ed4835.png)
<img width="633" alt="image" src="https://user-images.githubusercontent.com/45571948/163335301-f3ba7f76-4f32-4435-a9b9-541428b7cbfe.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/45571948/163335350-4b36ef1e-ac4a-477e-ac8e-21c8ad49895c.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser crome
 - Version 100.0.4896.88

**Comment by ElinorW** [comment]
Hi @MichaMican, 
This seems to be an issue with the Graph API. Please share it in the Q&A forum and it shall be routed to the proper team.
