### ISSUE TITLE
Fix the NPS scale to align with OCV scale

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#1667]
![image](https://user-images.githubusercontent.com/9458079/163344744-e3130d5d-b5b5-468c-aa83-73a8163048c7.png)

**Comment by ddyett** [comment]
@adhiambovivian can we get an update on this bug please?  It's assigned to three people so it's unclear who may be addressing it?

**Comment by adhiambovivian** [comment]
@ddyett  there is a PR already out for it, it's on this issue thread.

**Comment by ddyett** [comment]
Thanks @adhiambovivian i completely missed it
