### ISSUE TITLE
[Header Area] Design and Styling enhancements on the header area

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#1688]
The header area needs some design, styling and layout enhancements to make it intuitive, responsive and accessible.
Tracking these here.

- [x] #1683 
- [x] #1686
- [x] Make sample queries, history items and resources cover the full sidebar length #1709 
- [x] #1714 
- [x] Remove scrollbar from the settings items 
- [x] When signing in, the spinner and 'signing you in' message are not properly aligned 
<img width="151" alt="image" src="https://user-images.githubusercontent.com/45680252/167368347-a841c00c-60f3-4be1-b915-ab073b9a47a6.png">

- [x] Bottom part needs some alignment
- [x] Add a border around the sidebar component
- [x] Add an icon on Tenant info part 
- [x] Add hovering effect on the header buttons
- [x] #1738
- [x] #1761 
- [x] #1769 
- [x] #1799  - Breaking change. Reverted

**Comment by Onokaev** [comment]
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/1682
