### ISSUE TITLE
Integrate Request builder library to GE V2 ( Implement the resource explorer functionality)

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#169]
Related to #343 

**Is your feature request related to a problem? Please describe.**
At the moment, the user needs to memorize the query they want to run as there's no help provided to build a query in Graph Explorer

**Describe the solution you'd like**
The 2019 interns in the Graph Identity team build a request builder library as part of their internship project under Saurabh. The library is ready and this task seeks to integrate the library to Graph Explorer V2

**Describe alternatives you've considered**
Integration to Graph Explorer v2, but we would have to deliberate on the design to agree where the request builder UI will sit, preferably, it should be a tab next to request headers tabs

**Additional context**
N/A
 
[AB#7520](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7520)

**Comment by thewahome** [comment]
@ddyett @bettirosengugi 
Is this still required seeing that we now have autocomplete?

**Comment by bettirosengugi** [comment]
@thewahome This is now part of the resource explorer work, so will rename the issue to mirror that.
