### ISSUE TITLE
Running a search query with application permissions

### ISSUE THREAD

**Issue by ilyalehrman** [microsoftgraph/microsoft-graph-explorer-v4#1733]
**Describe the bug**
When running a Graph query (search, specifically) with application permissions, the query comes back with error:

"SearchRequest Invalid
Region is required when request with application permission."

**To Reproduce**
1. Register an application in Azure AD
2. Grant it appropriate permissions (Sites.Read.All, Files.Read.All, TermStore.Read.All / delegated & application)
3. Get access token for the registered app using clientid, secret, tenantid
4. Query Graph Search API using access token from step 3

**Expected behavior**
Expected to receive search results per search query

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Edge
 - Version: Version 101.0.1210.39 (Official build) (64-bit)

**Comment by ElinorW** [comment]
Hi @ilyalehrman,
Could you share with me the exact query you tried to run that resulted in the error you've described above.

**Comment by ilyalehrman** [comment]
> Hi @ilyalehrman, Could you share with me the exact query you tried to run that resulted in the error you've described above.
attached (path URL modified w/ generic values): 

[query.txt](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/files/8700024/query.txt)
