### ISSUE TITLE
'Isolate' on Resource Explorer not working 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1751]
For any given resource on Resource Explorer, when you click on Isolate, you don't see the children for that resource. 
Instead, it shows the following 
<img width="295" alt="isolate " src="https://user-images.githubusercontent.com/5781590/170026513-f4dc0579-c453-4e1f-a079-3892ce157fdb.png">

For now, let's disable the isolate functionality.

**Comment by thewahome** [comment]
This has been closed by this PR: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/1741 by @Onokaev
