### ISSUE TITLE
Remove 'Returning users' from telemetry dashboard

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1752]
Currently the way 'returning users' is measured, doesn't give an accurate reflection of the real number of users who keeps coming back to Graph Explorer. To avoid any confusion, can we please remove that number from the dashboard.

**Comment by adhiambovivian** [comment]
@millicentachieng  how do we measure returning users?

**Comment by millicentachieng** [comment]
@adhiambovivian Returning users are those with more than one session on Graph Explorer. A session on AppInsights is counted after half an hour of user inactivity.

Also, worth noting, is the number of users is also not 100% reliable. If a user accesses the site from multiple devices or different browsers, they will be counted as different users each time. Browsing incognito or regularly deleting or blocking cookies will have users logged as new each time they visit Graph Explorer.

@RabebOthmani, I am quite adamant about removing the measure, rather we should probably review it and come up with a scenario that works best for us.

**Comment by RabebOthmani** [comment]
@millicentachieng The reason why I asked for it to be removed is because it's misleading as you, yourself explained how it's implemented. 
Over the past months, this value never exceeded 11% which is very worrying but then again it's a reflection of a portion of users who are using the same device, same browser. In comparaison, we have 60% signed in users. 

I'd like to have a view on returning users but we can't leave a value that's up to interpretation out there. Is there a way to get more accurate value?

**Comment by darrelmiller** [comment]
@ddyett Can we remove the returning users metric until we have a clear understanding of how to generate a useful value?

**Comment by ddyett** [comment]
@adhiambovivian can you link the underlying bug to fix this issue and comment on the timeline for the fix.  If for some reason we can't fix this quickly and there's no redeeming value in it then it makes sense to remove it (with a tracking bug or backlog work item to support the functionality).

**Comment by millicentachieng** [comment]
The dashboard has been updated.
