### ISSUE TITLE
[Auto-Complete] Add dropdown list for public API version segment 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1771]
As a user, 
I want to see a dropdown list with the public API versions for me to choose from 
<img width="233" alt="api version" src="https://user-images.githubusercontent.com/5781590/171175260-bfd197fb-01e3-4c4b-8470-1f4014227e82.png">

**Comment by thewahome** [comment]
This is also described in #715

**Comment by thewahome** [comment]
Looks like this is a popular request #682

**Comment by RabebOthmani** [comment]
@thewahome the user can type anything random for a version and yet they can see auto-completion and even run a query. They should only be able to have beta and v1.0 as versions, anything else they should get an error 
<img width="301" alt="fake version " src="https://user-images.githubusercontent.com/5781590/179030189-f1048bf6-1ec6-4807-823a-bd387bbb7b68.png">
<img width="637" alt="run fake " src="https://user-images.githubusercontent.com/5781590/179030438-0d7ec9a2-eb83-4ed7-9619-472126275711.png">

**Comment by RabebOthmani** [comment]
@thewahome keep this on hold. I need to follow up with some teams internally. Potentially there might be a need to type anything as a version.

**Comment by RabebOthmani** [comment]
@thewahome This is all good, we need to keep the current behavior. I'm closing the ticket.
