### ISSUE TITLE
[Auto-Complete] Hide the 'more info' button

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1772]
Will hide for now until we rethink the info we want to provide there.

**Comment by adhiambovivian** [comment]
@RabebOthmani  any particular reason why this feature needs to be hidden ? I personally use it to discover the documentation for queries ie it shortens the journey of having to look for documentation related to a particular query. My recommendation is that we add telemetry for this feature and see the current usage metrics around it

**Comment by darrelmiller** [comment]
@adhiambovivian The button only works to discover documentation for ~1% of Graph URLs.  If the user happens to try it on a URL that does work, it sets the user up with the false expectation that it will work for all URLs and then they will find that it doesn't work for almost everywhere.

**Comment by RabebOthmani** [comment]
@thewahome  as per my comment above, I want us to hide the button temporarily until we have a complete picture of what it should look like and do. 
Currently, as an example if I have https://graph.microsoft.com/v1.0/me/activities and I click on the info button nothing happens. I can see that you logged an[ issue to surface the documentation ](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1854) . I'd rather we ensure we have the documentation before setting false expectations for the user.

**Comment by ddyett** [comment]
I'm not a fan of pulling a feature in production especially without knowing if anyone leverages it.  At this point this has been out for a while.  How about treating it like an experiment and adding indication that this is experimental and may not always work reliably.  Then as this is now live prioritize above any other feature work adding in the telemetry to validate the experiment. Then you can determine that the feature usage for this is so low we are deprecating it quickly or not.  Also gives anyone using this regularly at this point indication we might deprecate.

Does it work for the top 50-100 most used urls?

**Comment by darrelmiller** [comment]
It only works for urls that happen to have been used in samples, and if the sample includes a doc URL.

I understand the reluctance to remove a feature in prod, but it is not clear to me what this feature is for. As far as I know it was never spec'd out and discussed by the team. I would have expected us to add doc links to resource explorer as is currently done in the samples tree.  Taking up real-estate in the url textbox is less than ideal considering how limited the space is already.

If we really do want to keep it, can we at least fix the overlapping border when we hover over the (i) symbol. It currently appears broken.

**Comment by thewahome** [comment]
@darrelmiller  I've added telemetry to help us see how useful it is so that it is easy to make that decision.

I can work on the border so that it doesn't overlap the way it does

**Comment by darrelmiller** [comment]
@thewahome Great, thanks.  Can you help me understand how the telemetry is setup to enable our decision as to whether this is the best place to expose documentation links?

**Comment by thewahome** [comment]
@darrelmiller there is telemetry collected when someone clicks the more info button that launches the popup. The click together with a sanitised URL is collected so that we can know what URLs make people curious about the other information available

**Comment by RabebOthmani** [comment]
@ddyett  when on Resource Explorer and I select a query, the query box gets populated and the button is disabled. If I'm using autocomplete and adding anything after /me for example , the button is disabled and not doing anything 
<img width="285" alt="disabled info " src="https://user-images.githubusercontent.com/5781590/177606765-52f6072b-f25d-442d-b897-7a001fcee9e6.png">

**Comment by RabebOthmani** [comment]
Hi @adhiambovivian , I'm not clear on the reason why this ticket moved to parked. Can you please help me out? This is part of the auto-complete set of work and it's important to be done to be able to ship auto-complete.

**Comment by kristenwomack** [comment]
Can we please see the telemetry on this? This is a confusing experience and the behavior of the button is inconsistent (sometimes nothing happens when I click on the info icon).

**Comment by thewahome** [comment]
We will do #2150 to confirm how the button is doing
