### ISSUE TITLE
[Auto-Complete] Investigate why auto-complete is not working for non-GET queries and make necessary fixes

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1773]
This appears to be a bug. Upon investigation and requesting context, there is nothing in the original implementation that would stop auto-complete from working with non-GET queries.
The ask here is to confirm if this is a bug, in which case we should fix it.

**Comment by thewahome** [comment]
Autocomplete fully depended on the links provided by making a call to the autocomplete endpoint. Part of the payload is a links property that has all the paths we can use. These links are only present in the get segment of the response.

From consultations with @irvinesunday there was no need to also place the paths in the other methods. This for us means that we can assume that the paths available in the get method are available in the other methods.

**Comment by thewahome** [comment]
This means that the approach to fixing it should assume that the autocomplete options are available for all methods
