### ISSUE TITLE
[Auto-Complete] Investigate the validation of URL using ABNF syntax 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1775]
Currently, our only validate white spaces in URLs ( to be confirmed with developers). 
The aim is to have a full on validation using the ABNF syntax

**Comment by Onokaev** [comment]
Yes. We currently only raise invalid whitespace error.
What kind of extra validation are we looking at @RabebOthmani? ABNF is very general

**Comment by darrelmiller** [comment]
@Onokaev  ABNF itself is generic,  but this ABNF description https://github.com/oasis-tcs/odata-abnf/blob/main/abnf/odata-abnf-construction-rules.txt is specific to validating OData.  It contains specific syntax rules for OData URLs including validating query parameter values.

**Comment by RabebOthmani** [comment]
@Onokaev Do you feel like you have clarity on the task with the link provided by Darrel? Let me know if you need further details

**Comment by Onokaev** [comment]
Hey @RabebOthmani, @thewahome picked this up since he is already working on autocomplete.

**Comment by thewahome** [comment]
I am closing this since the investigation was successful and documented in a technical document. 

A PR exists that attempts to implement the findings for this under #2044
