### ISSUE TITLE
[Auto-Complete] Accurate error messaging 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1776]
This story is dependent on the validation story. 
Once we get the validation in place, we need to work on an accurate error message for each case.

**Comment by adhiambovivian** [comment]
@RabebOthmani  more details on what 'accurate' error message mean in context to what we have today in GE

**Comment by millicentachieng** [comment]
@RabebOthmani Nudging you to provide more information about this issue.

**Comment by RabebOthmani** [comment]
Hi @millicentachieng , as mentioned in the story details, this is related to https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1775 
I see @thewahome is working on both now. Charles did we make a progress on the validation? Thanks
