### ISSUE TITLE
AuditLog.Read.All permission is not available to consent inside of the Modify Permissions (Preview) tab

### ISSUE THREAD

**Issue by raidenGitHub** [microsoftgraph/microsoft-graph-explorer-v4#1782]
**Describe the bug**
A clear and concise description of what the bug is:

AuditLog.Read.All permission is not available to consent inside of the Modify Permissions (Preview) tab

**To Reproduce**

1. Login to Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer),
2. Try to run the query: "GET https://graph.microsoft.com/beta/users?filter=signInActivity/lastSignInDateTime le 2021-07-21T00:00:00Z"

3. The query produces the error: 
3. A. "Calling principal does not have required MSGraph permissions AuditLog.Read.All"
3. B. "Forbidden - 403 - 637ms. You need to consent to the permissions on the Modify permissions (Preview) tab"

4. Switch to the "Modify Permissions (Preview)" tab

5. AuditLog.Read.All permission is not available to consent. Several other permissions are listed but not AuditLog.Read.All.

**Expected behavior**
AuditLog.Read.All permission should be available to click the "Consent" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/16138546/171492136-89d6480a-4dde-472b-b041-f385d6684646.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by raidenGitHub** [comment]
Hi Support,
I have found the solution for this error message. 
The solution is to click on the 3-dots next to the user that is signed in, then select "Select permissions" and then grant the  AuditLog.Read.All permission.

![image](https://user-images.githubusercontent.com/16138546/171495863-da5e58b8-c8d3-4366-9d59-3fe8111eee24.png)

The error message for this could be modified  from:
"You need to consent to the permissions on the Modify permissions (Preview) tab"
to
"You need to consent to the permissions by clicking the thee dots on the left and then choosing, 'select permissions' and then grant the permission"

**Comment by darrelmiller** [comment]
@adhiambovivian  The problem here is the fact that we are missing permission metadata.  The work to fix this is ongoing and we should not use this error as signal to change the GE UX.
