### ISSUE TITLE
Browser end to end tests using playwright

### ISSUE THREAD

**Issue by Onokaev** [microsoftgraph/microsoft-graph-explorer-v4#1807]
Jest test runner which we use for unit tests is intended for unit testing an application's logic and components rather than for testing it for any DOM quirks it might encounter. For this, we are using a separate tool, (playwright), for browser end-to-end tests. 

We have also moved accessibility tests to run together with the E2E tests.

- [x] Write tests for anonymous scenarios
- [x] Write tests for authenticated scenarios
- [x] Write accessibility tests
- [ ] Run tests on Azure pipelines

**Comment by adhiambovivian** [comment]
@Onokaev  we will need to decompose this work-item

**Comment by Onokaev** [comment]
Working with the playwright team to figure out what the issue is with the authentication. Here is a recreation of the problem on codesandbox: https://codesandbox.io/s/unruffled-lehmann-i8bb1t?file=/src/tests/sample_spec.js
