### ISSUE TITLE
Adjust tooltip message on the Modify Permissions tab

### ISSUE THREAD

**Issue by Onokaev** [microsoftgraph/microsoft-graph-explorer-v4#1811]
**Is your feature request related to a problem? Please describe.**
From feedback, the role that the Modify Permissions tab plays is unclear to most of our users.

**Describe the solution you'd like**
Adjust the message so that it lets users know that they can use the Modify Permissions tab to give consent to permissions for GE to make calls on their behalf.
Currently, the message shown is: 'This feature is in Preview and might not currently show all permissions for some queries'. This assumes that users already know what the button does. 
![image](https://user-images.githubusercontent.com/45680252/172332713-d6d2c705-4502-425d-a1b9-61c867fc6fac.png)

We can have a message like: 'Use this tab to give consent to permissions for the app to make calls on your behalf. Note that this feature is in Preview and might not show all permissions for some queries'.
![image](https://user-images.githubusercontent.com/45680252/172333092-243eded8-c006-4a75-b0d3-d7b533b82511.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by ddyett** [comment]
does the feature team want to do this?

**Comment by ElinorW** [comment]
This may need some redesign since we no longer have the tooltip

**Comment by ElinorW** [comment]
Closing as the tab is no longer in preview
