### ISSUE TITLE
https://graph.microsoft.com/v1.0/subscriptions

### ISSUE THREAD

**Issue by racsonavi** [microsoftgraph/microsoft-graph-explorer-v4#1822]
**Describe the bug**
GET  https://graph.microsoft.com/v1.0/subscriptions is not working.  it's returning an empty array even though I have successfully created several subscriptions.

**To Reproduce**
1. Log into graph account on postman
2. pass token to the api
3. run api  GET https://graph.microsoft.com/v1.0/subscriptions
4. See response =>  "value": []

**Expected behavior**
It should bring the list of subscriptions created

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome latest version, postman latest versioni]

**Comment by adhiambovivian** [comment]
@Onokaev - I also noticed on the demo tenant, the subscriptions endpoint does not return any data.

**Comment by Onokaev** [comment]
I have tested this endpoint and can confirm that it is not returning the subscriptions. 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/45680252/173817988-f4ec9e6c-5c2f-4b75-ab95-4dbc1efd5bf2.png">

<img width="906" alt="image" src="https://user-images.githubusercontent.com/45680252/173818126-0e06e2aa-5788-45e5-a7d4-32619ec7b0b5.png">

**Comment by Onokaev** [comment]
@adhiambovivian the endpoint returns data for active subscriptions only. The subscriptions themselves have a time limit of about 400minutes. To have this data on the demo tenant would mean that we have to update the subscriptions every 400 minutes.

**Comment by Onokaev** [comment]
Hey @racsonavi. The engineering team has been notified of this issue and they are currently fixing it. You can follow the conversation here: 
https://docs.microsoft.com/en-us/answers/questions/890310/the-subscription-endpoint-returns-an-empty-array-e.html?childToView=893199#answer-893199
