### ISSUE TITLE
Include 'Connect-MgGraph -Scopes <permission>' for PowerShell Code snippets

### ISSUE THREAD

**Issue by dweverett** [microsoftgraph/microsoft-graph-explorer-v4#1826]
**Is your feature request related to a problem? Please describe.**
Issuing an MS Graph API call shows how to use the corresponding PowerShell cmdlet to perform that task, when the admin clicks "Code snippets" > PowerShell.  The example generated even includes which module to import.  What it lacks, and causes the command to fail, are the permissions that are required for the command to work. This forces the frustrated admin to have to locate the API documentation again in order to determine the permissions that are required. Once they know the permissions, they must re-authenticate with Connect-MgGraph while specifying the correct -Scopes.

**Describe the solution you'd like**
 In addition to showing the Import-Module command, the "Code snippet" for "PowerShell" should also include Connect-MgGraph -Scopes <permissions> that will allow the command to run.

**Describe alternatives you've considered**
There is no alternative unless we want to continue to force frustrated admins to have to look for the API docs page so they can look up the permission. Giving them the scope will also help drive MS Graph PowerShell adoption.

**Additional context**
N/A

**Comment by Onokaev** [comment]
Hey @dweverett. Sorry about this.
A quick way to locate permissions for any query is on the Modify Permissions tab: 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/45680252/175929510-85c426fb-b423-438d-94dc-0b5445b4e42f.png">
Also, to quickly locate docs, there is a button on the extreme right of the query textbox which takes you to the correct documentation
<img width="395" alt="image" src="https://user-images.githubusercontent.com/45680252/175930292-50f99d91-45cd-4fda-90f8-9cffd6a7aec4.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/45680252/175930398-07186139-c8e6-4662-bb26-df42f9cc0544.png">


I understand that you prefer to have the scopes pre-populated on the cmdlet. Let me escalate this as a feature request and tag the appropriate teams.

**Comment by Onokaev** [comment]
Hey @dweverett. For now, permissions required for specific request urls are on the Modify permissions tab. Whenever they are not available on the tab, the next option is to check the documentation through the 'Learn more' button. 
Appending scopes to the snippets will cause a subpar experience in cases where there are quite a number of scopes to consent to.
