### ISSUE TITLE
Share button have both tooltip and title property on it 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1839]
The Share button seems to have both a tooltip and title property on it. 
We should keep only one depending on the decision that will be made after consulting with the UX team. 
<img width="173" alt="double tooltip " src="https://user-images.githubusercontent.com/5781590/173611195-193808b3-0749-410e-8593-b46a877719da.png">

**Comment by ElinorW** [comment]
Fixed in #1821
