### ISSUE TITLE
Add support for unconsenting a permission

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#1844]
**Is your feature request related to a problem? Please describe.**
It is currently not possible from within Graph Explorer to remove a previously consented scope to test scopes with lower privileges.

- [x] Implement revoke consent
- [x] Enable tenant admins to revoke consent for tenant-wide permissions
- [x] Add a column for consentType
- [x] UI enhancements: Make 'Admin consent required' tab title wrap on small screens, Disable Unconsent button for users with no required permissions
- [x] Add info icon to Unconsent button and show consent-type column regardless of token being present

**Comment by RabebOthmani** [comment]
@adhiambovivian my plan is to do minimal UI/UX changes due to resources. We will rely on the current UI and make necessary changes on it.

**Comment by RabebOthmani** [comment]
@darrelmiller @adhiambovivian @MaryannGitonga @gavinbarron for the permissions tab, here's what I'm thinking. Please remember that the goal here is not to reinvent the UI and do minimum required work there. 
This is the current tab: 
<img width="686" alt="permissions tab old " src="https://user-images.githubusercontent.com/5781590/184172852-2ec6a394-e7e8-4d34-9ef4-e223a9fc05f1.png">
I'm thinking: 
<img width="715" alt="permissions tab proposal " src="https://user-images.githubusercontent.com/5781590/184172991-70f33513-4d6b-43c1-a426-7dff15f8195e.png">
so it would look something like this 
<img width="559" alt="permissions tab new " src="https://user-images.githubusercontent.com/5781590/184173068-67039946-2e15-4e34-991c-2ebc0aa0be7c.png">

**Comment by RabebOthmani** [comment]
@MaryannGitonga as for the actual implementation, what we need is to update oAuth2PermissionGrant to remove items (permissions in this case). 
@adhiambovivian  I'd suggest pairing Maryann with Evans or Elinor. Permissions are tricky to understand, let us give her the support she needs :)

**Comment by RabebOthmani** [comment]
@darrelmiller @gavinbarron @adhiambovivian @MaryannGitonga for the Permissions list under the user's profile. I captured some challenges with the current experience 

https://user-images.githubusercontent.com/5781590/184618287-4ade6cf7-3ee1-4f64-b12c-f7e2ebff9496.mp4

Similar to the permissions tab, is there any value of showing a count of the permissions selected? 
<img width="413" alt="number of permissions " src="https://user-images.githubusercontent.com/5781590/184618412-85fcd208-31f0-48ef-8967-17a5925d551a.png">

After some thought, do we want to encourage users to select a group of permissions? Isn't that against the recommendation to consent the least privileged whenever possible? @darrelmiller I'd love your opinion on this. 
My suggestions would be to remove the checkboxes, keep the list grouping and apply similar modifications to what we will apply on permissions tab (consent/unconsent button , yes/no admin etc)

**Comment by RabebOthmani** [comment]
How are we filtering the list of permissions cc @adhiambovivian 
<img width="425" alt="NA permissions " src="https://user-images.githubusercontent.com/5781590/184661955-58d5ff83-ba40-4c40-87ca-a9a5b06b93f7.png">
Family permission is hidden on Graph but it appears on the list. It shouldn't 
<img width="420" alt="family permissions" src="https://user-images.githubusercontent.com/5781590/184662118-00a4ef1a-4a17-4404-8b19-5669959be860.png">

**Comment by Onokaev** [comment]
While working on this, we noted some interesting things:
GE requires the User.Read permission  to make bare-minimum calls. What do we do in case a user unconsents to User.Read permission? Do we log them out? Do we restrict the ability to consent to such a permission?

Unconsenting requires the following permissions:
![image](https://user-images.githubusercontent.com/45680252/187236424-b9fdf1be-c2df-47b2-a25d-7815b119f657.png)
These permissions require admin consent before a user can consent to them. What do we do in such a scenario?

**Comment by gavinbarron** [comment]
I'm extrapolating a little here but it sounds like at an absolute minimum the user needs to have User.Read for some calls and there is no lower valid permission that can be consented to.
This is coupled with the fact that to unconsent to a permission Directory.Read.All is required.

Can we prevent these permissions from being unconsented and add a call out in the UI that User.Read and Directory.Read.All are the lowest permissions available to still have the GE application functional?

**Comment by MaryannGitonga** [comment]
@gavinbarron in that case, should `Directory.Read.All` (and `DelegatedPermissionGrant.ReadWrite.All` which is another permission required to enable unconsenting to permissions) be added to the list of default scopes that a user is consented to first off, on signing into GE?

**Comment by gavinbarron** [comment]
Great question, and I'm sorry to answer with another question.
What are the scopes we request on the initial sign-in at present? Are there permissions that require admin consent for a user to sign in? (My gut is that we do need admin consent being a multi-tenant app).

I'm hesitant to ask for those permissions until we absolutely need them, such as when a user wants to revoke consent for a scope just due to them having such wide reach.

As a good practice we should ask only for the minimum permissions necessary initially and then leverage incremental consent as needed.

**Comment by MaryannGitonga** [comment]
![image](https://user-images.githubusercontent.com/34104277/188101495-cc5dc353-f6ff-4a49-9e93-6d24ebc9b73b.png)
These are the default permissions.

The two permissions required for unconsenting require admin consent unlike the current default permissions. With regard to and appreciation of the principle of least privilege access, then the best option would be to let the user consent to them when they need to revoke a permission.

**Comment by gavinbarron** [comment]
I agree, thank you.

**Comment by RabebOthmani** [comment]
@Onokaev per our conversation today during the sync: 
* Can we please ensure that the requirements stated on this thread are followed (text content, UI, etc) 
* Consent to permissions modal should be consistent with the permissions tab. Action for me: Consult with the UX team to come up with a good filtering way. 
* Tested and the filtering is still not quite correct

**Comment by RabebOthmani** [comment]
@Onokaev  the consent/revoke button is the most important functionality on this screen and yet I can't see it properly. In comparaison the description is taking too much horizontal space. 
@gavinbarron could you please assist us with this . Thank you :) 
<img width="691" alt="permissions layout " src="https://user-images.githubusercontent.com/5781590/194274165-ee352591-dd14-4c3c-8acc-8669e3a46db6.png">

**Comment by gavinbarron** [comment]
@RabebOthmani happy to lend a hand here, although it looks like @Onokaev has added some text wrapping and a fix to ensure that the Consent/Unconsent button is not obscured by the scrollbar.
Not sure that there's much value for me to add on this.

**Comment by Onokaev** [comment]
> How are we filtering the list of permissions cc @adhiambovivian <img alt="NA permissions " width="425" src="https://user-images.githubusercontent.com/5781590/184661955-58d5ff83-ba40-4c40-87ca-a9a5b06b93f7.png"> Family permission is hidden on Graph but it appears on the list. It shouldn't <img alt="family permissions" width="420" src="https://user-images.githubusercontent.com/5781590/184662118-00a4ef1a-4a17-4404-8b19-5669959be860.png">

Hey @RabebOthmani. This filtering requires some work on the DevX API repo

**Comment by Onokaev** [comment]
Ticket tracking filtering of permissions: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1232
