### ISSUE TITLE
Tenant name does not appear when signing in as a guest user

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#1845]
# Steps to reproduce
- Access Graph explorer using tenanted URL  e.g.
https://developer.microsoft-tst.com/en-us/graph/graph-explorer?tenant=tavis.ca

- Sign in as a guest user to the tenant

# Expected
To see the tenant name in the header and in the user profile card.

# Actual

![image](https://user-images.githubusercontent.com/447694/174337727-77e20863-4ac2-4e16-8b04-d84395134209.png)

**Comment by ElinorW** [comment]
Hey @darrelmiller,
I am trying to reproduce this though I don't have a guest account. 
How can I create a guest account?

**Comment by ElinorW** [comment]
Got it, I have been able to reproduce this now. 

So, the first time I ran this, it was blank for me too... then after testing again, I got some tenant information
![image](https://user-images.githubusercontent.com/18407044/174612203-b51ef592-a865-40b0-9d1f-238cb05b1ea0.png)

could you try running it again and see if you'll get anything this time.

**Comment by ElinorW** [comment]
@adhiambovivian Could be because I have to make a separate network call to get tenant info... This info doesn't seem to be present on a user's account data

**Comment by ddyett** [comment]
@ElinorW is this really blocked or work we haven't gotten to yet.

**Comment by ElinorW** [comment]
@ddyett this isn't blocked, this should be in the backlog and can be worked on in the August milestone

**Comment by ElinorW** [comment]
This is resolved. For the tenant value I had to use a tenant ID as opposed to the tenant name 

https://user-images.githubusercontent.com/18407044/184647759-0f81994a-5eeb-470c-9514-6e0836b23517.mp4

**Comment by ElinorW** [comment]
This has been resolved also when with the use of a tenant name.

**Comment by iw-ed-gough** [comment]
I've tried using this today, and it is broken for both Tenant Id and Tenant Name
