### ISSUE TITLE
Error when write "+" inside the email on Get User by Email

### ISSUE THREAD

**Issue by raziel997** [microsoftgraph/microsoft-graph-explorer-v4#1847]
**Describe the bug**
when request get a user by mail and write a "+" inside the mail get an "UnknownError"

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'get user By Email'
3. Write in URL 'https://graph.microsoft.com/v1.0/users/random.mail+1@gmail.com'

{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2022-06-21T16:29:59",
            "request-id": "fab6e662-70ee-4ddc-839f-443d7e413cad",
            "client-request-id": "6753297a-5eda-2689-1cf7-de7d143c224a"
        }
    }
}

**Expected behavior**
must accept characters or respond with a message

**Screenshots**
![image](https://user-images.githubusercontent.com/81829004/174851950-b06149c2-0a21-4e4d-bea5-67f8fec31807.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome, safari

**Comment by Onokaev** [comment]
Hey @raziel997. What were you trying to achieve? 
I have noticed that the url is invalid. You can confirm the correct query url using the resources tab on the left side of the app. For instance, on users/ endpoint, here are the options that you have:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/45680252/174965341-4060e1d8-7d13-4997-96d9-a9c7f0cdcac2.png">


Also, the + character you have added is not allowed on email user names. Some characters you can use on user names are: !, #, ^, -, _
You can't use characters like: @, $, %, &, *, (, ). This is a list from trials that I made when creating a new outlook account.

**Comment by raziel997** [comment]
Im using "users by email"  and i understand we cant use this characters but we are getting a no Error Code, we just get an "UnknownError" so i think its just needed to add an error code that say we cannot use this special caracters

**Comment by Onokaev** [comment]
Sure @raziel997. I understand it's not the best experience not to get clear error messages. However, we cannot fix this on the Graph Explorer side. 
You can add the recommendation here: https://docs.microsoft.com/en-us/answers/questions/ask.html.
