### ISSUE TITLE
Show telemetry for feedback button on Power BI Dashboard

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/microsoft-graph-explorer-v4#1849]
Add telemetry for feedback button and the feedback submit button. Let's also capture dependency data for the POST request so to help us know when users can't submit feedback.

We also need to add telemetry for the NPS feedback pop up. Metrics captured should help us tell how many users had the pop up show up and what percentage of the users actually provided feedback.

**Comment by Onokaev** [comment]
Add telemetry for the feedback popup

**Comment by RabebOthmani** [comment]
@Onokaev @millicentachieng can you please provide more details on this work? is this a bug fix or new task? What telemetry are we adding here? thanks

**Comment by millicentachieng** [comment]
@RabebOthmani, @Onokaev  I've updated the description of the issue.

**Comment by Onokaev** [comment]
Hey @millicentachieng. What's the 'dependency data' and where do I get it?

**Comment by millicentachieng** [comment]
> Hey @millicentachieng. What's the 'dependency data' and where do I get it?

Hi @Onokaev, a dependency is any external resource that Graph Explorer calls, e.g. DevX API. You can read more about it [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies) on Azure Monitor.
