### ISSUE TITLE
Surface documentation about a URL in the query bar

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#1854]
**Is your feature request related to a problem? Please describe.**
Sometimes I paste/type in/ accept suggestions for a URL and I need to know where to find the documentation about the query. With a minimized sidebar or an already slimmed-down sidebar due to responsiveness, I can't easily find the documentation since the icon is hidden.

Sometimes I do not even know where to start checking so that I find the documentation.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/58787602/175259753-8b544ddc-2a6e-4296-8b4c-9870fd341970.png)

The more info button has been surfacing this but we may need to expand the source of documentation links so that it can support urls that are outside of the set of sample queries.

We could change it to a documentation icon so that it only gives us information about documentation instead

**Question**
Since the documentation on docs already has the http requests in them, is there a way to reverse search the docs so that we can get the links that are related to the URL?

**Comment by darrelmiller** [comment]
The work to make doc links made available in the OpenAPI description is ongoing here https://github.com/microsoft/OpenAPI.NET.OData/issues/230
