### ISSUE TITLE
Minor editorial fixes

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1855]
Our content writer reviewed the header and had some editorial suggestions: 

- Rename 'Graph Documentation' to 'Microsoft Graph API reference' or just 'API reference' 
- Rename 'Getting Started' to 'Get started' (lowercase s)
- Lowercase 'Preview' on the permissions tab

**Comment by adhiambovivian** [comment]
@RabebOthmani  do we still need 'preview' prefix on permissions tab?

**Comment by RabebOthmani** [comment]
@Onokaev No this is all related to the links we have on the header under help. 
@adhiambovivian Do you mind giving me context on why we have 'preview' on permissions in the first place? or maybe @ddyett has the context
