### ISSUE TITLE
The findMeetingTimes API always returns empty suggestions, reason:"OrganizerUnavailable"

### ISSUE THREAD

**Issue by henritzi** [microsoftgraph/microsoft-graph-explorer-v4#1856]
Hi,
I tried using the findMeetingTimes API (https://graph.microsoft.com/beta/me/findMeetingTimes) within the Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer) and the response is always "OrganizerUnavailable".

But the organizer (and the attendee) is available, has no out-of-office reply set and there are plenty of possible time slots free within the start and end dates.

I am logged in with my organisational account and tried it with the  V1 and Beta versions of the API.

**To Reproduce**
```
{
    "attendees": [
        {
            "emailAddress": {
                "address": "testuser@testdomain"
            },
            "type": "Required"
        }
    ],
    "timeConstraint": {
        "timeslots": [
            {
                "start": {
                    "dateTime": "2022-06-23T09:30:00",
                    "timeZone": "W. Europe Standard Time"
                },
                "end": {
                    "dateTime": "2022-06-30T09:30:00",
                    "timeZone": "W. Europe Standard Time"
                }
            }
        ],
        "activityDomain": "unrestricted"
    },
    "isOrganizerOptional": false
}
```

Response:
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#microsoft.graph.meetingTimeSuggestionsResult",
    "emptySuggestionsReason": "OrganizerUnavailable",
    "meetingTimeSuggestions": []
}
```

**Expected behavior**
The meetingTimeSuggestions of the response should be filled with possible meeting times.

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Version: 102.0.1245.44 (Official Build) (64-Bit)

**Comment by Onokaev** [comment]
Hey @henritzi. I have tested this with my organization and demo tenants and I am getting results. 
Is your attendee in the same time zone as the organizer(you)?

**Comment by henritzi** [comment]
@Onokaev Thank you for the testing. Yes the attendee is in the same time zone.

But the issue can be closed, it seems to have been a temporary error in the backend, the request is working again.
