### ISSUE TITLE
[Accessibility] Add pro-active accessibility checking workflows 

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#1883]
**Is your feature request related to a problem? Please describe.**
With an accessibility objective, we should improve our accessibility posture by pro-actively fixing issues as they arise and not wait for third-party investigations.

**Describe the solution you'd like**

Automated checking for accessibility issues:
- https://web.dev/accessibility-auditing-react/
- https://validator.w3.org/nu/?doc=https%3A%2F%2Fjolly-sand-0ac78c710-1852.centralus.azurestaticapps.net (compare this to the published site)
- https://www.npmjs.com/package/axe-core

Manual
- https://accessibilityinsights.io/docs/web/getstarted/fastpass/
- Running narrator
- Keyboard only use of GE

**Comment by ElinorW** [comment]
Hey @MIchaelMainer, 
we practice the manual testing in PR's
as for automated testing, we have one set up in the pipeline, this is in our [README](https://github.com/microsoftgraph/microsoft-graph-explorer-v4#testing-accessbility) and we use [Axe Accessibility Linter](https://marketplace.visualstudio.com/items?itemName=deque-systems.vscode-axe-linter) as part of our Vs Code extensions

**Comment by MIchaelMainer** [comment]
Solid. Glad to see this work.
