### ISSUE TITLE
Access denied with all permissions consented

### ISSUE THREAD

**Issue by bretthacker** [microsoftgraph/microsoft-graph-explorer-v4#1884]
**Describe the bug**
Using Graph Explorer to call /v1.0/me/onlineMeetings? with the joinWebUrl filter (per doc at https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http#example-3-retrieve-an-online-meeting-by-joinweburl) results in an error:
 "error": {
        "code": "Forbidden",
        "message": "An error has occurred.",
        "innerError": {
            "request-id": "fb1855de-06cf-49e3-91a9-7320b069d606",
            "date": "2022-07-03T02:08:14",
            "client-request-id": "f070758e-c479-c268-cbec-b3380e8ec6d2"
        }
    }

**To Reproduce**
Follow the doc as above.

**Expected behavior**
I expected to retrieve the results as articulated in the documentation.

**Screenshots**
Result screen showing call, consented permissions, and result:
![image](https://user-images.githubusercontent.com/693701/177021795-c260a2fa-e2fd-4428-ae0e-55d0ac971f9a.png)

scp in token:
![image](https://user-images.githubusercontent.com/693701/177021798-7a16a433-9601-4871-86f8-3c7e6c114a6a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 102.0.1245.44

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A

**Additional context**

**Comment by bretthacker** [comment]
An additional note: I created this onlineMeeting in Outlook by creating an event and adding Teams. I'm attempting to retrieve the resulting OnlineMeeting object by querying for the joinWebUrl presented in the event body. I'm logged into Graph Explorer with the same account I'm using in Outlook, so I should have organizer permissions on the onlineMeeting.

**Comment by ElinorW** [comment]
Hi @bretthacker,
Are you using a work or school account? or a Personal account?

**Comment by bretthacker** [comment]
Work or school, AAD, not personal.

**Comment by ElinorW** [comment]
Yeah, this could be an issue with the API itself. 
Could you kindly share this on the Microsoft Graph Q&A forum. The appropriate team will pick this up and get back to you

**Comment by bretthacker** [comment]
> Hi @bretthacker, Are you using a work or school account? or a Personal account?

Work or school
