### ISSUE TITLE
[Graph API] - Search query is returning duplicate elements when we use sortProperties for drive items

### ISSUE THREAD

**Issue by sahil1504001** [microsoftgraph/microsoft-graph-explorer-v4#1886]
**Search query is returning duplicate elements when we use sort properties for drive items.**

The search query is developed to get the XLSX files of the currently logged-in user.

**To Reproduce**
1. Open graph explorer.
2. Use the below query and request body
![image](https://user-images.githubusercontent.com/79520782/177160320-d3188cf0-7a69-4b98-b918-843195a8fc27.png)
3. Give all required consent permissions and click on "Run query"
4. The response I'm getting is as below and has mentioned the issue.
![image](https://user-images.githubusercontent.com/79520782/177158447-e07ece81-2d96-4868-b9cb-9790924eddfc.png)
5. Ranks 4 & 5 have the same XLSX file. this is impacting our application.

**Expected behavior**
It should not show duplicate objects.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version: N/A

**Additional context**
Also, tried to use trimDuplicate still its giving duplicates
Reference:- https://docs.microsoft.com/en-us/graph/search-concept-trim-duplicate

![image](https://user-images.githubusercontent.com/79520782/177153841-85be7584-37b8-4763-89cd-b19a292061ce.png)
3. Give all required consent permissions and click on "Run query"
4. The response I'm getting is as below and has mentioned the issue.
![image](https://user-images.githubusercontent.com/79520782/177158447-e07ece81-2d96-4868-b9cb-9790924eddfc.png)
6. Ranks 4 & 5 have the same XLSX file. this is impacting our application.

**Expected behavior**
It should not show duplicate objects.

**Note**: If we do not use sortProperties then its not giving duplicates it working fine.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version: N/A

**Additional context**
Also, tried to use trimDuplicate still its giving duplicates
Reference:- https://docs.microsoft.com/en-us/graph/search-concept-trim-duplicate

**Comment by ElinorW** [comment]
Hi @sahil1504001, 
I am currently unable to reproduce this. 
I will redirect you to the Ms Graph Q&A forum where you can post your question and receive some help from the team working on the search API.
https://aka.ms/askgraph
