### ISSUE TITLE
'Consent to permissions' link not showing up for some users

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1887]
Some external users reported not seeing the consent to permissions link under the user's avatar. 
An internal user also reported the issue but when they tried again, the link appeared!

**Comment by ElinorW** [comment]
Hey @RabebOthmani , 
I need some more details here to help me replicate this issue 
Browser used? version? device? OS?

**Comment by RabebOthmani** [comment]
This might be related to users expecting to see the permissions under Settings (as discussed during the feedback meeting). 
First step would be to surface the telemetry related to the header to help us make an informed decision whether to move the link under settings + discussion with UX cc @millicentachieng @ElinorW

**Comment by ddyett** [comment]
@ElinorW have we done this already.  Sounds like something we should prioritize unless we're confident users are not having an issue.

**Comment by RabebOthmani** [comment]
@ElinorW I'm closing this issue. It has not been reported again after the first days of releasing the header. The telemetry shows that users are finding the permissions link, in fact it is the most used feature on the header (latest data covering last 30 days , 40,559 event count on the permissions button). I believe it was a matter of users familiarizing themselves with the new header. cc @ddyett
