### ISSUE TITLE
[Telemetry] Surface header telemetry on the dashboard

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1892]
Can we please surface the telemetry related to the header components on the dashboard: 
* clicks on Settings 
* Clicks on Help 
*  clicks on sign in
* Clicks on feedback button
* Clicks on each link under Help
* Clicks on each link under Settings 
* Clicks on Consent to permissions 
etc

**Comment by ElinorW** [comment]
Seems like we do not track 
 - clicks on settings
 - clicks on help
 - clicks on sign in
 - clicks on sign in with other account
 
 Creating an issue to track this :

- [ ] Add Telemetry to track Button clicks on the header
