### ISSUE TITLE
Invalid whitespace in URL error in Graph Explorer with properly encoded URL

### ISSUE THREAD

**Issue by dotnvo** [microsoftgraph/microsoft-graph-explorer-v4#1893]
**Describe the bug**
When providing a properly formatted URL using %20 to represent a 'space', the Graph Explorer GUI indicates there is a invalid whitespace in the URL.

**To Reproduce**
1. Create folder in personal OneDrive called 'Test Folder'
2. Open Graph explorer, login, and grant proper permissions
3. In URL field use : https://graph.microsoft.com/v1.0/me/drive/root:/Test%20Folder
4. Error below URL field will say 'Invalid whitespace in URL'. However you can still click 'Run Query' and get a 200 response with data.

I provided a screenshot below to showcase the error and it still returning a response with data.

**Expected behavior**
with a properly encoded URL using %20 for spaces, I don't expect the error 'Invalid whitespace in URL'

**Screenshots**

![image](https://user-images.githubusercontent.com/29506123/177381050-4ffa1ed3-d88f-456d-9229-3354c54a5272.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 103.0.1264.44

**Comment by Onokaev** [comment]
This ticket is a repetition of the ongoing work on ABNF validation.
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2044
