### ISSUE TITLE
https://graph.microsoft.com/v1.0/sites API is returning 502 Bad Gateway

### ISSUE THREAD

**Issue by denisnigulas** [microsoftgraph/microsoft-graph-explorer-v4#1918]
**Describe the bug**
Unable to poll Microsoft Graph https://graph.microsoft.com/v1.0/sites API.  It is returning 502 Bad Gateway even though other APIs work fine and there are no permissions or other issue. API appears completely broken from the MS side.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Sign-in with credentials (i used Global Admin creds) that has Sites.Read.All
3. In the Sample queries list find 'Sharepoint Sites'
4. Select 'GET my organization's default SharePoint site'
5. Run Query

**Expected behavior**
This API endpoint is supposed to return information about my organization default Sharepoint site but instead I get
Bad Gateway - 502 - 112ms
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2022-07-12T02:48:46",
            "request-id": "81a213cf-8c39-4442-bd8f-7e964c690e8d",
            "client-request-id": "b8d5de76-1282-5090-48fe-a4ee923be096"
        }
    }
}

Same behavior is exhibited when polling API through Postman.

**Screenshots**
<img width="1585" alt="Screen Shot 2022-07-11 at 7 17 28 PM" src="https://user-images.githubusercontent.com/49700455/178398270-1b5d43e7-f0e4-427c-99e5-50e8511a68d7.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome
 - Version: 102.0.5005.61

**Additional context**
All issues point to a broken API on the MS side. Please repair ASAP as this is impacting our operations.

**Comment by Onokaev** [comment]
Hey @denisnigulas. I've just tested this and its working on my end.
![image](https://user-images.githubusercontent.com/45680252/178425214-5de993ac-8041-4bde-81bf-d859e43d50bb.png)
Are you still experiencing this issue?

**Comment by Onokaev** [comment]
Yes, it is. The error returned is confusing. However, this isn't an issue we can fix on Graph Explorer. 
For a wider audience, let me post this on the Microsoft Q&A side.

**Comment by Onokaev** [comment]
Here is a link to the issue I've opened on the Q&A side: https://docs.microsoft.com/en-us/answers/questions/951483/error-reporting-on-sitesroot-is-confusing-for-tena.html

**Comment by Onokaev** [comment]
From the Q&A response, this endpoint does not support personal tenants. This is the reason why you are getting 502s

**Comment by RabebOthmani** [comment]
@adhiambovivian @Onokaev  Looking at the thread above, it doesn't seem this ticket require any GE work.  Is there any particular reason for it to be added to august milestone instead of being closed?

**Comment by Onokaev** [comment]
Hey @RabebOthmani. Not really. Let me remove it from the milestone.
The bot will automatically close it tomorrow if there is no response from the author
