### ISSUE TITLE
Autocomplete errors on invalid Graph queries

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/microsoft-graph-explorer-v4#1919]
**Describe the bug**
An IcM alert was triggered for multiple errors reported calling the DevX API autocomplete endpoint.

Endpoint: _GET https://graphexplorerapi.azurewebsites.net/openapi?url=/{undefined-id}&style=geautocomplete&graphVersion=v1.0_
Result code: _404_

**Expected behavior**
The Graph URL is wrong, and thus the autocomplete endpoint should not have been called.
At what point do we use the cache to prevent multiple calls to the API?

**Comment by thewahome** [comment]
this is closed by the autocomplete work #1802
