### ISSUE TITLE
Add PHP to the Snippets tab.

### ISSUE THREAD

**Issue by SilasKenneth** [microsoftgraph/microsoft-graph-explorer-v4#1922]
**Acceptance criteria**

- Add preview text because Python SDK is still in preview
- Alphabetical order for snippets tab
- Add python SDK links & AKA links
- telemetry

**Comment by isvargasmsft** [comment]
Me here, without the -

**Comment by SilasKenneth** [comment]
Hi @adhiambovivian, yes the DevX API side is done,
You can test through.
[PR #1923  Deployment](https://jolly-sand-0ac78c710-1923.centralus.azurestaticapps.net/?devx-api=https://graphexplorerapi-staging.azurewebsites.net).
For the docs side, I will update you once I'm sure it is done.

**Comment by SilasKenneth** [comment]
Hi @adhiambovivian,
For the docs we are waiting for next week generation on Tuesday. For now we've created a draft PR just to show how PHP Snippets would look like on the docs.
[#17689](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17689)

**Comment by ElinorW** [comment]
This work has been reverted for now.
Waiting on the go ahead for which release/milestone shall include this work 

cc @adhiambovivian @RabebOthmani

**Comment by adhiambovivian** [comment]
@ElinorW  @SilasKenneth  this will be on-hold until we have the docs side complete, not sure about the PHP SDK feature parity and also updating the PHP download page to the latest information

CC: @RabebOthmani  @isvargasmsft
