### ISSUE TITLE
When width of window increases, URL textbox should expand to use all space and other controls remain fixed

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#1931]
Currently as the window gets wider, all the controls get wider proportionally.
![image](https://user-images.githubusercontent.com/447694/178985953-b2df4312-1f0a-4c84-ac0f-8f1f61d636b0.png)

![image](https://user-images.githubusercontent.com/447694/178986279-d178e219-d482-48d0-bf4b-1294f108fdc1.png)

As the URL textbox is the only control that contains variable length text, it should be the only control that gets wider, the other controls should remain the same width.  The fixed width controls should be resized to be the minimum width that can fit the text that is needed.  We need all the space we can get for the URL.

**Comment by Onokaev** [comment]
Hey @darrelmiller :). Let me add @RabebOthmani for direction on this requested change.
