### ISSUE TITLE
Info message inside response area

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1932]
The info message that used to be on the left side before adding the header area is now inside the response area. 

<img width="691" alt="info line" src="https://user-images.githubusercontent.com/5781590/179031324-999895e9-051e-4eb2-a4d0-67cf496c6db2.png">

**Comment by thewahome** [comment]
@RabebOthmani what's the ask here? It is not clear what the bug is
