### ISSUE TITLE
Permissions listed in the "Modified Permissions" tab are sorted alphabetically instead of by privilege

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#1933]
Need to investigate why these permissions are being re-ordered.  /cc @RabebOthmani

**Comment by RabebOthmani** [comment]
@darrelmiller https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1077

I just need to follow up with the right team

**Comment by RabebOthmani** [comment]
There's currently work to fix the issue and it's committed for this quarter.

**Comment by ddyett** [comment]
@RabebOthmani is this work on our team.  should this be assigned to a developer or linked to a devX api issue?

**Comment by thewahome** [comment]
This is closed by #2757
