### ISSUE TITLE
Code Snippets are not showing the construction of request bodies

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#1935]
e.g. 
![image](https://user-images.githubusercontent.com/447694/179354925-179c8bd8-20ad-4108-a574-141111babbf2.png)

I'm pretty sure we used to construct an object for request bodies.  Can someone investigate why we are not creating an example object based on the request body schema?  

@andrueastman Can you confirm my recollection that we used to do this?

**Comment by Onokaev** [comment]
We have tested this. When you edit the request body, the query isn't updated. This is why the changes you make to the request body are not reflected on the snippet response. 

A workaround for now is to run the query with the new request body. This will update the query and consequently return the correct snippet response with your new request body. 

We are fixing it :)

**Comment by ElinorW** [comment]
Hey @darrelmiller...
While testing this further... @Onokaev noticed there was an issue on the GE side with the snippets not updating when the request body is updated. 
Perhaps that's what is causing the issue above. 
This shall be fixed.

**Comment by ElinorW** [comment]
Closing this as this is currently not reproducible
