### ISSUE TITLE
Getting token details for MSA accounts fails since it's not a valid jwt token

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#1936]
**Describe the bug**
When you are signed in with an MSA Account, the JWT token redirection to jwt.ms is not able to open up the token and provide the details.

**To Reproduce**
1. Sign in with an MSA account
2. Click on the Auth tab and confirm the presence of an access token
3. Click on the json icon
5. See that there is no decoded information

**Expected behavior**
1. Hidden button when the user has an MSA account
2. Messaging that the details will not be visible and why

**Comment by ddyett** [comment]
blocked functionality.
