### ISSUE TITLE
Teams read and group read require admin consent

### ISSUE THREAD

**Issue by IsaacRoitman** [microsoftgraph/microsoft-graph-explorer-v4#1950]
Able to perform all needed operations using Graph Explorer, however Teams and Teams/Channel require admin consent (when Consent is clicked).

**Comment by Onokaev** [comment]
Hey @IsaacRoitman. It could be because your admin has restricted your access to teams endpoints/resources. 
Are you the tenant admin?

**Comment by IsaacRoitman** [comment]
This is related to our Microsoft internal tenant, most Graph functions work but some are not approved.

**Comment by Onokaev** [comment]
Was this working before? Which specific endpoints were you trying to access?
