### ISSUE TITLE
Investigate Canary endpoint failure

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1957]
It has been reported that canary is not working, thus preventing workloads from testing. 
We need to investigate the root cause of the failure and where it is exactly. For that we need a test tenant that can call Canary.

**Comment by darrelmiller** [comment]
I tested making a call to canary via VS Code RestClient and I see the same behavior as Graph Explorer on a tenant that isn't enabled for canary access.  Agree that we need to confirm the behaviour on a test tenant that is enabled for Canary

**Comment by uzarjuma** [comment]
@darrelmiller @RabebOthmani Can this be tracked internally on ADO? Thanks!

**Comment by darrelmiller** [comment]
@uzarjuma Graph Explorer is an OSS product tracked on GitHub.  We do not use ADO for tracking.  You can reach out to me internally to discuss further.

**Comment by RabebOthmani** [comment]
@adhiambovivian I'm adding this to the current milestone. Could we please make sure this is a priority as it's affecting internal teams. We just need to setup a test tenant for canary. Thanks!
