### ISSUE TITLE
Use Graph Toolkit implementation of Adaptive cards to show adaptive cards on GE V4

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#198]
**Is your feature request related to a problem? Please describe.**
The Microsoft Graph Toolkit is a collection of framework-agnostic web components and helpers for accessing and working with Microsoft Graph. All components can access Microsoft Graph without any customization required. This would be a great UI tool to compliment Adaptive cards and help developers learn and get access to great UI tools.

**Describe the solution you'd like**
Nikola created an implementation of Adaptive cards using Graph tool kit, you can find the code on this repo: https://github.com/microsoftgraph/microsoft-graph-toolkit/tree/nmetulev/adaptive-cards 

The code creates components like 'mgt-card' that accepts queries like below
`<mgt-card query="me"></mgt-card> ` 

This will fetch data from the me endpoint, ask your service for a template and then render the adaptive cards.
The requirement is to implement Adaptive cards in GE using Graph Toolkit then show developers the Graph Toolkit code we used for implementation. 

We shall reuse Adaptive cards tab to show the Cards and the Graph Toolkit UI components code used to render them. Under the tab, we can have two tabs, one that shows the visual and the other that shows the code complete with a copy button on top. The code shown will be the Graph Toolkit code with the components. 

Since GE is a learning tool, we need to show the developers the code and the results and make it easy for them to copy the code from GE.

**Describe alternatives you've considered**

**Additional context**

**Comment by jobala** [comment]
@bettirosengugi @jthake-msft 

Indeed Graph Explorer is a learning tool for Microsoft Graph and it's sdks. I think we are going to bloat it with features that are valuable to only a small percentage of our customers.

**Comment by jthake-msft** [comment]
The Microsoft Graph Toolkit is effectively a UI SDK, our SDKs are used by this tool.
We believe that the we can accelerate growth for web developers by using the Toolkit. That uses our SDK, Office UI Fabric, MSAL etc..
 
I would like to see Graph Explorer, as the most used part of our developer experience, tie things together that are under played or not well discovered. For instance, Graph Toolkit being brand new in v1.0 next week. And our tutorial and quick starts for instance. our videos that walk through conceptual things on Graph.
 
There are many things we can do on Graph Explorer to encourage deeper learning of graph than just clicking Run Query on a few samples.

**Comment by darrelmiller** [comment]
@jthake-msft  Can we consider MGT examples as a "HTML" code snippet ?

**Comment by bettirosengugi** [comment]
The Graph toolkit code that implements Adaptive cards has not been shipped yet and there's no set date when this will be done since focus has shifted. Therefore this issue cannot be implemented without this missing piece.
