### ISSUE TITLE
Being able to select the tenant for a given login

### ISSUE THREAD

**Issue by irwinwilliams** [microsoftgraph/microsoft-graph-explorer-v4#1982]
**Is your feature request related to a problem? Please describe.**
I have multiple Azure AD tenants associated with a given login.

**Describe the solution you'd like**
After sign-in, you should be able to select the tenant you want the graph explorer to focus upon

**Describe alternatives you've considered**
Modifying the graph explorer code to do it myself.

**Comment by ElinorW** [comment]
Hey @irwinwilliams ,
Do you mean you'd like something like this, where your other Azure tenants are displayed on the profile card?
![image](https://user-images.githubusercontent.com/18407044/182817007-adcb39c2-fe3e-4190-8844-610e208fff14.png)

**Comment by irwinwilliams** [comment]
I think so, thus explorer can query the correct AD.

**Comment by ElinorW** [comment]
This is in discussion, 
Meanwhile, you can easily switch tenants but selecting the "Sign in with a different account" option that's available on clicking the profile button.
![image](https://user-images.githubusercontent.com/18407044/183088690-2cfab787-5ee6-4c71-bc4f-7ad4c30808fc.png)

**Comment by superkat1111** [comment]
This was possible until recently using a querystring param but appears to have stopped working
e.g.
https://developer.microsoft.com/en-us/graph/graph-explorer?tenant=contoso.onmicrosoft.com

**Comment by irwinwilliams** [comment]
> This is in discussion, Meanwhile, you can easily switch tenants but selecting the "Sign in with a different account" option that's available on clicking the profile button. ![image](https://user-images.githubusercontent.com/18407044/183088690-2cfab787-5ee6-4c71-bc4f-7ad4c30808fc.png)

Oh, but I don't want to change the logged-in user, I want the logged in user to remain logged in, but change tenants.

**Comment by ElinorW** [comment]
> This was possible until recently using a querystring param but appears to have stopped working e.g. https://developer.microsoft.com/en-us/graph/graph-explorer?tenant=contoso.onmicrosoft.com

I'll look into this

**Comment by adhiambovivian** [comment]
Tagging @RabebOthmani  for review of the user experience

**Comment by ElinorW** [comment]
Hey @superkat1111 ,
I investigated the tenant querystring param issue... 
Seems like this can work with using the tenant ID instead of the tenant name.

**Comment by RabebOthmani** [comment]
@adhiambovivian at the moment, we are not implementing switching tenants. This is something that we will potentially review and prioritize in the future.

**Comment by darrelmiller** [comment]
@ElinorW @irwinwilliams  The tenant query parameter does still work with the tenant name.  @irwinwilliams  can you provide more details on how it failed for you?

@adhiambovivian Currently there is no way on Microsoft Graph for getting a list of tenants that a user can access.  We would need to investigate if there is an Azure API we can call to get this list.  I don't know if it is possible today.

**Comment by ElinorW** [comment]
@darrelmiller really? I must have been missing sth
I tried and recorded my outcome here.
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1845#issuecomment-1215036413
I'll retrace my steps and find out what I was missing

**Comment by irwinwilliams** [comment]
> 

Thanks, @ElinorW, I didn't know you could change the tenant in the URL and it just worked for me. I believe I should close this particular issue as that feature easily allows me to accomplish the goal. 
Cheers

**Comment by lsmith77** [comment]
I was now able to switch using the name using inconito mode.
