### ISSUE TITLE
TypeError: Ajv is not a constructor

### ISSUE THREAD

**Issue by irwinwilliams** [microsoftgraph/microsoft-graph-explorer-v4#1983]
**Describe the bug**
When attempting to run locally, via "npm start" I get:
TypeError: Ajv is not a constructor

**To Reproduce**
1. run npm install
2. run npm start
3. Observe this error in console, "TypeError: Ajv is not a constructor"

**Expected behavior**
Application starts

**Screenshots**

**Desktop (please complete the following information):**
 - OS: GitHub Codespace
 - Browser: chrome
 - Version 103.0.5060.134 (Official Build) (64-bit)

**Additional context**
Following advice on StackOverflow (https://stackoverflow.com/questions/71111343/typeerror-ajv-is-not-a-constructor-when-i-run-npm-run-build)  for that specific error, I downgraded the [mini-css-extract-plugin] package to 2.4.7 and the app started.

**Comment by Onokaev** [comment]
Hey @irwinwilliams. You should run the app with 'npm run start' not 'npm start'

**Comment by Onokaev** [comment]
Hey @irwinwilliams. Running 'npm run start' instead of 'npm start' will start the app without any errors. 
We are investigating why this is the case for 'npm start'
