### ISSUE TITLE
404 share links from Graph Explorer when URL includes query parameters

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-explorer-v4#1986]
The Graph Explorer "share" button generates a shareable link but I see the "value" part of the query string is replaced with a placeholder `<value>`. Unfortunately, customers are getting a 404 error for such links because the "<" and ">" symbols get encoded as well.

**Example: (Repro steps)**

- HTTP URL => https://graph.microsoft.com/v1.0/users?$filter=displayName eq 'Faith'
- Generated Shareable URL => https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3DdisplayName%2Beq%2B%3Cvalue%3E&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com 

I think if the intent is to not share sensitive values, maybe remove the "<"  ">" symbols and say "value" instead?

For example, the above link would be

https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3DdisplayName%2Beq%2Bvalue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

I'm also not sure it's appropriate to hide the values. I assume that a customer intending to share a shareable link either intends to share the link as-is or they are OK with sharing the test values publicly because they've already sanitized the value part of the query string.

**Comment by Onokaev** [comment]
Related to #1991

**Comment by Onokaev** [comment]
This has been fixed. It's in the coming release

**Comment by Onokaev** [comment]
#1993
