### ISSUE TITLE
Show code (JSON Schema) used to render Adaptive cards for developers to copy. 

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#199]
**Is your feature request related to a problem? Please describe.**
GE is a learning tool and therefore any technology we show on the tool, we should be able to let the developer how to use it as well.

That being the case, we should show the code used to render the adaptive cards on Graph Explorer. 
**Describe the solution you'd like**
Show the code used to render adaptive cards on GE.

Add 2 tabs below the adaptive cards tab, one should be named visual and the other code. The visual tab shows the adaptive card and the code tab shows the code used to render the card, and a copy button at the top of it to enable developers copy code from the tab. 
The code shown will be the JSON code used to generate the adaptive card. 
Then have an informational banner (just like in the Toolkit tab) redirecting users to the Adaptive cards playground: https://adaptivecards.io/designer/ if they want to learn more. 

Some code can be long, so the code tab should be scrollable, same to the cards tab since some cards can be so long or too many. 

**Describe alternatives you've considered**

**Additional context**

Related to #198  
[AB#6345](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6345)

**Comment by ddyett** [comment]
Test comment AB#4386
