### ISSUE TITLE
Wrong sharing link generated from a particular query

### ISSUE THREAD

**Issue by Licantrop0** [microsoftgraph/microsoft-graph-explorer-v4#1991]
If you try to generate a sharing link for this query:
```
https://graph.microsoft.com/beta/groups?$count=true&$filter=resourceProvisioningOptions/Any(x:x+eq+%27Team%27) and owners/$count eq 0&$select=id,displayName,visibility,classification,description,expirationDateTime,assignedLabels
headers: consistencyLevel=eventual
```

Then the generated link returns this error:
![image](https://user-images.githubusercontent.com/2388430/182439913-2050b068-9a85-48c8-86cf-fe7f9c1150de.png)

**To Reproduce**

1. Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
2. Paste `https://graph.microsoft.com/beta/groups?$count=true&$filter=resourceProvisioningOptions/Any(x:x+eq+%27Team%27) and owners/$count eq 0&$select=id,displayName,visibility,classification,description,expirationDateTime,assignedLabels`
3. Set headers `consistencylevel=eventual`
4. Run query (see that works)
5. Click the share button
6. Copy the link
7. Paste the link in another window

**Expected behavior**
the link is generated correctly

**actual behavior**
the url-decoded generated link is (see **wrong $filter parameter**)
```
https://developer.microsoft.com/en-us/graph/graph-explorer?
request=groups?
$count=true
&$filter=<unknown>+and++<unknown>+eq+<value>
&$select=id,displayName,visibility,classification,description,expirationDateTime,assignedLabels
&method=GET
&version=beta
&GraphUrl=https://graph.microsoft.com/
&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d
```

**Comment by Onokaev** [comment]
This has been fixed. It's in the coming release
