### ISSUE TITLE
Tenant name displays as 'Personal' when I am logged in with my Microsoft account 

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#1998]
**Describe the bug**
The Tenant label displays 'Personal' instead of 'Microsoft' when I am logged in with my Microsoft account.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Sign in with your Microsoft tenant
3. Observe 'Tenant Personal' 

**Expected behavior**
The tenant name should be 'Microsoft'

**Screenshots**
![image](https://user-images.githubusercontent.com/18407044/182637657-464c4392-d107-4644-b2a2-af3c5a26a9c2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Comment by ElinorW** [comment]
Seems like the '/beta/me/profile' endpoint returns a 200 with an error and thus affecting some queried user information.
![image](https://user-images.githubusercontent.com/18407044/182641385-4f685753-737e-4800-8c55-326c9f5ec77a.png)

**Comment by RabebOthmani** [comment]
adding a P1 label as we started receiving feedback around the issue @adhiambovivian
