### ISSUE TITLE
Unfriendly Auto-complete editing experience 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2005]
With the new work done on Auto-complete , it now tried to complete on every key press not just the slash making the editing experience challenging. 
Feedback received from a user:" entering a query is now broken. for each character typed into the query box, a suggestion is fetch and that locks and hangs the UI. We cannot type a query anymore." 

Also note that when fetching suggestions, the substring search is done while it should be a 'starts with'

**Comment by RabebOthmani** [comment]
Selecting options from the drop down list doesn't work in a consistent way and not as expected sometimes 

https://user-images.githubusercontent.com/5781590/185204063-0e0991ef-0094-4ad7-9c0a-5187535d666a.mp4

**Comment by Onokaev** [comment]
Hey @RabebOthmani. Try testing on this link https://jolly-sand-0ac78c710-2041.centralus.azurestaticapps.net/ and let me know if you still experience this issue

**Comment by RabebOthmani** [comment]
@Onokaev I'm not seeing the issue reported on the video anymore. Thanks!
