### ISSUE TITLE
ListPlaces and Associated $count Default Queries Under Resources Tab Return Errors

### ISSUE THREAD

**Issue by cparker-msft** [microsoftgraph/microsoft-graph-explorer-v4#2016]
**Describe the bug**
Under the Resources section in Graph Explorer, the default URL pattern for the ListPlaces call is https://graph.microsoft.com/v1.0/places, which will return an error since this API requires either microsoft.graph.room or microsoft.graph.roomlist passed as a segment in the URL ie: https://graph.microsoft.com/v1.0/places/microsoft.graph.room. Reference: https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=http#http-request.
 
Additionally, the default URL pattern supplied for $count (https://graph.microsoft.com/v1.0/places/$count) will also return an error for the same reason above, but also because according to the [API doc](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=http#optional-query-parameters) it only supports [the other method](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#count-parameter) of leveraging the $count query parameter ie: https://graph.microsoft.com/v1.0/places/microsoft.graph.room?$count=true. An error will occur for the 'GET microsoft.graph.room $count' Resource as well due to the requirement for the other method.

**To Reproduce**
1. In Graph Explorer, go to the 'Resources' tab on the left pane
2. Scroll down to the 'places' section
3. Click on the 'GET Places' or 'GET $count' or 'GET microsoft.graph.room $count' resources 
4. Select 'Run query'
5. See error

**Expected behavior**
For 'GET places', the URL pattern should be something like https://graph.microsoft.com/v1.0/places/microsoft.graph.room or https://graph.microsoft.com/v1.0/places/microsoft.graph.roomlist

For 'GET $count' or 'GET microsoft.graph.room $count' (under places Resource), the URL pattern should be something like https://graph.microsoft.com/v1.0/places/microsoft.graph.room?$count=true and/or https://graph.microsoft.com/v1.0/places/microsoft.graph.roomlist?$count=true 

**Screenshots**
![image](https://user-images.githubusercontent.com/4155756/183688659-f5763e79-99eb-45af-8190-2f5837729f7a.png)

![image](https://user-images.githubusercontent.com/4155756/183688568-7e059864-a3b3-49b4-b018-e4bcfd84645b.png)

![image](https://user-images.githubusercontent.com/4155756/183688431-2f1a4ff5-a3c2-45db-b889-d8625dc5753a.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.5 Monterey
 - Browser: Edge
 - Version 104.0.1293.47 (Official build) (x86_64)

**Comment by Onokaev** [comment]
Hey @cparker-msft. Thank you for this. This could because of an error with the way we generate the resource tree. We are on it

**Comment by thewahome** [comment]
Tagging @irvinesunday coz of how the resources are created

**Comment by Onokaev** [comment]
This issue has been fixed
