### ISSUE TITLE
Text not centered

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2019]
Both on the Toolkit Component tab and the Adaptive Cards tab, when a component/card is not available, the text appearing on the screen is not centered forcing the user sometimes to scroll while there's enough space . 
<img width="683" alt="adaptive card text" src="https://user-images.githubusercontent.com/5781590/183953655-1a13de10-40fd-452c-855a-21869ae64eea.png">
<img width="683" alt="MGT text " src="https://user-images.githubusercontent.com/5781590/183954777-82c40365-aadc-4ae5-bfa9-73459a3d0aa2.png">

**Comment by gavinbarron** [comment]
@RabebOthmani do you want these centered vertically and horizontally? 
The text block in Toolkit component view appears to be centered vertically, but not horizontally, while the adaptive card element looks about right horizontally but not vertically to my eye.

**Comment by RabebOthmani** [comment]
@gavinbarron agree on the adaptive cards. Actually, do we even want it to be horizontally centered? I'm concerned a user might need to scroll to eventually read a text telling them what they need is not available. We might just want this to be top left . Thoughts? 
Also the toolkit text on expand : 
<img width="834" alt="MGT tab on expand " src="https://user-images.githubusercontent.com/5781590/184181021-4d99abea-f7c6-4fc4-a481-4681fea2ae4e.png">

**Comment by gavinbarron** [comment]
Not a designer, but I'd go for those text elements being centered on the x but at the top of the y using a flexbox and the text having width 100% and with some padding from the container ensure that if you hit the wrap length there's equal spacing on the left and right.

Related question, does GE support RTL languages?
