### ISSUE TITLE
Yellow border on Adaptive cards tab

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2020]
There is a little yellow rectangle that looks like a border? 
IT's just next the copy button and can be confusing to users as it might look like a button
<img width="674" alt="border " src="https://user-images.githubusercontent.com/5781590/183957513-0fabb6eb-179e-4c11-a589-16175766153c.png">

**Comment by gavinbarron** [comment]
This one is from the Monaco editor that is used to show the JSON here. It's not finding a schema for the JSON supplied and marking a warning, see the squiggly under the opening brace, along with a corresponding mark in the gutter.
![image](https://user-images.githubusercontent.com/7122716/184005850-dcb37429-73cc-4466-a2d0-eeef65efb8b0.png)

I did some investigation and found that we can turn on the ability to load schema, but then I got a fetch failure.
Might be simplest to disable validation or set the schemaRequest issue to off from the default of warning.

Codesandbox exploring validation options: https://codesandbox.io/s/simple-usage-forked-plqtsf?file=/src/App.js
