### ISSUE TITLE
Permission Settings Consent Not Work

### ISSUE THREAD

**Issue by jianli0** [microsoftgraph/microsoft-graph-explorer-v4#2021]
**Permission Settings Self Consent Not Work**

**To Reproduce**
1. Go to self profile, the right top corner avatar.
2. Click on 'Consent to permissions'
3. search for 'Chat Create'
4. Select it
5. Click Consent button
6. nothing happened, loading forever

**Expected behavior**
I expect my permission is granted right away.

**Screenshots**
<img width="476" alt="image" src="https://user-images.githubusercontent.com/3704089/184042733-60b804a8-db5b-4f75-973a-7e0faf4f0060.png">

**Desktop (please complete the following information):**
 - Browser  chrome
 - Version : latest

**Comment by ElinorW** [comment]
Hey @jianli0,
There's a popup window that appears asking you to consent to the permission,
Sometimes this may be hidden by other windows on your screen and hence why it appears as though the 'Consent' action doesn't work
![image](https://user-images.githubusercontent.com/18407044/184165596-82ff2fa0-fea0-4b7b-8938-59df8845269d.png)
