### ISSUE TITLE
Graph Explorer crashing 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2024]
When signing out/signing in, Graph Explorer is crashing. This is something both @adhiambovivian and myself experienced.

**Comment by Onokaev** [comment]
Hey @RabebOthmani. We already created an issue here: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2022

**Comment by Onokaev** [comment]
Closing this as it is a duplicate of issue #2022
