### ISSUE TITLE
NPS survey doesn't have the zero score 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2026]
![NPS survey ](https://user-images.githubusercontent.com/5781590/184175196-8c733dc8-d31f-47ce-9b8c-54c7c90f8a94.png)

@adhiambovivian  @ElinorW  this was noticed during a meeting, the NPS survey doesn't start from zero. Didn't we fix a backend issue a while ago to take zero into consideration? OR is the 1 considered zero??!!!

**Comment by adhiambovivian** [comment]
@RabebOthmani  when was this screenshot taken? This was resolved

**Comment by RabebOthmani** [comment]
Closing the issue as it seems I had the wrong screenshot.
