### ISSUE TITLE
Update beta/me/profile endpoint

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#2028]
**Describe the bug**
Currently when you run the "my profile (beta)" from the Getting Started sample queries you get a 400 error

**To Reproduce**
1. Go to 'https://developer.microsoft-tst.com/en-us/graph/graph-explorer'
2. Click on 'my profile (beta).'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/18407044/184184550-234b0c0b-9131-4fd5-a729-e03f12f983f9.png)

The endpoint needs to be updated to **beta/me**
![image](https://user-images.githubusercontent.com/18407044/184185501-1aee0aa6-59e4-4eef-9b64-45ab8e0c2d32.png)

**Comment by adhiambovivian** [comment]
Related https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2030
