### ISSUE TITLE
Links in the snippets point me to a static powershell version

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#2029]
Open Graph Explorer
Go to the powershell code snippets tab
Click the link to download the powershell library.

Result: points to an old version of the library.

**Comment by ddyett** [comment]
this link may also result in errors because powershell has prerequisites. this page is probably more useful  https://docs.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0

**Comment by Onokaev** [comment]
The url has been updated
