### ISSUE TITLE
profile endpoint shows 400 error response when service returned 200

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#2030]
**Describe the bug**
Graph Explorer appears to be parsing the response body to decide what status code to show.  It should show the status code returned.

**To Reproduce**
Make this request in Graph Explorer with the devTools open.

GET https://graph.microsoft.com/beta/me/profile

You will see the response in the network tab is a 200.

**Expected behavior**
The response should be a 200 with the JSON payload describing the problem the server ran into.

**Comment by adhiambovivian** [comment]
@darrelmiller  shouldn't Graph return a 500 given that there was some kind of server error?
![image](https://user-images.githubusercontent.com/9458079/184335556-dc77baf1-b179-4bc8-a24a-1879f0e87617.png)

**Comment by MaryannGitonga** [comment]
Endpoint has been fixed.


![Image](https://user-images.githubusercontent.com/34104277/185055891-b33a8ec8-8ed6-4bae-8610-5924918ae3dc.png)
