### ISSUE TITLE
Unable to get Cloud PCs from API

### ISSUE THREAD

**Issue by jakerobson-ic** [microsoftgraph/microsoft-graph-explorer-v4#2031]
**Describe the bug**
I am trying to get a list of Cloud PCs that my user account has access to via the beta Graph API. I am trying in both code and via the Graph API Explorer, however, I am getting the same error on both: `Access is denied to the requested resource`

**To Reproduce**
1. Go to [Microsoft Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
2. Sign in with an account.
3. Select `GET` from the dropdown at the top
4. Select `beta` from the next dropdown
5. Put `https://graph.microsoft.com/beta/me/cloudPCs` into the textbox
6. Press the `Run Query` button
7. At this point you should get the error, however, you may need to accept the permissions via the `Modify Permissions` tab
8. If you had to modify permissions then run query again, you should still get the same error.

**Expected behavior**
A list of Cloud PCs the logged in user has access to show be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/101810887/184329699-8ede2bbf-9fd0-4b77-8124-0015e046b421.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge

**Smartphone (please complete the following information):**

**Additional context**
- I have accepted permissions for all users in the tenant via Azure Active Directory Apps as well and this has not made any difference.
- I have been trying to do this a couple of times a week for the past month but hasn't yet been patched.

**Comment by ElinorW** [comment]
Hey @jakerobson-ic,
I have been able to reproduce this error and I believe this is an issue with the Cloud PCs API. Unfortunately, at Graph Explorer we don't handle issues relating to particular graph API's but you can post this problem on the Graph Q&A forum where the appropriate team should be able to help you out. 
On this site: https://docs.microsoft.com/en-us/answers/products/graph at the top right there is an 'Ask a question' button where you can post the issue. 
Apologies for the inconvenience.

**Comment by jakerobson-ic** [comment]
Hi @ElinorW,

Thanks for clarifying and pointing me in the right direction. I have raised a question there.
