### ISSUE TITLE
Group GE release notes by area mostly 'New features/enhancements, Bug-fixes, Dependancy updates' 

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#2032]
Update Graph Explorer release notes to group issues by area - this will improve the overall clarity of the release notes both internally and externally.

**Comment by thewahome** [comment]
@adhiambovivian as discussed, this adds a manual aspect to the release authoring process. 

@ElinorW , @Onokaev, we can however use this as a recommendation when authoring the release notes.

Expected order is:
1. Features
2. Enhancements
3. Bug Fixes
4. Dependency updates
