### ISSUE TITLE
Selected checkboxes on the permissions panel are not visible to users

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#2034]
**Describe the bug**
On the permissions panel, when permission(s) are selected, the checked boxes are not visible to users unless the user hovers the selected permissions.
[screencast-cdx.transform.microsoft.com-2022.08.12-13_56_14.webm](https://user-images.githubusercontent.com/9458079/184341243-6d2ba3a1-06d1-4afd-8ba0-f45ac1277a7f.webm)

**To Reproduce**
1. Click on 'Consent to Permissions'
2. Select multiple permissions or even one
3. The UI does not show the user the selected permissions

**Expected behavior**
As a user, am hoping to see the checked permissions I have selected

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Browser edge

**Comment by RabebOthmani** [comment]
The checkboxes are expanding/collapsing the grouping of permissions when they shouldn't. The overall behaviour needs reworking

**Comment by adhiambovivian** [comment]
Refer to https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1844 for more context
