### ISSUE TITLE
Documentation links not working 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2036]
the documentation links for sample queries are not working.

**Comment by jasonjoh** [comment]
This applies to the "cached set of queries" - links seem to be fine as long as GE can get them from DevX API. It looks like:

https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/01a8e74285a60a049630e89935941da7540f0de5/src/app/views/sidebar/sample-queries/queries.ts

Needs to update their links to match https://github.com/microsoftgraph/microsoft-graph-devx-content/blob/dev/sample-queries/sample-queries.json
