### ISSUE TITLE
In scan mode, Narrator focus is going on unnecessary empty data cells while navigating with both down/up arrow key .

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#2040]
**Test Environment:**
OS: Win 11 Version (OS Build 2263.1010)
URL: [Graph Explorer - Microsoft Graph](https://developer.microsoft.com/en-us/graph/graph-explorer)
Browser: Edge Version: 100.0.1169.1
Screen Reader: Narrator

**Repro Steps:**
1. Open the above URL in Edge Dev.
2. Navigate to Sample queries tab item further navigate to getting started (8)
2. Navigate to the Data grid in scan mode.
3. Observe the issue.

**Actual Result:**
In scan mode, Narrator focus is going on unnecessary data cells and announce it as 'read only' while navigating with both down/up arrow key.

**Expected Result:**
In scan mode, Narrator focus should not go on unnecessary(empty) data cells while navigating with both down/up arrow key.

**Observation:**
Issue repro with NVDA.

**User Experience:**
Screen reader users will be impacted as they will get confused when navigate through table cells and will not be able to understand the structure of the content.

**MAS Reference:**
[Meaningful Sequence - Liquid (microsoft.com)](https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/01.03.02)

**Additional context**
See issue here: https://office.visualstudio.com/OC/_workitems/edit/5855798/

**Comment by adhiambovivian** [comment]
@thewahome  any update on this ticket - it's a high priority one.
