### ISSUE TITLE
microsoft.graph.getStaffAvailability returns UnknownError and has a N/A Permission

### ISSUE THREAD

**Issue by ConanAPK** [microsoftgraph/microsoft-graph-explorer-v4#2043]
Every request to microsoft.graph.getStaffAvailability, in the graph explorer as well as through code returns UnknownError. Possibly related to permissions 

**To Reproduce N/A Permission**
1. Go to [microsoft.graph.getStaffAvailability](https://developer.microsoft.com/en-us/graph/graph-explorer?request=solutions%2FbookingBusinesses%2Fapkgroup%40apkgroup.eu%2Fmicrosoft.graph.getStaffAvailability&method=POST&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=eyJzdGFmZklkcyI6WyJiZjVmNzdhNS1hMzE3LTRkMmYtYjhiNC01ZmRhMzZlZGFiZjMiXSwic3RhcnREYXRlVGltZSI6eyJkYXRlVGltZSI6IjIwMjItMDgtMTlUMDA6MDA6MDAiLCJ0aW1lWm9uZSI6IkV1cm9wZS9QYXJpcyJ9LCJlbmREYXRlVGltZSI6eyJkYXRlVGltZSI6IjIwMjItMDktMDJUMDA6MDA6MDAiLCJ0aW1lWm9uZSI6IkV1cm9wZS9QYXJpcyJ9fQ==)
2. Click on Modify Permissions
Only the N/A Permission will be displayed

**Expected behavior for Permissions**
List of required permissions

**Screenshots**
![image](https://user-images.githubusercontent.com/40423709/184891085-ba7c2c03-ec68-419d-8a63-559194093c52.png)

**Desktop**
 - Chrome

**To Reproduce Unknown Error**
1. Send any request to getStaffAvailability through the graph explorer (or code), with the correct parameters
2. UnknownError appears.

**Expected behavior for Request**
List of available timeslots for staff

**Screenshots**
![image](https://user-images.githubusercontent.com/40423709/184892787-3a1580f1-2d8f-42d1-8aaf-7ef702fdbb6f.png)
 (Note that getting staff, used above, works)
![image](https://user-images.githubusercontent.com/40423709/184893303-3accf136-3c5a-4c44-ba73-22a59a37f73a.png)

**Desktop**
 - Chrome, Visual Studio 2017, also in  Visual Studio 2022, 
 - Microsoft Graph 4.36.0

Side note:
In code, I get the GraphClient with a ClientSecretCredential. Client should have all required permissions for everything calendar and booking related.

![image](https://user-images.githubusercontent.com/40423709/185056259-6209ac65-7794-4587-8a3a-621c89a3c077.png)

**Comment by Onokaev** [comment]
Hey @ConanAPK. According to the docs https://docs.microsoft.com/en-us/graph/api/bookingbusiness-getstaffavailability?view=graph-rest-1.0&tabs=http, this endpoint only works with application permissions. Graph Explorer does not support application permissions.

Let me look into why this is not working on your code

**Comment by Onokaev** [comment]
Does your code work for other endpoints like https://graph.microsoft.com/me which in your case should be graphClient.Me.Request().GetAsync?

**Comment by ConanAPK** [comment]
Thanks for your response!

The /me endpoint, when executed like that gives me a delegated authentication flow error, but I assume that's normal because I am using client credentials, so there is no 'user' to resolve in this context.

![image](https://user-images.githubusercontent.com/40423709/185148425-c026889c-ace2-4ad0-a3c9-d8c009a04535.png)

But other endpoints, like getting the staffmembers of a calendar, do work like a charm

graphClient.Solutions.BookingBusinesses(calendar).StaffMembers.Request()

![image](https://user-images.githubusercontent.com/40423709/185150412-d13da68d-6244-4d6e-90e8-3e065472b145.png)

**Comment by Onokaev** [comment]
Right! Totally slipped my mind that /me is only supported for delegated requests.
If other endpoints are working, then this one has an issue. Let me run a couple of tests then I'll get back to you

**Comment by Onokaev** [comment]
We cannot fix this on Graph Explorer. The best place to get answers on this is the community Graph website. I have already started a thread here: https://techcommunity.microsoft.com/t5/microsoft-graph/the-endpoint-getstaffavailability-returning-unknown-error/m-p/3602887#M496. 
You can also use the Microsoft Q&A. I've started another thread here: https://docs.microsoft.com/en-us/answers/questions/971709/the-endpoint-httpsgraphmicrosoftcomv10solutionsboo.html

**Comment by ConanAPK** [comment]
Alright, thank you very much for the assistance so far!
I'll keep an eye on the threads you created.

**Comment by Onokaev** [comment]
Yes. That's correct. Does the workaround work for you?

**Comment by ConanAPK** [comment]
For now it will do :)
I'll have to convert local times to UTC, since the hours are quite critical to this application, but I'm happy to get a response from the api now!

**Comment by wpintegrate** [comment]
@ConanAPK I am still not able to get the response.  Is this working for you? I have tried with UTC as well.

**Comment by ConanAPK** [comment]
@wpintegrate UTC works for me, but not on the Explorer.

**Comment by wpintegrate** [comment]
@ConanAPK I have tried with the Graph Token and added all the permissions you mentioned but still it's showing a permission error.

**Comment by tpeterson-centrexIT** [comment]
Same boat here. I get a 403 - Forbidden error (Unknown Error) only for this endpoint. Can use staffMembers, services, calendarView, etc just fine. Permission scope in the oauth is as follows: offline_access Calendars.ReadWrite BookingsAppointment.ReadWrite.All Bookings.Read.All email openid profile. Made sure that the appropriate designation of Application is set, as this method looks to not take delegated permissions. Kind of stuck without this working, as there is no simple alternative to automating availability search.

**Comment by jagdishpal02000** [comment]
i guess the problem is still not solved :(  i'm trying this endpoint at 1
<img width="356" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/59500712/077de682-7a4a-4150-8928-46f3028f9be0">
3/07/2023 tried UTC but still getting unknown error with 403.
