### ISSUE TITLE
Example is wronge about gorup creation in Graph Explorer

### ISSUE THREAD

**Issue by AlexanderHolmeset** [microsoftgraph/microsoft-graph-explorer-v4#2060]
**Describe the bug**

**To Reproduce**
See screenshot.

**Expected behavior**
Dont think creating mail enabled security groups is supported. Need to specify grouptype of unified or dynamic.
https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http
Same behavour in both 1.0 and beta.

**Screenshots**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/86094924/186419063-76730590-7d65-4654-9d26-f2f9e9bc61ca.png">
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/86094924/186419285-bc48aa33-d6bd-4b73-8c68-48991e117865.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Edge Chromium

**Comment by Onokaev** [comment]
Thank you for this @AlexanderHolmeset. We will rectify this.

**Comment by Onokaev** [comment]
The fix will be out once the content repo is deployed.
