### ISSUE TITLE
ADDB2C - Error to filter identities by issuerAssignedId(email) with alias

### ISSUE THREAD

**Issue by carlos-rian-quartile** [microsoftgraph/microsoft-graph-explorer-v4#2061]
**Describe the bug**
The filter: 
```http
https://graph.microsoft.com/beta/users?$filter=identities/any(c:c/issuerAssignedId eq 'maria+1@gmail.com' and c/issuer eq 'xxx.onmicrosoft.com')
```

I tried to make a request using the email filter; when it has +1, +2, etc., a Gmail alias, the query returns nothing.

**To Reproduce**

1. Add a new e-mail on ADDB2C with an alias, for example, maria+1@gmail.com

2. Change URI, replace xxx to your issuer: https://graph.microsoft.com/beta/users?$filter=identities/any(c:c/issuerAssignedId eq 'maria+1@gmail.com' and c/issuer eq 'xxx.onmicrosoft.com')

3. Call URI with auth token on the headers.
```curl
curl --location \
--request GET 'https://graph.microsoft.com/beta/users?$filter=identities/any(c:c/issuerAssignedId eq '\''maria+1@gmail.com'\'' and c/issuer eq '\''quartileb2c.onmicrosoft.com'\'')' \
--header 'Authorization: Bearer {token}'
```

4. See an error

**Expected behavior**

**Screenshots**
```JSON
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users",
    "value": []
}
```

**Comment by Onokaev** [comment]
Hey @carlos-rian-quartile. Is the user available when you run `/users` only?

**Comment by carlos-rian-quartile** [comment]
@Onokaev yes.

Create user

![create-user](https://user-images.githubusercontent.com/88094994/188634676-6e4e7496-6a70-4e22-8037-515ee160852a.png)

List all user where display eq "Maria"

![get-by-displayname](https://user-images.githubusercontent.com/88094994/188634812-35acbbe9-061e-45bf-8180-190d04671ff1.png)

List by e-mail with alias
![get-user-by-email](https://user-images.githubusercontent.com/88094994/188634933-b91af483-c2af-4649-afb7-a7e23ccd6251.png)

**Comment by Onokaev** [comment]
This appears to be a Graph issue. We cannot fix it on Graph Explorer.
While I'm investigating, we can open the issue here https://docs.microsoft.com/en-us/answers/questions/ask.html for a wider Graph audience.

**Comment by Onokaev** [comment]
I have posted the same question here https://docs.microsoft.com/en-us/answers/questions/1006799/addb2c-error-to-filter-identities-by-issuerassigne.html on the MS Q&A

**Comment by Onokaev** [comment]
Hey @carlos-rian-quartile. I got a response from the team here: https://docs.microsoft.com/en-us/answers/questions/1006799/addb2c-error-to-filter-identities-by-issuerassigne.html?childToView=1008267#comment-1008267
I was also able to reproduce the error. They are actively investigating it. Hopefully they'll have a fix out soon.
Let me know if you need further assistance

**Comment by carlos-rian-quartile** [comment]
Hi @Onokaev thank you very much.

Using "%2B" worked.

https://docs.microsoft.com/en-us/answers/questions/1006799/addb2c-error-to-filter-identities-by-issuerassigne.html#comment-1008267
