### ISSUE TITLE
cannot read permissions

### ISSUE THREAD

**Issue by XinkunY** [microsoftgraph/microsoft-graph-explorer-v4#2064]
cannot fetch the permissions, I am a global admin. Account: xinkun@intunekun.onmicrosoft.com

**Screenshots**
![image](https://user-images.githubusercontent.com/59459032/187380833-83c919ce-f99e-4f90-9828-49f6a651149b.png)

**Desktop (please complete the following information):**
 - Browser Edge
 - Version Latest version

**Additional context**

**Comment by ElinorW** [comment]
hey @XinkunY , 
The API was temporarily down... can you confirm if you are still experiencing the issue now?

**Comment by XinkunY** [comment]
It is all good now.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月30日 17:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [microsoftgraph/microsoft-graph-explorer-v4] cannot read permissions (Issue #2064)


hey @XinkunY<https://github.com/XinkunY> ,
The API was temporarily down... can you confirm if you are still experiencing the issue now?

―
