### ISSUE TITLE
Update the readme with the latest details

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/microsoft-graph-explorer-v4#207]
**Is your feature request related to a problem? Please describe.**
The readme requires updating since it has unclear steps to onboarding a new user to the code

**Describe the solution you'd like**
Update the readme with true details of the current codebase

**Describe alternatives you've considered**

**Additional context**
 
[AB#7521](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7521)

**Comment by ezkemboi** [comment]
@thewahome and @bettirosengugi also when adding this feature, I would suggest that you can do a fix for the typo in the readme. 

> The varaible should end up looking like this: REACT_APP_CLIENT_ID=guid-client-id-value.

I think it should be 

> The variable should end up looking like this: REACT_APP_CLIENT_ID=guid-client-id-value.

Thank you.

**Comment by ezkemboi** [comment]
Also, 
in the section **Enabling authentication with your own credentials**, when I follow step for creating an app, the following error is shown: 

> Application registrations portal is no longer available to register and manage converged applications. We recommend that ​you manage your existing applications and register new applications by using the App registrations (now Generally Available) experience in the Azure portal. ​

Thus, I think as mentioned above, readme might need an update to help onboard new users.
Thank you.
