### ISSUE TITLE
Collapse / Expand request/response components

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/microsoft-graph-explorer-v4#208]
**Is your feature request related to a problem? Please describe.**
The request headers take up a lot of space especially when someone sends a GET request and has to scroll down to see the response. 
 
**Describe the solution you'd like**
Add a caret button on the left of both components that enables a user to expand the component when they want to see more details or collapse it when it is not mainly in use

**Describe alternatives you've considered**
To display the request and response components vertically as described in #133 

**Additional context**
When both are collapsed they can look like this:
![image](https://user-images.githubusercontent.com/53429535/66206488-f167e680-e6b8-11e9-9676-d04dc33a20cf.png)

When the response tabs is expanded
![image](https://user-images.githubusercontent.com/53429535/66206571-25430c00-e6b9-11e9-904a-d553f6642b8b.png)

When both are expanded
![image](https://user-images.githubusercontent.com/53429535/66206668-6affd480-e6b9-11e9-89d6-80340bab6cbb.png)

**Comment by thewahome** [comment]
Closing this as #822 reduces the views to a collapsed state
