### ISSUE TITLE
filter=startswith showing missleading error message when trying more than 120 characters

### ISSUE THREAD

**Issue by gabrielamaciasms** [microsoftgraph/microsoft-graph-explorer-v4#2103]
**Describe the bug**
It seems like "$filter=startswith" does not support performing the search with more than 120 characters.
However, the error message received does not explain the actual error, but instead is showing a misleading error message.

**To Reproduce**
1. Go to 'Graph explorer' (note: we found the same behavior using the sdk)
2. Try to test below url: (note: empty headers)
https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3Dstartswith(displayName%2C'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')%26%24top%3D40%26%24select%3Did%2CdisplayName%2Cmail&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

![image](https://user-images.githubusercontent.com/109746770/188487255-468f807b-969e-4a9e-9411-0883d955ecc5.png)
4. Run Query
**5. Receive misleading error**
```
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported or invalid query filter clause specified for property 'displayName' of resource 'User'.",
```

**Expected behavior**
Expected to receive a message stating that the maximum number of characters allowed as parameters of the filter

**Desktop (please complete the following information):**
OS: [Windows 11]
Microsoft Edge
Version 105.0.1343.27 (Official build) (64-bit)

**Additional context**
Note, if reducing the query to 120 characters, the query is performed without errors.
https://graph.microsoft.com/v1.0/users?$filter=startswith(displayName,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')&$top=40&$select=id,displayName,mail
![image](https://user-images.githubusercontent.com/109746770/188488921-f1fdedf4-e480-48a5-9e7b-4a3951d67834.png)

**Comment by gabrielamaciasms** [comment]
Could you please help me to clarify if the issue is with "$filter=startswith" or with the limits of the field? in this case "displayName"
Is there any change planned?

**Comment by Onokaev** [comment]
Hey @gabrielamaciasms. The issue must be with the filter. I was able to reproduce it on Postman. The text field does not limit inputs.
However, we cannot sort this out on Graph Explorer. You can post the questions here for a wider audience. You'll be helped by the relevant team that owns the endpoint: https://learn.microsoft.com/en-us/answers/questions/ask.html

Let me know if you need any further assistance
