### ISSUE TITLE
Graph API don't give recent results.

### ISSUE THREAD

**Issue by shabbir-dhangot** [microsoftgraph/microsoft-graph-explorer-v4#2104]
**Describe the bug**
I have added one user around 1 hour back and renamed one user with name "Grady" but while using search its not returning those user detail. It look like those users are not consider. I even tried searching with email but that also didn't work.

https://graph.microsoft.com/v1.0/me/people?$search=Grady

I even chat with them but its not coming in people API. I tried with top 100 where I have total 50 users in AD

https://graph.microsoft.com/v1.0/me/people/?$top=100

**To Reproduce**
1. Go to Graph Explore
2. Add new user
3. Try to search that user

**Expected behavior**
It should display that user

**Additional context**
Try with updating user's name and hit graph API.

**Comment by shabbir-dhangot** [comment]
In addition that rename person is still showing old name in Graph Call of people top 100.

**Comment by Onokaev** [comment]
Hey @shabbir-dhangot. Did you try /users/{user-id}?
I noticed that I get the result when I hit the /user/{user-id} endpoint. I am still looking into why /people/ does not return the required result

**Comment by Onokaev** [comment]
The same question was answered here: https://stackoverflow.com/questions/54305121/people-api-in-microsoft-graph-not-returning-the-updated-results
Let me know if you need any further help
