### ISSUE TITLE
Fields not returning when properties in $select parameters start with upper case only for "directoryObjects"

### ISSUE THREAD

**Issue by gabrielamaciasms** [microsoftgraph/microsoft-graph-explorer-v4#2111]
**Describe the bug**
Properties under the query parameter `$select` are behaving differently between the requests.
When selecting data from "**users**" the parameters can either start with upper case or lower case. The results will include the fields in both cases, however when selecting data from "**directoryObjects**" it will only return the fields if the parameters start with lower case.

**To Reproduce**
**Users**
https://graph.microsoft.com/v1.0/users/{objectId}?$select=AccountEnabled,SignInSessionsValidFromDateTime
![image](https://user-images.githubusercontent.com/109746770/189427625-eec09098-7c95-443d-88f9-90494c3f771e.png)
Returning results **also with lower case:**
https://graph.microsoft.com/v1.0/users/{objectId}?$select=accountEnabled,signInSessionsValidFromDateTime
![image](https://user-images.githubusercontent.com/109746770/189427386-049b3879-7f33-4553-9e3a-ce91e17219c6.png)

**Directory Object**
https://graph.microsoft.com/v1.0/directoryObjects/{objectId}?$select=AccountEnabled,SignInSessionsValidFromDateTime
![image](https://user-images.githubusercontent.com/109746770/189428052-1e8ffb65-606f-4794-a125-3a03982b226f.png)
**Only returns the fields** when these are starting with lower case letters:
https://graph.microsoft.com/v1.0/directoryObjects/{objectId}?$select=accountEnabled,signInSessionsValidFromDateTime
![image](https://user-images.githubusercontent.com/109746770/189427899-5495596b-49ff-4cb0-8227-d1e249f44c87.png)

**Expected behavior**
Behavior is expected to be consistent between the requests. Also, per the documentation, properties should start with lower case. Please clarify if it is case insensitive, and if that is the case, why **directoryObjects** does not return the fields when the properties parameter is starting with upper case.

**Desktop (please complete the following information):**
 - OS: Windows 11
Microsoft Edge
Version 105.0.1343.33 (Official build) (64-bit)

**Comment by Onokaev** [comment]
Hey @gabrielamaciasms. I have been able to reproduce this. We can't fix this on Graph Explorer. Let me open the issue on the Graph Q&A page for a wider audience

**Comment by Onokaev** [comment]
Here's a link to the issue I have created https://learn.microsoft.com/en-us/answers/questions/1053043/fields-not-returning-when-properties-in-select-par.html

**Comment by Onokaev** [comment]
Hey @gabrielamaciasms. There is a response on the ticket I created on the Q&A forum. Let me know if you need any further assistance
