### ISSUE TITLE
LifecycleWorkflows.Read.All, LifecycleWorkflows.ReadWrite.All permissions not available for consent via Graph Explorer

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-explorer-v4#2113]
**Describe the bug**
We have some new permissions (LifecycleWorkflows.Read.All, LifecycleWorkflows.ReadWrite.All) that are currently not available in the Graph Explorer permissions explorer experience. This means customers can't use Graph Explorer for testing the APIs.

**To Reproduce**
<img width="419" alt="image" src="https://user-images.githubusercontent.com/14026935/190243060-46617bb8-70ac-49fc-899f-5024d0618047.png">

**Expected behavior**
Show the latest permissions in Graph Explorer

**Screenshots**
<img width="419" alt="image" src="https://user-images.githubusercontent.com/14026935/190243094-35c16745-72d8-40db-98b2-2ea6165aef26.png">

Thanks.

cc @AlexFilipin for visibility.

**Comment by Onokaev** [comment]
Hey @FaithOmbongi. I just checked and the permissions are there
![image](https://user-images.githubusercontent.com/45680252/190343885-57590fbd-60dc-4673-96cb-a3bf7a8594e8.png)
Could you try again and let me know if you can see them

**Comment by FaithOmbongi** [comment]
Thanks for this confirmation, @Onokaev. Confirmed that this is now resolved. Closing the issue.
