### ISSUE TITLE
Resources tab doesn't have Children endpoint for a DriveItem (ex: Root)

### ISSUE THREAD

**Issue by Dean-NC** [microsoftgraph/microsoft-graph-explorer-v4#2115]
**Describe the bug**
In the Resources tab, under either `Drives` or `Drive`, then under `Root`, the main **`[GET] Children`** endpoint is missing. There is a Children item, but under that there's only [GET] $count.  I need [GET] Children, so that the URL will be: `/v1.0/drives/{drive-id}/root/children`

I'm trying to build a Postman collection that when used with Hidi and Kiota, will allow the following code:
`client.Drives["some id"].Root.Children.GetAsync()`

**To Reproduce**
1. Click Resources tab
2. Expand Drive, then under that expand Root, then under that expand Children.
3. Under Children, there's no option that will cause the URL to be:
`/v1.0/drives/{drive-id}/root/children`

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - Browser: Edge Chromium
 - Version 99

**Comment by thewahome** [comment]
@irvinesunday and @MaggieKimani1 how do we surface these?

**Comment by irvinesunday** [comment]
From the OpenAPI doc. the `GET` operation is defined for the path:

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/40403681/aa7428ed-04d9-4e4c-ba8c-9e264b10479e)

And the resulting resource tree:

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/40403681/fc7445bd-be05-4ffb-9153-75dfc74e526d)

**Comment by thewahome** [comment]
Thanks @irvinesunday, I've confirmed that this is available for both AutoComplete and the Resources Explorer.

@Dean-NC we are closing this. In case there's anything else, feel free to reopen this ticket

**Comment by Dean-NC** [comment]
@thewahome Better late than never. Thanks for following-up. Yes, I see it there now in explorer. I've moved on and use .NET HttpClient directly against Graph API, instead of the strange Kiota and Hidi stuff, so I don't need to build a Postman collection and jump through 20 hoops just to send a Http request.
