### ISSUE TITLE
bootstrapTokenEscrowed for macOS devices retrieved as false for all devices

### ISSUE THREAD

**Issue by engelcg** [microsoftgraph/microsoft-graph-explorer-v4#2116]
In MS Endpoint ManagerAdmin Center macOS devices have a property under 'Hardware' called 'Bootstrap token escrowed' which has the value 'Yes' for a lot of devices, but the property is not included in the exportable data there.
![image](https://user-images.githubusercontent.com/114164419/191766759-9ba218cb-7a48-4093-8593-0ed2bd5ff1cb.png)
I was looking for the same property both with Graph Explorer and using MgGraph ps modul, but I receive 'false' for 'bootstrapTokenEscrowed' on all devices when I run  get https://graph.microsoft.com/beta/deviceManagement/managedDevices?$filter=operatingSystem eq 'macOS'
no matter if I filter for a specific device or examine all macOS devices
This is what I receive from Graph Explorer for the same device from the other scrshot (I get the same value using PowerShell)
![image](https://user-images.githubusercontent.com/114164419/191771139-4ff93bb0-545e-48ae-a9ad-d84c8198fdf3.png)

I expected to receive the same value which I see at Endpoint Manager Admin Center.

**Comment by Onokaev** [comment]
Hey @engelcg. I cannot reproduce this. Let me post it on the Graph Q&A section for a wider audience

**Comment by Onokaev** [comment]
Here is a link to the issue I have created: https://learn.microsoft.com/en-us/answers/questions/1052650/bootstraptokenescrowed-for-macos-devices-retrieved.html

**Comment by Onokaev** [comment]
Hey @engelcg. There's a response on the ticket I created on the Q&A forum. Let me know if you need any further assistance
