### ISSUE TITLE
Response not showing in JSON format

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2117]
It has been reported that with some specific queries, the response is not formatted as a JSON. This happens when the query has $top or $skip . 
The expected behaviour is for every response to be formatted in JSON. 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/5781590/192239896-60d69129-09a6-4805-8463-967ce6c8526e.png)

**Comment by thewahome** [comment]
I'm unable to reproduce this. Is this still happening @RabebOthmani ?

**Comment by ElinorW** [comment]
Closing that as we are unable to reproduce
