### ISSUE TITLE
Refresh cached sample queries

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#2119]
**Is your feature request related to a problem? Please describe.**
In #2036 it was reported that the links weren't working. The cause was that the links in the cached sample queries that are built with the application had not been updated with the latest set.

These are shown when the DevX-API is unavailble for any reason.

**Describe the solution you'd like**
Routinely hand over the samples so that the latest ones are built with the app for deployment.

**Additional context**
This could mean moving the sample queries from the DevX-API service since there would essentially no need to make a round trip to get the latest if the latest has already been built with the application.

**Comment by RabebOthmani** [comment]
Pinging @darrelmiller  , @thewahome worked on a nice document on how to resolve this. Let's review .

**Comment by RabebOthmani** [comment]
@thewahome @darrelmiller Let's look at this work for the current milestone
