### ISSUE TITLE
Filters do not work in Graph Explorer

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2121]
I was unable to transfer this issue from the docs repo to here https://github.com/microsoftgraph/microsoft-graph-docs/issues/15922

**Comment by RabebOthmani** [comment]
@Onokaev I believe you fixed this problem?

**Comment by Onokaev** [comment]
The query does not raise a white space invalid error. It works as expected. I have run the query against my tenant and I am getting the correct response:
![image](https://user-images.githubusercontent.com/45680252/195263125-76e7ae3c-445b-424b-830a-550f8c8c979c.png)

From the issue raised on the docs side, it appears to be an issue with making calls to Graph with a filter clause using the SDKs. It is not an issue with the way Graph Explorer works

**Comment by Onokaev** [comment]
Closing this as it is not an issue with the way Graph Explorer works, but with supplying filter clauses to the sdks when making Graph API calls
