### ISSUE TITLE
Try It sidebar in docs doesn't render the source query, always defaults to /me query

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-explorer-v4#2160]
**Describe the bug**
Selecting the Try It link opens the embedded  Graph Explorer window _but_ the URL is always https://graph.microsoft.com/v1.0/me. You must manually paste the actual URL that you wanted to try.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/14026935/194386940-f7f90cef-9a9d-4c06-8b8a-b7bf543e280a.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/14026935/194387066-f68eab7c-99c9-43ec-8245-35bb0c82ad2f.png">

**Comment by thewahome** [comment]
Hello @FaithOmbongi. this has been fixed under #2148 and is part of the release going out immediately

**Comment by FaithOmbongi** [comment]
Thank you, @thewahome, for your swift action. I confirm that the issue has been resolved.
