### ISSUE TITLE
Update User Identities

### ISSUE THREAD

**Issue by benjaminbolitho** [microsoftgraph/microsoft-graph-explorer-v4#2163]
**Describe the bug**
A user currently has 3 user identity sign in types, userName, emailAddress & userPrincipalName.
The user's Azure AD B2C User Profile on the Azure Portal currently displays their username value as the User Principal Name under the Identity section. When updating the user's identities collection via MS Graph, the user's User Principal Name gets updated in Azure Portal to display their email address, rather than continuing to displaying their user name.

**To Reproduce**
1. Go to Azure Portal
2. Navigate to Azure AD B2C
3. Navigate to Users
4. Search for relevant user account
5. Click on User to open the User Profile screen.
6. View the User Principal Name under the Identity section.
7. Copy Object ID
8. Open MS Graph Explorer
9. Login to MS Graph Explorer
10. Run the MS Graph GET endpoint https://graph.microsoft.com/v1.0/users/{Id}/identities NB. Pass in the objectId copied in Step 7.
11. View results. There should be 3 signInTypes: userName, emailAddress & userPrincipalName.
12. The User Principal Name value from Step 6 should match the userName value from Step 11.
13. Run the MS Graph PATCH endpoint https://graph.microsoft.com/v1.0/users/{id} to update the user's identities. Pass a payload containing the same 3 signInTypes from Step 11 but make a change to the emailAddress issuerAssignedId value.
14. Go back to the User Profile screen in Azure Portal which was opened in Step 5.
15. Refresh the User Profile screen.
16. View the User Principal Name under the Identity section. It has updated to show the user's email address instead of their username.

**Expected behavior**
I expect that the User Principal Name value on the User Profile screen would continue to show the username value.

**Desktop (please complete the following information):**
 - OS: Windows 10 Business
 - Browser: Chrome
 - Version 105.0.5195.127

**Comment by Onokaev** [comment]
Hey @benjaminbolitho. Could you please provide screenshots on each of the steps? I got lost while trying to reproduce this

**Comment by benjaminbolitho** [comment]
Hi @Onokaev. Thanks for your response. I raised this issue with Microsoft Support and they have informed me that it is intended behaviour that the UPN value is updated in these circumstances.
