### ISSUE TITLE
Bookmark.Read.All And Acronym.Read.All permissions not available for consent via Graph Explorer

### ISSUE THREAD

**Issue by ZChristine** [microsoftgraph/microsoft-graph-explorer-v4#2164]
**Describe the bug**
 Following new permissions (Bookmark.Read.All, Acronym.Read.All) are currently not available in the Graph Explorer permissions explorer experience. This means customers can't use Graph Explorer for testing the search APIs.

How to Reproduce
**To Reproduce**
1. Go to 'permission picker' in graph explorer

**Expected behavior**
Bookmark.Read.All and Acronym.Read.All should be available in permission picker.

**Screenshots**
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/33659566/195268779-48abcfed-68d4-4331-9143-e29ca096d9f0.png">

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**

**Comment by ElinorW** [comment]
Hey @ZChristine, I'll look into this.

**Comment by ZChristine** [comment]
> Hey @ZChristine, I'll look into this.
Thank you for response. Feel free to let me know if more information is needed.

**Comment by RabebOthmani** [comment]
Hi @ZChristine , the update on permissions happens on the DevX API side, Graph Explorer simply consumes the permissions endpoint. 
I'm closing this issue as the permissions are there now. Please test on your side and let me know if you see any anomalies. Thanks

**Comment by ZChristine** [comment]
@RabebOthmani  the problem got fixed. thanks
