### ISSUE TITLE
Inconsistency in Config Import via PowerShell

### ISSUE THREAD

**Issue by AcpPasc** [microsoftgraph/microsoft-graph-explorer-v4#2165]
**Describe the bug**
We discovered, that one of our Imports of a Configuration json completes successfully but a few Settings are missing (NOT ALL)!
To be more Specific a #microsoft.graph.iosGeneralDeviceConfiguration. We used the [Intune-Config-Frameworks](https://github.com/microsoft/Intune-Config-Frameworks) as template and added our own changes. We discovered that when we import the Configuration via Powershell (With Token, ContentType "application/json" and the Invoke-RestMethod Command) that some Settigns are not Imported as "ture"/Condigured. If we Export, import and export again we get this diff:
![image](https://user-images.githubusercontent.com/104975665/195602875-c882c679-c1a9-426b-8f64-1d1b18f339cd.png)
What is strange if I import the same Config JSON in https://developer.microsoft.com/en-us/graph/graph-explorer it gets imported Correct. 
We did not have this issue with android Configurations or other Configs as far as I am aware.
Furthermore I would like to know why only some settings are missing and others not.

**To Reproduce**
1. Go to '[MEM configProfiles iOS](https://endpoint.microsoft.com/#view/Microsoft_Intune_DeviceSettings/DevicesIosMenu/~/configProfiles)'
2. Create a Device Restriction Policy
3. Set the Settings in the Diff shown above
- Block backup of enterprise books
- Block notes and highlights sync for enterprise books
- Block removal of system apps from device
- Allow copy/paste to be affected by managed open-in
4. Open a Powershell
5. Get an Auth-Token [Token Script](https://www.powershellgallery.com/packages/UnofficialIntuneManagement/0.2.0.0/Content/Private%5CGet-AuthToken.ps1)
6. Export the Configuration (to a File or Clipboard)
```
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/{deviceConfiguration-id}
Invoke-RestMethod -Uri $uri -Headers $global:authToken
```
7. Import the Configuration
```
$JSON = "EXPORTED CONFIG"
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations
Invoke-RestMethod -Uri $uri -Headers $global:authToken -Method Post -Body $JSON -ContentType "application/json"
```
8. Export the config again and check diffrences

**Expected behavior**
I expect the Imported Config to be the same as my Json or completely not Configured if it failes, but not some missing and some not.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [106.0.1370.42]
 - Powershell [5.1.19041.1682]

**Additional context**
We use Powershell Scripts to Export Tested Configurations and import them to our Customers, we need to be able to trust, that what we import will be what we configured or throw an error.

**Comment by ElinorW** [comment]
Hey @AcpPasc , 
To try and understand the issue here, 
Are these differences only present when you export, import, and export the scripts on PowerShell? 
On Graph Explorer, the settings are the same?

**Comment by AcpPasc** [comment]
Hey @ElinorW 
The differences are, like you assumed only presend if we import via PowerShell I didn't see differences, if I Import the same File via Graph Explorer.

**Comment by ElinorW** [comment]
@AcpPasc this seems to be a problem with PowerShell... and not Graph Explorer

**Comment by AcpPasc** [comment]
That is true. What is confusing for me, is that i think i am doing the same API Request as the Explorer but get a diffrent result.

**Comment by ElinorW** [comment]
I think it might be something with PowerShell

**Comment by RabebOthmani** [comment]
Hi @AcpPasc , as my colleagues mentioned we only handle Graph Explorer related issues here. I would recommend opening an issue on the PowerShell repo or using the [community forum ](https://answers.microsoft.com/en-us/) . Please do let us know if there are any Graph Explorer issues you're encountering.
