### ISSUE TITLE
The Adaptive Cards service is down

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/microsoft-graph-explorer-v4#2170]
**Describe the bug**
We are currently following with the Adaptive Cards Template service team to identify if the service is something we should be relying on as today its certificate is expired. https://github.com/microsoft/adaptivecards-templates/issues/302

![image](https://user-images.githubusercontent.com/7620955/196184404-e8d139c4-0fea-4e80-820a-8e972daebb23.png)

**Additional context**
It might be possible that we have to rely on a "local" version of these templates as the service is still in **pre-alpha** phase and doesn't offer any support.

**Comment by sebastienlevert** [comment]
My suggestion would be to bring the .json files directly in the GE repo for now and serve them. This templating service is alpha and got confirmation this is unlikely to go past that stage.

**Comment by ElinorW** [comment]
Does this mean there won't be any new templates?

**Comment by sebastienlevert** [comment]
In the service, yes. We will be rolling out new templates, but we will have to identify where to store / promote them.
