### ISSUE TITLE
Go and PowerShell snippets not loading 

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#2174]
**Describe the bug**
The Go and PowerShell code snippets calls are failing

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'Run Query'
3. Scroll down to 'Code snippets' and click on 'Go' or 'PowerShell'

**Expected behavior**
Go and PowerShell snippets should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/18407044/196514965-02f41d6d-a530-4da5-a297-0ea8efcba21f.png)

![image](https://user-images.githubusercontent.com/18407044/196515370-10129b8f-18f7-481d-b5db-383eb301f6d1.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [edge]

**Comment by irvinesunday** [comment]
This will potentially be resolved with a fix for this issue: https://github.com/microsoft/OpenAPI.NET.OData/issues/297

**Comment by irvinesunday** [comment]
This has been resolved by this PR: https://github.com/microsoft/OpenAPI.NET.OData/pull/299
