### ISSUE TITLE
getting 500 on the following request: https://graph.microsoft.com/v1.0/me/todo/lists

### ISSUE THREAD

**Issue by lionheart06** [microsoftgraph/microsoft-graph-explorer-v4#2175]
**Describe the bug**
server returns 500 when invoking https://graph.microsoft.com/v1.0/me/todo/.lists. With the following error:
"code": "generalException",
        "message": "One or more errors occurred. (Object reference not set to an instance of an object.)",

**To Reproduce**
It cannot be reproduced using the sample data.
Only with my login, it started happening yesterday.

**Expected behavior**
return list of list of todos

**Screenshots**
The request id is : 7fe96700-4386-4778-8ca2-250ec8abe502

**Comment by Onokaev** [comment]
Hey @lionheart06. I have tested this endpoint and it's working on my end
![image](https://user-images.githubusercontent.com/45680252/196609884-7abb2e92-d880-4424-b111-b72924038059.png)

Are you still experiencing the issue?

I have also noticed that the URL you have added on the issue description has a (.) before lists. The dot shouldn't be there

**Comment by lionheart06** [comment]
yes still happening:
![image](https://user-images.githubusercontent.com/746654/196613429-fa9703e5-f384-413a-9ebc-ef015e9175fc.png)

**Comment by lionheart06** [comment]
Let me try with a different account and report back

**Comment by lionheart06** [comment]
Yes, it works with a different account, must be something with my main account on the server side that started happening yesterday
<img width="1152" alt="graphexplorer" src="https://user-images.githubusercontent.com/746654/196614351-b83c3545-0a50-428b-abad-dd7c7d975f8d.png">

**Comment by Onokaev** [comment]
Which type of account were you using? An AAD account or a Microsoft(outlook.com) account?

**Comment by lionheart06** [comment]
outlook.com

**Comment by Onokaev** [comment]
I tested this with an outlook account and it seems to be working. It appears to be intermittent if it's not working on your end. Let me raise it on the Graph Q&A forum for a wider audience

**Comment by Onokaev** [comment]
Here is the link to Graph Q&A: https://learn.microsoft.com/en-us/answers/questions/1057701/getting-error-500-on-metodolists.html

**Comment by Onokaev** [comment]
Let me know if you need any further assistance

**Comment by lionheart06** [comment]
No thank you, it started working.
