### ISSUE TITLE
GET /roleManagement/directory/roleAssignmentScheduleRequests requires more permissions than necessary

### ISSUE THREAD

**Issue by Fuco1** [microsoftgraph/microsoft-graph-explorer-v4#2176]
**Describe the bug**

The endpoint `https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignmentScheduleRequests` should be accessible with a token with scope `RoleManagement.Read.Directory`, but when I try to make a request through the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=roleManagement%2Fdirectory%2FroleAssignmentScheduleRequests&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com) it fails with a permission error:

```json
{
    "instanceAnnotations": [],
    "message": "Authorization failed due to missing permission scope RoleAssignmentSchedule.ReadWrite.Directory,RoleManagement.ReadWrite.Directory.",
    "errorCode": "PermissionScopeNotGranted"
}
```

**To Reproduce**
1. get an access token with just `RoleManagement.Read.Directory` app privilege assigned
2. call `https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignmentScheduleRequests`
3. it errors 

**Expected behavior**

Read permissions should give enough access to *read* data.

**Screenshots**

![image](https://user-images.githubusercontent.com/2664959/196814598-10ba5b0d-e1d0-4f8e-8bdb-d253581517b5.png)

**Additional context**

This is probably not a graph explorer bug as I can reproduce this also with just calling the API with curl.  I don't know where to report this problem.

**Comment by ElinorW** [comment]
Hey @Fuco1, I have been able to reproduce this. I shall look into it

**Comment by ElinorW** [comment]
Seeing that it isn't an issue on Graph Explorer and has more to do with the API. 
I would suggest you ask the question here: https://learn.microsoft.com/en-us/answers/products/graph
