### ISSUE TITLE
chassistype not returned when querying all managedDevices

### ISSUE THREAD

**Issue by JonAmburn** [microsoftgraph/microsoft-graph-explorer-v4#2178]
**Describe the bug**
chassisType attribute is not returned when doing a managedDevices batch query, but is returned when querying individual devices by ID

**To Reproduce**
1. Go to Graph explorer
2. Send a GET to https://graph.microsoft.com/beta/deviceManagement/managedDevices
3. Note that the chassisType attribute is "unknown" for the entire list of returned devices
4. Now send a GET to https://graph.microsoft.com/beta/deviceManagement/managedDevices/{managedDevice-id}
5. Note that the chassisType correctly reflects the device that was queried

**Expected behavior**
chassisType attribute is returned correctly regardless of method used to query managedDevices data

**Screenshots**
When querying all devices
![image](https://user-images.githubusercontent.com/69934260/197040783-407284f4-354d-48f7-93dc-d850cfcab8dc.png)

When querying one device
![image](https://user-images.githubusercontent.com/69934260/197041546-8194b2a7-ac79-44ad-8547-568d9da04698.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 106

**Comment by Onokaev** [comment]
Hey @JonAmburn. I was able to reproduce this issue. However, we cannot fix this on Graph Explorer. I have opened an issue on the Microsoft Q&A forum for a wider audience. 
Here's a link to the ticket: https://learn.microsoft.com/en-us/answers/questions/1059700/chassistype-not-returned-when-querying-all-managed.html
Let me know if you need any further assistance

**Comment by JonAmburn** [comment]
Thanks for the update @Onokaev 
Is there any additional info I need to provide or anything else I need to do for now?

**Comment by Onokaev** [comment]
Not really. The support team has responded to the question on the Q&A forum. Check it out and let me know if it helps
