### ISSUE TITLE
@data.nextlink missing

### ISSUE THREAD

**Issue by Sky640q** [microsoftgraph/microsoft-graph-explorer-v4#2185]
In graph api for intune,AD there used to be nextlink to get > 1000 items, seems to be missing. 
Is there any other way from PS or graph to get more than 1000 items?

**Comment by Onokaev** [comment]
Hey @Sky640q. Please provide the exact endpoint you were making a call to for us to investigate

**Comment by Sky640q** [comment]
I was trying to get script run states for windows, so devicemanagementScripts.

_____________________________
Aakash Regmi
Sr. Systems Administrator
1025 Lenox Blvd, Atlanta, 30319
470-957-6294  | ***@***.******@***.***>
[cid:478e1ed6-5b07-42ae-b62b-b633ff3c5713]      [cid:88a1af2c-88df-4aef-8d05-2e2e8e71536d]
________________________________

**Comment by Onokaev** [comment]
Sorry :). I need the exact endpoint: https://graph.microsoft.com/v1.0/....

**Comment by Sky640q** [comment]
'https://graph.microsoft.com/beta/deviceManagement/deviceManagementScripts/{scriptID}/deviceRunStates

Here you go.
Thanks.
_____________________________
Aakash Regmi
Sr. Systems Administrator
1025 Lenox Blvd, Atlanta, 30319
470-957-6294  | ***@***.******@***.***>
[cid:cbc81277-4a4f-40b4-9746-1c682626f8be]      [cid:693fa5a3-b66c-433e-b7a2-71b77bdea524]
________________________________

**Comment by Onokaev** [comment]
Hey @Sky640q. I was able to reproduce this issue.
However, we can't be of assistance as we handle only Graph Explorer related queries and not issues pertaining to the Graph API. You can repost the question here https://learn.microsoft.com/en-us/answers/products/graph, and the relevant team will help you out.

If you have more questions related to Graph Explorer, feel free to re-open the issue or create a new one.
