### ISSUE TITLE
Autocomplete doesn't automatically load the next series of available paths when selected

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/microsoft-graph-explorer-v4#2231]
**Describe the bug**
When using autocomplete, when selecting a path (ie. /users), I'm expecting the next series of the available paths to become available. I recognize I might want "just" users, but then I could just escape the autocomplete dialog vs. having to enter the "/" to see the rest.

**Screenshots**
![Screenshot-20221110-163222](https://user-images.githubusercontent.com/7620955/201210545-405245cc-b815-4f55-a3e3-44c2e3c93f96.gif)

**Comment by thewahome** [comment]
@sebastienlevert are you saying that you'd want an interaction that does not require a user to enter a slash to load the options in the next path?

**Comment by sebastienlevert** [comment]
I think so. It just feels weird to me that I need to enter / between every clicks.

**Comment by thewahome** [comment]
@gavinbarron

**Comment by gavinbarron** [comment]
You're right @sebastienlevert that does feel a bit weird.

Let me ask you this, what would be the expected behavior when have `/me/calendar` in the url bar?

**Comment by sebastienlevert** [comment]
When I type / after `/me/calendar` I would see what is available under `/calendar` (events, etc.) and when clicking on the next segment I need, the bar would become `/me/calendar/events` and offer me what's under `/events` (`{event-id}`, etc.)

**Comment by gavinbarron** [comment]
@sebastienlevert  I picked that specific example as there are paths that are children of `/me` which are continuations of `calendar` 
How should we handle these continuations of `/me/calendar` that are also valid?
![image](https://user-images.githubusercontent.com/7122716/214711709-7e0397e5-6c35-42a9-8470-d2a177b2f54e.png)

The current implementation avoids scanning across a large set of data and keeps the options presented to the user shorter and more easily scanned, and TBH I'm leery of drilling additional levels down the tree without a `/`,

Perhaps the solution here is that when an auto-complete segment is selected the `/` character is appended to the end of the path? i.e. when a user types /me/calendar and selects that entry in the suggestions list the url path is written as `/me/calendar/`

@thewahome would that work to trigger the auto-complete/suggestions list?

**Comment by thewahome** [comment]
This would work @gavinbarron , however it'd not cater for the use case that someone wants to get the query parameters for me/calendar. Forcing the user to backspace and write the ? to get the suggestions 


Leaving it as is allows the user the choice of triggering the next path, query parameters or simply running the query without distractions

**Comment by gavinbarron** [comment]
Thanks for catching the thing I'd totally overlooked there @thewahome

**Comment by sebastienlevert** [comment]
I get the point of the query parameters. It's a good one and should stick. Maybe an indication to the user for their next "move" could be added, but I'm comfortable with the current state with that finding (I'm also seeing improvements in the auto-complete, so it's even better!)
