### ISSUE TITLE
Blue Consent button not visible

### ISSUE THREAD

**Issue by sassdawe** [microsoftgraph/microsoft-graph-explorer-v4#2238]
**Describe the bug**
Trying to test the `https://graph.microsoft.com/v1.0/users/<id>/mailFolders/inbox/messageRules` API but the consent button is not showing.

Calling `https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messageRules` but not for others. I receive 403 error.

**To Reproduce**
1. Go to Graph Explorer and sign in
2. Try to execute `https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messageRules`
3. Now try to call into another user's mailbox `https://graph.microsoft.com/v1.0/users/<id>/mailFolders/inbox/messageRules`
5. See `Unconsent` text/button.

**Expected behavior**
If consent is missing the blue consent button should be visible on the `Modify permissions` tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/10754765/201966401-561c7508-52f4-4cfd-ac93-f7645d3c0a8a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 108.0.1462.15

**Additional context**

**Comment by Onokaev** [comment]
Hey @sassdawe. Looks like consent to the permission has already been granted by your tenant admin. 
When testing this, I noticed that I still get the same error even after consenting to the MailboxSettings.Read permission. This appears to be a problem with mapping of permissions required to access this resource. 
Let me keep digging to see if I can find the permissions you need to access this resource. 

For a wider audience, re-post the question on the Q&A section of Graph: https://learn.microsoft.com/en-us/answers/questions/121237/microsoft-graph-api.html

**Comment by Onokaev** [comment]
Hey @sassdawe. For more context, the grey button appears when you have already given consent to that permission. 
Initially, it was a label that read 'Consented'. We changed this to an 'Unconsent' button to allow our users to be able to dissent to permissions. 
If you hover over the button, you can see a tooltip that shows  the permissions you need to be able to dissent to the permission. 

The permission listed on the tab seems to be insufficient for accessing the resources on the endpoint. We cannot solve this on the Graph Explorer side. Post it on the Q&A side and you'll get quick help.

Let me know if you need any further assistance

**Comment by Onokaev** [comment]
Let me know if you need any further assistance

**Comment by sassdawe** [comment]
Hi @Onokaev, I think I understand what you are saying, but it doesn't get me any closer to stop getting **403** error.

From the looks of it, I am not the only one who had problems with this: [MailboxSettings.Read and ReadWrite unclear and giving incorrect permissions](https://github.com/microsoftgraph/microsoft-graph-docs/issues/11205)

Is there any ways to grant Application level permissions? This is what I have now:
![image](https://user-images.githubusercontent.com/10754765/204023677-6c31043e-9f86-4c7b-b5cc-f64bf05fcd97.png)

**Comment by Onokaev** [comment]
Hey @sassdawe. It's not possible to grant application permissions to Graph Explorer. It only uses delegated permissions. 
Let me investigate further for a solution

**Comment by Onokaev** [comment]
Hey @sassdawe. Sorry for taking so long with this issue. The feedback I am getting is that it is not possible to access another user's mailbox settings using delegated permissions. There are no delegated permissions for this kind of access.

**Comment by sassdawe** [comment]
Thanks for following up @Onokaev, I really appreciate it.
