### ISSUE TITLE
Modifying permissions will list incorrect scopes for the permission after consent

### ISSUE THREAD

**Issue by musale** [microsoftgraph/microsoft-graph-explorer-v4#2241]
**Describe the bug**
Modifying permissions on the permissions list renders incorrect scopes below the permission after a reload.

**To Reproduce**
1. Open the permissions list from the account menu and search for "presence". This will list 3 scopes you can consent to:
![image](https://user-images.githubusercontent.com/8081536/202450301-6c6dc503-bc5e-4de9-acc3-622bff182726.png)
4. Consent on `presence.Read`. A pop up appears and vanishes. At this point I assume that the permission is consented to because I get this success alert:
![image](https://user-images.githubusercontent.com/8081536/202450663-56aac9fe-4c58-4b14-a28e-07ba9e985e45.png)
5. The bug is the list of scopes under "Presence" are not presence scopes but "APIConnectors" and "AccessReview" scopes:
![image](https://user-images.githubusercontent.com/8081536/202453390-82b9eb9a-6ece-403d-83b1-d3ab2b32a615.png)

**Expected behavior**
The permissions list for presence are correct after consenting to a scope.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge v107.0.1418.42 

**Additional context**
The same thing happens when you search and consent to other permissions like "booking".

**Comment by Onokaev** [comment]
Thanks for this @musale. We are working on it
We'll have a patch out soon
