### ISSUE TITLE
Graph Explorer: Intermittent behavior - Modify permissions tab shows "Admin consent required" is "No" for all APIs

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-explorer-v4#2243]
**Describe the bug**
When you select the Modify permissions tab, regardless of the API on the request box, _all_ listed permissions may show "Admin consent required" is "No", even if it's supposed to be "Yes". Same behavior when you select your profile icon  > Consent to permissions. Wierd thing, this behavior is intermittent. You run the query one time, it's "No", another time, the values are correct.

Try 1:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/14026935/202494864-15ca814d-ccb2-4902-9d79-c12224c324d0.png">

A few minutes later:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/14026935/202496332-dca97934-96bb-45fa-91a8-d888bc50998f.png">

**Expected behavior**
Graph Explorer should show the correct status for whether admin consent is required

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Tested on Chrome
 - Version [e.g. 22] 107.0.5304.107 

**Additional context**
It's all intermittent behavior

**Comment by ElinorW** [comment]
Related to https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2157

**Comment by irvinesunday** [comment]
Tracking this with this IcM ticket: https://portal.microsofticm.com/imp/v3/incidents/details/351055734/home

**Comment by zengin** [comment]
This should now be fixed by the linked PR. The telemetry confirms that we don't observe empty scopes array anymore (the underlying cause).

@irvinesunday I don't have privileges to close the issue. Could you please do that for me?

**Comment by irvinesunday** [comment]
> This should now be fixed by the linked PR. The telemetry confirms that we don't observe empty scopes array anymore (the underlying cause).
> 
> @irvinesunday I don't have privileges to close the issue. Could you please do that for me?

@zengin I too don't have privileges. Maybe @thewahome?

**Comment by ElinorW** [comment]
@zengin I'll close it
