### ISSUE TITLE
Support resources that require claim challenge

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2253]
As a developer, I can use MS Graph Explorer to access resources that require a claims challenge

**Comment by Onokaev** [comment]
Hey @RabebOthmani, could I have more information on this issue?

**Comment by Onokaev** [comment]
Currently confirming if during claims challenge, the current access token is invalidated: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5747

**Comment by Onokaev** [comment]
Currently under review

**Comment by Onokaev** [comment]
This work unblocked users and educated them about handling claim challenges because previously they were not getting the response they should be getting. 
They would get 401s but could not trigger a new authentication process to get the elevated access they needed to access these resources.
