### ISSUE TITLE
Getting 403 on non-admin user drive '/userId/drives' using global admin connection.

### ISSUE THREAD

**Issue by vigneshjp89** [microsoftgraph/microsoft-graph-explorer-v4#2258]
Hi, I am trying to get list of all users drive list using GET /users/userId/drives with scope File.Read.All File.ReadWrite.All Sites.Read.All Sites.ReadWrite.All User.Read.All. I'm getting 403 unauthorized error.

**Comment by ElinorW** [comment]
Hey @vigneshjp89 ,
Could you send a screenshot of the complete response that appears on the response preview?
