### ISSUE TITLE
Include the date header in the Response headers section

### ISSUE THREAD

**Issue by ngash** [microsoftgraph/microsoft-graph-explorer-v4#2262]
**Is your feature request related to a problem? Please describe.**
When debugging MS Graph requests, the _request-id_ and _date_ are crucial in identifying the request logs. The Graph Explorer (GE) interface provides the _request-id_ but not the _date_ in the _Response headers_ tab. This especially painful for requests that the user of GE can't remember the date (or date range) the request was sent e.g. retrieving API calls from history

**Describe the solution you'd like**
Addition of the date header to the response headers would enable easier debugging of requests.

**Describe alternatives you've considered**
Using the network tab of the browser's dev tools to look at the response being received from MS Graph APIs.
While this alternative works for APIs that have been recorded in the current session via the browser's dev tools, API calls retrieved from GE history don't have this alternative.

**Additional context**
![image](https://user-images.githubusercontent.com/6511656/204079616-6df63ccb-fa5c-440d-8f6d-b94f114d31c3.png)

**Comment by thewahome** [comment]
Hello @ngash 
We've encountered this in [this issue](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/995) where we chased down the reason why the headers are not displayed.

Here is [the comment](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/995#issuecomment-864025520) where we detail the findings.

**Comment by ngash** [comment]
Thanks @thewahome
