### ISSUE TITLE
Typing % in the query fields blanks out the screen

### ISSUE THREAD

**Issue by rlv-dan** [microsoftgraph/microsoft-graph-explorer-v4#2265]
**Describe the bug**
If you type % in the query field the screen instantly blanks out. The console shows "Uncaught URIError: URI malformed" errors.

**To Reproduce**
1. Open Graph Explorer
2. Query field is by default set to "https://graph.microsoft.com/v1.0/me"
3. Type % after "me"

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge, Pale Moon
 - Swedish Input keyboard

**Comment by RabebOthmani** [comment]
@adhiambovivian can we please deal with this issue as high priority. We should also consider a hot release once a fix is ready. cc @ddyett  @gavinbarron

**Comment by darrelmiller** [comment]
This bug will prevent any user from being able to search for any string that contains a character that needs to be percent encoded.  This is a MAJOR issue.  Can we please get this deployed ASAP?
