### ISSUE TITLE
Fix the errors thrown by the Resizable package

### ISSUE THREAD

**Issue by Onokaev** [microsoftgraph/microsoft-graph-explorer-v4#2303]
**Describe the bug**
Resizable is throwing loop limit errors every time a handle is resized. The errors are clogging our error reporting in a way that makes it difficult to discover relevant errors that we could be having.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Click on any resize handler and resize it
3. Open the the network tab on DevTools
4. See error (ResizeObserver error)

**Expected behavior**
The ResizeObserver loop limit error should not get to App Insights.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MaryannGitonga** [comment]
The telemetry that was captured regarding the ResizeObserver loop exceptions on App Insights has been filtered out on Power BI to clean them out from the Report.
