### ISSUE TITLE
Response Preview is loading and not finalize the request.

### ISSUE THREAD

**Issue by pandatech1** [microsoftgraph/microsoft-graph-explorer-v4#2305]
**Describe the bug**
When using Graph Explorer, I tried to get a query, is not appear nothing at Response preview. I tried several Get requests and in all it just appears that is loading and does not give the desired response

**To Reproduce**
https://developer.microsoft.com/en-us/graph/graph-explorer?request=me&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

**Expected behavior**
I can use this because i need to localize a SID of users and groups of my company

**Screenshots**
<img width="656" alt="image" src="https://user-images.githubusercontent.com/55597169/207617091-852891ec-c051-42d5-b9e8-74f3c793d228.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge and Chrome
 - Version Edge: 108.0.1462.46 and Chrome: 108.0.5359.100

**Comment by Onokaev** [comment]
Hey @pandatech1. Sorry about this.
We use Monaco Editor to show query responses. It appears the editor did not load correctly on your browser, possibly due to a network issue. 
Do you still experience the issue when you reload Graph Explorer?

**Comment by pandatech1** [comment]
Hi. thanks a lot. My issue is solved with success.

**Comment by Onokaev** [comment]
You are welcome :)
