### ISSUE TITLE
Can't retrieve Bitlocker Recovery Keys

### ISSUE THREAD

**Issue by TiredFindingUserName** [microsoftgraph/microsoft-graph-explorer-v4#2306]
Trying to retrieve Bitlocker keys with no success.
Issue 1 - the process can't be scripted (no application-based permission, delegated only). Why?
Issue 2 - "key" value does not exist in Graph Explorer and it is empty running Get-MgInformationProtectionBitlockerRecoveryKey.

For issue - 2 Azure AD does show the key

**To Reproduce**
Steps to reproduce the behavior - Graph
1. Go to 'https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys'
2. Click on 'Run query'
3. See the list of items - none of them have "key"
4. Copy-paste key ID from AAD, and put it in the query: https://graph.microsoft.com/beta/informationProtection/bitlocker/recoveryKeys/keyID - the result is the same, no key available

Steps to reproduce the behavior - PowerShell
1. Connect-MgGraph  -Scopes "BitLockerKey.ReadBasic.All", "DeviceManagementManagedDevices.Read.All"
2. Copy-paste key ID from AAD
3. Run Get-MgInformationProtectionBitlockerRecoveryKey -BitlockerRecoveryKeyId keyID
4. Value "key" is empty

**Expected behavior**
Issue 1 - it would be great to be able to assign this permission to apps, not only users
Issue 2 - expected to get a recovery key in the "key" field

**Comment by ElinorW** [comment]
Hey @TiredFindingUserName 
According to the documentation, this particular request doesn't return a key 
![image](https://user-images.githubusercontent.com/18407044/231429962-08a181ad-ca25-42ce-9048-abfb029de80d.png)

Ref: https://learn.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta
