### ISSUE TITLE
can't send mail

### ISSUE THREAD

**Issue by onomea** [microsoftgraph/microsoft-graph-explorer-v4#2307]
Send mail is requiring admin consent even though documentation says no admin consent required. There's a prompt about being blocked by admin. what would cause this?
![image](https://user-images.githubusercontent.com/120144524/209238427-f357d753-b385-41c0-9ba7-33a4565d96e5.png)

Thanks

**Comment by Onokaev** [comment]
Hey @onomea. It is possible for a tenant admin to block consent to specific permissions for the tenant regardless of the permissions not requiring admin consent. This appears to be the issue with your case.
Ask your tenant admin to grant you the consent as mentioned on the error message. Re-open the issue if you require further assistance
