### ISSUE TITLE
averageComparativeScores returning empty from /security/secureScores

### ISSUE THREAD

**Issue by kmtechsupport** [microsoftgraph/microsoft-graph-explorer-v4#2329]
querying the following endpoints 

https://graph.microsoft.com/v1.0/security/secureScores
https://graph.microsoft.com/beta/security/secureScores

both return "averageComparativeScores": [],

this worked fine yesterday, comparative scores appear correctly in the Defender portal.

**Comment by kmtechsupport** [comment]
This now seems to be working, but I changed absolutely nothing about the query. Seems to be inconsistent?

**Comment by Onokaev** [comment]
Hey @kmtechsupport. This appears to have been a temporary issue. Looks like it was resolved.
You can raise this issue on the Graph Q&A site here for more information: https://learn.microsoft.com/en-us/answers/questions/ask.html
We cannot investigate this further on Graph Explorer
