### ISSUE TITLE
Graph Explorer subscriptions is broken

### ISSUE THREAD

**Issue by spjf** [microsoftgraph/microsoft-graph-explorer-v4#2343]
**Describe the bug**
Using a developer account, I am the Owner of the account. When in Graph Explorer and trying to get subscriptions, it returns an empty array. Checking in the portal, using PowerShell as the same user, returns the subscription which as expected.

**To Reproduce**
1. Login
2. Enter https://graph.microsoft.com/v1.0/subscriptions
3. Click Run Query
4. Receive empty result.
e.g: {
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions",
    "value": []
}

To confirm, checking the Access Token at JWT.IO, I can see it has the role,  Subscription.Read.All.

**Expected behavior**
Receive the subscription the same as in PowerShell or via the portal.

**Desktop (please complete the following information):**
- Browser
- JavaScript libraries

**Comment by ElinorW** [comment]
Hey @spjf ,
I have been able to reproduce this. 
When you say via the Portal. Are you referring to Azure Portal?
