### ISSUE TITLE
Unable to change user's account status through Graph Explorer

### ISSUE THREAD

**Issue by chiyao-ms** [microsoftgraph/microsoft-graph-explorer-v4#2352]
**Describe the bug**

When target user has an AAD role (Azure AD Joined Device Local Administrator), unable to change account status using Graph Explorer.
If the user has no AAD role, it succeeded without any error.
Also, no error/issue when changing the status on Azure Portal or Microsoft Graph PowerShell SDK, only Graph Explorer.
Our support team confirmed repro on multiple tenants.

**To Reproduce**
1. Assign user to Azure AD Joined Device local Administrator role.
2. Sign in to MS graph explorer using another administrator user.
3. Set following permission.
User.ReadWrite, User.ReadWrite.All, User.ManageIdentities.All, Directory.ReadWrite.All

4. Run following query.

PATCH /users/{Object ID of User who has Azure AD Joined Device local administrator role}
Body {"accountEnabled": flse}

7. See error

![image](https://user-images.githubusercontent.com/28209857/213297094-d0a0d5be-0e85-45e5-a2dc-2bfa9efc3ee9.png)

**Expected behavior**
Can change user status using Graph Explorer.

**Screenshots**

![image](https://user-images.githubusercontent.com/28209857/213297335-7bd7ccc5-7073-454f-9076-a3c10d5bd52f.png)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser Edge
 - Version 

**Additional context**

**Comment by Onokaev** [comment]
Hey @chiyao-ms. This appears to be a permissions issue with the tenants that you are using. To be sure, could you create a sample sandbox here: https://developer.microsoft.com/en-US/microsoft-365/dev-program. Then try to reproduce the error.

I have tested this with my sample tenant and it's working. Confirm if the tenant admins have restricted consent to the permissions that you need. It's possible for tenant admins to restrict consent to some permissions. These permissions may still appear on Graph Explorer, and you'll be able to give consent to them, but calls to the endpoint still fail.
