### ISSUE TITLE
Code snippit for Powershell doesn't say which graph profile to use

### ISSUE THREAD

**Issue by jonwbstr** [microsoftgraph/microsoft-graph-explorer-v4#2357]
Using graph explorer I ran the following query
```
https://graph.microsoft.com/beta/deviceManagement/groupPolicyCategories?$expand=parent($select=id, displayName, isRoot),definitions($select=id, displayName, categoryPath, classType, policyType, version, hasRelatedDefinitions)&$select=id, displayName, isRoot, ingestionSource&$filter=ingestionSource eq 'builtIn'
```

The Code Snippet for Powershell suggested the following command:
```
Import-Module Microsoft.Graph.DeviceManagement.Administration

Get-MgDeviceManagementGroupPolicyCategory -ExpandProperty "parent(`$select=id,+displayName,+isRoot),definitions(`$select=id,+displayName,+categoryPath,+classType,+policyType,+version,+hasRelatedDefinitions)" -Property "id,+displayName,+isRoot,+ingestionSource" -Filter "ingestionSource+eq+'builtIn'" 
```

The command ```Get-MgDeviceManagementGroupPolicyCategory``` is currently available in the 'beta' profile so the correct code is
```
Import-Module Microsoft.Graph.DeviceManagement.Administration
Select-MgProfile -name beta

Get-MgDeviceManagementGroupPolicyCategory -ExpandProperty "parent(`$select=id,+displayName,+isRoot),definitions(`$select=id,+displayName,+categoryPath,+classType,+policyType,+version,+hasRelatedDefinitions)" -Property "id,+displayName,+isRoot,+ingestionSource" -Filter "ingestionSource+eq+'builtIn'" 
```

The javascript example does note which version of grah to use.

**Comment by peombwa** [comment]
Thanks for following up on this.

There is a link in the comments that shows customer how to load the right profile version using Select-MgProfile - https://aka.ms/pshellsdkdocs. We don't include Select-MgProfile in the snippets as it can be called at any point in a script, ideally at the beginning of a script together with Connect-MgGraph.

We've also dropped support for profiles in v2.x, so Select-MgProfile will no longer be needed once we GA v2.x in a few weeks - [msgraph-sdk-powershell/upgrade-to-v2.md at features/2.0 · microsoftgraph/msgraph-sdk-powershell (github.com)](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md#profile-support).

**Comment by jonwbstr** [comment]
Thanks for the update, looking forward to 2.x!
