### ISSUE TITLE
https://api.securitycenter.microsoft.com/api/vulnerabilities/machinesVulnerabilities api is not working. Showing bad request. Example is taken from here: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-all-vulnerabilities-by-machines?view=o365-worldwide

### ISSUE THREAD

**Issue by jimmymuzza** [microsoftgraph/microsoft-graph-explorer-v4#2361]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ElinorW** [comment]
Hey @jimmymuzza 
The API you are trying to access doesn't seem to be a Microsoft Graph API. Graph Explorer works with Microsoft Graph APIs

**Comment by ElinorW** [comment]
Closing this issue as it's not related to Graph Explorer. 
If you have further questions about Graph API's, you may ask here: https://developer.microsoft.com/en-us/graph/support
