### ISSUE TITLE
GE runs previous query on Enter/Return instead of current query

### ISSUE THREAD

**Issue by eduardomb08** [microsoftgraph/microsoft-graph-explorer-v4#2366]
**Describe the bug**
When I type/paste a query in the query input field in a way that the suggestions are not displayed and I hit Enter/Return on the keyboard, GE runs the previous query present in the query input field.

**To Reproduce**
1. Go to aka.ms/ge (no need to log in, the steps here work for the Sample tenant too)
2. Click on the query input field and hit Enter/Return on the keyboard
3. Confirm that the json doc for the current user is returned ("Megan Bowen" for me using the Sample tenant)
4. Click at the end of the query text in the query input field again
5. Hit backspace twice to delete "me" from the end of the text and type "sites/root/lists"
6. Hit Enter/Return again
7. Verify that the same json doc for a user (e.g. "Megan Bowen") is returned instead of the correct array of lists for the root site.
8. Hit Enter/Return one more time
9. Verify that the correct array of lists is returned this time.

**Expected behavior**
Hitting Enter/Return on the query input fields should always result in the current query present in that field to be executed.

**Screenshots**
Results after step 6 above:
![image](https://user-images.githubusercontent.com/11743735/215516515-6f7fc4e8-4979-4ac2-bb83-b26472aecfa5.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Version 21H2 (OS Build 19044.2364)
 - Browser Chrome Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by Onokaev** [comment]
Hey @eduardomb08. We are aware of this issue and have already fixed it. The fix will be out on our next release.
