### ISSUE TITLE
Add telemetry for code snippets tab clicks

### ISSUE THREAD

**Issue by Onokaev** [microsoftgraph/microsoft-graph-explorer-v4#2370]
We currently lack individual tracking of snippet tab clicks. We only have telemetry for the SDK and documentation link clicks

**Comment by RabebOthmani** [comment]
Hi @Onokaev , can you please clarify what you mean by individual tracking of snippet tabs? Do you mean tracking for each language?

**Comment by Onokaev** [comment]
Let me move this to AzDo
