### ISSUE TITLE
Missing requested permissions for (beta) search People?

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoftgraph/microsoft-graph-explorer-v4#2374]
**Describe the bug**
I am ( as the Global Admin ) trying to search for people using the Graph Explorer and the (beta) Search people sample query.

**To Reproduce**
1. Run the search unmodified
2. Grant any permission in the "modify permissions" tab
3. Run the search again

{
    "error": {
        "code": "System.UnauthorizedAccessException",
        "message": "Access to ExchangePerson in Graph API requires the following permissions: People.Read. However, the application only has the following permissions granted: Bookmark.Read.All, Calendars.Read, ChannelMessage.Read.All, Chat.Read, ExternalItem.Read.All, Files.Read.All, Mail.Read, Sites.Read.All, Sites.ReadWrite.All, User.Read, Acronym.Read.All",
        "target": "",
        "httpCode": 403
    },
    "Instrumentation": {
        "TraceId": "9b5699a7-7f59-a592-bd9d-92a98de68bed"
    }
}

**Expected behavior**
Some results would be nice :-)

**Screenshots**
![image](https://user-images.githubusercontent.com/20593570/216034114-904fcdfe-6685-4fe1-9c37-9652b27522be.png)

**Desktop (please complete the following information):**
 - OS: Win11 22H2
 - Browser Edge
 - Version 109.0.1518.70

**Additional context**

**Comment by Onokaev** [comment]
Hey @kasperbolarsen. The Modify Permissions tab does not have the People.Read permission that is required from the error message. 
Click on the profile component on the top right of the app:
![image](https://user-images.githubusercontent.com/45680252/216038369-331794d6-00d4-4586-bf99-a1d54df19601.png)

Next, click on 'Consent to permissions':
![image](https://user-images.githubusercontent.com/45680252/216038451-1a26fd6e-c61b-4cf8-8915-0c4223df055f.png)

On the panel that appears, search for People.Read:
![image](https://user-images.githubusercontent.com/45680252/216038571-f6211f39-c587-477a-a304-6f50c4797704.png)

Click on Consent.

That should fix the problem

**Comment by kasperbolarsen** [comment]
Spot on :-) That resolved the issue.
