### ISSUE TITLE
(beta) search people can't handle a wildcard?

### ISSUE THREAD

**Issue by kasperbolarsen** [microsoftgraph/microsoft-graph-explorer-v4#2375]
**Describe the bug**
When searching for lists, listitems and so forth, a queryString:"*" yields a result. People Search does not

**To Reproduce**
1. Go to (beta) search people
2. change queryString to "*" in the Request body tab
3. Run the query
4. See a total of 0 elements returned
5. Change the queryString to "Adele" (demodata)  and the user data is returned.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/20593570/216040322-8d3655c0-b3df-492a-97ef-2c9302056cc7.png)

**Desktop (please complete the following information):**
 - OS: Win 11 22H2
 - Browser Edge

**Comment by ElinorW** [comment]
Hi @kasperbolarsen 
I believe at the moment only the Email and Site properties can support wildcards. 
Ref https://learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta#keyword-query-language-kql-support

**Comment by kasperbolarsen** [comment]
Thanks @ElinorW for the answer.  However I wonder how come this feature is released as beta without this most basic option. Looking forward to the 1.0 version 🙂

**Comment by ElinorW** [comment]
@kasperbolarsen , 
Actually, you can suggest this feature update here: https://developer.microsoft.com/en-us/graph/support, and the appropriate team will look it up.
