### ISSUE TITLE
Multiple tabs will only show "Loading..." 

### ISSUE THREAD

**Issue by jessierobbins** [microsoftgraph/microsoft-graph-explorer-v4#2398]
**Describe the bug**
Request body, Response preview and Response headers tabs showing "Loading..." 

**To Reproduce**
1. Load https://developer.microsoft.com/en-us/graph/graph-explorer
2. By default, the Request body tab will show loading
3. Run query for https://graph.microsoft.com/v1.0/me
4. Get OK - 200 - ###ms alert bar between request/response sections
5. Response preview shows loading
6. Change to Response headers, shows loading
7. Code snippets and Toolkit component show content, but nothing personalized
8. Adaptive cards tab shows content with data from https://graph.microsoft.com/v1.0/me

**Expected behavior**
Data to be shown in request body, response preview, and response headers

**Screenshots**
![image](https://user-images.githubusercontent.com/4707069/216459128-06947c0a-43df-4c49-bfed-4264749a64c7.png)
![image](https://user-images.githubusercontent.com/4707069/216459168-d56b2324-e1f4-47fe-a24e-01dfb4e5f7d0.png)
![image](https://user-images.githubusercontent.com/4707069/216459186-439adf0f-ada1-4e7d-8431-2a202bb19805.png)
![image](https://user-images.githubusercontent.com/4707069/216459200-46742534-aa2a-44d8-b56b-2e08259252e7.png)
![image](https://user-images.githubusercontent.com/4707069/216459223-3db99405-2a66-4dfe-8867-7175b7c3ef39.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - (same behavior both browsers)
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] 109.0.1518.70 (64-bit)
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 109.0.1 (64-bit)

**Additional context**
This seems to have started happening at around the same time as the adaptive cards inclusion.

**Comment by Onokaev** [comment]
Hey @jessierobbins. This is happening because the Monaco editors did not load correctly, possibly due to a network connection issue on your end. Do you still experience this after reloading?
Refreshing or switching to a stronger internet connection will solve this problem

**Comment by jessierobbins** [comment]
@Onokaev - do you know what the base URL for Monaco editor references is? It is quite possible that our organizational web filter is blocking them.

**Comment by Onokaev** [comment]
Sure. Here it is: https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/loader.js
Let me know if it works

**Comment by jessierobbins** [comment]
That was it - the reference was being blocked by our web filter. Thank you!
