### ISSUE TITLE
[User Story-Resource Explorer] Ability to upload a collection

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2406]
As a user, when I click on the upload collection button, 
And I don’t have any other collection on Graph Explorer,
I have the ability to upload from my device a previously created collection

**Comment by thewahome** [comment]
@RabebOthmani

**Comment by RabebOthmani** [comment]
This story was out of the Feb milestone back now to be worked on
