### ISSUE TITLE
[User Story-Resource Explorer] Prompt user to choose which collection to use  

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2407]
As a user, when I click on the upload collection button, 
And I have another collection on Graph Explorer,
I see a pop-up asking me whether I want to continue with my current collection or I want to upload another one

**Comment by gavinbarron** [comment]
Suggest that we word this along the lines of "Overwrite existing collection" or "Cancel"

**Comment by thewahome** [comment]
So we expect to have multple collections at the same time?

**Comment by gavinbarron** [comment]
@thewahome my expectation is that is a future feature, the initial version will only support a single collection in the browser, perhaps @RabebOthmani can clarify?
