### ISSUE TITLE
[User Story-Resource Explorer] Button to start the client generation 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2409]
As a user, when I click on the generate button on the collection view ,
my collection will be used to generate an API client

**Comment by RabebOthmani** [comment]
Removing from milestone as spec might change

**Comment by RabebOthmani** [comment]
Closing this issue as it's not part of the scope anymore. New scope includes generating an API manifest which is covered in a different epic. @thewahome do you agree?

**Comment by thewahome** [comment]
agreed
