### ISSUE TITLE
"Run query" frequently executes previous query

### ISSUE THREAD

**Issue by wizofaus** [microsoftgraph/microsoft-graph-explorer-v4#2412]
**Describe the bug**
It seems if you update the query too quickly and click "Run query", it executes whatever it ran previoulsy

**To Reproduce**
1. Use a working example like GET /v1.0/me & click Run Query
2. Verify results
3. Edit query to something else that would return a different result and quickly click Run Query again
4. Observe that often the results are the same, and in fact you can determine it simply re-executed the previous query
5. Click Run Query again and you'll see the expected result

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: latest Chrome or Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
Hello @wizofaus we may have captured this experience and closed it in this PR: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2348

Might you have the time to confirm on this live environment whether that is still the case? https://jolly-sand-0ac78c710.azurestaticapps.net/

**Comment by wizofaus** [comment]
Nope, it's still happening, and in fact it some ways it seems worse when using the Enter key, it seems to pick the first suggestion if what I want to enter is what that suggestion *starts* with.  But if I query https://graph.microsoft.com/v1.0/me/, it works, then add "mailboxSettings" to the end and hit enter, it doesn't correctly requery with that new URL.

**Comment by thewahome** [comment]
Hello @wizofaus this is fixed now and in production. Thank you for notifying us and helping us test!
