### ISSUE TITLE
Graph API list MailFolders 

### ISSUE THREAD

**Issue by jonathanyaod3** [microsoftgraph/microsoft-graph-explorer-v4#2415]
**Describe the bug**
Graph API list MailFolders cannot list customer created folders, but the folder can be get with GET /users/{id | userPrincipalName}/mailFolders/{id}

**To Reproduce**
1. Go to  Graph Explorer 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. run GET /me/mailFolders
3. Only built-in folders are returned, including 
        "Archive",
        "Conversation History",
        "Deleted Items",
        "Drafts",
        "Inbox",
        "Junk Email",
        "Outbox",
        "RSS Feeds",
        "Sent Items",
5. But custom created folders are not returned. 
![image](https://user-images.githubusercontent.com/79876505/217654024-ed6a08df-a209-4233-9a7c-72590ab78913.png)
6. However, when I get folderId from web UI, I can retrieve this folder with GET /me/mailFolders/{id}. That means this folder is created successfully and is under root folder.
![image](https://user-images.githubusercontent.com/79876505/217653826-c38dc2a3-9409-4c89-89b6-dce69de4b84e.png)

**Expected behavior**
Both built-in folders and custom created folders are returned.

**Additional context**
I can get message from custom created folder with GET /me/mailFolders/{id}/messages. But cannot get the folder with List mailFolders API(GET /me/mailFolders)

**Comment by ElinorW** [comment]
Hey @jonathanyaod3,
From your first screenshot, the response has the message `This response contains an @odata property.: @odata.nextLink Click here to follow the link`
This is because of the pagination applied to the results. It's possible the folder is on the next page.
Could you try clicking on the link and confirming if the folder is there?
