### ISSUE TITLE
appears MS Graph Explorer doesn't handle Continuous Access Evaluation (CAE) errors

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-explorer-v4#2425]
Getting error:
"additional claims required" when making certain API calls...

MS Graph Explorer needs to implement this so that conditional access policies are enforced for CAE:
https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/active-directory/develop/claims-challenge.md
https://learn.microsoft.com/en-us/azure/active-directory/develop/app-resilience-continuous-access-evaluation?tabs=JavaScript

**Comment by Onokaev** [comment]
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2253

**Comment by Onokaev** [comment]
Hey @willfiddes, we are currently working on this. It should be possible to make this calls after our next release

**Comment by Onokaev** [comment]
Which endpoint threw the claims challenge?

**Comment by Onokaev** [comment]
You can also test if the claims are handled here: https://jolly-sand-0ac78c710-2422.centralus.azurestaticapps.net/
