### ISSUE TITLE
Got a 500 error when creating a service principal for first party app

### ISSUE THREAD

**Issue by yeeyang19** [microsoftgraph/microsoft-graph-explorer-v4#2427]
**Describe the bug**
I'm creating first party app according to [the document](https://review.learn.microsoft.com/en-us/identity/microsoft-identity-platform/app-config-test-flows?branch=main&tabs=1prepo#create-a-service-principal-for-your-app-in-your-test-tenant). 
I created a test tenant and followed the steps in the above link to create a service principal. I got a 500 error, so I don't know what's wrong with my request, could you help look into it? Thanks. 

**To Reproduce**
1. sign in with my test tenant
2. modify permission to consent 
3. request:
POST https://graph.microsoft.com/v1.0/servicePrincipals
{
    "appId": "xxx"
}
4. response:
{
    "error": {
        "code": "Service_InternalServerError",
        "message": "Encountered an internal server error.",
        "innerError": {
            "date": "2023-02-28T07:53:31",
            "request-id": "0e0b41a6-1871-4799-b27e-5a1acc994f6c",
            "client-request-id": "4535c38a-9086-6095-6b90-a33ed43517e0"
        }
    }
}

**Expected behavior**
Successfully create a service principal for the 1p app. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7833974/221802041-0ad1a67c-db4b-4c29-bd3f-572a142cb11a.png)

**Desktop (please complete the following information):**
 Browser Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ElinorW** [comment]
Hi @yeeyang19 ,
Could you confirm if you are still experiencing this issue?
