### ISSUE TITLE
Typing in the query bar loses/removes every other keystroke after adding $filter query

### ISSUE THREAD

**Issue by gavinbarron** [microsoftgraph/microsoft-graph-explorer-v4#2431]
**Describe the bug**

**To Reproduce**
Add ?filter=
Type more
Get frustrated
https://clipchamp.com/watch/CJ9UsEGtNLJ

**Expected behavior**
Users should love typing in a filter.

**Screenshots**
Video: https://clipchamp.com/watch/CJ9UsEGtNLJ

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge 
 - Version 110.0.1587.63 (Official build) (64-bit)

**Comment by Onokaev** [comment]
Hey @gavinbarron. Apologies for this experience. I have created a PR to fix it.
