### ISSUE TITLE
Drives Items returns 'filter required' incorrectly

### ISSUE THREAD

**Issue by OzBob** [microsoftgraph/microsoft-graph-explorer-v4#2442]
**Describe the bug**
When using the beta [MS Graph Explorer | Resources | ](https://developer.microsoft.com/en-us/graph/graph-explorer)
Use the https://graph.microsoft.com/beta/drives/{drive-id}/items endpoint
Then substitute the {drive-id} value for a valid sharepoint site, drive id.
Expect to have a list of drive items.
but the actial error message is
```
"error": {
        "code": "invalidRequest",
        "message": "The 'filter' query option must be provided.",
```

**Expected behavior**
Expect to have a list of drive items.

**Screenshots**
![image](https://user-images.githubusercontent.com/1796771/223664018-30eee9c6-9f8e-4645-b549-ea2fada46e9d.png)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser firefox v110
 - Version MSGRAPH beta

**Comment by ElinorW** [comment]
Hi @OzBob, 
This might be because the request is incorrect. 
To list the drive items, please reference the queries listed on the docs here https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-beta&tabs=http

**Comment by vishal-bihani** [comment]
I would like to reopen this issue. 

> Hi @OzBob, This might be because the request is incorrect. To list the drive items, please reference the alternative requests listed on the docs here https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-beta&tabs=http

This resource you are referring has apis that requires `item id`. I don't find this relevant to this issue. I want to list all items in a drive, I only know the drive id.

**Comment by ElinorW** [comment]
Hi @vishal-bihani, 
This is an issue related to the Graph OneDrive API's. Please raise this on the [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) forum where the appropriate team will be able to assist you
