### ISSUE TITLE
Graph API deviceManagement/managedDevices/ no POST/ not POSTING

### ISSUE THREAD

**Issue by BfWork** [microsoftgraph/microsoft-graph-explorer-v4#2448]
![Snip](https://user-images.githubusercontent.com/127439851/224127936-64900e2d-386e-4f67-9ef9-a5e82d2ae5eb.jpg)

Copied Stright from API Docs, doesn't work. added permission still doesn't work. First time experiencing internal error.

**Comment by ElinorW** [comment]
Hi @BfWork, 
This seems to be an issue with the Graph API. 
Please post this in the Micorosft Q&A forum where the appropriate team will be able to have a look at it
