### ISSUE TITLE
Very difficult to type text into URL area

### ISSUE THREAD

**Issue by theficus** [microsoftgraph/microsoft-graph-explorer-v4#2455]
**Describe the bug**
I'm trying to type an OData query into the URL section. It seems to be due to overly aggressive Intellisense. I find that I have to re-type characters a minimum two times for it to appear. It makes for a really frustrating experience. I have to type the URL into Notepad and copy/paste into the browser.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Click on "Applications" -> "list all applications with count"
3. Go to URL entry
4. Try to modify text around $count

**Expected behavior**
Typing should work properly

**Screenshots**
![pp](https://user-images.githubusercontent.com/11638244/225722443-0a5a5e75-2692-4aca-8735-0508d01f8bff.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 111.0.1661.41

**Comment by ElinorW** [comment]
hey @theficus, 
We have a new release that may have fixed this issue. 
Could you try launching the page again on a new window and confirming if this issue is still present?
