### ISSUE TITLE
404 errors on https://graph.microsoft.com/v1.0/invitations

### ISSUE THREAD

**Issue by nantoine555** [microsoftgraph/microsoft-graph-explorer-v4#2456]
**Describe the bug**
I get 404 errors on most of /invitations Resources

**To Reproduce**
1. Open graph explorer (same in curl by the way), connect with an account with correct permissions.
2. Test https://graph.microsoft.com/v1.0/invitations
3. Error 404
4. {
    "error": {
        "code": "UnknownError",
        "message": "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/><title>404 - File or directory not found.</title><style type=\"text/css\"></style></head><body><div id=\"header\"><h1>Server Error</h1></div><div id=\"content\"> <div class=\"content-container\"><fieldset>  <h2>404 - File or directory not found.</h2>  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3> </fieldset></div></div></body></html>",
        "innerError": {
            "date": "2023-03-17T11:27:56",
            "request-id": "8c4c76f0-5f1a-4c52-82ca-51bff770a5b6",
            "client-request-id": "7836f7ab-c0a7-7f29-f38e-cb21168ec4b6"
        }
    }
}

**Expected behavior**
I should see all invitations if permited, or an error if I am not. But not a 404 error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos 13.2.1
 - Browser chrome
 - Version 111

**Additional context**
 - Same error querying the /invitations with a get with a pure curl. Sending a POST works fine, invitation is sent correctly.

**Comment by nantoine555** [comment]
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/5659763/225893620-6fe4c4e8-709e-4602-b595-ed6ea5a3fdb8.png">

**Comment by ElinorW** [comment]
hi @nantoine555, 
This seems to be an issue with the Graph API.
