### ISSUE TITLE
FireFox AutoCorrect in URL textbox, adds "=" to make invalid URI, Drives Count$ endpoint Invalid

### ISSUE THREAD

**Issue by OzBob** [microsoftgraph/microsoft-graph-explorer-v4#2457]
**Describe the bug**
In the MS Grpah Explorer:
https://developer.microsoft.com/en-us/graph/graph-explorer
the URL 
https://graph.microsoft.com/beta/sites/51853ae5-8cd3-496d-960b-e509fb327822/drives/$count
is autocorrected to
https://graph.microsoft.com/beta/sites/51853ae5-8cd3-496d-960b-e509fb327822/drives/$count=

**Expected behavior**
do not add =

**Screenshots**
![image](https://user-images.githubusercontent.com/1796771/226235686-5d530edd-81eb-4147-831f-483d755c20d9.png)

**Desktop (please complete the following information):**
 - OS: windows Win11
 - Browser FireFox
 - Version 111

NOT present in Edge Dev on same url logged in to same Graph Explorer, but the URL suggested in the Resources tab as valid has a validation error and a return error of "invalidRequest"
![image](https://user-images.githubusercontent.com/1796771/226236134-997585e7-59cb-460a-94b4-8df198e1af83.png)

**Comment by ElinorW** [comment]
Hello @OzBob, 
I'm unable to reproduce the '=' sign that's added on firefox. 
Though we recently released an update with some autocomplete fixes and it's possible your Firefox may be loading a previous version of GE, clearing the cache and reloading the page should sort this out. 

Regarding the validation and "invalidRequest" error, rewriting this query to include a ? should fix it. i.e `https://graph.microsoft.com/beta/sites/51853ae5-8cd3-496d-960b-e509fb327822/drives/?$count`
