### ISSUE TITLE
employeeLeaveDateTime attribute not updating. 

### ISSUE THREAD

**Issue by lukewelden-mobysoft** [microsoftgraph/microsoft-graph-explorer-v4#2458]
**Describe the bug**
Hey, I've followed the instructions for setting the employeeLeaveDateTime https://learn.microsoft.com/en-us/graph/tutorial-lifecycle-workflows-set-employeeleavedatetime?toc=%2Fazure%2Factive-directory%2Fgovernance%2Ftoc.json&bc=%2Fazure%2Factive-directory%2Fgovernance%2Fbreadcrumb%2Ftoc.json&tabs=http but it doesn't appear to be updating the attribute. 

After updating the permissions I’m getting a 204 http response which indicates the api call has been successful. However, when checking the user attributes using the MsGraph PowerShell module the EmployeeLeaveDateTime field is empty. 
``` Get-MgUser -UserId $UserID | Format-List ```
I've also attempted to update this attribute via powershell to no avail. 

```
Connect-MgGraph -Scopes "User.Read.All","User-LifeCycleInfo.ReadWrite.All"
Select-MgProfile -Name "v1.0"

$UserId = "528492ea-779a-4b59-b9a3-b3773ef6da6d"
$employeeLeaveDateTime = "2022-09-30T23:59:59Z"
   
Update-MgUser -UserId $UserId -EmployeeLeaveDateTime $employeeLeaveDateTime
$User = Get-MgUser -UserId $UserId
$User.EmployeeLeaveDateTime
```

The above commands didn’t work. The field is still showing as empty after running the commands. Continuing to investigate. 

I’ve tried testing the EmployeeHireDate field as that is a field that is visible in the AzureAD GUI and the field is updating via Graph calls. This is evident in the GUI but when trying to query the user object in Powershell the field is showing as blank. 

**To Reproduce**
1. Use Graph to PATCH user object with the following body { "employeeLeaveDateTime": "2023-03-20T00:00:00Z"}
2. Also try the above powershell commands 

**Expected behavior**
Graph should update the user attribute employeeLeaveDateTime 

**Screenshots**
![image](https://user-images.githubusercontent.com/85990117/226381456-c6bc9ce6-0cbd-461b-a3d1-085c0ff16169.png)
![image](https://user-images.githubusercontent.com/85990117/226381485-9aab798d-6e2c-4069-a534-c827d9af522e.png)

**Comment by Onokaev** [comment]
Hey @lukewelden-mobysoft. I am currently testing this. I noticed that the PowerShell command references the /v1.0 endpoint while the PATCH was made on the /beta endpoint. This might not be the issue since the data is coming from one place, but it's worth checking out. 

When we find the issue, we won't be able to fix it on Graph Explorer, but just advice on the next steps. For this reason, I'd suggest reposting this question on the Q & A forum and tagging `Microsoft Graph Users API` for a wider audience.
Here is the link: https://learn.microsoft.com/en-us/answers/questions/ask/

Just paste the issue there as I follow up on my end

**Comment by lukewelden-mobysoft** [comment]
Hey, @Onokaev. 

Thank you for looking into this one for me. So it seems like it was working all along but to see the change we have to use the beta version of Graph, gotcha! 

I've tested on my end with a PATCH using the v1.0 endpoint and a GET with the beta endpoint and I can confirm that the field is being updated. 

Thank you!
