### ISSUE TITLE
Valid URLs marked as potential errors

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/microsoft-graph-explorer-v4#2461]
**Describe the bug**
When using the textbox to work with a lot of URLs is misleading when using a valid URL. For instance, I'm using this URL and it tells me I _might_ have an error. I don't know how other users feel about this but it's misleading. `https://graph.microsoft.com/v1.0/sites/m365x55726300.sharepoint.com,f2102bda-0e14-4fc5-bbe1-e65a13cd91a4,6be9dd5c-0640-4465-b955-1528279a0227/lists/7ec9d64f-732f-483b-b1d0-5abb149869f1?$expand=drive,items`

![image](https://user-images.githubusercontent.com/7620955/226636015-58d6a432-907e-43b5-bd11-edf96f538c69.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 111.0.1661.44 (Official build) (64-bit)

**Comment by thewahome** [comment]
@sebastienlevert this is a known issue.

@darrelmiller what's the feedback from the ABNF team on this?

**Comment by michaelmaillot** [comment]
Hi, I confirm the same error when trying to request places:

![image](https://user-images.githubusercontent.com/44271458/227183041-4688621a-c630-4f69-8bc2-c83dbcc1f0c8.png)
