### ISSUE TITLE
Cannot provide admin consent from test tenant

### ISSUE THREAD

**Issue by gingi** [microsoftgraph/microsoft-graph-explorer-v4#2462]
**Describe the bug**
When I try to log in as admin for my test tenant in order to consent to a permission, I get the error:

> Request Id: ac7b159c-e0dd-4eee-8812-8cf8671ee800
> Correlation Id: 385122b5-73e4-4369-9bda-b47d1ca99eae
> Timestamp: 2023-03-21T15:39:14Z
> Message: AADSTS900144: The request body must contain the following parameter: 'client_id'.

**To Reproduce**
1. Press on "Modify permissions"
2. Press on the "Consent" button for a permission that requires admin consent
3. Authenticate with admin account

**Expected behavior**
The consent action to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/50216/226660969-137b7abb-28e4-4f41-bd7a-0c56ea2a2c87.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2 / MacOS Ventura 13.2.1
 - Browser: Edge
 - Version: 111.0.1661.44

**Comment by Onokaev** [comment]
Hey @gingi. Are you still experiencing this issue?

**Comment by gingi** [comment]
@Onokaev: Unfortunately, I am. Just verified that it returns the same error.

**Comment by Onokaev** [comment]
Could you please share a screen recording of your authentication process?

Also, are you using the production version of Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer) or is it your own fork?
