### ISSUE TITLE
MSGRAPH API Create Channel failing...

### ISSUE THREAD

**Issue by atomorandy** [microsoftgraph/microsoft-graph-explorer-v4#2469]
I am useing C# implementation of create channel using
 https://graph.microsoft.com/v1.0/teams/{85fe0928-b51c-4384-83e6-57e22e4b8a85}/channels
The team-id is valid
I also attempt to perform on https://developer.microsoft.com/en-us/graph/graph-explorer
Have verified multiple times that the team-id 85fe0928-b51c-4384-83e6-57e22e4b8a85 is a vailid id using other api calls like get members of a team using the team-id with results.
As mentioned create channel does not seem to be working the response is an 400 error indicating ' teamID needs to be a valid GUID". Error below from https://developer.microsoft.com/en-us/graph/graph-explorer :

"error": {
        "code": "BadRequest",
        "message": "teamId needs to be a valid GUID.",
        "innerError": {
            "date": "2023-03-23T20:21:32",
            "request-id": "97efab33-5ce6-45d3-a3e6-5c378d0e73d4",
            "client-request-id": "159272e8-eae8-deb0-3a8a-6020638624a4"
        }
    }

Can let me know if there is an issue with the API? 

-randy
randy@atomocoffee.com

**Comment by Onokaev** [comment]
Hey @atomorandy. Remove the curly braces from the URL. Instead of this: https://graph.microsoft.com/v1.0/teams/{85fe0928-b51c-4384-83e6-57e22e4b8a85}/channels, use this: https://graph.microsoft.com/v1.0/teams/85fe0928-b51c-4384-83e6-57e22e4b8a85/channels
