### ISSUE TITLE
Rename 'Csharp' code snippets tab to 'C#'

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#2501]
For consistency across our tooling mainly our reference documentation and Graph Explorer, we need to rename the GE CSharp code snippets tab to C#

**In GE**
![image](https://user-images.githubusercontent.com/9458079/230081799-603d9cde-9f8c-481c-83a9-a9919b202c80.png)

**In Docs**
![image](https://user-images.githubusercontent.com/9458079/230081530-c1a58d4c-bf75-4c69-b168-d4ff379583aa.png)

**Comment by Onokaev** [comment]
These two can be handled as a single ticket: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2508
