### ISSUE TITLE
Errors with assigning a group to a intune configuration profile with the Graph API and Graph modules

### ISSUE THREAD

**Issue by JeroenB-Tredion** [microsoftgraph/microsoft-graph-explorer-v4#2511]
**Describe the bug**
Cannot assign group to a configuration profile with both the API calls and the powershell modules.

**To Reproduce**
I used the following:

1.
$body = @{
           id = "9bab0717-xxxx-xxxx-xxxxxxxxxxx"
    target = @{
        "@odata.type"                                                         = "#microsoft.graph.groupAssignmentTarget"
        deviceAndAppManagementAssignmentFilterId      = "null"
        deviceAndAppManagementAssignmentFilterType  = "none"
    }
}

invoke-restmethod -uri https://graph.microsoft.com/beta/deviceManagement/groupPolicyConfigurations/426b8eaa-xxxx-xxxx-xxxx-xxxxxxxxxxx/assignments -method post -header xxx -body ($Body | ConvertTo-Json)

2.
Did the same with Graph Explorer, also got a error.

3. Tried using the Powershell graph module ([Microsoft.Graph.DeviceManagement](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement/?view=graph-powershell-beta):

$params = @{
    Id                                         = "9bab0717-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    Target = @{
        "@odata.type"                              = "#microsoft.graph.groupAssignmentTarget"
        DeviceAndAppManagementAssignmentFilterType = "none"
        DeviceAndAppManagementAssignmentFilterId   = "null"
    }
}
}

Connect-Graph -AccessToken $token.access_token
Select-MgProfile -Name "beta"

New-MgDeviceManagementGroupPolicyConfigurationAssignment -GroupPolicyConfigurationId $DeviceConfID -BodyParameter $params

**Expected behavior**
With all of these options it would add a group to the assignments of a Administrative template policy in Intune.

**Screenshots**
![image](https://user-images.githubusercontent.com/103125142/231154832-13ddf3bf-aa81-4a9d-b4ca-050b83baacb8.png)
![image](https://user-images.githubusercontent.com/103125142/231154955-ee43c875-b884-4656-8267-5fa0b58610a6.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Graph Explorer was in Edge, both the REST method and powershell module were in Visual Studio Code (Powershell 7).
 - Version Edge Version 112.0.1722.34 (Official build) (64-bit) and VS Code is version 1.77.1 (all Graph modules are on the latest version 1.25.0)

**Additional context**

**Comment by Onokaev** [comment]
Adding a comment to trigger the bot to close the issue
