### ISSUE TITLE
Request Body is cleared when you navigate to the other tabs

### ISSUE THREAD

**Issue by musale** [microsoftgraph/microsoft-graph-explorer-v4#2517]
**Describe the bug**
When you set your request body in a POST request, the content is cleared when you navigate to the request headers, modify permissions or access token tabs.

**To Reproduce**
1. Go to https://aka.ms/ge
2. Change the HTTP Method to POST for any URL to query
3. Add a random valid json in the request body tab.
4. Click on the request headers, modify persmissions or access token tabs.
5. Click on the request body tab again.
6. The Request body content is cleared.

**Expected behavior**
The request body should be available for easier editing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version:  112.0.1722.48 

**Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by thewahome** [comment]
@Onokaev should we clear the request body content when we change the query url / Request method?

**Comment by Onokaev** [comment]
I think we should clear it when the query URL changes. I'm not so sure about the request method though. What do you think we should do?

**Comment by thewahome** [comment]
I agree. Only when the url has changed. 
There are methods that could use the same request body. So we could clear when users select the get method since it does not use the request body

**Comment by musale** [comment]
> I think we should clear it when the query URL changes. I'm not so sure about the request method though. What do you think we should do?

Could it be a qualified URL path change? For example doing `/v1/userss` then I change back to `/v1/users` should not trigger a change. But `/v1/users/id` changed to `/v1/users` should trigger a change. What do you think?

**Comment by musale** [comment]
> > 
> 
> This could be a problem. There are cases where a POST and a PATCH targetting a resource like /path and path/{path-id} might require the same request body. me/events is a good example, but I can't find a good sample request :)

You could trigger the body clearing when the request method changes to GET only?

**Comment by Onokaev** [comment]
Hey @musale. I made a quick fix here: https://jolly-sand-0ac78c710-2550.centralus.azurestaticapps.net/
Let me know what you think
