### ISSUE TITLE
Mismatch between the returned results of 'transitiveMemberOf/microsoft.graph.group' and the actual user groups

### ISSUE THREAD

**Issue by yasserMorgan** [microsoftgraph/microsoft-graph-explorer-v4#2518]
While using API "https://graph.microsoft.com/v1.0/me/transitiveMemberOf/microsoft.graph.group?$count=true", it doesn't return all the current groups and some groups are missing.
Case is like the following, If you run this query "https://graph.microsoft.com/v1.0/me/transitiveMemberOf/microsoft.graph.group?$count=true" under some of our system users, for example user principal name "someone@microsoft.com" it doesn't return group with id "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" but at the same time if you run query "https://graph.microsoft.com/v1.0/groups/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/members?$count=true" you can find that this group "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" assigned to the user principal name "someone@microsoft.com"

**To Reproduce**
When run all of the following steps under user 'someone@microsoft.com'
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'Groups'
3. Scroll down to 'all groups I belong to (direct or indirect membership) with count'
4. Click on 'Run Query'
5. Result doesn't contain group with ID 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
6. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
7. Click on 'Groups'
8. Scroll down to 'direct members of a group with count'
9. Click on 'Run Query' for group id 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
10. Results contains the principle user 'someone@microsoft.com'

**Expected behavior**
Group 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' should appear in results of step (4)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]
 - Version [Version 112.0.1722.39 (Official build) (64-bit)]

**Comment by Onokaev** [comment]
Hey @yasserMorgan. Does this happen immediately after assigning a member to a group or is it happening for all API calls?

**Comment by yasserMorgan** [comment]
@Onokaev , I waited for more than 48 hours after assigning a member to group and the issue still exists. It's happening for all the API calls.

**Comment by Onokaev** [comment]
I tested this and got the same issue as you. We can't however solve this issue on Graph Explorer or through a tenant config. It appears to be an issue with the endpoint. You can post this question on this forum: https://learn.microsoft.com/en-us/answers/questions/ask/ and the right team will attend to it. Tag `Microsoft Graph Groups API`. 
If I post it for you, you wont be able to get updates when the relevant team responds

**Comment by yasserMorgan** [comment]
Hi @Onokaev , Sure your help is appreciated [( https://learn.microsoft.com/en-us/answers/questions/1275760/bug-mismatch-between-the-returned-results-of-trans )](https://learn.microsoft.com/en-us/answers/questions/1275760/bug-mismatch-between-the-returned-results-of-trans)

**Comment by yasserMorgan** [comment]
Hi @Onokaev , Yes I was trying the recommended solution in the response and It solved the problem. :)
