### ISSUE TITLE
Add `scopeType=DelegatedWork` query parameter on permissions  endpoint

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/microsoft-graph-explorer-v4#2527]
We are updating the DevX API permissions endpoint to allow fetching all permissions scope types if none is specified. the current implementation defaults to `DelegatedWork`.  

Graph Explorer will be required to explicitly specify the scope type when fetching all graph permissions or for a single request URL.

**Comment by Onokaev** [comment]
We are already passing the correct scopeType query parameter depending on the signed-in account type
