### ISSUE TITLE
Get user by email from identities ( sign-in mail )

### ISSUE THREAD

**Issue by sha3m** [microsoftgraph/microsoft-graph-explorer-v4#2567]
**Describe the bug**

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Enter "https://graph.microsoft.com/v1.0/users?$filter=identities/any(x:x/issuerAssignedId eq 'admin@M365x214355.onmicrosoft.com' and x/issuer ne '')&$count=true" as a query. Set header "ConsistencyLevel: eventual"
3. Click "Run Query"
4. See error in response window

**Expected behavior**
A response with the list of users, who have that particular email in their identities is expected in the response. Instead:
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Unrecognized query argument specified: 'filter'.",
        "innerError": {
            "date": "2023-05-11T12:07:48",
            "request-id": "b2be8fc5-a2ba-44f6-85f3-e0763b95f60f",
            "client-request-id": "b2be8fc5-a2ba-44f6-85f3-e0763b95f60f"
        }
    }
}

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Edge
 - Version 112.0.1722.68 (Official build) (64-bit)

**Additional context**
"&$count=true" and header "ConsistencyLevel: eventual" are necessary for "ne" (not equal), being an advanced query option. If no x/issuer is set, with a plain query ( no additional headers and no $count set ) the error message is: "Issuer is not set in the query. Issuer issuer, IssuerUserId: issuerUserId"

**Comment by ElinorW** [comment]
Hi @sha3m,
I think the reason the request is failing is because you aren't setting an issuer. For more information on how to set the issuer refer to this: https://learn.microsoft.com/en-us/graph/api/resources/objectidentity?view=graph-rest-1.0
Once you have the issuer, you will no longer need the 'ConsistencyLevel:eventual' header and the query should return a 200.
