### ISSUE TITLE
Often Graph API to get Outlook calendars and events fail with "Unknown Error"

### ISSUE THREAD

**Issue by itague** [microsoftgraph/microsoft-graph-explorer-v4#2568]
**Describe the bug**
I'm using following Graph API calls in a Java Backend:

- https://graph.microsoft.com/v1.0/me/events
- https://graph.microsoft.com/v1.0/me/calendars

Often API returns following error:

```
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2023-05-12T07:50:26",
            "request-id": "3a497a63-9a12-4492-8d7a-8548cc1c8b6c",
            "client-request-id": "cc09d87e-1b67-4631-f6dc-b7c0ca29d7d8"
        }
    }
}

```

Sometime same APIs ran without any issue.

I ran APIs also with MS Graph Explorer and I got same issues.
I tried with my AD credentials guerriero.italo@grimaldi.napoli.it where is configured a Exchange onprem mailbox with Exchange hybrid connector.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Run query with above APIs

**Expected behavior**
No unknow errors.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 113.0.1774.35 

**Additional context**
I noticed that a collegue with an Exchange Online mailbox on same tenant got always successfull results.

**Comment by ElinorW** [comment]
Hey @itague, 
This may be a problem with the Outlook API.
Please post this on the Graph Q&A forum where the appropriate team will be able to help.
