### ISSUE TITLE
Unable to manage conditional access using Graph Explorer 

### ISSUE THREAD

**Issue by hhazeley** [microsoftgraph/microsoft-graph-explorer-v4#2580]
Unable to manage conditional access using Graph Explorer on one of my tenants. Not sure if there is something i need to do on this specific tenant to resolve issue.

Get call to https://graph.microsoft.com/beta/policies/conditionalAccessPolicies failing.  User has consented and is a Global Admin in tenant. I was able to manage another delegated admin task using Graph Explorer.

![Image](https://i.imgur.com/gmIsVqm.png)

````
{
    "error": {
        "code": "AccessDenied",
        "message": "You cannot perform the requested operation, required scopes are missing in the token.",
        "innerError": {
            "date": "2023-05-17T18:21:53",
            "request-id": "88820748-c0ba-48f2-9313-a16c43e31e93",
            "client-request-id": "ec5c6326-f075-3bfe-55e7-eb9ea6c0643d"
        }
    }
}
````
Scope in token

![image](https://i.imgur.com/Xr0pmXg.png)

Token available upon request if needed.

**Comment by Onokaev** [comment]
Hey @hhazeley. Do you get a new popup to reauthenticate for other tenants?

**Comment by Onokaev** [comment]
Could you check if there are any claims stored in session storage when you run the query?
Also, check if there are failed query runs on the History tab? When an endpoint throws a claims challenge, that query run fails then we re-try it once the claims challenge is satisfied. 

It's also possible that the claims challenge is not being thrown from the error message you are getting, meaning you might be having a configuration issue on your tenant. If a claims challenge is not added, you should be getting this error:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/45680252/89efb0c0-c44d-42cb-92d4-c7796a8980dd)


Last thing you can check is whether the policy  in your tenant has a 'require MFA' as part of its config

**Comment by hhazeley** [comment]
I cleared all the browser storage and tried again, Same error.  MFA not enabled for this user.  Here is token from date, hope it helps. 

https://gist.githubusercontent.com/hhazeley/828a8cbfcd3f2bb4e014f8cb5e8757ad/raw/a38b45c4dd1180f1f4cafd7fcf9725916491986e/token

**Comment by Onokaev** [comment]
Hey @hhazeley. I looked at the token and also tried a couple of different configs and I was still getting re-authenticated. 
Could you try adding 'Require MFA' as a policy option for this specific user?

**Comment by hhazeley** [comment]
I added MFA, reconsented permission to graph and got same issue.

Latest error:

{
    "error": {
        "code": "AccessDenied",
        "message": "You cannot perform the requested operation, required scopes are missing in the token.",
        "innerError": {
            "date": "2023-06-07T06:33:37",
            "request-id": "76b2e237-c1ed-41c9-b22f-7afd16e7257c",
            "client-request-id": "702a310d-1e3d-e73c-2f77-5dca3cf06b6a"
        }
    }
}

Latest Token:
[https://gist.githubusercontent.com/hhazeley/84ee40e95ac595f8c98788fd9f4dff98/raw/8e3957e6ea8d2f40576b0b026136c56fe6c68caa/token06062023](https://gist.githubusercontent.com/hhazeley/84ee40e95ac595f8c98788fd9f4dff98/raw/8e3957e6ea8d2f40576b0b026136c56fe6c68caa/token06062023)

**Comment by Onokaev** [comment]
Hey @hhazeley. After a couple of tests, it appears you are missing Policy.Read.All permission.
Click on your profile on the top right part of the page, then click on Consent permissions. Search for Policy.Read.All on the searchbox.
This should fix your issue.

You can compare your token with this one:
eyJ0eXAiOiJKV1QiLCJub25jZSI6ImxVUjZucUpELU0zWjA1c1k2cmw4dkFoOHpNOVZ0MzlRZTl0SFR4cTZLTjAiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kZWZjNDUwMy0xZGQwLTQzZDMtYWViYy0xMGRhN2Q5ZDQ4MjIvIiwiaWF0IjoxNjg2ODEzNjQ0LCJuYmYiOjE2ODY4MTM2NDQsImV4cCI6MTY4NjkwMDM0NCwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsiYzIwIl0sImFpbyI6IkFUUUF5LzhUQUFBQUJ4WmpYS0VPSEQ2Z2xkcFlLQ0FjZFhMS0N1aSt1OHhhckc5Y2tGbllDUE9QZC9MYjBWbTBNOExCTTVJSk1BUE8iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIEV4cGxvcmVyIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyYTAxOjExMDo4MDEyOjEwMTA6MzliNTo3YmI2Ojk1ZDQ6YTUzZCIsIm5hbWUiOiJFdmFucyBBYm9nZSIsIm9pZCI6IjlmNzhlZDYzLWVhOWItNDhmMS1hNzc4LTQ0ZTJhNzZkYzIwYSIsInBsYXRmIjoiNSIsInB1aWQiOiIxMDAzMjAwMjdBMjU0RTlGIiwicmgiOiIwLkFYd0FBMFg4M3RBZDAwT3V2QkRhZloxSUlnTUFBQUFBQUFBQXdBQUFBQUFBQUFCOEFHdy4iLCJzY3AiOiJEZWxlZ2F0ZWRQZXJtaXNzaW9uR3JhbnQuUmVhZFdyaXRlLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgb3BlbmlkIFBvbGljeS5SZWFkV3JpdGUuQ29uZGl0aW9uYWxBY2Nlc3MgUG9saWN5LlJlYWRXcml0ZS5Dcm9zc1RlbmFudEFjY2VzcyBwcm9maWxlIFVzZXIuUmVhZCBlbWFpbCBQb2xpY3kuUmVhZC5BbGwiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiJJV3RYdDMtN0NPdUpWeVY5a015RlU0ZnphWW9LeURrNlU0Mm93dmd2NnowIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6Ik5BIiwidGlkIjoiZGVmYzQ1MDMtMWRkMC00M2QzLWFlYmMtMTBkYTdkOWQ0ODIyIiwidW5pcXVlX25hbWUiOiJldmFuc0BsZ3J5YnJwLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImV2YW5zQGxncnlicnAub25taWNyb3NvZnQuY29tIiwidXRpIjoiZDZuMWhaNFhzVUdCZWo3RzhUWU5BQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiODQyNGM2ZjAtYTE4OS00OTllLWJiZDAtMjZjMTc1M2M5NmQ0IiwiNThhMTNlYTMtYzYzMi00NmFlLTllZTAtOWMwZDQzY2Q3ZjNkIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19jYyI6WyJDUDEiXSwieG1zX3NzbSI6IjEiLCJ4bXNfc3QiOnsic3ViIjoiczZOclI2U2dkanVKZlhKSW9HZ3Q1RWdJLUxOLUphRmF0U2htUlV1R0Y3NCJ9LCJ4bXNfdGNkdCI6MTYyMDE2Njc1NH0.LLaBC6wUlFSUuTnd7btgUuz8CYLn-fab-IAr1EIR61a9LQQPiqtRaiLqGGIAFnB8uvR2SMzthk3naELwFjOsFYtjcxPiPbaoidC4gX6Tsl6vSUmm4fWYvRZxVr36rWuINpQ1TnUtekJ-9kTaQqfynxUT5z51-yvp4gEteRrYm1h1UIHk_Ty2LgA3R_RxT2Hk_yC8GSc6suHiakH0mXEyp4MaOuvzu0Se52-XwJdqQeUI0QoycfO9iuhdFiEH9S17fmnDysBqZj60Ozhj5aSgXIU3McggCX1rPnCc6RnYdRkXP5j9v6BtmBLEP2WT26sZvc7JN9B8Kn6ZbZQQ3Tggmw

**Comment by hhazeley** [comment]
Thanks.  Never realized till today that Policy.ReadWrite.ConditionalAccess doesn't read conditional access polices. :( 

https://learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&tabs=http
