### ISSUE TITLE
Preview URL broken 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2587]
The Graph Explorer preview URL is broken. Checked with the team and we don't really user it. Do we want to keep it? Is there a use case for it? @adhiambovivian @gavinbarron @ddyett

**Comment by adhiambovivian** [comment]
@RabebOthmani  the preview link was previously used to test and preview the v4 migration of Graph Explorer from angular tech stack to what we have today. Today, we no longer use the preview env, except in scenarios where we are shipping massive changes.
