### ISSUE TITLE
Graph Explorer Stuck on "Loading..."

### ISSUE THREAD

**Issue by MAbdElRaouf** [microsoftgraph/microsoft-graph-explorer-v4#2628]
**Describe the bug**
https://developer.microsoft.com/en-us/graph/graph-explorer/
Whenever I press "Run query" it shows "Loading..." but never loads the resources for request or response, even when I get OK - 200 responses. I tried on Edge and Chrome on 2 different computers same issue. This is my first attempt to use the Graph Explorer.

**Expected behavior**
Shows request and response resources.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/60540684/acffc049-fb09-415e-9b6a-1fa859f7eeac)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/60540684/634f1b62-a813-49d5-b7f9-e687b5742bb0)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [Chrome, Edge]
 - Version [Version 114.0.5735, Version 114.0.1823.51]

**Additional context**
I use the Graph Explorer while logged in with an organization account.

**Comment by Onokaev** [comment]
Hey @MAbdElRaouf. It seems you have some filters blocking Monaco editor downloads.
The same issue was reported here: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2398
Let me know if that solution works for you

**Comment by MAbdElRaouf** [comment]
Hi @Onokaev, you are right turns out https://cdn.jsdelivr.net was recently [censored in Egypt](https://stackoverflow.com/questions/76456950/cdn-jsdelivr-net-not-loading-in-my-country), along with other websites.

**Comment by adhiambovivian** [comment]
@MAbdElRaouf  thank you for reporting this issue - we are reviewing possible solutions internally and will revert as soon as possible.
