### ISSUE TITLE
Investigate failing telemetry pipelines

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#2633]
In the last few months, we've experienced intermittent failure in telemetry pipelines which has resulted in missing data for some dashboards. 

Action: 

- RCA for telemetry pipelines failures
- Alerting

**Comment by RabebOthmani** [comment]
@adhiambovivian can we please prioritize this work for the July milestone. This is very critical

**Comment by RabebOthmani** [comment]
As the GE team, we want to get notified when the telemetry pipelines don't work as expected
So we have enough information to take action 

Acceptance criteria: 
* We want to receive email notifications (All GE team to receive the email) 
* Notifications when the pipelines don't run at all or fail
