### ISSUE TITLE
RoleManagementPolicy.Read.AzureADGroup permission isn't listed in the Permissions blade

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-explorer-v4#2635]
**Describe the bug**
In the Permissions blade (after clicking the "Consenting to permissions" link), searching for the RoleManagementPolicy.Read.AzureADGroup permission doesn't return a result.

**To Reproduce**
1. Click the profile image on the top-right.
2. Click on "Consenting to permissions" 
3. Search for RoleManagementPolicy.Read.AzureADGroup

**Expected behavior**
It was expected to find the RoleManagementPolicy.Read.AzureADGroup permission.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/103036544/cb6bc1bc-c300-4d6b-a60d-18a4fc8526f5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Version 114.0.1823.43 (Official build) (64-bit)

**Additional context**
This permission is documented here: https://learn.microsoft.com/en-us/graph/permissions-reference#role-management-permissions
For example, the following endpoint uses this permission: https://learn.microsoft.com/en-us/graph/api/unifiedrolemanagementpolicy-get?view=graph-rest-beta&tabs=http

**Comment by ElinorW** [comment]
Hi @manuel-falcao-magalhaes, 
Yes, the permission appears to be missing. I'll investigate this

**Comment by manuel-falcao-magalhaes** [comment]
Thank you, I can confirm that the permission is now available to be consented. Closing issue.
