### ISSUE TITLE
Encourage callers to use $select and inform callers when there's default properties in the response

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-explorer-v4#2636]
**Is your feature request related to a problem? Please describe.**
Today API consumers regularly call API endpoints without using $select. This impacts performance of client apps (and impacts service COGS too).  Additionally, APIs endpoints that return a default set of properties in a response don't inform callers that there are more properties available, and that they'll need to use $select - which is often a support call driver.  

The API Gateway Service team is trying to address these related issues by including a new "tips" instance annotation in the response to alert developers and encourage them to use $select, if $select is not being used.  This annotation is also only added if the client application provides an opt-in "ms-graph-dev-mode" Prefer request header

**Describe the solution you'd like**
As one the the premium tools for API discoverability and testing, we'd like Graph Explorer to send the `prefer: ms-graph-dev-mode` request header, so that the tips instance annotation shows up.

**Describe alternatives you've considered**
NA - although we vetted a range of ideas with Identity Developer Advisors.

**Additional context**
[Feature spec](https://microsoft-my.sharepoint-df.com/:w:/p/dkershaw/EU1SpMyyyeBJn-eJ00J1_8wBO_HvzOFHt3f6QRksN8fqgg?e=C8oZSD)

**Comment by dkershaw10** [comment]
This feature is now fully deployed, and available for anyone to use.  Please note that for workloads that adopt a passthrough strategy, AGS will not provide the @tips annotation - so this is expected when calling APIs like /messages, /events or personal contacts.

**Comment by ElinorW** [comment]
Hey @dkershaw10 ,
I have created a pull request with the fix, feel free to test this out.
Question: I noticed it only works for the instances where a user is signed in, is this by design?

**Comment by dkershaw10** [comment]
Nice!!!  Not sure I'll be able to have time to test it.

_Question: I noticed it only works for the instances where a user is signed in, is this by design?_
Not sure how your experience works for the "non signed-in" case.  That shouldn't really have any bearing on the annotation.  Is the header still being sent for your non-signed-in case?

**Comment by ElinorW** [comment]
> Nice!!! Not sure I'll be able to have time to test it.
> 
> _Question: I noticed it only works for the instances where a user is signed in, is this by design?_ Not sure how your experience works for the "non signed-in" case. That shouldn't really have any bearing on the annotation. Is the header still being sent for your non-signed-in case?

In the non signed-in case, the tips annotation doesn't show up.
Yeah I'm sending the header but it doesn't have an effect on the responses
