### ISSUE TITLE
Bundle Monaco with GE

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#2638]
**Is your feature request related to a problem? Please describe.**
Monaco is an integral part of Graph Explorer. We should consider bundling Monaco for the following reasons:
1. We find that CDNs can be blocked sovereign entities. https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2628. This makes Graph Explorer unusable from affected regions.
2. More broadly speaking, we don't take a 3rd party CDN dependency - less risk. 
3. Potential to make load times smaller in case monaco functions are organized in a way that supports treeshaking.

**Describe the solution you'd like**
Bundle Monaco with GE bundle.

**Describe alternatives you've considered**
If for some reason we can't get this work prioritized, we must use [Subresource Integrity](https://www.w3.org/TR/SRI/). We should also have a fallback CDN resource in case the resource we reference is not available. This may have protected us in the case of jsdelivr being blocked in Egypt.

**Comment by ElinorW** [comment]
Related to #2628 and #2640
