### ISSUE TITLE
Request Body in Graph Explorer shows as "Loading.."

### ISSUE THREAD

**Issue by aendrawos** [microsoftgraph/microsoft-graph-explorer-v4#2640]
**Describe the bug**
For some reason I always have the Request Body showing as "Loading..." which is not letting me put anything in the request Body

**To Reproduce**
1- Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2- Login in with your account
3- You should see the Request Body section is showing as "Loading..."

**Expected behavior**
Request Body section should let me write/insert a body to be used with my various requests that needs it (like POST request)

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/91459443/ad33a2d9-656a-454f-8d8d-aef4fba16cc4)

**Desktop (please complete the following information):**
 - OS:  Windows (tried on Windows 11 and Windows server 2019)
 - Browser: tried with different browsers (Edge, Chrome and Firefox)

**Comment by ElinorW** [comment]
Hi @aendrawos 
This is similar to #2628. 
Must be an issue with the CDN being blocked. We are working on a fix.

**Comment by aendrawos** [comment]
Hi Elinor,

Are their any update on the issue, as I get many customer cases which require troubleshooting using Graph calls and it is a bit frustrating that I am not able to run the graph calls to test customer scenarios.

Is there any other UI tool that you can suggest to help run Graph calls while this issue is fixed?

Regards,
Armia Endrawos
Support Escalation Engineer
Modern Workplace


From: Armia Endrawos
Sent: Monday, July 3, 2023 1:07 PM
To: microsoftgraph/microsoft-graph-explorer-v4 ***@***.***>; microsoftgraph/microsoft-graph-explorer-v4 ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoftgraph/microsoft-graph-explorer-v4] Request Body in Graph Explorer shows as "Loading.." (Issue #2640)

Hello Elinor,

Is there any update on the issue?

Regards,
Armia Endrawos
Support Escalation Engineer
Modern Workplace

**Comment by ElinorW** [comment]
Hi @aendrawos, 

I am still working on the fix. 
It seems that the cdn was recently blocked in Egypt. 

In the meantime, I would suggest using Postman to test Graph API calls

**Comment by ElinorW** [comment]
Hey @aendrawos, 

This is resolved. Please confirm this on your end.

**Comment by aendrawos** [comment]
Hi Elinor,

Thank you for the heads up.
The issue is now solved, thanks a lot for your help.

Regards,
Armia Endrawos
Support Escalation Engineer
Modern Workplace
