### ISSUE TITLE
Resources tree consistency 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2641]
Currently on the resources tree, the nodes look like this 
<img width="188" alt="tree nodes" src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/5781590/2696a1df-c925-48e6-9d90-7f2c228152cc">

it should be 
<img width="117" alt="tree vs " src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/5781590/b4faed86-2f22-4f7a-b007-861c6abfec5b">

Methods (GET, POST, etc) shouldn't have the name of the resource
Children nodes should be places before methods
Children nodes should have the same structure as parent node ie all the rules above

**Comment by RabebOthmani** [comment]
@Onokaev can we please change the order between the method nodes and other nodes? The opposite to my previous request as we had new insights and changed the order on VS code. Apologies, this one is on me.

**Comment by Onokaev** [comment]
Hey @RabebOthmani. No worries. Let me make the changes
