### ISSUE TITLE
employeeExperience/learningCourseActivities is  not on the resources list and autocomplete

### ISSUE THREAD

**Issue by Onokaev** [microsoftgraph/microsoft-graph-explorer-v4#2642]
**Describe the bug**
learningCourseActivities segment is not appearing on the resource tree

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Click on Resources tab
3. Search for learningCourseActivities
4. Notice that the child segment 'learningCourseActivities' does not appear under employeeExperience

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ElinorW** [comment]
Hey @Onokaev, 
This might have been an API issue...
It has it's own node 
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/9e2dc060-67c8-4e70-89ed-3c31ce234e54)
and it's also present under /me node
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/b33542fc-2aed-4731-a9d5-46b57f54ccac)
 and also under /users node
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/d797911a-71ec-4d6e-86b8-48a4692138dc)

**Comment by Onokaev** [comment]
Thanks @ElinorW. 
The workload team also raised other issues about the new paths that should be fixed on devx API. Let me close this one as the issue it raised was resolved.
