### ISSUE TITLE
Create Event fails with 500 response when extension missing name

### ISSUE THREAD

**Issue by Lawton** [microsoftgraph/microsoft-graph-explorer-v4#2665]
**Describe the bug**
A get a 500 error when creating an event with an open extension that is missing `extensionName` field

**To Reproduce**
1. Go to Graph Explorer
2. Click on `Schedule a Meeting` post request
3. Update to include an open extension that is missing an `extensionName`

**Expected behavior**
Respond with 400 indicating that the extension is missing `extensionName` field

**Screenshots**
<img width="1319" alt="Screenshot 2023-07-05 at 11 47 02 AM" src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/2728335/83405ae9-02da-4ff2-bcb6-90a7c9709600">

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - Browser: Firefox
 - Version: 114

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Onokaev** [comment]
Remember to tag `Microsoft Graph Calendar API`
