### ISSUE TITLE
Capture code snippets copying (ctr+c) on the telemetry dashboard

### ISSUE THREAD

**Issue by Onokaev** [microsoftgraph/microsoft-graph-explorer-v4#2668]
Add visualizations for `Cntrl + C` action on the `Code snippets` tab

**Comment by RabebOthmani** [comment]
@Onokaev could you please confirm if we can close this issue.

**Comment by RabebOthmani** [comment]
Rabeb to check with Dani on the copy button design

**Comment by RabebOthmani** [comment]
As the GE team, we want to capture when users are copying using ctr+c
And we want to access that information on the dashboard
So we have an understanding on how many people are using snippets in their own apps

Acceptance criteria:
* ctr+c should be captured into copying telemetry 
* We should have a visualization of the above telemetry on the dashboard

**Comment by petrhollayms** [comment]
The events are captured in the code already, but the second part is open as it could be related to the pipeline work. To be continued.

**Comment by ElinorW** [comment]
This was added and is included as part of the copy button visualization.
