### ISSUE TITLE
[BUG] Incompatible dependencies

### ISSUE THREAD

**Issue by gavinbarron** [microsoftgraph/microsoft-graph-explorer-v4#2670]
**Describe the bug**
The project has dependencies with conflicting peer dependencies.

**To Reproduce**

1. Using node v16.20.0 and npm 8.19.4
1. Run `npm i` 
1. package-lock.json is updated to version 2 format
1. Run `npm i`
1. Observe that npm fails to complete the install

this also occurs in CI builds where the v2 package-lock.json is committed
See these CI runs:
- https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=119352&view=logs&j=cb4db6dd-e658-55b7-b337-8761517bc1a3&t=5f69cb92-a4fc-59e7-06e5-11f91b5ae56f
-  https://github.com/microsoftgraph/microsoft-graph-explorer-v4/actions/runs/5469927279/jobs/9959414580

**Expected behavior**
npm i works without error when run multiple times.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser n/a
 - node: 16.20.0
 - npm: 8.19.4

**Comment by ElinorW** [comment]
Hi @gavinbarron,
This is a known issue. 
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/b0ca61cd-5d1c-4b54-9e84-5150e1bf8d6e)
The **augloop/types-core** is a peer dependency of the **@ms-ofb/officebrowserfeedbacknpm** which is the package we use to display the NPS and CES feedback forms. 
This package resides in Azure Artifacts and our package-lock by default searches for packages on npm. 
As a result, we store the 2 packages locally, but unfortunately, running `npm i` resets the augloop package to the npm version, which doesn't exist. 
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/a2e7d079-7a80-47da-b847-bf931865a8ac)
As a fix, we have to manually paste the location of the file. As shown on the left side of the image is what will fix the issue. 
We have no other known workaround at the moment.

**Comment by gavinbarron** [comment]
Thanks for the additional context here @ElinorW 
IMO we should either document this issue in a way that is easy to discover for developers or add a postinstall script to automate this fix.

**Comment by gavinbarron** [comment]
@ElinorW, what versions of node and npm are you using? 
The core problem, at least that I'm seeing is not with `augtypes`, but with `enzyme-adapter-react-16` the second run of npm install.

**Comment by ElinorW** [comment]
I am using node 14.20.0
and npm v6.14.17...

Yeah we definitely need to update our node and npm packages. I'll create a new issue 
to track this
