### ISSUE TITLE
validate graph queries before making calls to devx API

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#2688]
GE to validate user queries before making API calls to DevX API for both permissions and code snippets and display correct error message to the user.

**Today:**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/9458079/dffc9584-8b3c-4b51-bac6-d76532212f18)

**Expected:**
GE to display error message on the permissions tab & code snippets that the query is incorrect instead of 'snippets not available' & 'check permissions panel'. Snippets not available & check permissions panel message should only be used in scenarios where a user has run a valid query, but we do not have support for snippets or permissions..

**Comment by RabebOthmani** [comment]
@darrelmiller we had a debate this morning with Caleb and the team around the URLs validation and the metadata challenges. I'd love your opinion as our trusted architect :)
