### ISSUE TITLE
Internal server error without error message except "generalException"

### ISSUE THREAD

**Issue by equipment-studios** [microsoftgraph/microsoft-graph-explorer-v4#2692]
**Describe the bug**
White trying to update the SharePoint admin center settings via Graph, there is an _error 500 / internal server error_ without further description. The error first time appeared while trying pushing the values via PowerShell module (MgGraph). 

**To Reproduce**
Either: pushing a JSON configuration throught graph exporer to SharePoint Online

```

Connect-MgGraph -Scopes SharePointTenantSettings.ReadWrite.All
Welcome To Microsoft Graph!

PS C:\WINDOWS\system32> $Uri = "https://graph.microsoft.com/v1.0/admin/sharepoint/settings"
>> Invoke-MgGraphRequest -Uri $Uri

$settings = @{

    isUnmanagedSyncAppForTenantRestricted = $false
    isMacSyncAppEnabled = $true
    isRequireAcceptingUserToMatchInvitedUserEnabled = $true
    isSharePointMobileNotificationEnabled = $true
    #"@odata.context" = "https://graph.microsoft.com/v1.0/$metadata#admin/sharepoint/settings/$entity"

    personalSiteDefaultStorageLimitInMB = 25600
    isCommentingOnSitePagesEnabled = $true
    isSiteCreationEnabled = $false
    excludedFileExtensionsForSyncApp = @(
        '*.exe'
        '*.iso'
        '*.mp3'
        '*.mp4'
    )
    isSyncButtonHiddenOnPersonalSite = $false
    sharingCapability = "externalUserSharingOnly"
    sharingAllowedDomainList = @()
    isResharingByExternalUsersEnabled = $true
    siteCreationDefaultManagedPath = "/teams/"
    deletedUserPersonalSiteRetentionPeriodInDays = 365
    allowedDomainGuidsForSyncApp = @()
    isSiteCreationUIEnabled = $false
    tenantDefaultTimezone = "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"
    isLoopEnabled = $false

}

$json = $settings | ConvertTo-Json

Invoke-MgGraphRequest -Uri $uri -Method PATCH -Body $json -ContentType "application/json"
```

or: via PowerShell code instead of JSON

```

Connect-MgGraph -Scopes SharePointTenantSettings.ReadWrite.All
Welcome To Microsoft Graph!
PS C:\WINDOWS\system32> $Uri = "https://graph.microsoft.com/v1.0/admin/sharepoint/settings"
>> Invoke-MgGraphRequest -Uri $Uri

$settings = @{

    isUnmanagedSyncAppForTenantRestricted = $false
    isMacSyncAppEnabled = $true
    isRequireAcceptingUserToMatchInvitedUserEnabled = $true
    isSharePointMobileNotificationEnabled = $true
    #"@odata.context" = "https://graph.microsoft.com/v1.0/$metadata#admin/sharepoint/settings/$entity"

    personalSiteDefaultStorageLimitInMB = 25600
    isCommentingOnSitePagesEnabled = $true
    isSiteCreationEnabled = $false
    excludedFileExtensionsForSyncApp = @(
        '*.exe'
        '*.iso'
        '*.mp3'
        '*.mp4'
    )
    isSyncButtonHiddenOnPersonalSite = $false
    sharingCapability = "externalUserSharingOnly"
    sharingAllowedDomainList = @()
    isResharingByExternalUsersEnabled = $true
    siteCreationDefaultManagedPath = "/teams/"
    deletedUserPersonalSiteRetentionPeriodInDays = 365
    allowedDomainGuidsForSyncApp = @()
    isSiteCreationUIEnabled = $false
    tenantDefaultTimezone = "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"
    isLoopEnabled = $false

}

Invoke-MgGraphRequest -Uri $uri -Method PATCH -Body $settings

```

or even via Graph Explorer as pure JSON:

`

PATCH v1.0 https://graph.microsoft.com/v1.0/admin/sharepoint/settings

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#admin/sharepoint/settings/$entity",
    "allowedDomainGuidsForSyncApp": [],
    "availableManagedPathsForSiteCreation": [
        "/sites/",
        "/teams/"
    ],
    "deletedUserPersonalSiteRetentionPeriodInDays": 365,
    "excludedFileExtensionsForSyncApp": [
        "*.exe",
        "*.mp4",
        "*.iso"
    ],
    "imageTaggingOption": "basic",
    "isCommentingOnSitePagesEnabled": true,
    "isFileActivityNotificationEnabled": true,
    "isLegacyAuthProtocolsEnabled": true,
    "isLoopEnabled": false,
    "isMacSyncAppEnabled": true,
    "isResharingByExternalUsersEnabled": true,
    "isSharePointMobileNotificationEnabled": true,
    "isSharePointNewsfeedEnabled": false,
    "isSiteCreationEnabled": false,
    "isSiteCreationUIEnabled": false,
    "isSitePagesCreationEnabled": false,
    "isSitesStorageLimitAutomatic": true,
    "isSyncButtonHiddenOnPersonalSite": false,
    "isUnmanagedSyncAppForTenantRestricted": false,
    "personalSiteDefaultStorageLimitInMB": 32768,
    "isRequireAcceptingUserToMatchInvitedUserEnabled": true,
    "sharingAllowedDomainList": [],
    "sharingBlockedDomainList": [],
    "sharingCapability": "externalUserSharingOnly",
    "sharingDomainRestrictionMode": "none",
    "siteCreationDefaultManagedPath": "/sites/",
    "siteCreationDefaultStorageLimitInMB": 26214400,
    "tenantDefaultTimezone": "(UTC) Monrovia, Reykjavik",
    "idleSessionSignOut": {
        "isEnabled": false,
        "warnAfterInSeconds": 0,
        "signOutAfterInSeconds": 0
    }
}
`

**Expected behavior**
Changing settings in SharePoint admin center as expected.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/139269878/38ff1a5f-100c-4176-b6bc-b45c779434dc)
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/139269878/aca16fe0-6f0b-4fe7-b1c3-4bca8d55d79d)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 build 22621.1992
 - Browser Edge Browser 115.0.1901.183 (Official build) (64-bit) & Chrome 114.0.5735.248 (Offizieller Build) (64-Bit)
 - Version (see above)

**Comment by Onokaev** [comment]
Hey @equipment-studios. Apologies for this experience. We can't help you resolve this on Graph Explorer. Repost the question on the Q&A site and tag `Sharepoint`. The appropriate team will respond with concrete answers
