### ISSUE TITLE
Sample request contents do not load in graph explorer

### ISSUE THREAD

**Issue by ashaabansoliman** [microsoftgraph/microsoft-graph-explorer-v4#2699]
**Describe the bug**
When I click on any of the sample requests , it contents do not load

**To Reproduce**
1. Open Graph API explorer https://developer.microsoft.com/en-us/graph/graph-explorer
2. Sign in with your @microsoft account
3. search for the create group API and click on it 
4. You will get this eternal loading indicator
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/109526961/62b9868f-725c-485d-900b-ce39c119a6bf)

**Expected behavior**
See a sample of the request contents

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise 22H2
 - Browser Chrome Version 115.0.5790.110 (Official Build) (64-bit)

**Comment by Onokaev** [comment]
Hey @ashaabansoliman. Do you still experience this issue when you reload the page?
I can't reproduce it on my end:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/45680252/eeccbab6-d526-41f9-8f2d-07e8d4441628)

**Comment by Onokaev** [comment]
Hey @ashaabansoliman. Try again. Everything should be okay now.
