### ISSUE TITLE
Can't revoke Mail.Read permission on my personal account in graph explorer

### ISSUE THREAD

**Issue by LaughingJohn** [microsoftgraph/microsoft-graph-explorer-v4#2700]
I cannot revoke permissions to graph Explorer

I wanted to test the Graph API so I decided to use my personal account. I was able to do this and gave graph explorer read permission to my emails.

I've now finished testing and I wanted to revoke the permission I granted, but there doesn't seem to be a way of doing this. Can you advise? 

It seems to suggest that I need Directory.Read.All and DelegatedPermissionGrant.ReadWrite.All. Firstly I'm surprised I need this, given presumably I was able to give permission without it. Secondly it seems a bit crazy that I have to give myself even more permissions to revoke a fairly specific permission. And lastly when I tried to give myself those permissions it didn't seem to do anything and I still can't revoke the Mail.Read permission I gave myself.

Any help/suggestions appreciated. I feel I have left my account in a potentially vulnerable position and can't get it back to where it was before.

Thanks.

**Comment by ElinorW** [comment]
Hi @LaughingJohn,
Unfortunately revoking permissions isn't currently supported for personal accounts. 
If you would like to test Graph API's I would suggest using the sandbox which provides you with sample users and data.
Here is a link: https://developer.microsoft.com/en-us/microsoft-365/dev-program

**Comment by MIchaelMainer** [comment]
You can revoke permissions to Graph Explorer. Go to https://go.microsoft.com/fwlink/p/?LinkId=829203 which takes you to https://account.live.com/consent/Manage, select the Graph Explorer app, and revoke consent. It will revoke all consent.

**Comment by LaughingJohn** [comment]
Thanks @MIchaelMainer, that worked perfectly!

**Comment by agobeaux** [comment]
Reopening as I am having the same issue. Not being able to easily remove the permissions given to Microsoft Graph is a big problem. I followed the links given by @MichaelMainer and I erased the permissions of Microsoft Graph Explorer. However, I was still able to do GET requests to get my emails from Microsoft Graph Explorer (using my web browser). How is this even possible? I want to make sure Microsoft Graph Explorer does not have any access to my emails anymore.
Please help.

**Comment by flawesomesoft** [comment]
> You can revoke permissions to Graph Explorer. Go to https://go.microsoft.com/fwlink/p/?LinkId=829203 which takes you to https://account.live.com/consent/Manage, select the Graph Explorer app, and revoke consent. It will revoke all consent.

This seems to be the only way when working with a personal account (MSA). Thanks!
