### ISSUE TITLE
Unable to find MSGraph permissions Insights-GuestActivity.Read.All

### ISSUE THREAD

**Issue by rogers14k** [microsoftgraph/microsoft-graph-explorer-v4#2701]
Im attempting to use the new Entra guest inactivity report and the report doesnt have an export option which makes no sense but it is in preview... So I found the calls (https://graph.microsoft.com/beta/identitygovernance/insights/guestInactivityInsights) they were making and attempted to use them in Graph Explorer. When running the query I get "Calling principal does not have required MSGraph permissions Insights-GuestActivity.Read.All" but it seems to not exist. I assume because the report is still in preview I might have some issues but explorer is telling me to use an API that seems to not exist.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Call https://graph.microsoft.com/beta/identitygovernance/insights/guestInactivityInsights 
3. Read Response Preview

**Expected behavior**
Finding the correct API

**Screenshots**
![Screenshot 2023-07-28 at 2 39 42 PM](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/64924757/390e4d07-90b3-4b2c-a806-3f03d249823b)
![Screenshot 2023-07-28 at 2 39 05 PM](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/64924757/108f2c53-37a5-448d-8e3c-33c9b21bd6da)

**Additional context**
Again the overall goal is to export the report so if anyone has ideas im all ears.

**Comment by Onokaev** [comment]
Hey @rogers14k. I was able to reproduce this.
However, since the feature is still in preview, I suspect some things may not work as you expect. I'd recommend reposting this issue on the Q&A site here: https://learn.microsoft.com/en-us/answers/questions/ask/ and tag `Microsoft Identity Manager`. The team working on the feature will respond with more concrete information

**Comment by Onokaev** [comment]
Let me know if this helps
