### ISSUE TITLE
Unable to provide graph API consent despite of having global administrator permission

### ISSUE THREAD

**Issue by NarenderSingh** [microsoftgraph/microsoft-graph-explorer-v4#2702]
I'm unable to provide graph api consent. I was trying to use the onlinemeeting graph api end-point. But it constantly return Scope consent failed - invalid_client. Please see the attached error

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/12576426/123c6074-873f-4b1f-8ce2-4c3d7a2eea06)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/12576426/fd8dce7e-a186-4a20-9d1d-2614e52a62d9)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/12576426/05938666-cb79-4bb4-8eb7-2055f987c7d6)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/12576426/41583f80-ba72-44d1-844c-6c66f2aa7301)

**Comment by Onokaev** [comment]
Hey @NarenderSingh. Is this happening on the production app or is it your local fork of the repo?

**Comment by NarenderSingh** [comment]
Hi @Onokaev . Thanks for the reply. I was able to solve it through Graph Explorer (Office site)
Steps I followed:
1. Open https://portal.azure.com/
2. Go to Enterprise Applications
3. Go to Graph explorer (official site)
4. Go to Permissions tab
5. Go to User Consent tab
6. Grant admin consent for the tenant

**Comment by NarenderSingh** [comment]
Thanks @Onokaev !
