### ISSUE TITLE
Sign in activity - unable to add permission for `AuditLog.Read.All` 

### ISSUE THREAD

**Issue by bubbletroubles** [microsoftgraph/microsoft-graph-explorer-v4#2731]
**Describe the bug**
When doing a GraphAPI call for a query that needs `AuditLog.Read.All` permission scope, there is no option to modify permissions to add that permission.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Log on with a user account to Graph Explorer (don't use sample data)
3. Enter the query GET https://graph.microsoft.com/v1.0/users?$select=displayName,signInActivity
5. Click "Modify permissions"
6. There is no option to add the "AuditLog.Read.All" permission scope

```json
{
    "error": {
        "code": "Authentication_MSGraphPermissionMissing",
        "message": "Calling principal does not have required MSGraph permissions AuditLog.Read.All",
        "innerError": {
            "date": "2023-08-08T05:24:56",
            "request-id": "redacted",
            "client-request-id": "redacted"
        }
    }
}
```

**Expected behavior**
When selecting Modify Permissions, there is the option to add "AuditLog.Read.All"

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/42738824/9dd39957-9348-4286-ad89-a4c32d5a3b84)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 115.0.1901.188

**Comment by Onokaev** [comment]
Hey @bubbletroubles. We have another panel with all permissions.
Once you are signed in, click on your profile:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/45680252/0bec8f2e-28e6-41f6-b2aa-f3f74f0b9ca9)

You should see this:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/45680252/9571f8cd-a817-457f-99ba-5fb2a90748d2)

Click on `Consent to permissions` and search for `AuditLog.Read.All`

**Comment by bubbletroubles** [comment]
That worked, many thanks :)
