### ISSUE TITLE
Try It experience on beta doc pages runs a V1.0 url 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2732]
When using Graph Explorer from within the documentation with a beta API, the URL resolves a v1.0 API 
see example here https://learn.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&tabs=http#code-try-1

Expected behaviour: A user on a beta API expecting to test it out, should be able to run the beta API

**Comment by ElinorW** [comment]
Hey @RabebOthmani ,
This seems to be an issue with the way the URL is written.
 
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/8417623d-f089-4ecc-aab5-c8b1a1ed57f5)

By default, GE adds a `https://graph.microsoft.com/v1.0` domain to requests that don't have the domain part added....
In the case of beta requests, the full URL should be included to avoid confusion 
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/4af209a1-7225-4074-9ce6-907b7ab167da)

**Comment by ElinorW** [comment]
This seems to now be resolved.
