### ISSUE TITLE
The app is unresponsive for `/tenantRelationships/microsoft.graph.findTenantInformationByDomainName(domainName='{domainName}')`

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-explorer-v4#2736]
**Describe the bug**
By using autocomplete I'm trying to type the following URL in the Graph Explorer
 `https://graph.microsoft.com/v1.0/tenantRelationships/microsoft.graph.findTenantInformationByDomainName(domainName='{domainName}')`

No issues when typing

    https://graph.microsoft.com/v1.0/tenantRelationships

But when the combobox appears and I select `microsoft.graph.findTenantInformationByDomainName(domainName='{domainName}')`` then the whole page is stuck and unresponsive

**To Reproduce**
1. Insert the URL `https://graph.microsoft.com/v1.0/tenantRelationships/microsoft.graph.findTenantInformationByDomainName(domainName='{domainName}')` and try to change `domainName` parameter

**Expected behavior**
Application doesn't stuck

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser All possible browsers

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Onokaev** [comment]
Acknowledged. We are looking into it
