### ISSUE TITLE
Value cannot be null.Parameter name: source

### ISSUE THREAD

**Issue by guanxin365** [microsoftgraph/microsoft-graph-explorer-v4#2739]
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/75707815/e5b59fc8-645f-455b-bd84-e48c17a0e1db)
https://graph.microsoft.com/v1.0/places/microsoft.graph.room
Internal Server Error - 500 - 730ms
{
    "error": {
        "code": "",
        "message": "An error has occurred.",
        "innerError": {
            "message": "Value cannot be null.Parameter name: source",
            "date": "2023-08-15T04:01:47",
            "request-id": "604f0ae2-e701-4b66-a07b-4ff7bfc0f698",
            "client-request-id": "cbfc3820-5ef5-5518-330e-c866f7aec191"
        }
    }
}

**Comment by ElinorW** [comment]
.
