### ISSUE TITLE
Using Todo.Lists["Tasks"] works for most queries but not for GetTodoTask

### ISSUE THREAD

**Issue by GuymanDudeson** [microsoftgraph/microsoft-graph-explorer-v4#2743]
**Describe the bug**  
The graph-endpoint "/me/todo/lists/{todoTaskListId}/tasks/{taskId}" is the only TodoTask endpoint that does not allow the usage of the "Tasks" shorthand for the todoTaskListId parameter. It returns an "invalidRequest: Parent folder specified does not contain a Task with given Id" Exception.

**To Reproduce**  
1. Go to [GraphExplorer](https://developer.microsoft.com/en-us/graph/graph-explorer)
1. Sign In since the default User does not have any Tasks
2. Add a Task in the defaultList if you have none
3. Query all tasks in your list with the "https://graph.microsoft.com/v1.0/me/todo/lists/Tasks/tasks" endpoint
4. Choose one and copy the Id
5. Try to query this specific task by appending the taskId ("https://graph.microsoft.com/v1.0/me/todo/lists/Tasks/tasks/{taskId}")

**Expected behavior**  
The TodoTask with the given Id found in the defaultList is returned.

**Desktop:**
- OS: Windows 10
- Browser: chrome
- Version: 22

**Additional context**  
- I haven't tried all endpoints, but the endpoints "List Tasks", "List Task List", "Create Task", "Delete Task" and "Update Task" all work when using "Tasks" as the {todoTaskListId}.  
- The GetTask enpoint works without issue when using the id of the defaultList, it is only the "Tasks" shorthand that produces the error.  
- This happens both in the GraphExplorer and with the DotNet SDK.  
- Might not be a bug if this is intended behaviour, but if it is, I would like to know why?

**Comment by ElinorW** [comment]
Hi @GuymanDudeson, 
I have been able to reproduce the issue on my end. 
However we at Graph Explorer only handle the issues related to the web application. For issues regarding the API, I would suggest posting this on the Microsoft Q & A forum where the Microsoft To Do Api team will be able to respond.
