### ISSUE TITLE
Issue regarding updating MS ToDo Task's status to completed.

### ISSUE THREAD

**Issue by konsultoo-kaushal** [microsoftgraph/microsoft-graph-explorer-v4#2747]
**Describe the bug**
I am trying to update the Status to 'completed' of Microsoft ToDo's Task using Microsoft Graph REST API v1.0 -> Microsoft To Do API. I am using Python language. but on the status change to 'completed' the task on my MS ToDo will be deleted rather than fall into the list of completed tasks.
The same code was working perfectly 2 months ago but now it is not.

**To Reproduce**
1. Use Microsoft Graph REST API v1.0 -> Microsoft To Do API
2. With PATCH Request provide the value of the task's status as 'completed'
3. now the task on MS ToDo will be deleted

**Expected behavior**
This task should fall into lists of completed tasks.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
The same code was working perfectly 2 months ago but now it is not.
Please provide me with the right guidance.

**Comment by samwelkanda** [comment]
Hi @konsultoo-kaushal 

Thank you for reporting this issue. Can you please clarify what client you are using to make the request? 

We are unable to replicate this issue both on Graph Explorer and the Microsoft Graph Python SDK. Please also share the relevant code snippet if you can.

Thanks

**Comment by konsultoo-kaushal** [comment]
Respected Reader,

I have registered the application on Azure Portal to get the client id and client secret, then using the following code.

task_done_url = 'https://graph.microsoft.com/v1.0/users/' + task.user_id.login + '/todo/lists/' + list_id + '/tasks' + '/' + task.todo_task_id
                data = {
                    "status": "completed"
                }
done_task_response = requests.patch(task_done_url, data=json.dumps(data), headers=task_headers)

Regards

  *   Kaushal

________________________________

**Comment by samwelkanda** [comment]
@konsultoo-kaushal 

I see you are using `requests` library to make the call.

Ideally, your request should work if all parameters are populated.

For your case, what response do you get from the server. Is it a `200`?

**Comment by konsultoo-kaushal** [comment]
Respected Readers,

Yes, I do get response code 200, My concern is that around 3 months ago with this request the task was falling in the list of completed tasks in the Microsoft ToDo application, but now with this same request task is being deleted.

Best Regards

  *   Kaushal

________________________________

**Comment by samwelkanda** [comment]
Unfortunately, I am still unable to reproduce this error.

The todo task status is updated as expeced. Here's my code:
```py
headers = {
    "Authorization": f"Bearer {token}",
    "content-type": "application/json"
}


task_done_url = f'https://graph.microsoft.com/v1.0/me/todo/lists/{task_list_id}/tasks/{task_id}'
data = {
    "status": "completed"
}
done_task_response = requests.patch(task_done_url, data=json.dumps(data), headers=headers)
print(done_task_response.text)
```

**Comment by konsultoo-kaushal** [comment]
Respected Reader,

It is all right I found the issue, it was some third-party code that was producing this issue, I was unable to track it till now because I did not have access to the client's repository.

Thank you very much for all of your support I appreciate it 🙏

Best Regards

  *   Kaushal

________________________________
