### ISSUE TITLE
Get-MgBetaDeviceManagementVirtualEndpointDeviceImage (/deviceManagement/virtualEndpoint/deviceImages) Permissions

### ISSUE THREAD

**Issue by itsTerryDuckett** [microsoftgraph/microsoft-graph-explorer-v4#2750]
**Describe the bug**
The commandlet "Get-MgBetaDeviceManagementVirtualEndpointDeviceImage" returns 403 with proper permissions.
![2023-08-17 13_48_23-Graph Explorer _ Try Microsoft Graph APIs - Microsoft Graph and 8 more pages - W](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/105518999/ed1347f9-24a8-4076-b75d-fafb60628413)

**To Reproduce**
1. Go to the Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer) and run a query against https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/deviceImages.
2. Grant proper consent/permissions (CloudPC.Read.All or CloudPC.ReadWrite.All
3. Run Query. Should return results, or nothing if no images exist. However, this returns a 403 error.

**Expected behavior**
Should return results, or nothing if no images exist.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 1
 - Browser: Edge
 - Version: Version 115.0.1901.203 (Official build) (64-bit)

**Comment by ElinorW** [comment]
Hi @itsTerryDuckett, this appears to be an issue with the Graph API. 
Please post this on the Microsoft Graph Q&A forum.
