### ISSUE TITLE
The endpoint https://graph.microsoft.com/v1.0/external/connections returns 429 

### ISSUE THREAD

**Issue by xinzhaozhang1985** [microsoftgraph/microsoft-graph-explorer-v4#2751]
**Describe the bug**
I am trying to retrieve external connections via https://graph.microsoft.com/v1.0/external/connections, but the API returns 429
Not sure why it is not working now because it was working before.

**To Reproduce**
1. Go to (https://developer.microsoft.com/en-us/graph/graph-explorer)
2. Click on "Resources" -> External -> Connections -> Get Connections
3. Click on Run Query and consent with the required permission
4. Instead of seeing existing connectors I See error 429

**Expected behavior**
All the existing external connectors should return

**Screenshots**
![searcherror](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/102950394/d039f9eb-4381-4f87-af71-22d88128c804)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Onokaev** [comment]
Hey @xinzhaozhang1985. I have reproduced this problem on postman. The endpoint has an issue. Repost this question on the Graph Q&A forum.
