### ISSUE TITLE
Graph explorer /sites return empty value and /sites/getAllSites return Access denied

### ISSUE THREAD

**Issue by Kalshu** [microsoftgraph/microsoft-graph-explorer-v4#2753]
**Describe the bug**
The API endpoint https://graph.microsoft.com/v1.0/sites is returning an empty list instead of the expected data. I have verified that the API request is being made with the correct parameters and headers and permissions. However, the response I receive is consistently empty.

Alternative : 
The API endpoint /sites/getAllSites return an error code :  "accessDenied"
Same, permissions Sites.Read.All & Sites.ReadWrite.All are  consented

I have root site and a list of site in sharepoint

**To Reproduce**
1. Go to(https://learn.microsoft.com/fr-fr/graph/api/site-list?view=graph-rest-1.0&tabs=http#code-try-11)
2. Click on "run query"
4. See empty response
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/2726957/e6a26726-7e09-4624-aa56-13201c304a88)

**Expected behavior**
The API endpoint consistently returns an empty response, without any error messages or status codes that might indicate the reason for the issue.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/2726957/e6a26726-7e09-4624-aa56-13201c304a88)

**Desktop :**
 - OS: W11
 - Browser Chrome
 - Version 116.0.5845.97

**Comment by Onokaev** [comment]
Hey @Kalshu. This appears to be an issue with the /sites endpoint. I have reproduced both behaviors on postman. We however can't help you solve this on Graph Explorer. Repost the question on the Graph Q&A site and remember to tag `Microsoft Graph Site Lists API`
