### ISSUE TITLE
As a user, I want to be able to change the height of the request area and response area ratio

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-explorer-v4#278]
In Graph Explorer v3, I can hover over with my mouse the area between the request area and response area. I can click and then drag to make the height different. I would like to be able to do that in v4. 

The main reason for this is so that I can see all the permissions in the list visually without having to scroll. It's great when you are teaching and presenting on a screen.

Task:
#311

**Comment by jobala** [comment]
I believe this solves the same problem as #208

**Comment by jobala** [comment]
I tried resizing in Graph Explorer v3 but it didn't work for me. @bettirosengugi were you able to resize v3? If you did, please attach a GIF to provide context.

**Comment by thewahome** [comment]
Closing this as it is represented in #311
