### ISSUE TITLE
Graph API SharePoint List Filter action not working

### ISSUE THREAD

**Issue by logulrs88** [microsoftgraph/microsoft-graph-explorer-v4#2782]
OData Query : /items?expand=fields&items?$filter=fields/Title+eq+'adfadsfads'

We got entire list from the SharePoint.  This issue happening from sep-2-2023

**Comment by ElinorW** [comment]
Hi @logulrs88 ,
Could you provide an example of the response you are getting?

**Comment by logulrs88** [comment]
After day , issue automatically fixed. Thanks for your support

**Comment by ElinorW** [comment]
Welcome! 
I'll close this now
