### ISSUE TITLE
"https://graph.microsoft.com/v1.0/invitations/{invitation-id}" is suggested by MS Graph Explorer while not existing in the API

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-explorer-v4#2787]
**Describe the bug**
MS Graph Explorer suggests "https://graph.microsoft.com/v1.0/invitations/{invitation-id}", however this API endpoint does not exist in MS Graph API, resulting in a "UnknownError" code error.

This API endpoint is suggested for the GET, DELETE, and PATCH methods.

**To Reproduce**
1. Go to the Resources tab
2. Type "invitation-id"
3. Open the "invitation-id" resource. The "GET", "DELETE", and "PATCH" methods are present there.

**Expected behavior**
Since there's no "https://graph.microsoft.com/v1.0/invitations/{invitation-id}" API endpoint in MS Graph API, MS Graph API should not display as it existing.

**Screenshots**
Response of "GET https://graph.microsoft.com/v1.0/invitations/{invitation-id}"

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/103036544/a9f0ee45-190a-4e40-b65a-c7fddeba8d10)

Resources tab

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/103036544/fa9661a8-385e-419b-9eeb-49a41a6dda5b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Version 115.0.1901.203 (Official build) (64-bit)

**Additional context**
N/A

**Comment by thewahome** [comment]
@irvinesunday is this captured in the over-generation problem?

**Comment by irvinesunday** [comment]
> @irvinesunday is this captured in the over-generation problem?

From the docs. [page](https://learn.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0), it seems the API **only** supports [POST](https://learn.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http#http-request) operation. 

From the API definition in docs, it seems indexing into an invitation resource is not supported, i.e., _/invitations/{invitation-id}_, however, I might need to get clarification from the respective workload team on this. 
In the meantime, I can go ahead and add the necessary restriction annotation in the metadata to restrict indexing by key for this resource. This will remove all operations under _/invitations/{invitation-id}_

Possibly related to: https://github.com/microsoftgraph/msgraph-cli/issues/370

**Comment by irvinesunday** [comment]
Besides adding the annotation in the metadata, we will also need to add support for `IndexableByKey` annotations for entity set in the conversion library. Here's a link to this work item: https://github.com/microsoft/OpenAPI.NET.OData/issues/541.
These work items have been queued to be actioned in the current milestone for the month of June.

**Comment by ElinorW** [comment]
Closing this as the endpoint is now restricted
