### ISSUE TITLE
Drafts folder has an email with attachment and body.Search returns 200 response but value is empty list.

### ISSUE THREAD

**Issue by Amulyakr** [microsoftgraph/microsoft-graph-explorer-v4#2790]
Api used, https://graph.microsoft.com/v1.0/me/mailFolders/drafts/messages?$search="body:'210923124127767testsnf9'"

Created an email in drafts folder with attachment. This api returns 200 response but value field is empty. 
Note : Works sometimes but most of the time returns empty value.

**Comment by ElinorW** [comment]
Hi @Amulyakr,
I'm currently unable to produce this which might be because of the intermittent behaviour. 
This could be an issue with the Outlook Mail API's. Please raise this issue in the Microsoft Q&A forum, where the appropriate team will be able to offer more assistance.
