### ISSUE TITLE
Cannot search for folders anymore

### ISSUE THREAD

**Issue by razisyed** [microsoftgraph/microsoft-graph-explorer-v4#2791]
**Describe the bug**
Before, searching for files used to return folders on top, but something has changed and now only files are returned in search api

**To Reproduce**
Use "Search my OneDrive" option to setup this api call:
https://graph.microsoft.com/v1.0/me/drive/root/search(q='finance')?select=name,id,webUrl

**Expected behavior**
Search result should include folders first, but it doesn't include any folders, it only returns files. In onedrive.com interface, to replicate this behavior, when you search on top, you have to change "&searchScope=all", and the results match the api call. However, the default behavior is "&searchScope=folder", and that's what I want the api to return as well. How can I specify the search query parameter to specify folder search? This used to work as expected a few months ago. 

**Additional Context**
I understand this isn't a graph explorer issue, it's a change in the actual onedrive api behavior. There is no documentation on the change, and there isn't any documentation on how to include folders in search either. This was the best place I could find to highlight this issue and report it as a bug.

**Comment by ElinorW** [comment]
Hi @razisyed, 
This is likely a change in the onedrive api as you had mentioned. Please raise this issue in the Microsoft Q&A forum where the appropriate time shall be able to help
