### ISSUE TITLE
get profileCardProperties error

### ISSUE THREAD

**Issue by iavoo** [microsoftgraph/microsoft-graph-explorer-v4#2793]
**Describe the bug**
https://graph.microsoft.com/beta/organization/<tenant-id>/settings/profileCardProperties gives error :
message": "Resource not found for the segment 'profileCardProperties'

**Comment by iavoo** [comment]
I am global admin, Tenant ID and permission are set for User.ReadWrite andUser.ReadWriteAll

**Comment by ElinorW** [comment]
Hey @iavoo, 
Ref: https://learn.microsoft.com/en-us/graph/api/peopleadminsettings-list-profilecardproperties?view=graph-rest-beta&tabs=http
I think this has the query you would need to obtain 'profileCardProperties'
