### ISSUE TITLE
Graph API Inline image in MS Teams channel

### ISSUE THREAD

**Issue by mrsabapathy** [microsoftgraph/microsoft-graph-explorer-v4#2794]
**Describe the bug**
I'm able to post an inline image into MS teams channel using graph API but when I try to click the image in Teams channel, the image is not shown in full screen and not showing an enlarged image

**To Reproduce**
1. post inline image using  "https://graph.microsoft.com/v1.0/teams/<id>/channels/<id>/messages" using steps mentioned here: https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=http

2. Image seen in Teams channel
3. Click the image
4. Image is not shown in full screen/not able to zoom in

**Expected behavior**
Upon clicking the image, the image should show in full screen or be able to zoom in

**Comment by thewahome** [comment]
@mrsabapathy 

Any chance you can post the question at the link below to get feedback from the API owners? As this repo is mainly intended for the Graph Explorer issues, we may not be best placed to answer question regarding the behavior of the API.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
