### ISSUE TITLE
Bad request rising wrongly

### ISSUE THREAD

**Issue by RuanAlesi** [microsoftgraph/microsoft-graph-explorer-v4#2817]
**Describe the bug**
Sending a HTTP request with both Postman and GraphExplorer returns the error message "The 'filter' query option must be provided" even such option being already provided.

**To Reproduce**
1. Send a request to https://graph.microsoft.com/v1.0/me/drive/root/items?$filter=Name eq "something"

**Expected behavior**
The items should be listed (or not found error message at least)

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/64651136/74762c26-45b7-4931-bcc9-3e5d3204fcac)

**Comment by ElinorW** [comment]
Hi @RuanAlesi ,
Instead of using /items could you try replace this with /children and see if it works?
i.e ` https://graph.microsoft.com/v1.0/me/drive/root/children?$filter=Name eq "something"`
