### ISSUE TITLE
Autocomplete suggestions list displaying v1.0 endpoints even when beta is selected

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#2828]
**Describe the bug**
When writing a query that includes the beta version, the list of suggestions appears to be similar to the v1.0 list and is missing some of the beta nodes that are visible on the resource tree

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Click on query input
3. Erase the current query up until the version and write '/beta/' instead
4. Notice the list is missing some endpoints e.g AccessReviewDecisions which appears first on the beta resources tree

**Expected behavior**
The suggestions list should have beta endpoints as well

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/571e3d73-5036-433c-a724-000b2830582b)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
false alarm...

**Comment by ElinorW** [comment]
Re-opening as issue is still present
