### ISSUE TITLE
Access a shared calendar with application permissions

### ISSUE THREAD

**Issue by ryanhulsker** [microsoftgraph/microsoft-graph-explorer-v4#2829]
**Is your feature request related to a problem? Please describe.**
I am building an integration with a custom phone system product.  I would like to be able to link a shared calendar of some sort with this phone system using the graph api.  For example, we could have a calendar in which we place an event called 'business hours' and then we can change the routing of the phone calls based on this.  Or alternately we could have an event called 'on call' and whoever is invited to the current day's on-call event will have emergency phone calls routed to them.

Using a Microsoft calendar for this is ideal because then all the staff who need to make changes don't need permissions and training to update calendars that are inside of the phone system, and the MS calendars can be updated remotely using existing procedures that everyone is familiar with.

Here is the problem, there is no way right now in the graph API to view or update a shared or group calendar with application permissions in a way that guarantees future access.  The only way to access calendars is with delegated permissions (please correct me if this is wrong).  The problem with delegated permissions in this context is that if the employee delegating the permissions is terminated then the phone system will loose access to the calendar.  If I use a service account I will have to create a monitoring solution to make sure that the delegated permissions are still working. etc.

**Describe the solution you'd like**
I would like to be able to set up permanent application permissions to a group calendar, and to use application permissions to access the events in the calendar without user intervention.  In my use case I am trying to write a simple python script that will run periodically (via cron) to pull in events in the calendar and there is no UI, and no user interacting with it.

**Describe alternatives you've considered**
I tried a group calendar and cannot access it with the graph api using application permissions.  I tried to do the same with a personal shared calendar, but there is no way guarantee access if my account is disabled.  If there was a way to list all the users that have permissions to a calendar or who is the current owner I may be able to work around this.

**Additional context**
None

**Comment by thewahome** [comment]
Hello @ryanhulsker 
It is true that for shared or group calendars, you need to use delegated permissions, such as Calendars.ReadWrite.Shared or Group.ReadWrite.All. These permissions allow the app to access the calendars that are shared with or owned by the signed-in user. Application permissions, such as Calendars.ReadWrite, only allow the app to access the calendars of all users in the organization, not the shared or group calendars

One possible way that you could try is to use a service account that has access to the shared or group calendar and delegate the permissions to the app. You need to make sure that the service account is not terminated or disabled, and that the permissions are not revoked. You can also monitor the access token expiration and refresh it when needed. Here is documentation on [how to create a service account](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http)

Another alternative might be to use the Microsoft Graph subscriptions API to create a subscription for the shared or group calendar. This way, the app can receive notifications when the calendar changes, without having to access the calendar directly. So here people can interact with the calendar freely.
