### ISSUE TITLE
bug/childCount not correct in search query

### ISSUE THREAD

**Issue by ncarvajalc** [microsoftgraph/microsoft-graph-explorer-v4#2830]
**Describe the bug**
When trying to search for a folder inside of an item in the OneDrive api, the folder -> childCount is always set to zero. But when the folder is accessed directly, the childCount is displayed correctly.

**To Reproduce**
1. Make the following request in a folder with child folders which you know have childs:
GET https://graph.microsoft.com/v1.0/me/drive/items/{{folder_id}}/search(q='{search_term}')
2. See that the folder -> childCount property is set to 0 and copy the id of that folder
3. Make the following request with the previous id:
GET https://graph.microsoft.com/v1.0/me/drive/items/{{previous_folder_id}}
4. folder -> childCount property is not 0

**Expected behavior**
The childCounts should be consistent

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/66692533/acb3ecb2-3b94-48fe-8b67-58e4d491919b)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/66692533/626d5a39-c4a4-4a41-9428-1e463e9e2c09)

Notice that the folder with id '01RASYKTIE76MUOKLKWBA32BC77ZCMFK5G' has a childCount which is different in the 2 images.
  
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Arc
 - Version 1.13.1 (42579)

**Comment by thewahome** [comment]
@ncarvajalc this is a detailed analysis you've provided.
We are going to mark this as a `API: Graph` issue since it is likely an issue with the Graph API
