### ISSUE TITLE
Code snippets that actually work?

### ISSUE THREAD

**Issue by PaulPetersenAtTheAA** [microsoftgraph/microsoft-graph-explorer-v4#2833]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ElinorW** [comment]
Hi @PaulPetersenAtTheAA , 
Which snippet didn't work for you? Could you share an example?

**Comment by PaulPetersenAtTheAA** [comment]
PS C:\Windows\system32> Import-Module Microsoft.Graph.Users
 
# A UPN can also be used as -UserId.
Get-MgUserPhotoContent -UserId $userId -OutFile $outFileId
Get-MgUserPhotoContent : Cannot bind argument to parameter 'UserId' because it is an empty string.
At line:4 char:32
+ Get-MgUserPhotoContent -UserId $userId -OutFile $outFileId
+                                ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-MgUserPhotoContent], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-MgUserPhotoContent
 

PS C:\Windows\system32>

**Comment by maisarissi** [comment]
Hi @PaulPetersenAtTheAA it seems like the $userId parameter you are trying to use is empty.
The userId can be replaced with a valid id or upn directly in the command, for example
```powershell
Get-MgUserPhotoContent -UserId email@email.com -OutFile "outputFile.jpg"
```

Or even populating the userId and outFileId parameters before calling the command in your script, like:
```powershell
$userId = "email@email.com"
$outFileId = " C:\Users\user\photo.jpg"
Get-MgUserPhotoContent -UserId $userId -OutFile $outFileId
```
