### ISSUE TITLE
⚠🐛 Bad JSON Returned: `https://graph.microsoft.com/{version}/planner/tasks/{task-id}/details`

### ISSUE THREAD

**Issue by hb-webdev** [microsoftgraph/microsoft-graph-explorer-v4#2834]
### **This does not affect only Graph Explorer, but Microsoft Graph API as a whole.**

**Describe the bug**
`https://graph.microsoft.com/{version}/planner/tasks/{task-id}/details` sometimes returns bad (red-colored) JSON.  There is seemingly a mismatch in the number of opening/closing curly braces, and there are escape characters (`\`) littered throughout the data. (aka it's representing the JSON in plaintext instead of as a JSON object.) This results in the JSON being unparsable in Power BI where I'm calling the Graph API.

**To Reproduce**
Simply run the `https://graph.microsoft.com/{version}/planner/tasks/{task-id}/details` endpoint in Graph Explorer with an offending Task ID.

(I cannot determine the exact conditions that cause this. It might be caused by certain characters within some of the tasks' data that are breaking the API.)

**Expected behavior**
I expect the JSON to be correctly formatted so I can use the Graph API in my app.

**Screenshots**
### 2 Task ID's that return good JSON:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/85006632/a3a957cb-33f6-4353-8b0e-c762c3b44e55)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/85006632/667ee924-a5c0-4622-9203-42a024e3bfa1)

### 2 Task ID's that return bad JSON:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/85006632/f12d9cf3-e575-4987-abdd-c59f680a9137)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/85006632/ecfbd3d9-f6f7-42af-90f7-a4a8097a3855)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 117.0.5938.149 

**Additional context**
All permissions in Graph Explorer are granted. All necessary Read permissions are granted in Power BI

**Comment by ElinorW** [comment]
Hey @hb-webdev,
could you send me a screenshot of the network call being made when you get the response in the bad JSON format?
