### ISSUE TITLE
I cannot run request for Windows Update API

### ISSUE THREAD

**Issue by guliteb** [microsoftgraph/microsoft-graph-explorer-v4#2835]
**Describe the bug**
I cannot run Windows Updates sample queries. The error is 'Forbidden - 403 - 301ms. Either the signed-in user does not have sufficient privileges'.

But I have following licenses on the user.
1. Enterprise Mobility + Security E5
2. Intune
3. Microsoft Entra ID P2

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/39818609/62a60fcc-b42c-4b57-a88c-bc35cd80ac47)
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/39818609/8c37bc54-e24d-4238-8d4f-83159da7bfcd)

**Desktop (please complete the following information):**
 - OS (Client): Windows 10 IoT Enterprise LTSC 2021
 - Browser: Edge
 - Version: 119.0.2151.30

**Comment by thewahome** [comment]
Hello @guliteb,
I've found [this article](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/try-windows-update-for-business-with-microsoft-graph/ba-p/3663728) that could possibly help highlight the steps that could have missed.

Incase the steps are the same, it could be that there is a permissions mismatch between the ones you have and the ones that are needed. for example, to use this API, you need to have one of the following subscriptions in your organization:

Windows 10/11 Enterprise E3 or E5 (included in Microsoft 365 F3, E3, or E5)
Windows 10/11 Education A3 or A5 (included in Microsoft 365 A3 or A5)
Windows Virtual Desktop Access E3 or E5
Microsoft 365 Business Premium
