### ISSUE TITLE
[User story] Copy API manifest path 

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2836]
As a user, when I click on the 'copy to clipboard' button
I want the API manifest path to be copied
So I can use it with the Kiota extension on VS Code 

Acceptance criteria:
* I want to have a valid API manifest Path

**Comment by thewahome** [comment]
What is an API manifest path?

**Comment by RabebOthmani** [comment]
@thewahome I'm noticing that what we are copying is an encoded value. Originally we encoded that to manage the URL and be able to open directly in VS Code. There's no need to encode anymore. Is there a use case for encoding?

**Comment by baywet** [comment]
both would be supported I believe at this point. But To Rabeb's point, since we don't need to encode it anymore, having it copied to the clipboard not-encoded would be useful to people who want to copy it to do something else with it.

**Comment by RabebOthmani** [comment]
Test scenario 
<img width="545" alt="collection to generate" src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/5781590/0348f6d8-f0a8-482d-8bdf-a8d2604ff213">

Path generated 
```
{
    "publisher": {
        "name": "Microsoft Graph",
        "contactEmail": "graphsdkpub@microsoft.com"
    },
    "apiDependencies": {
        "graph-v1.0-DelegatedWork": {
            "apiDescriptionUrl": "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
            "apiDeploymentBaseUrl": "https://graph.microsoft.com",
            "apiDescriptionVersion": "v1.0",
            "auth": {
                "clientIdentifier": "",
                "access": [
                    {
                        "type": "openid",
                        "claims": {
                            "scp": {
                                "essential": true,
                                "values": [
                                    "Chat.ReadBasic"
                                ]
                            }
                        }
                    }
                ]
            },
            "requests": [
                {
                    "method": "GET",
                    "uriTemplate": "/chats"
                },
                {
                    "method": "GET",
                    "uriTemplate": "/chats/$count"
                }
            ]
        },
        "graph-beta-DelegatedWork": {
            "apiDescriptionUrl": "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/beta/openapi.yaml",
            "apiDeploymentBaseUrl": "https://graph.microsoft.com",
            "apiDescriptionVersion": "beta",
            "auth": {
                "clientIdentifier": "",
                "access": [
                    {
                        "type": "openid",
                        "claims": {
                            "scp": {
                                "essential": true,
                                "values": []
                            }
                        }
                    }
                ]
            },
            "requests": [
                {
                    "method": "GET",
                    "uriTemplate": "/admin"
                }
            ]
        }
    }
}
```

If I change the scope 
<img width="578" alt="scope " src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/5781590/3065d826-d5e8-4329-a677-ef70344bd4e1">

The generation 
```
{
    "publisher": {
        "name": "Microsoft Graph",
        "contactEmail": "graphsdkpub@microsoft.com"
    },
    "apiDependencies": {
        "graph-v1.0-DelegatedWork": {
            "apiDescriptionUrl": "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
            "apiDeploymentBaseUrl": "https://graph.microsoft.com",
            "apiDescriptionVersion": "v1.0",
            "auth": {
                "clientIdentifier": "",
                "access": [
                    {
                        "type": "openid",
                        "claims": {
                            "scp": {
                                "essential": true,
                                "values": [
                                    "Chat.ReadBasic"
                                ]
                            }
                        }
                    }
                ]
            },
            "requests": [
                {
                    "method": "GET",
                    "uriTemplate": "/chats"
                },
                {
                    "method": "GET",
                    "uriTemplate": "/chats/$count"
                }
            ]
        },
        "graph-v1.0-Application": {
            "apiDescriptionUrl": "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
            "apiDeploymentBaseUrl": "https://graph.microsoft.com",
            "apiDescriptionVersion": "v1.0",
            "auth": {
                "clientIdentifier": "",
                "access": [
                    {
                        "type": "openid",
                        "claims": {
                            "roles": {
                                "essential": true,
                                "values": []
                            }
                        }
                    }
                ]
            },
            "requests": []
        }
    }
}
```

@thewahome @darrelmiller the requests are empty once we change the scope to Application and we are not capturing the app permissions required.  This isn't the expected behaviour, is it?

**Comment by darrelmiller** [comment]
@RabebOthmani  `GET /beta/admin` isn't actually a valid Graph URL, so it will fail to return permissions. That might be why we are seeing invalid generation for the app only scenario.  Try it with GET /users

**Comment by RabebOthmani** [comment]
@darrelmiller GET/users is working, FYI @thewahome  which means the conversation should be around the paths so we avoid such cases

**Comment by thewahome** [comment]
The faulty permissions are fixed now @RabebOthmani it's possible that @darrelmiller is looking at the updated values

**Comment by petrhollayms** [comment]
@baywet Could you please have a look on the VSCode integration? To be discussed.

**Comment by baywet** [comment]
@thewahome is this in production or do you have a URI for a preview?
@petrhollayms I believe the repro scenario has changed a couple of times throughout the discussion here now, do you have clear repro instructions?

**Comment by baywet** [comment]
Update: I was able to isolate and fix the bug. However this is now going to consistently fail for both approaches because I also updated the api manifest dependency and the apiDeploymentBaseUrl generated by GE doesn't end with a trailing slash. Could you fix that last detail @thewahome please?

https://github.com/microsoft/kiota/pull/3877

**Comment by baywet** [comment]
(also application name now seems to be required by the spec)

**Comment by thewahome** [comment]
@baywet, I've added the trailing slash

**Comment by baywet** [comment]
Thanks, do you have a staging URL for me to run integration tests? Or were you able to validate end to end with the latest preview of the vscode extension?
