### ISSUE TITLE
SetPresence and ClearPresence Does not work

### ISSUE THREAD

**Issue by afallingstone** [microsoftgraph/microsoft-graph-explorer-v4#2837]
SetPresence and ClearPresence does not work from Blazor WASM application.

**Here is my clear presence code:** 
_I get a status of 200, but it doesn't update anything. Even waiting 20 mins it doesn't change it._
`var requestBody = new Microsoft.Graph.Me.Presence.ClearPresence.ClearPresencePostRequestBody
  {
      SessionId = _configuration["AppSettings:ApplicationId"],
  };
  await Client.Me.Presence.ClearPresence.PostAsync(requestBody);`

**Here is my SetPresence Code:**
_I get a status of 200 only if the availability and activity are set to "Available". Otherwise, I get invalid callouts for them. If I set the Availability and Activity to "Available" I get a return status of 200, but it doesn't change the presence of the user even waiting 20 mins. _
`                    var requestBody = new Microsoft.Graph.Me.Presence.SetPresence.SetPresencePostRequestBody
                    {
                        SessionId = _configuration["AppSettings:ApplicationId"],
                        Availability = "Busy",
                        Activity = "Busy",
                    };
                    await Client.Me.Presence.SetPresence.PostAsync(requestBody);`

**This all gets more confusing because I can change the status message no problem with this code:**
`      DateTimeTimeZone? ExpiryTime = null;
        if (Selection.SignOutDateTime != null)
        {
            ExpiryTime = new DateTimeTimeZone
            {
                DateTime = Selection.SignOutDateTime?.ToString("yyyy-MM-ddTHH:mm:ss.fffffff"),
                TimeZone = "Eastern Standard Time",
            };
        }

        var statusChange = new Microsoft.Graph.Me.Presence.SetStatusMessage.SetStatusMessagePostRequestBody
        {
            StatusMessage = new PresenceStatusMessage
            {
                Message = new ItemBody
                {
                    Content = Selection.Comment,
                    ContentType = BodyType.Text,
                },
                ExpiryDateTime = ExpiryTime
            },
        };
        await Client.Me.Presence.SetStatusMessage.PostAsync(statusChange);`

I am not sure what I am missing to get 200 statuses and able to set the message, but it won't update or allow me to change the Availability and Activity of the user. 

This application is Blazor WASM Hosted and is authenticated by MSAL auth. This application also has other features that work perfectly like: sending and receiving mail, creating draft messages with attachments, and Event creation. 

Help would be appreciated. :)

**Comment by andrueastman** [comment]
Thanks for raising this @afallingstone 

Any chance you can post the question at the link below to get feedback from the API owners? As this repo is mainly intended for the Graph Explorer issues, we may not be best placed to answer question regarding the behavior of the API. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
