### ISSUE TITLE
Presence GET Request Not Working

### ISSUE THREAD

**Issue by GreatHavoc** [microsoftgraph/microsoft-graph-explorer-v4#2838]
**The get my presence query throwing Bad Request - 400**
On running the **get my presence**  on the graph explore page, it threw AuthenticationError, so I went to the permission panel and provided the presence permission. It showed **Success - Scope consent successful**, but after rerunning the same query, it shows the same error, and I also noticed that after reloading the page, the consent is gone.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Search under Sample queries for 'get my presence'
3. Run the query

**Expected behavior**
On running the query, I should be getting the JSON with the desired data on it.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/77237918/6ac9ec52-80be-4b09-bba1-dbb8a6ce8a32)
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/77237918/e166a957-b0d1-46f7-94fa-ce399e9b29c7)

**Desktop:**
 - OS: Windows 11 Home
 - Firefox, Chrome(tried both)

**Comment by ElinorW** [comment]
Hi @GreatHavoc, 
I notice you are using a Personal account. 
The Get Presence endpoint isn't supported for personal accounts 
You can read more about it here: https://learn.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-beta&tabs=http
