### ISSUE TITLE
Support “edm.stream” format in Graph Explorer

### ISSUE THREAD

**Issue by ishatyagiit** [microsoftgraph/microsoft-graph-explorer-v4#2872]
We have recently introduced an API endpoint whose response is of type "text/csv."
https://graph.microsoft.com/beta/employeeexperience/goals/exportJobs/{jobId}/content

Here,  "/content" property is of type "Edm.Stream." on export job.
When we hit the above endpoint in graph explorer, we get an empty object; however, we can see the data in the console. It is happening because Graph Explorer currently only supports JSON and showing user photos.

Can we please start supporting response type "text/csv"?

Or, is there a way we can tooltip when there is an Edm.Stream?

Schema PR: https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/8561460?_a=files&path=/Workloads/Microsoft.Viva.Goals/override

**Comment by ishatyagiit** [comment]
@thewahome : Can we please merge this pull request as I see that this issue is still active

**Comment by thewahome** [comment]
I have reopened it as it still doesn't work as it should

**Comment by ishatyagiit** [comment]
Hi @thewahome @darrelmiller 
Can we please prioritize this issue as it has been pending for a long time?
