### ISSUE TITLE
Api Calls

### ISSUE THREAD

**Issue by Nasty00** [microsoftgraph/microsoft-graph-explorer-v4#2876]
A complete example of the "Calls" api call, you don't understand anything, the media etc.. a complete example on creating a voip call, notification and response to this call, there is very little to read.

**Comment by ElinorW** [comment]
Hi @Nasty00 ,
Please share this feature suggestion on the [Graph Q&A](https://aka.ms/askgraph) forum where the appropriate team would be able to help out
