### ISSUE TITLE
https://graph.microsoft.com/v1.0/teams/{team-id}/members returns only owner role

### ISSUE THREAD

**Issue by anthonyherring** [microsoftgraph/microsoft-graph-explorer-v4#2893]
The only role returned is owner. The member role is blank. Same result using PowerShell.

**Comment by ElinorW** [comment]
Hi @anthonyherring ,
This is the correct response as indicated in the documentation here 
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18407044/2900451a-9b3c-443d-92be-1a8623891871)

Please find more information here: https://learn.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0
