### ISSUE TITLE
Can't revoke Mail.Read permission on my personal account in graph explorer

### ISSUE THREAD

**Issue by agobeaux** [microsoftgraph/microsoft-graph-explorer-v4#2894]
I wanted to reopen https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2700 but I do not have the permissions.
As mentioned there:
Not being able to easily remove the permissions given to Microsoft Graph is a big problem. I followed the links given by @MIchaelMainer (https://account.live.com/consent/Manage) and I erased the permissions of Microsoft Graph Explorer. However, I am still able to do GET requests to get my emails from Microsoft Graph Explorer (using my web browser). How is this even possible? I want to make sure Microsoft Graph Explorer does not have any access to my emails anymore.
Please help.

**Comment by thewahome** [comment]
Hello @agobeaux 
You can try to revoke the Mail.Read permission by:
1. Consent to two additional permissions - Directory.Read.All and DelegatedPermissionGrant.ReadWrite.All
2. Open the select all permissions panel on Graph Explorer: Profile > Consent to permissions
3. Unconsent to the Mail.Read permission and any other Mail permission that you have.

If this doesn't work, please reach out

**Comment by flawesomesoft** [comment]
> Hello [@agobeaux](https://github.com/agobeaux) You can try to revoke the Mail.Read permission by:
> 
> 1. Consent to two additional permissions - Directory.Read.All and DelegatedPermissionGrant.ReadWrite.All
> 2. Open the select all permissions panel on Graph Explorer: Profile > Consent to permissions
> 3. Unconsent to the Mail.Read permission and any other Mail permission that you have.
> 
> If this doesn't work, please reach out

This is not working for me with my personal account (MSA).
Had to do it via [https://account.live.com/consent/Manage](https://account.live.com/consent/Manage) as mentioned here [#2700](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2700#issuecomment-1696042060)
