### ISSUE TITLE
No longer able to login - get a token parsing error

### ISSUE THREAD

**Issue by JK-WP** [microsoftgraph/microsoft-graph-explorer-v4#2895]
**Describe the bug**
I am no longer able to login to MS Graph Explorer. When I try, I get an error message of "**_Authentication failed - token parsing error_**", as shown in the screenshot below. This was not happening when I last tried to use the Graph Explorer, a few weeks ago.

**To Reproduce**
1. In a new InPrivate window, go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'Sign In'
3. Proceed with the authentication process

**Expected behavior**
I would expect to be authenticated, and able to use the Graph Explorer against data in my employer's tenant (via use of a `tenant=<id>` query parameter)

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/92494241/e1941345-ea58-4ea1-9f9d-5a640ef33adf)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 119.0.2151.58 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: N/A

**Additional context**
Using developer tools, I can see that a set of tokens has been returned, and I can, for example, decode the access token to what looks like a valid jwt.

**Comment by ElinorW** [comment]
Hi @JK-WP, 
I am unable to reproduce this. Could you try clearing your cache and trying again?

**Comment by ElinorW** [comment]
Hi @JK-WP, 
I am unable to reproduce this. 
Have you tried clearing cache and signing in again? or signing in in incognito mode?
Let me know how if the result is still the same

**Comment by tts-tomohiro-uryu** [comment]
Sorry I jumped into this issue. We have a same issue. 
Our display name is formed like "First Last (Company)/日本名". When I put the space before and after "/" like "First Last (Company) / 日本名", then the problem is gone. 
I could reproduce this error in the different tenant so I think you can reproduce it as well.

**Comment by JK-WP** [comment]
> Sorry I jumped into this issue. We have a same issue. Our display name is formed like "First Last (Company)/日本名". When I put the space before and after "/" like "First Last (Company) / 日本名", then the problem is gone. I could reproduce this error in the different tenant so I think you can reproduce it as well.

@tts-tomohiro-uryu Thanks for jumping in! Encouraging to hear you are seeing the same problem, which sounds like it matches my issue exactly, as my display name has a similar format to yours, with a katakana version of my name after the slash.

@ElinorW - Just to confirm, I've tried this on multiple browsers, on multiple OSes, including via incongnito mode, and the result is always the same failure, which makes me reasonably confident that this is a real issue, and the feedback from @tts-tomohiro-uryu provides good insight into the likely cause. Please could you adjust your display name to include a forward slash, and try again? Since I wasn't seeing this problem a couple of weeks ago, I suspect something must have changed in the way tokens are being decoded and parsed tokens, which is now stumbling when it finds a slash embedded in the display name.

**Comment by ElinorW** [comment]
@JK-WP @tts-tomohiro-uryu , this is now resolved
