### ISSUE TITLE
Remove 'open in VS Code' button

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#2903]
Due to technical challenges, we decided to remove the ability to directly open in VS Code and instead copying the path to the clipboard. The users then can use the copied path with the Kiota extension on VS Code. 

Acceptance criteria: 
We should not have an open in VS Code button , it should be removed.

**Comment by thewahome** [comment]
After the team deliberation this button was placed back into the design. We should close this as it is no longer a requirement
