### ISSUE TITLE
Call Attribute #5

### ISSUE THREAD

**Issue by kristymadimike** [microsoftgraph/microsoft-graph-explorer-v4#2928]
I need to make a MS Graph call for just Extended Attribute 5. This will call all 15, but do you know how to specify only #5?

https://graph.microsoft.com/v1.0/me?$select=onPremisesExtensionAttributes

We think something like this should work, but it doesn't:

https://graph.microsoft.com/v1.0/me?$select=onPremisesExtensionAttributes/extensionAttribute5

**Comment by ElinorW** [comment]
Hi @kristymadimike, 
I am not sure how to only get a specific Extension Attribute. 
Please post your question on the [Microsoft Graph Q&A](https://developer.microsoft.com/en-us/graph/support) forum where someone from the appropriate team will be able to assist you.
