### ISSUE TITLE
Missing labels under resources tab

### ISSUE THREAD

**Issue by MasoudSamadi** [microsoftgraph/microsoft-graph-explorer-v4#2929]
**Describe the bug**
The API labels under Resources are missing. 

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Click on Resources on the left
3. Expand any available resources
4. Labels next to for examle GET/PATCH actions are missing. 

**Expected behavior**
Label/name of the API action should be visible
**Screenshots**
See attached screenshots

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Edge, Chrome, Firefox]

**Smartphone (please complete the following information):**
 - Device: [iPhone 12]
 - Browser [safari]
![resources](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/30056287/bfadcbfc-bfb3-45fe-a267-7ee1a664e49e)
![sample-queries](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/30056287/092cf156-1c11-4989-81d9-d67caecd9425)

**Comment by thewahome** [comment]
Hello @MasoudSamadi
We intentionally changed the labels as described in [this issue](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2641) so that it is consistent with the Kiota VS Code extension and to reduce repetition
