### ISSUE TITLE
Error Bad Request - /deviceAppManagement/policySets/{policysetID}/assignments

### ISSUE THREAD

**Issue by bitsele** [microsoftgraph/microsoft-graph-explorer-v4#2930]
**Describe the bug**
When I try to get the assignments of a policySet via Graph i get the following error

**To Reproduce**
1. Go to Graph Explorer
2. Using Ressource-> https://graph.microsoft.com/beta/deviceAppManagement/policySets 
to get PolicySetID
3. Using Resource-> https://graph.microsoft.com/beta/deviceAppManagement/policySets/{policysetID}/assignments

**Expected behavior**
Http 200 with payload

**Error Response**

Bad Request - 400 - 130ms
{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/navigation with http verb GET for request /GnT/StatelessPayloadLinkingService/8d87088f-ffff-9909-1207-120500510090/deviceAppManagement/policySets('xxxx')/assignments.",
        "innerError": {
            "date": "2023-12-13T14:04:27",
            "request-id": "4f95d057-0eef-4414-bf93-cfe4ff981026",
            "client-request-id": "51fd598a-0256-23bc-8dad-b7dd21596e08"
        }
    }
}

**Comment by thewahome** [comment]
Hello @bitsele this is likely a problem with the API. I've tagged it appropriately. You should be able to get help from https://aka.ms/askgraph
