### ISSUE TITLE
Access package assignment requests via Graph API bypass approval policy

### ISSUE THREAD

**Issue by quentinmarois** [microsoftgraph/microsoft-graph-explorer-v4#2931]
When creating an access package assignment request with the Graph API, the approval policy is consistently bypassed.

When creating a direct access package assignment in the Azure Portal, I can specify if approvals are bypassed for that request.
![create form](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/56384953/9471e8a2-13ee-4bf1-b2fd-49a0a8a976c7)
Screenshot from this [page](https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-access-package-assignments#directly-assign-any-user-preview).

When choosing not to bypass, the `requestState` and `requestStatus` parameters of the request are `PendingApproval` as expected.
However, when creating an access package assignement with the Graph API, the API always seems to bypass the approval. The `requestState` and `requestStatus` are `Submitted` and `Accepted` respectively, then automatically changes to `Delivered` and `Fulfilled`.
(Endpoint used : https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentRequests)

When checking what the payload sent by the Azure Portal looks like (i.e the request that is not bypassing the approval), I get the following:

```json
{
  "accessPackageAssignment": {
    "target": {
      "displayName": "John Doe",
      "email": "john.doe@contoso.onmicrosoft.com"
    },
    "accessPackageId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "assignmentPolicyId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  },
  "justification": "testing",
  "requestType": "AdminAdd",
  "parameters": [
    {
      "name": "IsApprovalRequired",
      "value": "true"
    }
  ]
}
```

The problem is that even when sending the exact same payload to the Graph API, **and even if the assignment policy requires approval**, the approval still get bypassed.

**Desktop**
 - OS: Windows 11
 - Browser: Edge
 - Version: 120.0.2210.77

**Comment by thewahome** [comment]
Hello @quentinmarois 
This is outside the scope of Graph Explorer but you should be able to easily find help here https://aka.ms/askgraph
