### ISSUE TITLE
Cannot Delete Attachments from an Event

### ISSUE THREAD

**Issue by AFrazier-Git** [microsoftgraph/microsoft-graph-explorer-v4#2943]
**Describe the bug**
Unable to delete attachments from an event. Returns a "Internal Server Error - 500"
```
{
    "error": {
        "code": "ErrorInternalServerError",
        "message": "An internal server error occurred. The operation failed."
    }
}
```

**To Reproduce**
use DELETE /me/events/{id}/attachments/{id}

**Expected behavior**
Attachment specified should be deleted from event

**Desktop (please complete the following information):**
 - OS: Mac OS client
 - Browser: chrome
 - Version: 120.0.6099.129

**Comment by thewahome** [comment]
Hello @AFrazier-Git 
This is likely a problem with the service and you'd need to head on to https://aka.ms/askgraph

**Comment by thewahome** [comment]
Hello @AFrazier-Git
This is likely a problem with the service and you'd need to head on to https://aka.ms/askgraph
