### ISSUE TITLE
Graph API token issue in List teamsApp

### ISSUE THREAD

**Issue by krishnab333** [microsoftgraph/microsoft-graph-explorer-v4#2944]
**Describe the bug**
I'm getting app not found issue while using GET https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/${AppId}/appDefinitions 

**To Reproduce**
1. Go to Graph explorer
2. Provide the https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/${AppId}/appDefinitions in the url part. Replace AppId ID with your app id.
3. Make sure the method is GET request
4. Click on run query
5. 404 error with app is not found message is shown

**Expected behavior**
Expected to get the application details without getting any error.

**Screenshots**
![Screenshot 2024-01-05 at 11 45 48 AM](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/154399912/ca7bc7be-9e38-43a7-9851-e9c1f35546e6)

**Desktop (please complete the following information):**

**Additional context**
The app is available in Teams Admin Center but not listing while calling the graph api.

**Comment by thewahome** [comment]
Hello @krishnab333 
Confirm whether this still doesn't work for you
