### ISSUE TITLE
tenantRelationships/delegatedAdminRelationships and tenantRelationships/delegatedAdminCustomers returns no results

### ISSUE THREAD

**Issue by dbcfd** [microsoftgraph/microsoft-graph-explorer-v4#2953]
**Describe the bug**
Attempting to hit either of those list endpoints returns no results. I have a customer that I have both DAP and GDAP relationships with.

**To Reproduce**
1. Have a customer with a DAP or GDAP relationship
2. Request https://graph.microsoft.com/v1.0/tenantRelationships/delegatedAdminRelationships or https://graph.microsoft.com/v1.0/tenantRelationships/delegatedAdminCustomers
3. Examine Result

**Expected behavior**
I would expect the relationship or customer to be returned

**Comment by ElinorW** [comment]
Hi @dbcfd , 
Are you still experiencing this issue?
