### ISSUE TITLE
Not able to query alerts generated from custom detection methods

### ISSUE THREAD

**Issue by tazthetyrant** [microsoftgraph/microsoft-graph-explorer-v4#2954]
**Describe the bug**
We have a custom detection method that creates alerts when emails from a specific domain are blocked. The category the alerts fall under is 'Collection' when querying these alerts via graph explorer or the graph security connector in power automate, the results are blank. 

**To Reproduce**
1. Create a custom detection method in security.microsoft.com

##########Detection Query##############
EmailEvents
| where SenderFromDomain in ("emaildomain.com")
| where Timestamp >= ago(1d)
| where not(DeliveryLocation has "Inbox" or DeliveryLocation has "Forwarded" or DeliveryLocation has "Deleted" or DeliveryLocation has "On-premises")
| summarize Count = count(), Timestamp = max(Timestamp), ReportId = max(ReportId) by Subject, DeliveryLocation, RecipientEmailAddress
| project Subject, DeliveryLocation, Count, Timestamp, RecipientEmailAddress, ReportId
| sort by Count desc
####################################

Custom detection method settings:

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/156265259/2a2af981-ef6e-4449-876b-2218372946b0)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/156265259/14ea7da9-2812-43a0-afae-0d22593956cc)

2. run the detection method to generate alerts

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/156265259/14414733-cc87-4bf3-859a-5bf2400ce4c6)

3. run this query in graph explorer 
     -https://graph.microsoft.com/v1.0/security/alerts?$filter=category eq 'Collection'
4. sigh

**Expected behavior**
Alerts created from custom detection methods or alerts with the category Collection can be queried from the Graph API

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/156265259/48098ba5-f1fe-4017-868b-8849d97eeb4f)
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/156265259/c0b978ba-9e52-4da5-9ff4-503aaf0d8644)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge, Teams (workflows)
 - Version: current as of 1/10/24

**Additional Context**
I have tried querying the alerts through other means (title, severity, etc.), the API does not return any info on these alerts

**Comment by ElinorW** [comment]
Hi @tazthetyrant, 
If you are still experiencing this issue, it's likely a problem with the API. 
Please create a support ticket here https://developer.microsoft.com/en-us/graph/support
