### ISSUE TITLE
`whatin` requests that result in a `400` don't have the response body displayed

### ISSUE THREAD

**Issue by corranrogue9** [microsoftgraph/microsoft-graph-explorer-v4#2955]
**Describe the bug**
`whatin` requests that result in a `400` don't have the response body displayed

**To Reproduce**
1. Navigate to graph explorer [here](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24expand%3Dcalendar%26whatin&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com)
2. Submit the request
3. Observe that there is no response body in the lower panel
4. Submit a request to `https://graph.microsoft.com/v1.0/users?$expand=calendar&whatin` using postman and the accesstoken copied from graph explorer
5. Observe that a response body is provided by graph

**Expected behavior**
1. Navigate to graph explorer [here](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24expand%3Dcalendar%26whatin&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com)
2. Submit the request
3. The same response body view in postman above is displayed in the lower panel of graph explorer

**Screenshots**
Response from graph explorer:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/16618938/608b5ddc-d1fa-48e2-b757-91ca6ad85e7f)

Response from postman:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/16618938/fd3c5e0c-5fca-47dc-a2dd-66d18080ba45)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: edge

**Smartphone (please complete the following information):**
 - Version: 120.0.2210.121

**Comment by thewahome** [comment]
@corranrogue9 this was resolved. Kindly confirm whether it works for you
