### ISSUE TITLE
MS Booking - create a booking 500 error

### ISSUE THREAD

**Issue by Kovinis** [microsoftgraph/microsoft-graph-explorer-v4#2957]
**Describe the bug**
Trying to create a new booking and it's returning the 500 Internal Error.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'Resources'
3. Scroll down to 'Solutions -> BookingBusiness'
4. Add the body -> {
    "displayName": "Fourth Coffee"
}
5. Run the query

**Expected behavior**
The call creates the booking.

**Screenshots**
<img width="1542" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/17912549/6a38fa4c-691d-4b5f-8193-a64cffcc0063">

**Additional context**
The logged-in user has the Exchange Online and MS F3 license.

**Comment by ElinorW** [comment]
Hi @Kovinis, 
Could you try this again and confirm if the error is still there? 
Do you have the **Bookings.Manage.All** permission consented?
I'm unable to reproduce this as the booking is successfully created on my end

**Comment by Kovinis** [comment]
Hey @ElinorW ,

from the AZURE I could see this:
<img width="1268" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/17912549/8488c331-1679-42ff-b0d1-40b58932b84c">

In the User consent, there are no records. Do I need to add any users to this?

**Comment by Kovinis** [comment]
Solved. Nothing change from my side, but working 👍  thanks!
