### ISSUE TITLE
Microsoft Graph Permissions CustomDetection.ReadWrite.All - how do I use this? 

### ISSUE THREAD

**Issue by mathurin68** [microsoftgraph/microsoft-graph-explorer-v4#2958]
I'm trying find information on what methods are available on the following Microsoft Graph API Permissions....
CustomDetection.Read.All
CustomDetection.ReadWrite.All
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/5932961/481be177-dd44-4a93-822a-55b4a520cc50)

Anyone have any idea how to use these?   I didn't see anything under the Graph Explorer queries and I didn't see anything in the Microsoft Graph powershell modules. 

Thank you!!

**Comment by thewahome** [comment]
Hi @mathurin68 ,
You could do a quick search using the Permission names in this JSON file:
https://github.com/microsoftgraph/microsoft-graph-devx-content/blob/dev/permissions/new/permissions.json

You'll find the URLs you'd be able to call once you have the permissions

**Comment by mathurin68** [comment]
Fantastic link... thank you so much!!!
