### ISSUE TITLE
Select fields cannot contain a filtered field when querying users in the graph explorer

### ISSUE THREAD

**Issue by dlynes** [microsoftgraph/microsoft-graph-explorer-v4#2964]
**Describe the bug**
It complains about a syntax error at '/any'

**To Reproduce**
1. Copy and paste the following URL into graph explorer:
https://graph.microsoft.com/v1.0/users?$select=userPrincipalName,accountEnabled,assignedLicenses&$filter=assignedLicenses/any(u:u/skuId eq fd249f8f-dd6a-48bd-981b-b2478377c7e3)
2. Error "Possible error found in URL near: /any(u" appears, and 'Run query' button is disabled
3. Remove ',assignedLicenses'
4. 'Run query' re-enables itself
5. Re-run the query
6. Works fine
7. Type in ',assignedLicenses' after ',accountEnabled' and before '&$filter='
8. Displays 'Possible error found in URL near: /any(u' again, but 'Run query' button is not disabled
9. Re-run the query
10. Works fine

**Expected behavior**
Should have worked fine the first time without having to go through this hoop.

**Screenshots**
Error can be seen in the attached screenshot.

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - 121.0.6167.85 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - didn't try on smartphone

**Additional context**
No additional context
![Screenshot 2024-01-26 081812](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/840918/68be4570-9df3-4c8a-9c68-a6d1a653b24d)

**Comment by dlynes** [comment]
![Screenshot 2024-01-26 081812](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/840918/52ecbc8b-5eb2-4794-94b2-b1aca53382e2)

**Comment by ElinorW** [comment]
Hey @dlynes , 
this was resolved and the button is no longer disabled
