### ISSUE TITLE
Unable to get Site ID with Site search in graph API

### ISSUE THREAD

**Issue by Manikandhar** [microsoftgraph/microsoft-graph-explorer-v4#2965]
**Describe the bug**
Unable to fetch Site ID from Site sreach in Graph API since three hours. It is happening since three hours. 
If you are deploying any changes to graph api, please let us know through mails. It is annoying when a working functionality suddenly stops working.

I already have consented all required permissions, yet it does not return any value. This was working fine till last three hours

**To Reproduce**
1. Go to 'graph api explorer'
2. Search for a sharepoint site 

**Expected behavior**
A json with Site ID information should be returned.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/7301506/a3fbe8bf-e4e7-459e-9827-caa3bb1f4be6)
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/7301506/533918c8-5720-44bd-af99-43dc464c6224)

What is the issue?
Our client applications have stopped working because of this issue.
I need answer as soon as possible.

**Comment by ElinorW** [comment]
Hi @Manikandhar,
Could you confirm if you are still experiencing this issue?

**Comment by Manikandhar** [comment]
Hi @ElinorW ,
I am getting partial data. I have three site collections, but Graph API is returning only one site collection.
Even with individual name search, am not getting any information.

Why is this happening? Are there any changes happening on Microsoft end? 
This behavior of API is really annoying as our logic purely depends on fetching information from Graph API (site collection id) based on site collection name, as you can see in the screen shot provided above.

Please let us know what is the issue? and when can it be resolved.

**Comment by ElinorW** [comment]
Hi @Manikandhar, 
This must be a problem with the API. I'm not sure if something changed or why you are only getting partial data. 
A different team works on the Sharepoint API. Please post this issue here https://learn.microsoft.com/en-us/answers/tags/161/ms-graph then the appropriate team can reach out and help you
