### ISSUE TITLE
Authentication fails 

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/microsoft-graph-explorer-v4#2972]
When using sample account and trying to login to use GE, the authentication fails and returns an error. Upon retry, the login works. 

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/9458079/99218690-8130-401a-9b80-d4820d93cf0b)

**Metrics on scope of affected users:**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/9458079/e0f7e0a9-a343-4568-a862-ccf815daeab4)

**Comment by ElinorW** [comment]
related to #2967

**Comment by adhiambovivian** [comment]
@ElinorW  is this a regressive bug?

**Comment by adhiambovivian** [comment]
@ElinorW  this was fixed with the msal upgrade?

**Comment by ElinorW** [comment]
Yeah the numbers seem to have dropped... but I'm still monitoring it

**Comment by adhiambovivian** [comment]
Resolved by upgrading MSAL package
