### ISSUE TITLE
Adding possibility to get shared mailbox's members

### ISSUE THREAD

**Issue by adstechnic** [microsoftgraph/microsoft-graph-explorer-v4#2993]
Adding member's list of a shared mailbox in "/beta/users/sharedmailbox@domain.com" URL

**Comment by thewahome** [comment]
Hello @adstechnic 
Thanks for reaching out to us. Could you add a bit more detail so that we know where we can help?

**Comment by adstechnic** [comment]
Hello, sorry to be late.
On O365 Graph API, it's not possible to see members of a shared mailbox using the URL "/beta/users/sharedmailbox@domain.com".

**Comment by thewahome** [comment]
It's likely you'd need to ask the question on the API side
