### ISSUE TITLE
Federated login to graph-explorer website is failing to complete

### ISSUE THREAD

**Issue by buckley-john** [microsoftgraph/microsoft-graph-explorer-v4#2997]
Having issues logging into graph-explorer website as the authentication flow never finishes 

1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer 
2. Click on the user icon to login
3. New browser window opens to enter login information
4. Enter username/password/mfa
5. Login window refreshes and loads the website https://developer.microsoft.com.mcas.ms/en-us/
6. No information is passed back to the original browser window for https://developer.microsoft.com/en-us/graph/graph-explorer
7. If you close the window with the website https://developer.microsoft.com.mcas.ms/en-us/ you are presented this error on the Graph Explorer window
```
Authentication failed - user cancelled
Tip - Please wait for the authentication process to finish.
```
Have replicated this behaviour on Windows/MacOS using Edge/Chrome/Firefox/Safari latest versions

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
@buckley-john do you still experience this? 
Fixes related to authentication were in this release: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/releases/tag/v9.6.0
