### ISSUE TITLE
Page goes blank when showing all permissions after opening modify permissions tab

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#2999]
**Describe the bug**
Once a user checks the permissions using the modify permissions tab and there are no permissions to display, they are directed to open the permissions panel via a link on the tab. 

This causes the page to crash and is no longer visible

**To Reproduce**
1. Go to [developer.microsoft.com](https://developer.microsoft.com/en-us/graph/graph-explorer)
2. On the samples search, type goals and pick the first sample available. 
3. Open the modify permissions tab, and follow the instructions to open the panel

**Expected behavior**
The permisssions panel should be available and the page should not crash

**Comment by craftzneko** [comment]
@thewahome Has this been resolved as i am having the same issue when trying to access this new graph reports https://graph.microsoft.com/beta/reports/azureADPremiumLicenseInsight. Directed to open permissions panel which then crashes the page to white 
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/662108/c2e6f3a3-db3b-4404-b689-8c83466aeaff)

**Comment by thewahome** [comment]
@craftzneko it still hasn't been released yet. We are working on the next release

**Comment by RachanaW** [comment]
@thewahome Please can you provide an ETA on the release date? Thank you.

**Comment by thewahome** [comment]
Hey @craftzneko and @RachanaW 
This is fixed now

**Comment by thewahome** [comment]
Hello @RachanaW and @craftzneko 
The release is out now for this

**Comment by RachanaW** [comment]
Thank you for confirming  Appreciate your help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
