### ISSUE TITLE
preferredSingleSignOnMode query only showing SAML apps

### ISSUE THREAD

**Issue by joleeds** [microsoftgraph/microsoft-graph-explorer-v4#3001]
**Describe the bug**
Running a query that should return all preferredSingleSignOnMode types except saml. Results only returning null for applications. I've verified this is incorrect by looking at applications in Entra and found some that are using OIDC. 

**To Reproduce**
1. Go to Microsoft Graph explorer
2. Query https://graph.microsoft.com/v1.0/servicePrincipals?$select=appDisplayName,preferredSingleSignOnMode&$count=true&$top=999
4. Add consistancylevel : eventual header
5. All entrprise apps are returned, only saml or null shown as "preferredSingleSignOnMode" values

**Expected behavior**
preferredSingleSignOnMode should show saml or OIDC results

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/147419367/e7bd3b22-41f0-490b-aad1-6d2bab04faa9)

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/147419367/644fd66f-3fbd-42c8-907b-d801e0beac23)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 120

**Comment by thewahome** [comment]
Hello @joleeds this is outside the scope of Graph Explorer. The best place for you to get help is here: https://aka.ms/askgraph
