### ISSUE TITLE
Update to Redux 5.x.x

### ISSUE THREAD

**Issue by ElinorW** [microsoftgraph/microsoft-graph-explorer-v4#3007]
**Describe the bug**
This [PR]( https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/2975) requires the Redux package to be update to v5.

This is a major update with breaking changes 

** Associated changes **
- [x] #3190
- [x] #3191
- [x] #3192
- [x] #3193
- [x] #3194
- [x] #3195
- [x] #3196
- [x] #3197
- [x] #3198
- [x] #3199
- [x] #3200
- [x] #3201
- [x] #3202
- [x] #3203
- [x] #3204
- [x] #3205
- [x] #3206
- [x] #3207
- [x] #3208
- [x] #3209
- [x] #3210
- [x] #3211
- [x] #3256
- [x] #3259
- [x] #3260
- [x] #3265

**Comment by musale** [comment]
@microsoftgraph/microsoft-graph-explorer-v4-write all tasks are done here 🥳 We would appreciate thorough testing before merging to the main PR.
