### ISSUE TITLE
Cannot Unconsent to a permission

### ISSUE THREAD

**Issue by rlwjr7212** [microsoftgraph/microsoft-graph-explorer-v4#3010]
**Describe the bug**
I was using the mail request to list subject and sender of my email account using
https://graph.microsoft.com/v1.0/me/messages?$filter=importance eq 'high'

**To Reproduce**
I used the modify permission to allow mail basic read and executed the request.  All went as expected.  Then I tried to unconsent to the permission and I couldn't unconsent was inactive and could not be selected

**Expected behavior**
I expected to be able to select the unconsent and for the permission to be revoked on next attempt.

**Screenshots**

**Desktop (please complete the following information):**

 - Browser Edge Version 121.0.2277.128 (Official build) (x86_64)

**Additional context**

**Comment by thewahome** [comment]
Hello @rlwjr7212 
To unconsent to a permission you'd need to consent to two additional permissions:
- Directory.Read.All
- DelegatedPermissionGrant.ReadWrite.All
Once done, the unconsent button will be active.
