### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by SzyBar123** [microsoftgraph/microsoft-graph-explorer-v4#3012]
Hi, I have a problem with requests from the application to the API.
I'm getting error 500. Requests in Graph Explorer is working.
Request to https://graph.microsoft.com/beta/solutions/bookingBusinesses/{id}/appointments/{id2} is not working 

{error={code=UnknownError, innerError={date=2024-02-20T10:45:51, client-request-id=1711a935-817a-4b75-b7f9-58d4bddfb8bf, request-id=1711a935-817a-4b75-b7f9-58d4bddfb8bf}, message=}}

**Comment by thewahome** [comment]
Hello @SzyBar123 did you change the `{id}` and `{id2}` placeholders with real values?
