### ISSUE TITLE
userPrincipleName empty in GET my profile request

### ISSUE THREAD

**Issue by shireenLan** [microsoftgraph/microsoft-graph-explorer-v4#3013]
![userPrincipleName_empty](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/160703424/d6b679c0-7200-4a1c-ba51-a4c6cb5be273)
# Bug Report

## Prerequisites

-   [ Y] Can you reproduce the problem?
-   [ Y] Are you running the latest version?
-   [ Y] Are you reporting to the correct repository?
-   [ Y] Did you perform a cursory search?

## Description

[Description of the bug or feature]

- Since a few weeks ago, the `userPrincipleName` field is always empty in the GET my profile request response.
- This occurs in the graph explorer (see screenshot) or when using the graph SDK in javascript.
- I have logged out and back in and nothing fixes it.
- The `mail` field is not empty though.
- I don't have this issue with my other microsoft accounts.

## Steps to Reproduce

1. Sign into shireenlannister.98@gmail.com.
2. Perform a `GET my profile` request on the graph explorer.

**Expected behavior:** [What you expected to happen]

The `userPrincipleName` field should contain "shireenlannister.98@gmail.com".

**Actual behavior:** [What actually happened]

The `userPrincipleName` is empty.

## Additional Context

I have searched the internet and this shouldn't occur. For example, [this post](https://learn.microsoft.com/en-us/answers/questions/1109943/will-graph-list-user-api-return-users-with-empty-u).

I don't think this is necessarily a problem with the graph explorer since it occurs when using the graph SDK in javascript. But it is most easily reproduced here, so that's why I am putting this issue here.

## Usage Information
```
{
    "client-request-id": "9b2b64a2-9bd0-cb07-2797-4d8978371746",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "0ef42f0c-8f3e-4aad-84a3-7628c6efc066"
}
```

**Comment by ElinorW** [comment]
Hi @shireenLan 
Is the userPrincipalName still returning an empty value?

**Comment by shireenLan** [comment]
Hello thanks for getting back to me.

`userPrincipalName` is still empty and in addition, the `mail` field is now empty too.
![no_mail_no_userPrincipleName](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/160703424/d2a78d3b-27b4-4e64-b94c-448544cabe25)

**Comment by ElinorW** [comment]
@shireenLan This might be an issue with the API.
Could you please post this on the  [Graph Q&A forum](https://aka.ms/askgraph), the appropriate team will be able to help out.

**Comment by shireenLan** [comment]
Done: https://learn.microsoft.com/en-us/answers/questions/1607356/userprinciplename-empty-in-get-my-profile-request

**Comment by shireenLan** [comment]
Hello, I have not received any response on https://learn.microsoft.com/en-us/answers/questions/1607356/userprinciplename-empty-in-get-my-profile-request. Is there somewhere else I can ask?
Thanks!
