### ISSUE TITLE
Online Graph Explorer rejects parameters

### ISSUE THREAD

**Issue by UTSAGrad** [microsoftgraph/microsoft-graph-explorer-v4#3017]
**Describe the bug**
Microsoft Graph Explorer does not accept query parameters.

**To Reproduce**
1. Go to '(https://developer.microsoft.com/en-us/graph/graph-explorer/)'
2. Logon to your office 365 tenant account
3. Enter query https://graph.microsoft.com/v1.0/me/drives
4. Run the query
5. Copy the id from the values 
6. Enter query https://graph.microsoft.com/v1.0/me/drives/{drive-id}
7. Under request header add a key value of drive-id and the id from step 5
8. Run query
9. Query errors out with        "code": "invalidRequest",
        "message": "The provided drive id appears to be malformed, or does not represent a valid drive.",

**Expected behavior**
The query should provide information for the drive-id specified.  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [edge]
 - Version [Version 122.0.2365.52 (Official build) (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**
This feature used to work but it is stopping me from completing my work.

**Comment by ElinorW** [comment]
Hi @UTSAGrad, 
The drive id should be replaced within the query instead and not added as a request header.
For example, if the drive id is 1234567890, the query would be https://graph.microsoft.com/v1.0/me/drives/1234567890
