### ISSUE TITLE
Planner Tasks Error 403: Insufficient Permissions 

### ISSUE THREAD

**Issue by crknox6** [microsoftgraph/microsoft-graph-explorer-v4#3022]
**Describe the bug**
When attempting to get all tasks assigned to a user in Planner, I receive an error "403 Either the signed-in user does not have sufficient privileges, or you need to consent to one of the permissions on the Modify permissions tab"

**To Reproduce**
1. Sign into Global admin account within Graph
2. Run query GET v1.0 https://graph.microsoft.com/v1.0/users/{coworker-mail}/planner/tasks

**Expected behavior**
List all tasks that are assigned to user list in query. Currently only works when querying my own assigned tasks in Planner. 

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/137321309/d687ddfe-d203-4842-865d-84e658245e8a)

**Desktop (please complete the following information):**
 - OS: Windows 11 Business [23H2, v22631.3155]
 - Browser: Microsoft Edge
 - Version 122.0.2365.59 

**Additional context**
All permissions have been granted within the Enterprise applications registration in the Azure Portal.

**Comment by ElinorW** [comment]
Hi @crknox6,
This is a problem with the Planner API. 
Please post this on the [Graph Q&A](https://aka.ms/askgraph) forum where the appropriate team will be able to provide further assistance.
