### ISSUE TITLE
Move mail from mailboxto shared mailbox

### ISSUE THREAD

**Issue by adstechnic** [microsoftgraph/microsoft-graph-explorer-v4#3042]
Hello !

Is it possible to add a feature in order to allow moving mails from a mailbox's folder to another mailbox's folder.

For example : I'd like to move some mails from one user's mailbox into his shared mailbox

I don't know if there is a way to add a feature to the POST request with URL /beta/users/id/messages/id/move ?

Thanks a lot and have a nice day !

Paul.

**Comment by ElinorW** [comment]
Hi @adstechnic,
You should be able to do this.
I think this documentation should help: https://learn.microsoft.com/en-us/graph/api/message-move?view=graph-rest-1.0&tabs=http
