### ISSUE TITLE
Querying SharePoint Library files to Apply retention label 

### ISSUE THREAD

**Issue by MuthurajC** [microsoftgraph/microsoft-graph-explorer-v4#3047]
var driveitems = await GraphClient.Drives[$"{driveid}"].Items.GetAsync(); code throw exception {"The 'filter' query option must be provided."} | Microsoft.Graph.Models.ODataErrors.ODataError same exception in Graph explorer as well

**Comment by MuthurajC** [comment]
https://graph.microsoft.com/v1.0/drives/b!cgdf08eYmE64fxjNVaz5as7J36-7MRhIk44qW4OiXEsJF9oWkc8XSKLaESd6v6OY/items
Query
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/120944748/0ff23d9a-d9b5-49a1-94f4-1f3fa5b38a87)

**Comment by ElinorW** [comment]
Hi @MuthurajC,
To query drive items, use the children endpoint. 
`GET /me/drive/root/children` 
If this doesn't provide the solution you need, please raise the issue in the [Graph Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) where the team handling the API will be able to help you
