### ISSUE TITLE
Private preview API accidentally published as GE sample query 

### ISSUE THREAD

**Issue by jessicaaawu** [microsoftgraph/microsoft-graph-explorer-v4#3051]
**Describe the bug**
GE has accidentally published the Search grounding API, even though the API isn't available beyond private preview (see screenshot below).

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Search "grounding"
3. Click on POST (beta) search grounding

**Expected behavior**
A private preview API should not have a GE sample query published publicly.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/56090713/41dc17ca-71a7-4b98-aefe-7fb6fb6a7cf7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 
**Need to do:**

1. Have this private preview sample query removed from GE.
2. Can you tell me more about the process of how a sample query is added onto GE? Please describe this process in detail, as I'd like to understand what the gap was that allowed this to happen.

**Comment by thewahome** [comment]
This has been fixed at source here: https://github.com/microsoftgraph/microsoft-graph-devx-content/pull/534
