### ISSUE TITLE
Microsoft Explorer is not working as it should

### ISSUE THREAD

**Issue by DiegoMirmir** [microsoftgraph/microsoft-graph-explorer-v4#3065]
**Describe the bug**
The "beta" option of the Microsoft Explorer is not properly working, as when trying to find any user using the email, it doesn't give me back any result. Even when I search on the Me tab, I get the results of another user, not myself.

**To Reproduce**
1. Open the Microsoft Graph Explorer
2. try to use the User> EmailAdress option
3. Change the search options from V1.0 to Beta
4. Search for an email. It won't find the user.

**Expected behavior**
It should find the users and give back their attributes

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Version: 122.0.2365.52

**Comment by ElinorW** [comment]
Hi @DiegoMirmir, 
Please share an example of the query you are trying to run

**Comment by DiegoMirmir** [comment]
CONFIDENCIALIDAD: La informaci?n contenida en este mensaje es confidencial y para uso exclusivo del destinatario. Si ha recibido este mensaje por error, le agradeceremos nos lo indique y proceda a su eliminaci?n.
CONFIDENTIALITY: The information contained in this message is confidential and for the exclusive use of its addressee. If you have received this message in error, please notify us and delete it from your system.
Hello, this is an example with my own email:
***@***.***

De: Elinor ***@***.***>
Enviado el: Tuesday, March 26, 2024 12:10 PM
Para: microsoftgraph/microsoft-graph-explorer-v4 ***@***.***>
CC: Mir Mir,Diego,ES-Esplugues Llobregat ***@***.***>; Mention ***@***.***>
Asunto: Re: [microsoftgraph/microsoft-graph-explorer-v4] Microsoft Explorer is not working as it should (Issue #3065)

This message is from an EXTERNAL SENDER. BE CAUTIOUS, particularly with links and attachments.
________________________________

Hi @DiegoMirmir<https://github.com/DiegoMirmir>,
Please share an example of the query you are trying to run

-

**Comment by ElinorW** [comment]
@DiegoMirmir, 
please share the complete query that you're trying to run

**Comment by DiegoMirmir** [comment]
CONFIDENCIALIDAD: La informaci?n contenida en este mensaje es confidencial y para uso exclusivo del destinatario. Si ha recibido este mensaje por error, le agradeceremos nos lo indique y proceda a su eliminaci?n.
CONFIDENTIALITY: The information contained in this message is confidential and for the exclusive use of its addressee. If you have received this message in error, please notify us and delete it from your system.
Hello Elinor,

I am not sure If I am understanding correctly, as the query is on the screenshot, however this is the query: ***@***.***

Best Regards

De: Elinor ***@***.***>
Enviado el: Tuesday, March 26, 2024 1:25 PM
Para: microsoftgraph/microsoft-graph-explorer-v4 ***@***.***>
CC: Mir Mir,Diego,ES-Esplugues Llobregat ***@***.***>; Mention ***@***.***>
Asunto: Re: [microsoftgraph/microsoft-graph-explorer-v4] Microsoft Explorer is not working as it should (Issue #3065)

This message is from an EXTERNAL SENDER. BE CAUTIOUS, particularly with links and attachments.
________________________________

@DiegoMirmir<https://github.com/DiegoMirmir>,
please share the complete query that you're trying to run

-

**Comment by ElinorW** [comment]
Hi @DiegoMirmir ,
I can't access the screenshot

**Comment by DiegoMirmir** [comment]
CONFIDENCIALIDAD: La información contenida en este mensaje es confidencial y para uso exclusivo del destinatario. Si ha recibido este mensaje por error, le agradeceremos nos lo indique y proceda a su eliminación.
CONFIDENTIALITY: The information contained in this message is confidential and for the exclusive use of its addressee. If you have received this message in error, please notify us and delete it from your system.
Hello,

You can close this ticket.

Best Regards

Diego Mir-mir López  [Forma  Descripción generada automáticamente con confianza baja] <https://nestle.workplace.com/profile.php?id=100073511454687>
Technology Specialist - Digital Adoption | Workforce 360
Nestlé Global IT Hub Barcelona

[Nestlé logo for signature]

[image]
WalkMe 9-5 - Now accepting submissions for the first
Digital Adoption Hackathon in Nestlé!
Learn more!<https://nestle.sharepoint.com/teams/DigitalAdoptionSolutionswithWalkMe/SitePages/WalkMe9-5.aspx>


De: Elinor ***@***.***>
Enviado el: Thursday, April 4, 2024 7:26 PM
Para: microsoftgraph/microsoft-graph-explorer-v4 ***@***.***>
CC: Mir Mir,Diego,ES-Esplugues Llobregat ***@***.***>; Mention ***@***.***>
Asunto: Re: [microsoftgraph/microsoft-graph-explorer-v4] Microsoft Explorer is not working as it should (Issue #3065)

This message is from an EXTERNAL SENDER. BE CAUTIOUS, particularly with links and attachments.
________________________________

Hi @DiegoMirmir<https://github.com/DiegoMirmir> ,
I can't access the screenshot

-

**Comment by ElinorW** [comment]
Okay great!
