### ISSUE TITLE
GE crashes when attempting to get the /$metadata

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/microsoft-graph-explorer-v4#3068]
**Describe the bug**
When attemtpting to call the /$metadata endpoint, GE seems to assume that's an invalid URL and crashes.

**To Reproduce**
Attempt to call https://graph.microsoft.com/v1.0/$metadata or https://graph.microsoft.com/beta/$metadata

**Expected behavior**
- GE to understand the $metadata endpoint.
- For invalid URLs, GE to throw an invalid URL error instead of crashing.

**Screenshots**
![GE-metadata](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/14026935/1bf8865c-bdfb-4f18-8cd0-3b9622ea0eec)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Additional context**
N/A

**Comment by ElinorW** [comment]
Hi @FaithOmbongi , 
This has been resolved in #3062 and is awaiting deployment
