### ISSUE TITLE
"Cannot set the presence of another user" by using the Presence GraphAPI - changing the presence of another user

### ISSUE THREAD

**Issue by N3XPW** [microsoftgraph/microsoft-graph-explorer-v4#3096]
**Describe the bug**
By using the grapAPI with the presence statusmessage function, i get the following error:
"Cannot set the presence of another user... Status: 401 Unauthorized"

I tried this with the graphapi over 
https://developer.microsoft.com/en-us/graph/graph-explorer 
and with the 
Microsoft.Graph.Users.Actions 
Powershell Module.

For both with my admin user that has the required consensts . (Presence.ReadWrite)

**To Reproduce in Powershell**
`Import-Module ActiveDirectory
Import-Module Microsoft.Graph.Authentication
Import-Module Microsoft.Graph.Users
Connect-MgGraph Presence.ReadWrite

$params = @{
    statusMessage = @{
        message        = @{
            content     = "Hey, this is a test"
            contentType = "text"
        }
        expiryDateTime = @{
            dateTime = "2024-04-02T20:05:33.2079781"
            timezone = "Europe/Berlin"
        }
    }
}
Set-MgUserPresenceStatusMessage -UserId "UserID" -BodyParameter $params
Disconnect-MgGraph`

**To Reproduce in the graphAPI**
`url: https://graph.microsoft.com/v1.0/users/[UserID]/presence/setStatusMessage
Body:
{
    "statusMessage": {
        "message": {
            "content": "Hey, this is a test",
            "contentType": "text"
        }
    }
}`

**Expected behavior**
Chaning the statusmsg in teams

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/54949122/abec1873-5530-4028-b5ad-1a820425469a)

**Comment by ElinorW** [comment]
Hi @N3XPW , this is likely an issue with the Presence API.
Please post this on the Graph Q&A forum where the appropriate team will be able to help you out.
