### ISSUE TITLE
When I enter "https://graph.microsoft.com/v1.0/oauth2PermissionGrants" in the URL for running query, app fails

### ISSUE THREAD

**Issue by chamric** [microsoftgraph/microsoft-graph-explorer-v4#3098]
**Describe the bug**
I go to aka.ms/ge
I enter  https://graph.microsoft.com/v1.0/oauth2PermissionGrants as the url
graph app disappears

**To Reproduce**
I go to aka.ms/ge
I enter  https://graph.microsoft.com/v1.0/oauth2PermissionGrants as the url

**Expected behavior**

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/46796859/df67d457-a4c3-441b-9102-a5d9f150a69f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ElinorW** [comment]
resolved now
