### ISSUE TITLE
Filter for EntraID groups combined with endswith and attribute description is nor working

### ISSUE THREAD

**Issue by HIRSCHDBASF** [microsoftgraph/microsoft-graph-explorer-v4#3101]
**Describe the bug**
Trying to get all groups which endswith "UNINSTALL" as description is not working:
https://graph.microsoft.com/beta/groups?$filter=endsWith(displayName,'uninstall')&$count=true

This will result in an error:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/164996599/9e64af83-0777-4f5c-b07d-de2a7051a625)

Mentioned is the way here:
https://learn.microsoft.com/en-us/graph/filter-query-parameter

**To Reproduce**
1. Go to graph
2. Add url
3. Add neaded header infos
4. Run

**Expected behavior**
As output only groups with the search parameter as ending should be visible.

**Comment by ElinorW** [comment]
Hi @HIRSCHDBASF , 
This is an issue with the Groups API.
Please post this on the Graph Q&A channel where the appropriate team will be able to assist you
