### ISSUE TITLE
Cannot select oauth2PermissionGrants in URL

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-explorer-v4#3105]
**Describe the bug**
I'm trying to select oauth2PermissionGrants. When I try to select oauth2PermissionGrants from autocomplete or simply copy/paste, the whole app crashed and it's restarted.

**To Reproduce**
1. Try select oauth2PermissionGrants endpoint

**Expected behavior**
The Graph Explorer not crashing

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ElinorW** [comment]
Hi @MartinM85, 
This has been resolved and the fix shall be available by next week 

duplicate of #3048
