### ISSUE TITLE
engage communities endpoint returning 400 bad request

### ISSUE THREAD

**Issue by sellarsm1** [microsoftgraph/microsoft-graph-explorer-v4#3106]
**Describe the bug**
requests to https://graph.microsoft.com/beta/employeeExperience/communities/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiIyMDIxMzQ1Njg5NiJ9 result in 400 bad request

**To Reproduce**
1. Go to 'graph explorer'
2. enter https://graph.microsoft.com/beta/employeeExperience/communities/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiIyMDIxMzQ1Njg5NiJ9
3. click run report
4. See error 400 bad response

**Expected behavior**
get viva engage community properties, including the mapped entraID objectID of the communities unified group

**Screenshots**

**Desktop (please complete the following information):**

 

**Additional context**

**Comment by ElinorW** [comment]
Hi @sellarsm1, this seems to be an issue with the API. 
Please post this on the Graph Q&A forum shared below.
