### ISSUE TITLE
Issue with filter on managerDevices

### ISSUE THREAD

**Issue by derekb519** [microsoftgraph/microsoft-graph-explorer-v4#3125]
When attemption to use a filter for the 'userId' property on https://graph.microsoft.com/v1.0/deviceManagement/managedDevices, it is returns ALL managed devices and disregarding the filter.

**To Reproduce**

- Find the userId of an Entra User.
- Issue is present using both 1.0 and Beta endpoints, select either one.
- Goto Graph Explorer, do a GET for https://graph.microsoft.com/v1.0/deviceManagement/managedDevices?$filter=userId eq '66903bee-b442-40c1-8629-xxxxxxxxxx', with your valid userId.
- Results in the 'Response preview' return ALL managed devices for ALL users, completely ignoring the userId filter.
- Filter works correctly for other properties, such as operatingSystem.

**Expected behavior**
I would expect either the filter be honoured as described above, or simply return an error if filtering by userId is not supported.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Any
 - Browser [e.g. chrome, safari]: Any
 - Version [e.g. 22]: Any

**Comment by derekb519** [comment]
This issue can also be seen here:
https://learn.microsoft.com/en-us/answers/questions/934936/microsoft-graph-filtering-managed-devices-by-wifim

I have a ticket open with Microsoft but no helpful responses as of this time.

**Comment by thewahome** [comment]
@derekb519 it is likely filter is not supported on this endpoint
