### ISSUE TITLE
get "Service Unavailable - 503" error when I use https://graph.microsoft.com/v1.0/me/messages API

### ISSUE THREAD

**Issue by Alan815** [microsoftgraph/microsoft-graph-explorer-v4#3143]
**Describe the bug**
First, I loged in with microsoft account, so I have access token already
then when I try to use https://graph.microsoft.com/v1.0/me/messages API, I got "Service Unavailable - 503"  error
I have Mail.Read permission already
and I tried https://graph.microsoft.com/v1.0/me API, works fine

error json:
{
    "error": {
        "code": "MailboxInfoStale",
        "message": "Target resource '00030000-ca28-936b-0000-000000000000' hosted on database '8d02d25d-52fe-4702-86ee-78bc22716108' is currently on backend 'Unknown'"
    }
}

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser Chrome
 - Chrome Version 124.0.6367.91

**Comment by thewahome** [comment]
@Alan815 this is likely an intermittent issue with the API should it happen again, please raise it here:
