### ISSUE TITLE
Service Principal - Remove keyCredential 403

### ISSUE THREAD

**Issue by Daniel-SW** [microsoftgraph/microsoft-graph-explorer-v4#3145]
**Describe the bug**
'v1.0/servicePrincipals/{servicePrincipal-id}/removeKey' does not seem to work. No combination of request body or permissions on Graph Explorer help.

**Prerequisites**
- keyCredential and passwordCredential were setup following [Configure a custom signing key](https://learn.microsoft.com/en-us/entra/identity-platform/jwt-claims-customization#configure-a-custom-signing-key).
- The correct Permissions are given delegated and with admin consent as described in 'Modify Permissions'.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Enter POST, 'https://graph.microsoft.com/v1.0/servicePrincipals/{servicePrincipal-id}/removeKey'
3. Add correct SP ID
5. Add a payload, such as [example](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-removekey?view=graph-rest-1.0&tabs=http#request)
 ```
{
    "keyId": "f0b0b335-1d71-4883-8f98-567911bfdca6",
    "proof":"eyJ0eXAiOiJ..."
}
```
7. All attempts and combinations return a 'Forbidden - 403'

**Expected behavior**
The request completes with a 204 or some more specific error describing what is missing/wrong.

**Additional context**
Additionally attempting to remove the passwordCredentail associated with the keyCredential results in a 500 error.

I see there is also a PowerShell command [Remove-AzureADServicePrincipalKeyCredential](https://learn.microsoft.com/en-us/powershell/module/azuread/remove-azureadserviceprincipalkeycredential?view=azureadps-2.0), maybe this would work, it does not require a 'proof'.

**Comment by thewahome** [comment]
Since the call was successful but the results are unclear, it is likely an issue with the API. Please feel free to contact support
