### ISSUE TITLE
Graph Explorer does not return Json formatted output

### ISSUE THREAD

**Issue by CarlosGuadamuz** [microsoftgraph/microsoft-graph-explorer-v4#3158]
**Describe the bug**

Graph Explorer is not returning Json formatted output. 
Endpoints being tested so far:
https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=* 
https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=appDefinitions
The same API works as expected if I pull Teams Apps information from other tenants.
My assumption is that this could be because the amount of information returned may varies. But I’m not sure.

**To Reproduce**
1. Go to (https://developer.microsoft.com/en-us/graph/graph-explorer)
GET 

https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=* 
https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=appDefinitions

4. I get a 200 OK response.
5. The output is not easy to read because it is not Json formated.

**Expected behavior**
The output being returned in Json format.

**Comment by musale** [comment]
@CarlosGuadamuz I can't reproduce this on my end:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/8081536/c7e7039b-593d-4786-8122-d58c63579f9d)


What kiind of unformatted json are you getting?

**Comment by musale** [comment]
@CarlosGuadamuz on tyring this endpoint `https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?$expand=*` I can reproduce this:

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/8081536/5489be5e-a69f-42cb-a111-41647e51ca13)

**Comment by adhiambovivian** [comment]
@musale  We were able to repro the issue internally and it's mostly affecting the anonymous experience.
