### ISSUE TITLE
Calling principal does not have required MSGraph permissions AuditLog.Read.All

### ISSUE THREAD

**Issue by mlakas01** [microsoftgraph/microsoft-graph-explorer-v4#3165]
**Describe the bug**
I am running an API using azure's API-driven provisioning to on-premises Active Directory.
After running the API using curl and verifying the user has been created in on premise AD, I want to read the api call's response using MS Graph.

Once I run the query such as:
 https://graph.microsoft.com/v1.0/auditLogs/provisioning?$filter=(contains(changeId,'d93a226c-4cea-43f5-ae6f-b40a1e1e5973')%20and%20(jobId%20eq%20'API2AD.42bee3df98534f9ab52933f3156060a0.285a406e-bc9a-4f37-b7f9-91bc3b65c333'))

It shows the below error
"error": {
        "code": "Authentication_MSGraphPermissionMissing",
        "message": "Calling principal does not have required MSGraph permissions AuditLog.Read.All",
        "innerError": {

I then Consent to AuditLog.Read.All permission and request Admin to provide this access, 

Graph Explorer access request approved
Your request has been approved. Details of your request are below.

WHAT ARE THE ROLES THAT ARE REQUIRED.
This will help request exactly what's needed.

**Screenshots**
![Screenshot 2024-05-31 121719](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/171326916/88ea4659-0ee0-4d0c-a5ad-3a92993ab40e)

**Desktop **
 - OS: Windows
 - Browser Edge
 - Version

**Comment by musale** [comment]
@mlakas01 what is the issue here?
