### ISSUE TITLE
Graph Explorer Events API is not considering $isOnlineMeeting filter

### ISSUE THREAD

**Issue by PraveenPatelG** [microsoftgraph/microsoft-graph-explorer-v4#3188]
**Describe the bug**
Even after applying isOnlineMeeting filter to return only online meetings, the API response contains events which has online meeting is 'false'!!

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Copy Paste https://graph.microsoft.com/v1.0/me/events?$isOnlineMeeting eq 'true'
3. Scroll down to API 'Response Preview' tab
4. You will see events which have isOnlineMeeting is 'False'

**Expected behavior**
Events API response should consider the isOnlineMeeting filter.

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/18389413/f0d90244-a4f9-46fe-bf95-10e61c19882d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge, Chrome
 - Version Edge 125.0.2535.92, Chrome 125.0.6422.142

**Comment by musale** [comment]
hello @PraveenPatelG I tried running this query with the `$filter` parameter and I got this error:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/8081536/ad0f5158-8b99-4072-a86c-9d7b1d590327)

In such a scenario, this becomes a service issue which we don't handle on GE. You can escalate the issue on https://aka.ms/askgraph.
