### ISSUE TITLE
Wrong documentation links for some methods 

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#321]
**Describe the bug**
The link to documentation for Create Chat Query is wrong. It's supposed to be https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http and not  https://docs.microsoft.com/en-us/graph/api/channel-post-chatthreads?view=graph-rest-beta

The link documentation for "Items in Team Drive" query under Microsoft Teams samples should be https://docs.microsoft.com/en-gb/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http

The link for Notifications samples should be https://docs.microsoft.com/en-gb/graph/api/user-post-notifications?view=graph-rest-beta

The link documentation for the "Search items in drive" should be https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http

The link for create a folder in Onedrive should be https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer/preview
2. Click on Microsoft Teams Beta
3. Scroll down to POST - Create chat 
4. Click on documentation link

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4668452/71235999-cf245300-230e-11ea-9e36-e263952b2413.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
This has been handled partially in the local file that stores the queries.
For a more wholesome effect, this should be handled by @irvinesunday in the api he owns

**Comment by bettirosengugi** [comment]
@thewahome avoid closing issues that haven't been resolved for easier tracking. if they are reported on the wrong repo, create an issue in the right repo and reference them on the reported repo with a comment.

**Comment by bettirosengugi** [comment]
Reported here: https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/230

**Comment by bettirosengugi** [comment]
Resolved here: https://github.com/microsoftgraph/microsoft-graph-devx-content/pull/14
