### ISSUE TITLE
subjectRightsRequests - Update (Patch) & Delete is not working (Both Privacy & Security)

### ISSUE THREAD

**Issue by MayankHatsOff** [microsoftgraph/microsoft-graph-explorer-v4#3228]
**Describe the bug**
`{
    "error": {
        "code": "UnknownError",
        "message": "{\"message\":\"No HTTP resource was found that matches the request URI 'https://aedservice-apc02.cloudapp.net/compliance/privacyManagement/dataSubjectRequest('7af04277-68bf-49f4-befe-72f0fb33d0e1')'.\",\"messageDetail\":\"No type was found that matches the controller named 'dataSubjectRequest'.\"}",
        "innerError": {
            "date": "2024-06-24T11:11:19",
            "request-id": "1488e901-67b7-43ee-ab68-07275aad891e",
            "client-request-id": "f441dd6b-871c-dfab-5b99-db607b3b6fca"
        }
    }
}`

**To Reproduce**
1. Go to '[...](https://developer.microsoft.com/en-us/graph/graph-explorer)'
2. Click on 'Resources' & search for subjectRightsRequests
3. Scroll down to 'Patch' or 'Delete' in either "Privacy" or "Security" & try to execute it

**Expected behavior**
It should update / delete the request

**Screenshots**
![Graph Error](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/72543399/7f3df54f-8ece-4a8f-b2eb-f57cc13bed53)

**Comment by ElinorW** [comment]
Hi @MayankHatsOff ,
This is likely an issue with the API. Please create a support ticket here if you are still experiencing this issue: https://developer.microsoft.com/en-us/graph/support
