### ISSUE TITLE
Graph Try-It on MS Learn showing blank screen when activated.

### ISSUE THREAD

**Issue by jupajupajupa** [microsoftgraph/microsoft-graph-explorer-v4#3234]
**Describe the bug**
Graph Explorer is embedded in Microsoft Learn site as a feature via an iFrame next to the code block that users can easily open up and try out the graph explorer for learning purposes. This feature has been in place on MS Learn for a while and we were reported by the partner team that multiple users are facing the same issues with blank screen when activating the Try-It experience. 

**To Reproduce**
1. Go to [Quickstart: configure a restricted user experience with Assigned Access - Configure Windows | Microsoft Learn](https://learn.microsoft.com/en-us/windows/configuration/assigned-access/quickstart-restricted-user-experience?tabs=intune&pivots=windows-11#code-try-1)
2. Click on Try-It on the code block if the iFrame on the right side pane doesn't open automatically.
3. You'll see the blank screen on the right side pane, but you should really see the Graph Explorer experience embedded.
4. See error:
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/105000310/0b5743f2-0da8-49c7-9b8c-fc6997178c58)

**Expected behavior**
User should be given a graph explorer environment opened within iFrame on the right side pane from the screenshot above, this experience is activated when user clicks on "Try-It" button from the code block.

**Screenshots**
attached above.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 126.0.2592.61
 - **Issue was reported in multiple environments with multiple users** 

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by scottbreenmsft** [comment]
Hi @musale is this something you could look into?

**Comment by scottbreenmsft** [comment]
@thewahome will it take a while for this code to be in production? I can still reproduce the issue on this page:

https://learn.microsoft.com/en-us/mem/intune/fundamentals/remote-help-macos?tabs=graph%2Cintune#code-try-0

It loads successfully the first time and then if i close it and try again or reload the page it doesn't work.

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/39719539/9a68dffa-76b9-4bc8-b626-8305708fc78b)

**Comment by thewahome** [comment]
No. Not too long. A new release is going out this week

**Comment by thewahome** [comment]
@scottbreenmsft @jupajupajupa 
These changes are live. This problem should be fixed now
