### ISSUE TITLE
Getting "Forbidden - 403 - 1207 ms. Either the signed-in user does not have sufficient privileges, or you need to consent to one of the permissions on the Modify permissions tab" error for "/admin/sharepoint/settings" API

### ISSUE THREAD

**Issue by BhaveshNakumZymr865** [microsoftgraph/microsoft-graph-explorer-v4#3243]
**Description**
I am trying to access SharePoint tenant settings with "/admin/sharepoint/settings" Graph API. It was working earlier, but now it is giving "Forbidden - 403 - 1207 ms. Either the signed-in user does not have sufficient privileges, or you need to consent to one of the permissions on the Modify permissions tab" error. I have consented to "SharePointTenantSettings.Read.All" permission, but the error still persists.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Call 'https://graph.microsoft.com/v1.0/admin/sharepoint/settings' Graph API with "SharePointTenantSettings.Read.All" permission only.

**Expected behavior**
Response with 200 OK status and data in the response body.
> {
    "value": {
        "@odata.type": "#microsoft.graph.sharepointSettings",
        "allowedDomainGuidsForSyncApp": [
            "bdd1ab9b-3fd0-4def-a761-ec8d7471732c", 
            "ad31vb6b-5zd0-7tyg-m231-kj8d6578432c"
        ],
        "availableManagedPathsForSiteCreation": [
            "/sites/",
            "/teams/"
        ],
        "deletedUserPersonalSiteRetentionPeriodInDays": 344,
        "excludedFileExtensionsForSyncApp": [
            ".md", 
            ".git"
        ],
        "idleSessionSignOut": {
            "isEnabled": true,
            "warnAfterInSeconds": 120,
            "signOutAfterInSeconds": 300
        },
        "imageTaggingOption": "basic",
        "isCommentingOnSitePagesEnabled": true,
        "isFileActivityNotificationEnabled": true,
        "isLegacyAuthProtocolsEnabled": false,
        "isLoopEnabled": true,
        "isMacSyncAppEnabled": false,
        "isRequireAcceptingUserToMatchInvitedUserEnabled": true,
        "isResharingByExternalUsersEnabled": true,
        "isSharePointMobileNotificationEnabled": true,
        "isSharePointNewsfeedEnabled": true,
        "isSiteCreationEnabled": true,
        "isSiteCreationUIEnabled": true,
        "isSitePagesCreationEnabled": true,
        "isSitesStorageLimitAutomatic": true,
        "isSyncButtonHiddenOnPersonalSite": true,
        "isUnmanagedSyncAppForTenantRestricted": true,
        "personalSiteDefaultStorageLimitInMB": 113664,
        "sharingAllowedDomainList" : [
            "contoso.com",
            "fabrikam.com"
        ],
        "sharingBlockedDomainList" : [
            "contoso.com",
            "fabrikam.com"
        ],
        "sharingCapability": "externalUserAndGuestSharing",
        "sharingDomainRestrictionMode": "allowList",
        "siteCreationDefaultManagedPath": "/sites/",
        "siteCreationDefaultStorageLimitInMB": 808034,
        "tenantDefaultTimezone": "(UTC-05:00) Eastern Time (US and Canada)"
    }
}

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/174711812/c60f1916-ca8f-4cde-8767-2c21e42c616b)

**Additional context**
With the exact same permission, it was working 2 weeks back.

**Comment by ElinorW** [comment]
Hi @BhaveshNakumZymr865, 
I have tried running the call and it works as expected, could you confirm if the issue is still present on your end?
