### ISSUE TITLE
504 Gateway Timeout when getting OneNote Section Pages

### ISSUE THREAD

**Issue by anielii** [microsoftgraph/microsoft-graph-explorer-v4#3245]
**Describe the bug**
Starting from 30.06.2024, all my requests to `https://graph.microsoft.com/v1.0/users/{{user}}/onenote/sections/{{section}}/pages` return 504 Gateway Timeout. Below is an example response:

``` HTTP
HTTP/1.1 504 Gateway Timeout
Transfer-Encoding: chunked
Content-Type: application/json
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 1ac33d6c-b299-46c1-863e-56788de0182b
client-request-id: 1ac33d6c-b299-46c1-863e-56788de0182b
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"4","ScaleUnit":"003","RoleInstance":"FR1PEPF000011E4"}}
Date: Fri, 05 Jul 2024 11:55:09 GMT
Connection: close

{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2024-07-05T11:55:09",
      "request-id": "1ac33d6c-b299-46c1-863e-56788de0182b",
      "client-request-id": "1ac33d6c-b299-46c1-863e-56788de0182b"
    }
  }
}
```

I have already tried to limit the response message size by using $top and $select parameters, but this does not resolve the issue. 

This problem did not occur in the past; I was successfully using the endpoint before the previously mentioned date.

**To Reproduce**
1. Issue a request to `GET https://graph.microsoft.com/v1.0/users/{{user}}/onenote/sections/{{section}}/pages`

**Expected behavior**
The response should return 200 status code and a list of section pages.

**Desktop (please complete the following information):**
 - OS: Windows, Android, 

**Other** 
request-id: 1ac33d6c-b299-46c1-863e-56788de0182b
client-request-id: 1ac33d6c-b299-46c1-863e-56788de0182b
Date: Fri, 05 Jul 2024 11:55:09 GMT

**Comment by ElinorW** [comment]
Hi @anielii ,
Could you please confirm if you are still facing this issue?

**Comment by anielii** [comment]
Hi @ElinorW,

Thank you for looking into this.

Yes, the problem is still there.

If you need fresh logs:

``` HTTP
HTTP/1.1 504 Gateway Timeout
Transfer-Encoding: chunked
Content-Type: application/json
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 648b6d15-a983-4e1c-871f-ddf159d2fb3e
client-request-id: 648b6d15-a983-4e1c-871f-ddf159d2fb3e
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"4","ScaleUnit":"002","RoleInstance":"FR3PEPF00000351"}}
Date: Wed, 21 Aug 2024 13:52:40 GMT
Connection: close

{"error":{"code":"UnknownError","message":"","innerError":{"date":"2024-08-21T13:52:40","request-id":"648b6d15-a983-4e1c-871f-ddf159d2fb3e","client-request-id":"648b6d15-a983-4e1c-871f-ddf159d2fb3e"}}}

```

**Comment by ElinorW** [comment]
@anielii 
This is likely an issue with the OneNote API's ...
Please open a support ticket on [Microsoft Graph Support](https://developer.microsoft.com/en-us/graph/support) ,where the appropriate team will be able to help you out
