### ISSUE TITLE
Permission page returns blank

### ISSUE THREAD

**Issue by kenmoritest** [microsoftgraph/microsoft-graph-explorer-v4#3246]
**Describe the bug**
After clicking "Consent to permissions",  blank list is returned.

Request
https://graphexplorerapi.azurewebsites.net/permissions?scopeType=DelegatedWork

Payload
{"StatusCode":400,"Message":"Failed to fetch permissions"}

**To Reproduce**
1. Authenticate User.
2. Click user icon.
3. Click "Consent to permission".

**Expected behavior**
List of permissions are displayed.

**Screenshots**
<img width="449" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/31373382/3d17532a-6079-47f6-a312-a9f6a41d3697">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 126.0.2592.87

**Additional context**

**Comment by thewahome** [comment]
This can be closed now. There was a downtime on the permissions service. Please reopen this issue if it
