### ISSUE TITLE
Unable to Update Multiple Choice/Check Box Columns in SharePoint List Using MSGraph Explorer

### ISSUE THREAD

**Issue by trothe** [microsoftgraph/microsoft-graph-explorer-v4#3247]
**Describe the bug**
I am trying to update a SharePoint List item using the MS Graph API. According to the documentation ([ListItem Update](https://learn.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=http&wt.mc_id=knwlserapi_inproduct_azportal)), the API should support updating all column types. However, updating **Multiple Choice** / **Check Box** columns results in an "Invalid request" error. The documentation does not specify any special requirements for these column types.

**To Reproduce**
1. Go to [Microsoft Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer).
2. Authenticate and ensure the necessary permissions (Sites.ReadWrite.All) are granted.
3. Select "PATCH" method and enter the endpoint: `https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items/{item-id}/fields`
4. Enter the request body containing the multi-choice column name and values:
   ```json
   {
     "Ranby": {
       "results": [
         "Test User 1",
         "Test User 2"
       ]
     }
   }
   ```
5. Click "Run Query".
6. Observe the error response:
   ```json
   {
     "error": {
       "code": "invalidRequest",
       "message": "Invalid request",
       "innerError": {
         "date": "2024-07-08T20:15:57",
         "request-id": "XXXXX",
         "client-request-id": "XXXXX"
       }
     }
   }
   ```

**Expected behavior**
The API should successfully update the multi-choice column values or return a clear and specific error message indicating why the request is invalid. Ideally, the documentation should provide detailed information on how to format the request payload for different column types, including multi-choice columns.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10]
 - Browser [e.g., Chrome 91]
 - Version [e.g., 91.0.4472.124]

**Additional context**
This issue is specific to columns that allow multiple choices (check boxes). Single-choice columns and other types of columns update successfully with the same request format. The lack of detailed error messages makes it difficult to understand the root cause of the issue.

**Comment by ElinorW** [comment]
Hi @trothe, 
This is likely an issue with the SharePoint API's . Please post this on the [Microsoft Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) where the appropriate team will be able to help.
