### ISSUE TITLE
Unable to view Excel worksheets. "General exception while processing"

### ISSUE THREAD

**Issue by eugene-kim** [microsoftgraph/microsoft-graph-explorer-v4#3255]
**Describe the bug**
I'm trying to list worksheets in a workbook in Microsoft Graph Explorer

**To Reproduce**
1. Go https://developer.microsoft.com/en-us/graph/graph-explorer
2. Sign in
3. Grant yourself Files.ReadWrite permissions
4. Make a GET request to: https://graph.microsoft.com/v1.0/me/drive/items/<replace_me>/workbook/worksheets
(update <replace_me> with an excel file you have in your one drive)
5. Get the following response: `Internal Server Error - 500 - 275 ms`
```json
{
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "date": "2024-07-15T14:48:29",
            "request-id": "3b2f22df-944f-48bb-bc64-bb44336bc465",
            "client-request-id": "537a1bbf-21a8-0c28-e514-c618a0b1a509"
        }
    }
}
```

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/df4f9d9a-534d-45cb-9081-bdc6601c4caa)

**Additional context**
I tried to do this via Node and wasn't successful so I looked to get some resolution via the explorer. Received the same response:

```typescript
async function getWorksheets(accessToken: string, userId: string, fileId: string): Promise<any> {
  const client = await getAuthenticatedClient(accessToken);
  const worksheets = await client.api(`/users/${userId}/drive/items/${fileId}/workbook/worksheets`).get();
  return worksheets;
}
```

**Comment by eugene-kim** [comment]
The file id i was using: `6BB86F66F0707C42!122`

**Comment by ElinorW** [comment]
Hi @eugene-kim , could you please confirm if you are still experiencing this issue?

**Comment by eugene-kim** [comment]
@ElinorW yes. Are you asking because there was a fix in place?

**Comment by ElinorW** [comment]
@eugene-kim no, but I believe it's an issue with the Excel API's. 
Please post this on the [Microsoft Graph Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) where the appropriate team will be able to help

**Comment by eugene-kim** [comment]
@ElinorW I'm trying to post in the forum but it says I'm violating the Code of Conduct.

All I did was post the text of the original question and referred back to this issue. 
Are you able to assist?

Thank you

<img width="874" alt="image" src="https://github.com/user-attachments/assets/370d857b-29b4-42f6-b08c-0a348900b5b6">

**Comment by ElinorW** [comment]
@eugene-kim, 
that's strange. I've tried to post it as well but I got the same error. 😞 
Let me try and find an alternative

**Comment by ElinorW** [comment]
@eugene-kim if you have a paid azure subscription or an m365 tenant, you can create a support ticket instead 
https://developer.microsoft.com/en-us/graph/support

**Comment by eugene-kim** [comment]
I'm trying to create a support request but I'm prevented from doing so. I've put in my details and I only see self help solutions. Do you have any suggestions on how I can proceed?

I have the standard support plan

![Screenshot 2024-08-27 at 11 31 27 AM](https://github.com/user-attachments/assets/b03d8f4e-7915-407d-8510-351e581f34a3)
![Screenshot 2024-08-27 at 11 31 50 AM](https://github.com/user-attachments/assets/4c595126-0150-4567-8b80-7ff3b55a389d)
![Screenshot 2024-08-27 at 11 33 07 AM](https://github.com/user-attachments/assets/91de4d14-45de-422b-a89c-e4aebd7bf134)

**Comment by ElinorW** [comment]
Hey @eugene-kim 
click on the 'Return to support request" and then click `Next`
![image](https://github.com/user-attachments/assets/41de5d6a-7469-4ba3-923e-f35cbda45257)
![image](https://github.com/user-attachments/assets/ff48c382-5356-4517-be9b-1b49071bcf4b)

**Comment by eugene-kim** [comment]
Thank you! I was able to create a support ticket

**Comment by ElinorW** [comment]
Closing this for now. If you encounter any issues on Graph Explorer, please feel free to create an issue
