### ISSUE TITLE
Sharepoint APIs

### ISSUE THREAD

**Issue by segundevbcf** [microsoftgraph/microsoft-graph-explorer-v4#3269]
Need to know if there are graph APIs available for these tasks as I can't find them

Total number of documents with external link shared in a site
The details of a document including if the files have external link sharing details of the site including if it has eternal sharing
list of all external users with access to any SharePoint or OneDrive site

**Comment by ElinorW** [comment]
Hi @segundevbcf,
This repo mainly handles issues related to Graph Explorer. For questions regarding Graph APIs, please post them on the [Microsoft Graph Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) where the appropriate team should be able to help
