### ISSUE TITLE
Insufficient permissions to post device query

### ISSUE THREAD

**Issue by taraldjoh** [microsoftgraph/microsoft-graph-explorer-v4#3282]
**Describe the bug**
When attempting to use the Graph API in order to post a 'Device Query' on an Intune Device, no matter the permissions set it still responds with a '403 Forbidden' error. This is regardless if using the Graph Explorer or the Graph-module in PowerShell.

**To Reproduce**
Steps to reproduce the behavior includes using the same base64-encoded query-string which can be found while posting a query through the Intune portal. ( See [this link](https://www.systanddeploy.com/2024/02/run-device-query-on-intune-devices-with.html) for reference)
1. In Graph Explorer, set the environment to 'Beta'
2. Consent to the permissions "DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.Read.All, DeviceManagementManagedDevices.PrivilegedOperations.All"
3. Add a post request to the url: https://https://graph.microsoft.com/beta/deviceManagement/managedDevices/INSERT_DEVICE_ID/createQuery
4. In the 'Request body', pass a base64-encoded query. For example:
`{
   "query": "Q3B1IHwgcHJvamVjdCBQcm9jZXNzb3JJZCwgQ3VycmVudENsb2NrU3BlZWQsIE1heENsb2NrU3BlZWQsIENwdVN0YXR1cyANCg=="
}`
 
This encoded string represents the query: 
Cpu | project ProcessorId, CurrentClockSpeed, MaxClockSpeed, CpuStatus 
5. The error received is then a 403 Forbidden, which indicates that some permissions are missing. 

**Expected behavior**
After running the query, it should return a deviceQueryResult containing the information received from the query. 

**Screenshots**
![image](https://github.com/user-attachments/assets/5f2923c6-bb38-4f58-b8a6-bd9c8c40c0ed)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser Microsoft Edge 
 - Version 127.0.2651.98

**Additional context**
The query works perfectly fine if I do it from the Intune-portal itself. However being able to run the query through powershell enables us to iterate through larger chunks of devices and generate reports instead of doing as much manual work. I've tried to find anything related to permissions for this, but I can't seem to find anything.

**Comment by ElinorW** [comment]
Hey @taraldjoh,
this is likely an issue with the Intune APIs . Please post this on the [Microsoft Graph Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph), where the appropriate team will be able to assist you.
