### ISSUE TITLE
Extra results when searching for display names when the first and last name start with the same character.

### ISSUE THREAD

**Issue by Armordragon7** [microsoftgraph/microsoft-graph-explorer-v4#3285]
**Describe the bug**
This is most likely an issue with the underlying API. However, when using the Microsoft Graph Explorer, you can get extra results to appear when the DisplayName contains a space and the first and last word start with the same character. It appears to ignore the last character.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Change the query to `https://graph.microsoft.com/v1.0/users?$search="displayName:Conf Room C"`
3. Click `Run Query`
4. Notice all six `Conf Room...` results are showing. (See: `https://graph.microsoft.com/v1.0/users?$search="displayName:Conf Room"`)

**Expected behavior**
The result to only be `Conf Room Crystal`. Just like the result of this query when the displayName just has one more character added: `https://graph.microsoft.com/v1.0/users?$search="displayName:Conf Room Cr"`

**Screenshots**
Error Results:
![image](https://github.com/user-attachments/assets/d507c340-b8f5-4319-81c3-dd3020d67c0b)

Expected Result Query:
![image](https://github.com/user-attachments/assets/69b6d28a-b097-4d0a-a0e4-5dbdce3f27fc)

**Desktop:**
 - OS: Windows 11 Enterprise 23H2
 - Browser [Microsoft Edge, Google Chrome]

**Additional context**
I also experienced this behavior with the Microsoft Graph C# SDK. More examples or problem names: `chris c` and `mike m`. If this needs to be posted somewhere else, please let me know. Thanks!

**Comment by ElinorW** [comment]
Hey @Armordragon7 , 
So this is how the &search parameter works because it uses tokenization and therefore returns a list of results that contain "conf", "room" and "C"
Ref: https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http#using-search-on-directory-object-collections

**Comment by ElinorW** [comment]
Let me know if you need further assistance.

**Comment by Armordragon7** [comment]
Elinor, thanks for the explanation. That makes sense now. Thanks for quick clarification!
