### ISSUE TITLE
Reading Mailfolder response in error : The requested user 'userid' is invalid.

### ISSUE THREAD

**Issue by dashandwerk** [microsoftgraph/microsoft-graph-explorer-v4#3293]
**Describe the bug**
When reading Mailfolders for new mails, i am getting this error
The requested user '<userid>' is invalid."

**To Reproduce**
This GET request is starting every day:
https://graph.microsoft.com/v1.0/users/<userid>/mailFolders/<MailFolderID>/messages?$filter=createdDateTime gt 2024-08-30T11:00:00Z&$top=100

I double checked folderid, it is present and reachable.
Userid is present and reachable.
All other functions are working, like sendMail, setCalendar etc.

**Expected behavior**
Expected behavior should be a list of mails.

**Comment by dashandwerk** [comment]
Userid and folderid was deleted for security reason.

**Comment by musale** [comment]
> Userid and folderid was deleted for security reason.

I suppose this allows this issue to be closed now?
