### ISSUE TITLE
Example query fails with Preview Graph Explorer, succeeds in currently released Graph Explorer

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#331]
Refer to this Issue reported in GE V3: https://github.com/microsoftgraph/microsoft-graph-explorer/issues/390
[AB#6143](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6143)

**Comment by thewahome** [comment]
@MIchaelMainer I investigated this and found the graph client can not run this particular query.
It truncates the request after it gets to the filter section of the url

**Comment by nikithauc** [comment]
This parsing of the URL  is fixed in Microsoft Graph JS SDK version 2.1.0.
