### ISSUE TITLE
Making a patch call to https://graph.microsoft.com/beta/contracts/{id} no permissions documented

### ISSUE THREAD

**Issue by superheroham** [microsoftgraph/microsoft-graph-explorer-v4#3328]
Documentation and "Modify Permissions" tab on the graphAPI endpoint https://graph.microsoft.com/beta/contracts/{id} is unclear and incomplete for the a "Patch" call to update display name on a partner contract.

This was originally available in the Azure Graph API which is now deprecated.

**Comment by superheroham** [comment]
running this will produce the following error:
Forbidden - 403 - 322 ms. Either the signed-in user does not have sufficient privileges, or you need to consent to one of the permissions on the Modify permissions tab

**Comment by ElinorW** [comment]
Hi @superheroham, 
Do you still get this same error even though you've consented to `Directory.Read.All` and `Directory.ReadWrite.All` permissions?
