### ISSUE TITLE
Can't access the files from one drive

### ISSUE THREAD

**Issue by rfpanfil** [microsoftgraph/microsoft-graph-explorer-v4#3329]
I'm using the https://graph.microsoft.com/v1.0/me/drive/root/children
All the permissions are enabled.

![Screenshot_178](https://github.com/user-attachments/assets/0d6d8d24-cc26-4344-96b1-615d769220a2)
![Screenshot_179](https://github.com/user-attachments/assets/244ec592-a289-47ea-9fa5-a3761ccaa9c7)

**Comment by ElinorW** [comment]
Hi @rfpanfil, 
Are you still experiencing this issue?
