### ISSUE TITLE
https://graph.microsoft.com/v1.0/devices/{$deviceid}

### ISSUE THREAD

**Issue by Bpop161** [microsoftgraph/microsoft-graph-explorer-v4#3330]
**Describe the bug**
when I put id in this request on the graph explorer https://graph.microsoft.com/v1.0/devices/$id

**To Reproduce**
1. Go to 'graph explorer'
2. Click on run query - https://graph.microsoft.com/v1.0/devices/456.....
3. Scroll down to 'response preview'
4. error - 
{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource 'XXXXXXXXXXXXXXXXXXXXXXXXX' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2024-09-19T11:52:23",
            "request-id": "016940f7-f46f-4b64-8df5-368740da3995",
            "client-request-id": "304f50dd-c941-6879-c699-7e569f5db0ea"
        }
    }
}

**Expected behavior**
data on the device referenced through the id given in the request

**Screenshots**
![err](https://github.com/user-attachments/assets/0365a9ad-7951-4c75-83eb-970c10c400d2)
![err1](https://github.com/user-attachments/assets/312f19f8-444d-4ac2-9519-da5a2a1ec9a5)
![err2](https://github.com/user-attachments/assets/89492a8c-2ec0-419e-873e-f73378e25290)
![err3](https://github.com/user-attachments/assets/71f0d2c1-fda3-4cdd-9ced-daafb5f7b491)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [chrome]
 - Version [129.0.6668.59 ]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by musale** [comment]
@Bpop161 does running the same query using a different client give you the expected response? This looks like a service issue and the only way we can isolate it as a GE issue is if the query works with a different client.
