### ISSUE TITLE
Delete mobileAppContentFile - No OData route exists that match template with http verb DELETE

### ISSUE THREAD

**Issue by VerbalHerbal** [microsoftgraph/microsoft-graph-explorer-v4#3334]
**Describe the bug**
Using Graph Explorer (or Powershell), when attempting to delete an iOS LOB App Content File via Graph API as per Microsoft Docs, I get an error "No OData route exists that match template with http verb DELETE". With both v1.0 of Graph API as well as Beta

Using GET for the same URI works just fine. Resource is pulled correctly.

Docs: https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileappcontentfile-delete?view=graph-rest-beta

Query: DELETE https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/{mobileApp-id}/microsoft.graph.iosLobApp/contentVersions/{id}/files/{file-id}

As per Microsoft docs, the HTTP request should be: "DELETE /deviceAppManagement/mobileApps/{mobileAppId}/contentVersions/{mobileAppContentId}/files/{mobileAppContentFileId}"
No additional request body. 

Using Powershell with "Remove-MgBetaDeviceAppManagementMobileAppAsiOSLobAppContentVersionFile -MobileAppId $matchingApps.Id -MobileAppContentFileId "{file-id}" -MobileAppContentId {id}"  results in the same error

I have relevant permissions: DeviceManagementApps.ReadWrite.All, DeviceManagementConfiguration.ReadWrite.All

**Expected behavior**
Return Code 204

**Screenshots**
![image](https://github.com/user-attachments/assets/c761862d-c99b-45f1-ac01-c21ad62516aa)
![image](https://github.com/user-attachments/assets/c5a4f06f-b6a4-415f-b703-23bbf9f0d0e1)

**Desktop:**
 - OS: [e.g. iOS] Windows 11 23H2
 - Browser [e.g. chrome, safari]: Edge 129.0.2792.52

**Comment by ElinorW** [comment]
Hi @VerbalHerbal , 
This seems to be an issue with the Graph API. Please post this on the [Microsoft Graph Q&A forum](http://aka.ms/askgraph) where the appropriate team should be able to assist you
