### ISSUE TITLE
Graph Explorer Resources not working properly

### ISSUE THREAD

**Issue by jessicaaawu** [microsoftgraph/microsoft-graph-explorer-v4#3335]
**Describe the bug**
When user goes to resources tab and search something in the resources search bar, the entire Graph Explorer web app disappears, and only the footer is visible. 

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Go to resources tab
3. Enter 'folder' or any other phrase in the search bar
4. See error --> 
![image](https://github.com/user-attachments/assets/bef34c90-7591-4acd-901a-c86b2008b1fc)

**Expected behavior**
The correct resources and request should be returned. 

**Screenshots**
![image](https://github.com/user-attachments/assets/79714240-3ecb-4992-9636-26140033e9a4)

**Comment by musale** [comment]
@jessicaaawu we figured the reproduction is in US regions and I can repro from this region. We're working on a fix.
