### ISSUE TITLE
MS Graph API Certificate Issue

### ISSUE THREAD

**Issue by ACA1993** [microsoftgraph/microsoft-graph-explorer-v4#3347]
I use the MS Graph API to connect with my Teams Chat, but currently the certificate will not be approved and I get following error: {"error":{"code":"ValidationError","message":"HttpRequestException:An error occurred while sending the request. WebException:The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. AuthenticationException:The remote certificate is invalid according to the validation procedure. ","innerError":{"date":"2024-09-30T16:24:35","request-id":"ff84c630-4449-4c5e-858c-4ba3ffb85b03","client-request-id":"ff84c630-4449-4c5e-858c-4ba3ffb85b03"}}} Maybe you can help me? I already change my certificate, but it does not work.

**Comment by ElinorW** [comment]
Hi @ACA1993 , 
This seems to be a service issue. Please share this on https://aka.ms/askgraph where the appropriate team will be able to provide further assistance
