### ISSUE TITLE
"Permissions" always says "retry"

### ISSUE THREAD

**Issue by zhuxiaodics6** [microsoftgraph/microsoft-graph-explorer-v4#3392]
I need to test the api but I cant add any permissions
![image](https://github.com/user-attachments/assets/7947104e-b16c-4932-83d7-c68c4f75f0b3)
![image](https://github.com/user-attachments/assets/98e0849c-74f3-4bb8-9763-00b7fb97aee6)

**Comment by ElinorW** [comment]
Hi @zhuxiaodics6 , 
Is there a specific uri you're using that is bringing this?

**Comment by zhuxiaodics6** [comment]
> Hi @zhuxiaodics6 , Is there a specific uri you're using that is bringing this?
no，i just use the example URL in the left list.

**Comment by ElinorW** [comment]
@zhuxiaodics6,
I would like to try and reproduce this.
Which specific URL are you using?
