### ISSUE TITLE
Interface issue when adding a custom graph URL

### ISSUE THREAD

**Issue by StephaneSeguin** [microsoftgraph/microsoft-graph-explorer-v4#3420]
The interface is completely blank when changing the URL of the Graph API.
**To Reproduce**
1. Go to 'URL.'
2. Enter 'ttps://graph.microsoft.com/v1.0/solutions/bookingBusinesses/Contosolunchdelivery@contoso.com/appointments"
3. Click away of the field or "Tab"
4. The form is cleared.

**Expected behavior**
I should be able to enter the header and body of the graph API request

**Screenshots**

![image](https://github.com/user-attachments/assets/cc577435-b0bc-4db7-b736-3773f78c6d8d)

**Desktop (please complete the following information):**
 - Windows 11
 - Browser Edge

**Comment by musale** [comment]
@StephaneSeguin sorry for this experience. A similar issue was reported a while back and fixed https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/3335. Which region are you facing this issue from?

**Comment by StephaneSeguin** [comment]
Hello,

I'm in canada.

[Solution d'affaires BOOST  BOOST Business Solutions]
Stéphane Séguin
Président et consultant principal | President and Senior Consultant
M: 514.883.4779
***@***.******@***.***>
[linkedin]<https://www.linkedin.com/in/stephaneseguincrm/>

**Comment by musale** [comment]
@StephaneSeguin could you run `appVersion` in the console of your app and let me know what version you get?
![image](https://github.com/user-attachments/assets/441439f3-665e-4dad-ba4d-a670e71abf2f)

**Comment by StephaneSeguin** [comment]
Hello,

I do not get this info from the browser


[Solution d'affaires BOOST  BOOST Business Solutions]
Stéphane Séguin
Président et consultant principal | President and Senior Consultant
M: 514.883.4779
***@***.******@***.***>
[linkedin]<https://www.linkedin.com/in/stephaneseguincrm/>

**Comment by musale** [comment]
@StephaneSeguin it's a bit challenging to figure out what is causing your issue if I don't know these details. As mentioned, this was faced earlier, fixed and deployed. Could you try a different browser?
