### ISSUE TITLE
I can't add processorArchitecture property when I try create an extension attribute

### ISSUE THREAD

**Issue by pandatech1** [microsoftgraph/microsoft-graph-explorer-v4#3433]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pandatech1** [comment]
I have any MacOS computers managed by Microsoft Intune, but I tried add a processorArchitecture property in extension attributes to create a Dynamic Group based in this property. Because I have MacOS with x64 and ARM. If any have a solution, please, help me. Thanks a lot.

**Comment by ElinorW** [comment]
Hi @pandatech1, please post this on https://github.com/microsoftgraph/msgraph-sdk-powershell/issues
or on the Graph Q&A forum where the appropriate team shall be able to provide the help needed.
