### ISSUE TITLE
sponsors

### ISSUE THREAD

**Issue by jhnworks** [microsoftgraph/microsoft-graph-explorer-v4#3452]
**Describe the bug**
Looking to export "Sponsors" field of all the guest users

**To Reproduce**
1. Go to 'https://graph.microsoft.com/v1.0/users?$filter=userType+eq+'guest'&$select=id,displayName,mail,city,Sponsors'
2. Click on 'Run query'

**Expected behavior**
"Sponsors" field value is not returned.

**Comment by ElinorW** [comment]
Hi @jhnworks, 
I have seen that the sponsors field value is not returned. This is likely an issue with the Users API. 
Please paste this question on the [Microsoft Graph Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) where the appropriate team will be able to help out.
