### ISSUE TITLE
Cannot run Windows Update API

### ISSUE THREAD

**Issue by guliteb** [microsoftgraph/microsoft-graph-explorer-v4#3478]
**Describe the bug**
Fail to run list catalog entries

**To Reproduce**
1. Go to 'Windows Updates'
2. Click on 'GET list catalog entries'
3. Consent 'WindowsUpdates.ReadWrite.All'
4. Click on 'Run Query'
5. See error

**Screenshots**
![image](https://github.com/user-attachments/assets/c97eb0ee-f649-4dbf-8151-fc036c45944d)
![image](https://github.com/user-attachments/assets/50366721-da11-4868-9ece-cd13d3de5021)
![image](https://github.com/user-attachments/assets/ac52da27-3b43-4934-bfae-fd392312a630)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 131.0.2903.70

**Additional context**

**Comment by ElinorW** [comment]
Hi @guliteb ,
This is likely an issue with the Windows Updates API. Please post this question on the [Microsoft Graph Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) where the appropriate team will be able to help you out.
