### ISSUE TITLE
Add request headers to the data that's shared on the share button

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#355]
**Is your feature request related to a problem? Please describe.**
the share button only shares the request url but this is not helpful when it's a POST request option that has request headers. 

**Describe the solution you'd like**
There is a need to add the request headers to the data shared on the request headers portion.

**Describe alternatives you've considered**

**Additional context**

**Comment by thewahome** [comment]
I think we should not send the Bearer request header... @bettirosengugi
