### ISSUE TITLE
Signing In bug 

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#357]
**Describe the bug**
When you try logging into GE V4 on New Edge, the Signing In button continuously rotates without signing the user in. and when you reload the page the app loads without signing you in.

The problem is worse in Old Edge, and since there's no deprecation date yet for Old Edge, it's important to support our developers using this Browser as well. If you try to login to Old Edge, you are redirected to https://developer.microsoft.com/en-us/ which shouldnt be the case.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer/preview
2. Click on Sign in
3.Try signing in

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
I was not able to repro this on new Edge
