### ISSUE TITLE
api sandbox proxy probe

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#368]
**Is your feature request related to a problem? Please describe.**
We want to discover when the API sandbox proxy is unavailable to service requests. We have experienced a down api sandbox proxy which was only discovered when WE made an anonymous request. 

**Describe the solution you'd like**
A scheduled cloud task that regularly probes the sandbox proxy.

**Describe alternatives you've considered**
Graph Explorer should raise an incident if it encounters a down api sandbox proxy 
[AB#7527](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7527)

**Comment by MIchaelMainer** [comment]
Related https://github.com/microsoftgraph/microsoft-graph-explorer/issues/403

**Comment by thewahome** [comment]
We should close this since our confidence in the proxy improved greatly since the creation of the issue. The issue should be reopened if this changes
