### ISSUE TITLE
api sandbox proxy failover

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#369]
**Is your feature request related to a problem? Please describe.**
In the case of API sandbox proxy failure, we should have a failover scenario to gracefully handle this scenario.

**Describe the solution you'd like**
A failover web app

**Describe alternatives you've considered**
instructions to signed in (use the authenticated) experience, or even dummy **response** 
[AB#7528](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7528)

**Comment by thewahome** [comment]
No...
