### ISSUE TITLE
Make paging easier

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-explorer-v4#392]
**Is your feature request related to a problem? Please describe.**
When I get the first page of a set of paged results back, it's difficult to go to the next page.  I have to copy the nextLink value into the REST request URL text box and remove the quote marks.  (Also cutting and pasting from the response into the REST request URL text box seems to have a bug - when I do ctrl-v to paste this seems to reload the page.)

**Describe the solution you'd like**
It would be great if the response contains a nextLink, for Graph Explorer to show a next button or some such that would more easily allow me to go to the next page in the result set.

**Describe alternatives you've considered**
Already described, and it's clunky.

 
[AB#7530](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7530)

**Comment by thewahome** [comment]
>(Also cutting and pasting from the response into the REST request URL text box seems to have a bug - when I do ctrl-v to paste this seems to reload the page.)

This part has been closed by #397

**Comment by bettirosengugi** [comment]
Got some additional feedback from a customer who would like to have this feature added, quoting the customer "Being able to navigate the nextLink, deltaLink, etc. properties by clicking on them instead of having to copy and paste them"
