### ISSUE TITLE
Some users are unable to sign-in to Graph Explorer (Preview) depite having the same 

### ISSUE THREAD

**Issue by ademolaadedeji** [microsoftgraph/microsoft-graph-explorer-v4#396]
**Some users are unable to sign-in to graph explorer(preview)**

Tried signing into graph explorer (preview) with my Microsoft account 
1. Go to 'aka.ms/ge'
2. Click on 'toggle on preview and click sign-in'
3. Scroll down to ''
4. See error (No error is shown, but the screen just keeps spinning)

**Expected behavior**
All users that have the required permissions are meant to successfully sign-in.

![Graphexplorerpreview](https://user-images.githubusercontent.com/61559952/75479766-131a8080-596e-11ea-9984-d8bae8f48e93.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Edge, chrome, safari]
 - Version [e.g. Windows 1903]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone, Android]
 - OS: [e.g. All versions]
 - Browser [e.g. All browsers]
 - Version [e.g.All]

**Additional context**

**Comment by max-vaughn** [comment]
Adding more information.
The issue occures on all browsers on the windows desktop as well as on all browsers on iOS and Andoid.

**Comment by thewahome** [comment]
Hi @max-vaughn / @ademolaadedeji ,
Might you have blocked popups on your browser?

**Comment by minhaj12498** [comment]
I too thought the same thing but I specifically allowed the popup for developer.microsoft.com and still it doesn't work for me. I have tried different browsers but it doesn't work.
For me it works in Chrome but not in Edge. I have made sure I am allowing popups in both the browsers.
