### ISSUE TITLE
Add a link to the main Graph Explorer Full experience

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#400]
**Is your feature request related to a problem? Please describe.**
Try it login should act as a teaser and has limited features and there's need to add a link to main Graph Explorer

**Describe the solution you'd like**
Add a link to the main GE with context of the link that carries the url that the user was looking at in try it and request headers as well if they were using non-GET request option. 

Wording: 

To get more Microsoft Graph Features , go to the full experience Graph Explorer.

**Comment by thewahome** [comment]
@bettirosengugi how related is this task to this one? #356
