### ISSUE TITLE
Bug: Words in buttons when in Dark Mode and High Contrast should be white

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#414]
**Describe the bug**
The words "Sign in to Graph Explorer" and "Run Query "should be white when in Dark Mode and in High Contrast themes

**To Reproduce**
1. Go to GE Preview
2. Change themes
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
The change here should only be in dark mode. it is not readable when white in High contrast.

![image](https://user-images.githubusercontent.com/58787602/76424106-d95b6800-63b8-11ea-9b5a-b7f4ce530c0e.png)

**Comment by thewahome** [comment]
Closing this as the buttons follow the guidelines provided in https://developer.microsoft.com/en-us/fabric#/controls/web/button
