### ISSUE TITLE
Bug: when signing in, there's no option to sign in with a different account other than the one you've used before

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#419]
**Describe the bug**
If you want to login using a different account at the moment, you can't do this at the moment on new Graph Explorer

**To Reproduce**
1. Go tohttps://developer.microsoft.com/en-us/graph/graph-explorer/preview
2. Sign in
3. No option to change account you want to sign in with 

**Expected behavior**
It should allow you to choose the account you want to login with or add a new account. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
@bettirosengugi 
If you had logged out of your previous session then your details would be removed from the cache. MSAL checks the cache location to see if there are details and uses them to help it sign in. 

Logging out and logging in to a different account should work fine.
