### ISSUE TITLE
Update libraries to resolve security alerts on repo

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#426]
**Describe the bug**
The following security alerts have been reported. 

![image](https://user-images.githubusercontent.com/4668452/76315889-a34fb280-62ea-11ea-97d3-3ef050710f47.png)

Task: update libraries.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#7489](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7489)

**Comment by thewahome** [comment]
Task was closed when #844 was merged
