### ISSUE TITLE
Increase the space occupied by Access Token

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#433]
The Auth Token area has so much space but everything seems so squeezed in the middle. 

Increase the area occupied by the token in a more intuitive way and use fonts type and size that's in line with the rest of the app when showing the words "Sign in to see the access token"

**Comment by thewahome** [comment]
@bettirosengugi 
I am closing this as it was fixed by PR #430 that has been pending your approval :-)
