### ISSUE TITLE
search only show 1 sample and not 5

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#434]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4668452/76450753-5e597800-63df-11ea-9feb-604cccbbc6b8.png)

**To Reproduce**
1. Go to GEV4
2. Click on Search bar on Sample
3. Type "One drive"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
The search as we designed it was to help filter all the requests whose titles have the characters in the search box. 

If you'd want us to change this implementation, we can refer to it as a feature and not a bug
