### ISSUE TITLE
Unable to sign-in 

### ISSUE THREAD

**Issue by svpsiva** [microsoftgraph/microsoft-graph-explorer-v4#451]
**Describe the bug**
Sign-in process seems to be broken. I'm on Edge Dev build. 

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer/preview'
2. Click on 'Sign in to Graph explorer' button
3. Complete the AAD sign-in, authorization flow
4. Notice that the "Signing you in" progress bar continues to be displayed. 

**Expected behavior**
Sign-in should be successful. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Dev
 - Version: Version 82.0.446.0 (Official build) dev (64-bit)

**Additional context**

**Comment by bettirosengugi** [comment]
@svpsiva  We have fixed this in our next release, it should go out by tomorrow, please have a look and let me know if the bug repros.

**Comment by bettirosengugi** [comment]
This is resolved now and in production.
