### ISSUE TITLE
Result empty when running Report Query in O365

### ISSUE THREAD

**Issue by Smartboss88** [microsoftgraph/microsoft-graph-explorer-v4#459]
![Report Explorer](https://user-images.githubusercontent.com/48076085/77583298-3d9d2200-6eb7-11ea-90d9-dd0736198c8a.PNG)

Follow the steps in the doc to get Activity Report via Graph Explorer and it returned nothing.  If you go to Developer Tools in the Browser, then Network tab, you can see the link under Locations.  But really, it should return what is documented here https://docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityusercounts?view=graph-rest-1.0 
[AB#7491](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7491)

**Comment by bettirosengugi** [comment]
@thewahome @ElinorW the task here is to support redirects in GE by showing the link to the file redirected to in the location header and displaying/rendering the file in the response area.

**Comment by thewahome** [comment]
@finsharp has expressed interest in seeing how to fix it. Can we assign this to him? I will help him out too. He has been able to sort this out on the powershell sdk he has been working on and could have valuable insights

**Comment by bettirosengugi** [comment]
@thewahome we cannot assign to him because he has deliverable to meet on his project, but you can definitely sync with him for guidance.
