### ISSUE TITLE
A user should see the list of all permissions when they click the Permissions option under the Setting Gear

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#471]
**Is your feature request related to a problem? Please describe.**
there are expert users who know the permissions they require and want to consent to, and we need to take care of them too. they dont have to get to a query to see the permission. The only way is to list all the permissions for them.

**Describe the solution you'd like**
add an option under the settings gear to show the list of all permissions and the status i.e Admin consent required, Consented and the consent button. 

Since the permission will be too many, add a search bar to allow users to search for a permission.

**Describe alternatives you've considered**

**Additional context**

**Comment by thewahome** [comment]
Does the devX api support this?

The current implementation of the api dictates that we need to add a request url like '/me' with a method so that it can pass the relevant permissions
