### ISSUE TITLE
Fix responsiveness

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#485]
**Describe the bug**
Graph Explorer is not responsive in small screens. see screenshots below:

![image](https://user-images.githubusercontent.com/4668452/80186999-94f9f380-8617-11ea-9ede-22d05af1ef8a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ddyett** [comment]
AB#4588
