### ISSUE TITLE
Fix Sign in bugs

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#486]
**Describe the bug**
When you try to sign in, then cancel mid way, the rotating sign in progress bar keeps rotating even after sign in process has been aborted.

This also happens when there's a problem in the sign in process, instead of showing the user the correct error, the progress bar keeps rotating giving the user false hope, till they reload the page and there they see the sign in button again.

Also, MSAL doesn't give you the option to choose the account you want to sign in with may be we can solve this by forcing MSAL pop up to have it select an account rather than it pick one.

**To Reproduce**
1. Go to GE Preview
2. Try to Sign in
3. GE will not allow you to change account to login with
4. Also if you abort the sign in process mid-way, sign in rotating progress bar keeps rotating endlessly

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
@bettirosengugi I believe these bugs can be isolated for ease of work and tracking.

I suggest they be:

1. The signing in rotating spinner does not stop spinning when authentication fails or is aborted
2. A user is not given the option to choose the account they want to sign in with

**Comment by ddyett** [comment]
AB#4588

**Comment by thewahome** [comment]
Closing this as new issues created under #488  and #487
