### ISSUE TITLE
tslint suppression must moved inline with code

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#507]
**Is your feature request related to a problem? Please describe.**
This is a security review requirement. We want to validate suppression on an individual basis per suppression so we can review justifications.

**Describe the solution you'd like**
Remove suppression from tslint.json and move into code with justifications. 
[AB#7496](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7496)

**Comment by thewahome** [comment]
we migrated to eslint. This may not be required #627
