### ISSUE TITLE
Add a tab next to History tab on the side bar for graph resources.

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#510]
**Is your feature request related to a problem? Please describe.**
Now that we have all resources and navigation properties in autocomplete endpoint of DevX API we can have a tab dedicated for these on GE

**Describe the solution you'd like**
Add a resources tab on Graph Explorer next to History that lists all parent resources and their children on Graph API together with the navigation properties. Like in the screenshots below:
![image](https://user-images.githubusercontent.com/4668452/81167226-8f989380-8f9d-11ea-92ba-de47aacfb7fb.png)

When one selects, the query is pasted on the address bar. 

**Describe alternatives you've considered**

**Additional context**
 
[AB#7498](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7498)

**Comment by thewahome** [comment]
Closing this as the resource explorer will be a fly out
