### ISSUE TITLE
Monaco editor not working on Old Edge and Safari browsers

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#514]
**Describe the bug**
The responses on Old Edge do not appear formatted. 
**To Reproduce**
1. Use old Edge to  Go to Graph Explorer
2. Click on a sample query
3. Scroll down to Response 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#7499](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7499)

**Comment by thewahome** [comment]
This is fixed in #765
