### ISSUE TITLE
Enable Graph Explorer to check Onedrive for samples first before requesting DevX API

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#515]
**Is your feature request related to a problem? Please describe.**
With the separation of roles between Graph Explorer and DevX API, there's need to create a way to allow users to test samples when they are uploaded. 
**Describe the solution you'd like**
When a Microsoft user is logged in, check their Onedrive folder to see if any samples exist if they do, ask if they user wants to show those, or would like to see the ones in DevX API.

**Describe alternatives you've considered**

**Additional context**
 
[AB#7500](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7500)

**Comment by thewahome** [comment]
This should be closed by @MaggieKimani1's PR #833
