### ISSUE TITLE
Clear history upon successful sign out 

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#524]
**Is your feature request related to a problem? Please describe.**
Users should expect that signing out of GE with their user doesn't leave any data about their account or organization in the browser storage. History data is still maintained when they sign out. This data may contain consumer or organization information in the stored URL or request bodies.

**Describe the solution you'd like**
History data is cleared when the GE is loaded when their isn't a signed in user. I state this as the sign out flow redirects to a sign out page and then after signing out of an arbitrary account, GE is reloaded. They user does not necessarily sign out of the account that was logged into GE. 

**Additional context**
A user that wants to keep history doesn't have to sign out.

**Comment by jobala** [comment]
@MIchaelMainer @bettirosengugi 
> A user that wants to keep history doesn't have to sign out.

We should let the user know that they'll lose their history after signing out.

**Comment by Kachulio1** [comment]
@MIchaelMainer @bettirosengugi @jobala should we clear the history on login? because the current behavior is, when you run some queries with the sample account and later sign in, you still see the history of the sample account

**Comment by jobala** [comment]
Good question @Kachulio1. Tagging @thewahome as well. 

My guess is we don't have to. The workflow is that a user moves from using the sample account to their own account.
