### ISSUE TITLE
Abandoned sign-in leaves UI in unexpected state

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#531]
**Describe the bug**
Select login, and the login account selection browser window is opened with focus. If you close the login account selection browser window, the 

**To Reproduce**
1. Go to **Sign into Graph Explorer**. The login account selection browser window is opened.
2. Abandon the login by closing the account selection browser window.

**Expected behavior**
The abandoned login should result in a UI state that doesn't represent an in progress login. We may want to remove the progress indicator as I don't know if there is a way to message back onClose of the login account select browser window..

**Screenshots**
This image shows the state
![Bad sign in state](https://user-images.githubusercontent.com/8527305/81351464-3b62e180-9079-11ea-9644-92b4058b606c.png)

https://developer.microsoft.com/en-us/graph/graph-explorer/preview

**Desktop (please complete the following information):**
 - Browser: chrome

**Comment by bettirosengugi** [comment]
This has been fixed by #492
