### ISSUE TITLE
jwt.ms functionality in Graph Explorer for access token

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#532]
**Is your feature request related to a problem? Please describe.**
We provide access to an access token in GE. It would ne nice to easily decode it.

**Describe the solution you'd like**
jwt.ms decodes access token in the browser. We could provide the same. Another perhaps simpler way to help customers here is to open jwt.ms. I've seen an call in a Azure b2c document where it made a call to jwt.ms and decoded a passed in token.

**Describe alternatives you've considered**
Copy and paste into jwt.ms isn't painful.

**Comment by baywet** [comment]
I was about to create a similar suggestion when I saw this issue.
We could add a "Open in JWT.ms" button here.
![image](https://user-images.githubusercontent.com/7905502/86042257-e312e500-ba14-11ea-9149-9388b1071c73.png)

The URL format is https://jwt.ms/#access_token=<access_token>. With that JWT.ms will "open" the token right away, no copy/pasting required.
