### ISSUE TITLE
Error: Share link, navigate to page, then click sign in

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-explorer-v4#540]
**Describe the bug**

**To Reproduce**
1. Go to https://developer.microsoft.com/en-US/graph/graph-explorer/preview
2. Click on My Photo
3. CLick on Share
4. Copy URL
`https://developer.microsoft.com/en-US/graph/graph-explorer/preview?request=me&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=dW5kZWZpbmVk`
5. navigate to URL in tab
6. Click Sign in to Graph explore
7. Pick an acount
8. ERROR

`Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'de8bc8b5-d9f9-48b1-a8ad-b748da725064'. More details: Reply address did not match because of case sensitivity.`

**Expected behavior**
Signs me in

** suggested fix **
Locale needs to be all lower case.

`https://developer.microsoft.com/en-US/graph/graph-explorer/preview?request=me&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=dW5kZWZpbmVk`
to
`https://developer.microsoft.com/en-us/graph/graph-explorer/preview?request=me&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=dW5kZWZpbmVk`

**Comment by ddyett** [comment]
We should fix this.  It does happen with classic as well but it's a simple fix.
