### ISSUE TITLE
Sample queries in the new Graph Explorer is out of sync 

### ISSUE THREAD

**Issue by sureshja** [microsoftgraph/microsoft-graph-explorer-v4#544]
The old Graph Explorer showed "Applications" in the sample query. But the new one shows 'Applications Beta". This makes me think the new GE is out of sync with the old one for the sample queries.

Old GE:
![image](https://user-images.githubusercontent.com/8422237/82079918-804dd000-9698-11ea-954d-291690bd1996.png)

New GE:
![image](https://user-images.githubusercontent.com/8422237/82080193-f3efdd00-9698-11ea-9e75-daea6a8b3278.png)

**Comment by bettirosengugi** [comment]
This has been resolved here: https://github.com/microsoftgraph/microsoft-graph-devx-content/pull/18
