### ISSUE TITLE
PowerShell snippet support

### ISSUE THREAD

**Issue by ChrisLGardner** [microsoftgraph/microsoft-graph-explorer-v4#546]
**Is your feature request related to a problem? Please describe.**
It'd be great if we could use PowerShell in the Code tab, many admins interacting with Graph will be doing so with PowerShell so having native support for it so they can run their queries there before moving them to automation solutions would greatly improve their experience using the Graph Explorer and help drive adoption. 

**Describe the solution you'd like**
Support for PowerShell in much the same way the other 4 languages are supported.

 
[AB#7503](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7503)

**Comment by bergmeister** [comment]
By that, do you mean a snippet using the Microsoft.Graph module?

**Comment by ChrisLGardner** [comment]
Yes, that'd be ideal but even some Invoke-RestMethod calls would be good too.

**Comment by guidooliveira** [comment]
This would be amazing!

**Comment by ezkemboi** [comment]
I am not sure if I am right or wrong but taking a look at the current implementation, 
I feel that this feature request could be done from [microsoft-graph-explorer-api](https://github.com/microsoftgraph/microsoft-graph-explorer-api). 
After implementation from the `API` side and fully supported,  it could be just passing the language type on the request and get the snippet.

**Comment by millicentachieng** [comment]
We now have PowerShell snippets on Graph Explorer. 🥳 Please check them out.
