### ISSUE TITLE
'Select permissions' page pops up every time.

### ISSUE THREAD

**Issue by foxdave** [microsoftgraph/microsoft-graph-explorer-v4#547]
**Describe the bug**
Please take below steps to reproduce the issue. My web browser is Chrome 81.0.4044.138 32bit.
#1 Click the gear icon, select 'Select permissions' menu to show the permissions list page.
#2 Close the page and click the hamburger icon, the permissions list page pops up again, every time I click the hamburger icon, it will pop up.

**To Reproduce**
1. Click the gear icon, select 'Select permissions' menu to show the permissions list page.
2. Close the page and click the hamburger icon, the permissions list page pops up again, every time I click the hamburger icon, it will pop up.

**Expected behavior**
The permissions list page shouldn't pop up when I click the hamburger icon.

**Screenshots**
![issue](https://user-images.githubusercontent.com/7928690/82192958-45ad9700-9927-11ea-9ddf-1e647cbf64d0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 81.0.4044.138 32bit

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bettirosengugi** [comment]
@thewahome this could an issue with the close (X) button not working.
