### ISSUE TITLE
Guid interaction

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-explorer-v4#553]
In an original Graph Explorer build, in the response that came back. It was super easy to click on the GUIDs and get some options:

**Copy ID**
Being able to just copy the GUID. Many times in code I want to grab GUIDs quickly. Selecting them in the response is hard in Chrome/Edge. This would be much smoother an experience.

**Run query**
Imagine the scenario where you run `/me/events` and then click on the event-id in the json response. This immediately changes the graph explorer address bar to `/me/events/{event-id}` and returns that response. It makes the graph more "graphy" navigating around.

We would want some obvious way that either on hover or clicking on GUID has an interaction. 
[AB#7504](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7504)

**Comment by adhiambovivian** [comment]
@RabebOthmani  looks like a feature parity issue compared to previous version of GE

**Comment by darrelmiller** [comment]
@adhiambovivian As a partial solution, could you ask one of the devs to look into the Monaco editor configuration options so that when we double click on a GUID it highlights the entire GUID and does not stop at the nearest hyphen?  Thanks.

**Comment by Onokaev** [comment]
Can I get some screenshots of what the experience is like now, and the expected outcome of the fix? Thank you :)
