### ISSUE TITLE
Handle non wellformed JSON for request bodies

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#557]
**Describe the bug**
Request bodies with trailing JSON commas cause Graph Explorer to perform in an unexpected way. JSON spec does not allow trailing commas.

**To Reproduce**
1. Go to Graph Explorer
2. Sign in.
3. Create a POST or PATCH request with a request body that contains a trailing comma.
4. See error in console.

**Expected behavior**
We show an error message stating that the supplied JSON is invalid. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8527305/82934442-4dc99000-9f40-11ea-9355-b2fc2d2b6923.png)

**Desktop **
 - Browser chrome, edge

**Additional context**
Incident 187938447

**Comment by JimmyLS** [comment]
Based on my testing, the issue occurred if request syntax error (like invalid JSON) detected in PATCH/POST method, or even send an empty request body. 
No error indicated user to correct request syntax, the query just stuck or hang there without any response until you refresh browser. 
This is quite confusing and annoying experience to users.

**Comment by JimmyLS** [comment]
Hi Guys, 

Just want to check when we can fix this bug?

Thanks.

**Comment by JimmyLS** [comment]
Hi Team, 

It's still not working on my side. The symptom is the same.

![image](https://user-images.githubusercontent.com/25541899/84222226-9caf2200-ab09-11ea-93e2-fd1b7a341230.png)

**Comment by ddyett** [comment]
this change hasn't deployed yet.  Current schedule is later this week.

**Comment by JimmyLS** [comment]
> this change hasn't deployed yet. Current schedule is later this week.

Thanks! I will try this next Monday.

**Comment by JimmyLS** [comment]
Hi Team,

May I know if the change has been deployed now? I tried it today but looks like still didn't work.

Thanks.

**Comment by JimmyLS** [comment]
Sorry, I test in the local instance and it worked, version 4.1.3.

May I know then this version can be published to the public instance?

**Comment by MIchaelMainer** [comment]
@JimmyLS We are awaiting a resolution to a related deployment blocker.

**Comment by JimmyLS** [comment]
Thank you so much!
