### ISSUE TITLE
If there are no permissions on "Modify Permissions" tab redirect users to Select Permissions option

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#560]
**Is your feature request related to a problem? Please describe.**
The Modify permissions tab does not have the full list of all permissions  since the document we are using doesn't have the full list of permissions and their end points linked. 

**Describe the solution you'd like**
If no permissions are available show a message directing users to the Select permissions options under settings. 

**Describe alternatives you've considered**

**Additional context**
 
[AB#7505](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7505)

**Comment by ddyett** [comment]
@bettirosengugi what's the proposed change? Add a string with a hyperlink to the select permissions page?

**Comment by bettirosengugi** [comment]
> @bettirosengugi what's the proposed change? Add a string with a hyperlink to the select permissions page?

@ddyett Yes, the hyperlink triggers the Select Permissions pop up to open. This would be the best user experience.
