### ISSUE TITLE
Tips message do not show unless the user is logged in. 

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#563]
**Describe the bug**
Tips message do not show unless the user is logged in. 

**To Reproduce**
1. Go to Graph Explorer
2. Do not log in, log out if logged in
3. Run the Get a user's presence sample

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
Adding user-id to the tokens fixes this
