### ISSUE TITLE
Localized resources for Search don't appear on intl GE builds

### ISSUE THREAD

**Issue by elenaost** [microsoftgraph/microsoft-graph-explorer-v4#572]
**Describe the bug**
Localized resources for "Search sample queries" and "Search history items" don't appear on intl GE builds. Text boxes appear empty, see the screen shot.

**To Reproduce**
1. Go to https://developer.microsoft.com/de-de/graph/graph-explorer
2. Scroll down to Search text box
4. See that the text box does not contain any text while English GE contains either "Search sample queries" or "Search history items" 

**Expected behavior**
Localized "Search sample queries" and "Search history items" appear localized.
**Screenshots**
![image](https://user-images.githubusercontent.com/20428552/83805330-85cd8300-a664-11ea-8ac1-e0f092c0a29d.png)

Please re-build with loc files submitted 23 days ago.

**Comment by thewahome** [comment]
This has already been fixed by the translation commits. The changes were not visible because we have not made a new release since the changes were added
