### ISSUE TITLE
Filter on Sharepoint Items not working due to too long Endpoint call.

### ISSUE THREAD

**Issue by NielsHamelryck** [microsoftgraph/microsoft-graph-explorer-v4#573]
Describe the bug
When I am trying to target specific Sharepoint Items using the Graph Explorer, is does not work. The same problem happens when you use graphClient, and put everything into the .api()
Whenever I create a very long REST-Api call it gets cut off at (I guess around +-255 characters)
To Reproduce

Go to 'Graph Explorer'
Fill out the following QUery:

https://graph.microsoft.com/v1.0/sites/DevTenantForTesting.sharepoint.com,a8e3e990-da7f-4f09-8aea-85911fd5eb5b,8be9c9ae-d580-459b-a763-e2dfcff52731/lists/97ee04f3-9a1b-401a-804d-386002970233/items?$expand=fields($select=Field1,Field2,Field4)

Open F12, check the Network calls.
See error that is is trying to call the following:

https://graph.microsoft.com/v1.0/sites/DevTenantForTesting.sharepoint.com,a8e3e990-da7f-4f09-8aea-85911fd5eb5b,8be9c9ae-d580-459b-a763-e2dfcff52731/lists/97ee04f3-9a1b-401a-804d-386002970233/items?$expand=fie
Expected behavior
The previous version of MS Graph Explorer did not have this problem. It came up today as I can no longer access the old version  of Graph Explorer...
Screenshots

Desktop (please complete the following information):
Chrome Browser
Additional context
[AB#6141](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6141)

**Comment by NielsHamelryck** [comment]
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/491

Related to this problem.

**Comment by nikithauc** [comment]
This issue is fixed in Microsoft Graph JS SDK version 2.1.0.
