### ISSUE TITLE
calendarView API response doesn't convert time value into UTC

### ISSUE THREAD

**Issue by komatat** [microsoftgraph/microsoft-graph-explorer-v4#578]
**Describe the bug**
calendarView API response doesn't convert time value into UTC

**To Reproduce**
1. Create full day event in user's calendar with timezone which is different from UTC, for example UTC+3
2. Go to https://developer.microsoft.com/en-us/graph/graph-explorer and retrieve newly created  event with `https://graph.microsoft.com/v1.0/me/calendar/getSchedule` API
<< start and end time fields are returned in UTC with converted time values as expected:
```
                    "start": {
                        "dateTime": "2020-06-12T21:00:00.0000000",
                        "timeZone": "UTC"
                    },
                    "end": {
                        "dateTime": "2020-06-13T21:00:00.0000000",
                        "timeZone": "UTC"
                    }
```

3. Retrieve the same event with calendarView API `https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=2020-06-12T21:00:00.000Z&endDateTime=2020-06-14T20:59:59.999Z`
**Expected result:** start and end datetime fields and timeZone are set to the same values as for getSchedule API response
**Actual result:** timeZone is set to UTC which is expected, but dateTime is not converted from UTC+3 to UTC and remains set to 00:00:
```
            "start": {
                "dateTime": "2020-06-13T00:00:00.0000000",
                "timeZone": "UTC"
            },
            "end": {
                "dateTime": "2020-06-14T00:00:00.0000000",
                "timeZone": "UTC"
            }
```
**Desktop:**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [83.0.4103.61 (Official Build) (64-bit)]

**Comment by bettirosengugi** [comment]
@komatat all-day meeting is one that is floating on a specific date and across different time zones. Hence it always returns the default time zone i.e. UTC and does not do time conversion in calendarView.
If it is a meeting that is dependent on time zone then the meeting can be created as 24hr meeting with 'isAllDay' false. Please let me know if this is okay.
