### ISSUE TITLE
When receive a 401 unauthorized error link to MOdify Permission tab

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-explorer-v4#583]
If a user calls a Graph url and the response is 401 unauthorized. In the error message, have a button that will automatically open the Modify Permission tab. To make it obvious they need to consent Graph Explorer access to run this. 
[AB#7507](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7507)

**Comment by thewahome** [comment]
401 means they are not who they say they are on the graph. 403 means that they are who they say they are but do not have the right permissions to make that call.

We have a messaging for the 403 error but not the 401. Can we have the particular call/calls that give us the 401 response?

**Comment by ddyett** [comment]
yes 401 normally means there's something to be fixed about the auth ticket not permissions.

**Comment by thewahome** [comment]
> yes 401 normally means there's something to be fixed about the auth ticket not permissions.

Quite right... If this is related to having an expired access token when making the call then we have a fix for that ready to get to production. @ddyett

**Comment by bettirosengugi** [comment]
@thewahome the issue you fixed on auth token was on the display area, in that when the access token expires and a new one is issued, the token on the access token tab wasn't being updated to the new one. The task here is to display text that helps the user debug easily when a http error code is returned.

**Comment by thewahome** [comment]
Closing this as 403 errors should be linked to modify permissions tab. The 401 errors receive appropriate authentication error messages
