### ISSUE TITLE
All permissions show as required

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/microsoft-graph-explorer-v4#594]
### Expected behavior

GE shows permissions required for the given query

### Actual behavior

GE shows all permissions as required for the query

### Steps to reproduce the behavior

1. In the query field paste the following URL `https://graph.microsoft.com/v1.0/drive/special/approot:/file.txt:/content`
1. Run query > 403 Forbidden error (as expected)
1. Click on the Modify permissions tab > empty
1. From the settings menu, select the Select permissions option
1. Close the permissions pane > the Permissions tab shows all permissions as required

![image](https://user-images.githubusercontent.com/11164679/83628915-8b11cb80-a599-11ea-814f-fc0b317f51d0.png)
 
[AB#7511](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7511)

**Comment by bettirosengugi** [comment]
@thewahome it seems like the moment you open "Select Permissions" panel and scroll down then come up and close it, all permissions on that list are copied on the "Modify permissions" tab.
