### ISSUE TITLE
Feature request: allow setting the tenant

### ISSUE THREAD

**Issue by hongooi73** [microsoftgraph/microsoft-graph-explorer-v4#596]
I'm an MS FTE, and I've created my own tenant in AAD using my MS email. When I use Graph Explorer and login with my email, it always uses the MS tenant. It would be nice if I could tell it to use my tenant instead.

This is probably relevant to anyone in an org who does work in a tenant separate to their org's regular tenant.

**Comment by bettirosengugi** [comment]
@hongooi73  This has been resolved by this PR: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/568 by @agrabhi . let me know if this works now.

**Comment by hongooi73** [comment]
@bettirosengugi Thanks! But are you sure it's working? I just tried this:

1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer?tenant=aicatr.onmicrosoft.com (my tenant)
2. Login with my MS email
3. Get https://graph.microsoft.com/v1.0/users (list of users)

This retrieves the list of users in the MS tenant, not my tenant. Or is this only with the standalone client?

**Comment by agrabhi** [comment]
It works for me. If you are already signed into Graph explorer, you need to sign out. You can also try in in-private browser.
