### ISSUE TITLE
Two sign in buttons on graph explorer

### ISSUE THREAD

**Issue by maliksahil** [microsoftgraph/microsoft-graph-explorer-v4#597]
Use the issues in this repository to open issues about the Graph Explorer application. Questions about the Microsoft Graph should be directed to StackOverflow. Use the [microsoftgraph] tag on StackOverflow.

### Expected behavior

There should be only one sign in button

### Actual behavior

There are two sign in buttons

### Steps to reproduce the behavior

This tweet explains it all https://twitter.com/sahilmalik/status/1263706872416219136?s=20

### HTTP traffic capture
Not necessary

**Comment by ddyett** [comment]
this is admittedly awkward for users as they wouldn't understand that they're two separate applications running on the same page.  I'm not sure what we'd do here though.

**Comment by bettirosengugi** [comment]
@maliksahil @ddyett we have removed the second sign in button at the top right corner for the Graph Explorer pages. Hopefuly this makes the experience better for our users. Thanks.
