### ISSUE TITLE
Under what circumstances would a user not be able to create a OneNote page using Graph Explorer?

### ISSUE THREAD

**Issue by 1001QAdotNET** [microsoftgraph/microsoft-graph-explorer-v4#598]
Use the issues in this repository to open issues about the Graph Explorer application. Questions about the Microsoft Graph should be directed to StackOverflow. Use the [microsoftgraph] tag on StackOverflow.
Expected behavior
After logging in I am able to use graph explorer to see my notebooks and their sections
When I click on create  a section a template is copied in the query line where the user is supposed to fill in the notebook-id and then press "Run query"
Similar behavior is expected for "Create page" nothing happens. Is that expected?
Actual behavior
When I click on "Create page" nothing happens
Steps to reproduce the behavior
I use  a MS Account, and I login in in MS Graph Explored
Then I try to create a page.
HTTP traffic capture
N/A
[AB#6144](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6144)

**Comment by bettirosengugi** [comment]
@thewahome @irvinesunday Please investigate the query "create page" sample query under OneNote. It doesn't copy the request url to the address bar

**Comment by irvinesunday** [comment]
@thewahome does GE support content-types of `application/xhtml+xml` ? This sample query specifies headers of this type.

**Comment by darrelmiller** [comment]
@irvinesunday If Microsoft Graph supports it then Graph Explorer should support it :-D

**Comment by thewahome** [comment]
@bettirosengugi this is not related to #626 because it fails before sending. Hence why there is no HTTP traffic capture. What needs to be fixed here is placing the query body in the request body to allow someone to send the post request.

**Comment by thewahome** [comment]
I have partially fulfilled this. It can now display the content in the request body. However it fails to create the one note page. I have created an issue on the [SDK repository](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/298) related to the failing request

**Comment by nikithauc** [comment]
This issue is in Microsoft Graph JS SDK version 2.1.0.
