### ISSUE TITLE
Graph explorer throwing AADSTS50011 error

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-explorer-v4#599]
Not sure what changed yesterday, but I can no longer login to the Graph explorer. More specifically I can login, but then run into an AADSTS50011 error. Tried multiple different tenants, different browsers, private sessions and whatnot - same behavior. Removing the Graph explorer app from the tenant and re-consenting to it doesnt change a thing either.

### Expected behavior
Be able to login with my org id

### Actual behavior
![image](https://user-images.githubusercontent.com/38553333/82416064-1fe8d500-9a82-11ea-847f-1023a23b8b47.png)

### Steps to reproduce the behavior
Hit the Sign in to Graph explorer button, try to complete the login process

**Comment by bettirosengugi** [comment]
@michevnew What url of Graph Explorer were you using?

**Comment by michevnew** [comment]
I was using the "standard" one, https://developer.microsoft.com/en-US/graph/graph-explorer/. I've actually seen few folks reporting the same issue since, and I believe it might have been browser-dependent (could repro it with Firefox and IE, but not Chrome). In any case, it seems to be working fine now with Firefox, so you can go ahead and close this.

**Comment by michevnew** [comment]
Aaaaaaaaaand we're back to having the same experience, this time I can log in just fine, but if I try to modify the permissions/consent I run into the same AADSTS50011 error. Using Firefox.
