### ISSUE TITLE
Graph Explorer Preview version does not render image on me/photo/$value

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-explorer-v4#602]
Use the issues in this repository to open issues about the Graph Explorer application. Questions about the Microsoft Graph should be directed to StackOverflow. Use the [microsoftgraph] tag on StackOverflow.

### Expected behavior
Should render the photo as in the original version of Microsoft Graph Explorer.

### Actual behavior
Empty json value is returned instead:  {}

### Steps to reproduce the behavior
Perform a get request to https://graph.microsoft.com/v1.0/me/photo/$value  -- in production version, an image is rendered.  In the preview version, just the empty json is returned.

**Comment by bettirosengugi** [comment]
@RayGHeld this is now resolved here: https://developer.microsoft.com/en-us/graph/graph-explorer
