### ISSUE TITLE
Webhook Subscription for Teams Conversation not working with WCF Relay

### ISSUE THREAD

**Issue by webdevelperify** [microsoftgraph/microsoft-graph-explorer-v4#604]
Hi,

Can someone please help me to fix this Issue. I am not able to debug from where it is going wrong. Basically I have created a WCF Rest API WebService using WCF Relay in Azure to have hybrid connection between on-premise and Azure. Also if I am ignoring any certificate validation, that endpoint is for on-premise as it is self-signed certificate but when making API call, I am using the base64 encoded public key provided by WCF Relay when publishing it in Azure.

**WCF Contract And Implementation:**

**_Contract Interface_**
![image](https://user-images.githubusercontent.com/30578236/76708020-c5499a80-6719-11ea-9e3d-c0bca4ff2913.png)

**_Implementation_**
![image](https://user-images.githubusercontent.com/30578236/76708028-d8f50100-6719-11ea-9b1d-32c61545dcb1.png)

I am successfully able to get the "validationToken" in the WCF service and also returning the same validationToken immediately below 5 seconds. After returning, it always error out showing this message.

**_Postman Client For Sending HTTP Request_**
![image](https://user-images.githubusercontent.com/30578236/76708149-a7c90080-671a-11ea-9661-1bb78a04ea33.png)

**_Error Response and no subscription created_**
![image](https://user-images.githubusercontent.com/30578236/76708058-fd50dd80-6719-11ea-8976-e5499185d45a.png)

Thank you in advance for all the help.

**Comment by ddyett** [comment]
please post this question to stackoverflow as we are not able to help on this issue.
