### ISSUE TITLE
Add "intellisense" and sample for /teams/{teamId}/primaryChannel

### ISSUE THREAD

**Issue by pschaeflein** [microsoftgraph/microsoft-graph-explorer-v4#605]
The `primaryChannel` relationship for the team resource type was added in January 2020. Add this to the intellisense/prompt when entering a url and a sample.

https://docs.microsoft.com/en-us/graph/changelog?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#january-2020

https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0#relationships 
[AB#7532](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7532)

**Comment by ddyett** [comment]
related to #480
