### ISSUE TITLE
Example Query and end-point Broken for Create-Thread for Teams

### ISSUE THREAD

**Issue by paddymccallan** [microsoftgraph/microsoft-graph-explorer-v4#606]
The following end-point that can be found on graph-explorer errors out >
`https://graph.microsoft.com/beta/teams/{team-id}/channels/{channel-id}/chatThreads.`
### Expected behavior
Response ok : 200

### Actual behavior
```
{
"error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'chatThreads'.",
    "innerError": {
        "request-id": "8cd24e52-f0eb-4203-bc63-0de4f358c863",
        "date": "2020-01-24T10:53:02"
    }
}
```

### Steps to reproduce the behavior
Link to graph explorer to reproduce - [Graph-Explorer, Preview.](https://developer.microsoft.com/en-us/graph/graph-explorer)
Navigate to create channel thread and follow example request.

![image](https://user-images.githubusercontent.com/43668273/73066639-7b250500-3e9e-11ea-9cdb-322adb105a55.png)

**Comment by ddyett** [comment]
not present in the newer graph explorer.
