### ISSUE TITLE
Certain default values returning null

### ISSUE THREAD

**Issue by nexxai** [microsoftgraph/microsoft-graph-explorer-v4#608]
Use the issues in this repository to open issues about the Graph Explorer application. Questions about the Microsoft Graph should be directed to StackOverflow. Use the [microsoftgraph] tag on StackOverflow.

### Expected behavior

Let's say I have a user "js123456@domain.com" and I have an administrator "admin@domain.com" who has User.ReadBasicAll permissions to the domain.

If I visit the https://graph.microsoft.com/v1.0/users/js123456@domain.com endpoint while logged in as 'admin@domain.com', I expect:

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "businessPhones": [],
    "displayName": "Joe Smith",
    "givenName": "Joe",
    "jobTitle": "Senior Analyst, Analysis Services",
    "mail": "joe.smith@domain.com",
    "mobilePhone": "123-456-7890",
    "officeLocation": "The Moon",
    "preferredLanguage": "en-US",
    "surname": "Smith",
    "userPrincipalName": "js123456@domain.com",
    "id": "1532477f-026d-4742-ab6e-6c1796521530"
}
```

I do not believe we've set any special permissions on those fields that are returning `null`, nor would I even know how to do such a thing.

### Actual behavior
When I run the query, I get back:

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "businessPhones": [],
    "displayName": "Joe Smith",
    "givenName": "Joe",
    "jobTitle": null,
    "mail": "joe.smith@domain.com",
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null,
    "surname": "Smith",
    "userPrincipalName": "js123456@domain.com",
    "id": "1532477f-026d-4742-ab6e-6c1796521530"
}
```

### Steps to reproduce the behavior

1. Log in as a user with User.ReadBasicAll permissions on the domain
2. Look up another user

### HTTP traffic capture
n/a 
[AB#7533](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7533)

**Comment by bettirosengugi** [comment]
@nexxai does this still persist in the new graph explorer? you can access it here: https://developer.microsoft.com/en-us/graph/graph-explorer/

**Comment by nexxai** [comment]
Unfortunately I was laid off earlier this year so I no longer have access to my previous company's tenant to test

**Comment by bettirosengugi** [comment]
> Unfortunately I was laid off earlier this year so I no longer have access to my previous company's tenant to test

I'm so sorry @nexxai to hear that. Praying you get something soon.

**Comment by thewahome** [comment]
This seems to have been solved.
