### ISSUE TITLE
Add create schema extension sample

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#609]
Customers are asking for this. 
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/schemaextension 
[AB#7534](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7534)

**Comment by RabebOthmani** [comment]
Samples fall under the workloads responsibilities. Unfortunately, at this time, the GE team doesn't have the capacity to expand on our responsibilities and build samples on behalf of workloads.
