### ISSUE TITLE
Update the Chinese version to latest Graph Explorer

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-explorer-v4#614]
Please update the Chinese version https://developer.microsoft.com/zh-cn/graph/graph-explorer-china.
![image](https://user-images.githubusercontent.com/3375461/34583022-e4a33eb4-f14a-11e7-94be-73a8f5e01eec.png)

to latest Graph Explorer.

(I heard it is because the AzureAD was blocked, but please work on it to get this work)

2121651 
[AB#7539](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7539)

**Comment by RabebOthmani** [comment]
Enabling Graph Explorer to work in different clouds will solve this issue. 
That's an ongoing effort captured on this ticket https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/868
