### ISSUE TITLE
Remove admin permissions by default

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-explorer-v4#615]
I think we should remove admin permissions in UI if the user does have those permissions.

I am using browser private mode to log in my account, you can see it has admin permissions by default, although I actually don't have admin permissions.

And even after I removing these permissions, when I log in again, they are back.

![image](https://user-images.githubusercontent.com/3375461/35193206-3a8b64c6-fe54-11e7-8174-5c3a84795a0b.png)

2121657

**Comment by bettirosengugi** [comment]
@Hongbo-Miao permissions have been implemented differently in the new Graph Explorer, therefore closing this task now. In case you have feedback on the new implementation, please let us know.

Thanks.
