### ISSUE TITLE
Changing Permissions

### ISSUE THREAD

**Issue by mlafleur** [microsoftgraph/microsoft-graph-explorer-v4#616]
When a user changes the selected permissions those changes don't seem to be persisted. I believe this is due to the re-authentication not forcing the user to also re-consent to the new set of scopes. 

Today the code is passing `prompt=select_account` in the query string. From the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-implicit#send-the-sign-in-request), it doesn't look like `select_account` is supported in the v2 Endpoint. Possibly just a carried over option that predate switching to v2?

Regardless, manually switching this to `prompt=consent` successfully results in the new permissions being persisted. 

Would it make sense to switch to `prompt=consent` (at least within the context `scopes-dialog.component.ts`)?  
[AB#7540](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7540)

**Comment by bettirosengugi** [comment]
@thewahome is this resolved in new Graph Explorer?

**Comment by thewahome** [comment]
From what I gather, Graph Explorer:
- Has only these non-admin consent scopes selected - `opened`, `profile`, `User.Read`
- Shows the user's consented scopes vs the scopes required for the user to run a specific query in the Modify Permissions tab
- No longer uses the consent prompt which means a user does not have to reconsent. The only time a consent screen is shown is when the user logs in for the first time or when they want to consent to specific permissions in the permissions lists


@bettirosengugi and @MIchaelMainer I think this can be closed now unless there is anything pending that I may not have understood
