### ISSUE TITLE
Internet Explorer 11 - Microsoft Graph Explorer Fails to load

### ISSUE THREAD

**Issue by evaristobm** [microsoftgraph/microsoft-graph-explorer-v4#621]
**Describe the bug**
With Internet Explorer 11 (version 11.329.19041.0)

**To Reproduce**
1. Open Internet Explorer 11
2. Go to: https://developer.microsoft.com/en-us/graph/graph-explorer
3. You will see the message "Starting the Microsoft Graph Explorer..." but the tool never loads.

**Expected behavior**
Tool should launch as it does in Microsoft Edge, Chrome or Firefox.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 (OS Build 19041.329)
 - Browser Internet Explorer
 - Version 11.329.19041.0

**Additional context**
Reproduced the problem in other computers running IE11.
![2020-06-30 16_19_12-MSN _ Outlook, Office, Skype, Bing, Breaking News, and Latest Videos - Internet ](https://user-images.githubusercontent.com/52426613/86183077-74a25580-baee-11ea-8cb5-eba4a9c11630.jpg)

![2020-06-30 16_20_32-k780-online-setup-guide pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/52426613/86183049-65bba300-baee-11ea-814a-8f7afc48e9ac.jpg)

 
[AB#6256](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6256)

**Comment by adhiambovivian** [comment]
@RabebOthmani  do we have baseline cross-browser support requirement?

**Comment by darrelmiller** [comment]
We do not have a need to support IE 11 for a learning tool.
