### ISSUE TITLE
Supports for PPE and sovereign clouds endpoint?

### ISSUE THREAD

**Issue by lostindark** [microsoftgraph/microsoft-graph-explorer-v4#622]
**Is your feature request related to a problem? Please describe.**
Currently the graph explorer seems only support PROD environments.

**Describe the solution you'd like**
I need a version that can targeting PPE and sovereign cloud endpoints.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
 
[AB#6255](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6255)

**Comment by bettirosengugi** [comment]
@lostindark We have plans to support sovereign clouds, but PPE we do not plan to support it yet unfortunately.

**Comment by lostindark** [comment]
@bettirosengugi Why not PPE? I would image people would like to test against PPE for new features before they went to PROD endpoint. Is adding PPE support a lot of work?

**Comment by darrelmiller** [comment]
@lostindark Because Graph Explorer is a tool for learning how to use Microsoft Graph. It is not designed for 1P teams to use for testing.

**Comment by darrelmiller** [comment]
@adhiambovivian @thewahome This work is out of scope.
