### ISSUE TITLE
Support all different content types and fallback to showing text

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v4#626]
The default behavior should be to render as text.  We should have a case for `application/octet-stream` that doesn't render it as text and just shows a message such as "Binary Response".  Ideally this would allow a download of that binary response.

https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/e3ce0206d787fef1928f2b6821e607996e2773d2/src/app/services/actions/query-action-creator-util.ts#L79-L90

This will fix the rendering of report endpoints that return text/csv and will future proof us for other text formats that might be used.   
[AB#6253](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6253)

**Comment by bettirosengugi** [comment]
Related to this issue: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/598

**Comment by thewahome** [comment]
@darrelmiller @bettirosengugi which endpoints can I call to test binary response queries?

**Comment by darrelmiller** [comment]
If you search for "Edm.stream" in the metadata you will find endpoints that return binary payloads.  Many of the report endpoints return text/CSV https://docs.microsoft.com/en-us/graph/reportroot-concept-overview
The OneNote APIs return and accept text/HTML

**Comment by thewahome** [comment]
> If you search for "Edm.stream" in the metadata you will find endpoints that return binary payloads. Many of the report endpoints return text/CSV https://docs.microsoft.com/en-us/graph/reportroot-concept-overview
> The OneNote APIs return and accept text/HTML

Thanks @darrelmiller
