### ISSUE TITLE
azure pipeline

### ISSUE THREAD

**Issue by Kachulio1** [microsoftgraph/microsoft-graph-explorer-v4#628]
**Is your feature request related to a problem? Please describe.**
Open source contributors don't have access to view azure builds 
 
<img width="1247" alt="Screenshot 2020-07-06 at 00 32 19" src="https://user-images.githubusercontent.com/22243090/86542833-fac10080-bf21-11ea-899d-f37875f12257.png">

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ddyett** [comment]
sorry but you cannot be granted access to that for a number reasons including security.
