### ISSUE TITLE
Response body preview pane extends beyond view port

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#630]
**Describe the bug**
Large response bodies scroll handle goes beyond view port.

**To Reproduce**
1. POST https://graph.microsoft.com/v1.0/me/calendar/getSchedule?$top=5 with a large enough time window that will have many results. https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=http
2. Click on the response body and scroll down. The scroll handle will leave the view port as you scroll down for a sufficiently large response.

**Expected behavior**
The scroll handle stays within view port.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

![GE_ResponsePreview](https://user-images.githubusercontent.com/8527305/86728957-c876d800-bfe1-11ea-8794-88ce4954b89d.gif)
 
[AB#7483](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7483)

**Comment by thewahome** [comment]
This could be handled when #311 is closed. Leaving this link here for validation
