### ISSUE TITLE
Bug in the "share query" button

### ISSUE THREAD

**Issue by aycabas** [microsoftgraph/microsoft-graph-explorer-v4#638]
There is a bug in the "share query" button. When I click the link below link, it is generating the correct query. Here is the link:
https://developer.microsoft.com/en-US/graph/graph-explorer/preview?request=users?$count=true%26$orderby=displayName%26$filter=startswith(officeLocation,%20%2718%27)%26select=id,displayName,officeLocation&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&requestBody=&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d

After clicking the link above, hit "run query", then click on "share query" button. It generates the below link, which is not getting the full query. It only catches the first parameter:
https://developer.microsoft.com/en-US/graph/graph-explorer/preview?request=users?$count=true&$orderby=displayName&$filter=startswith(officeLocation,%20%2718%27)&select=id,displayName,officeLocation&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&requestBody=IiI=&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d
[AB#5814](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5814)

**Comment by thewahome** [comment]
@bettirosengugi can we confirm whether this is still an issue? It could already be solved in the non-preview URL

**Comment by thewahome** [comment]
Closing this. Confirmed that it works well in the full GE experience. 

@aycabas please follow this [link](https://developer.microsoft.com/en-US/graph/graph-explorer?request=users?$count=true%26$orderby=displayName%26$filter=startswith(officeLocation,%20%2718%27)%26select=id,displayName,officeLocation&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&requestBody=&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
