### ISSUE TITLE
Issue with revokesigninsessions API 

### ISSUE THREAD

**Issue by Naakhta** [microsoftgraph/microsoft-graph-explorer-v4#654]
Describe the bug
The 1st call to this API always end up spinning with no result unless any other query is executed first and then attempt to call this API which works fine.
User signs in and make the first call.
https://graph.microsoft.com/v1.0/me/revokeSignInSessions
Result - It ends up spinning with no result.
User makes any random query - example querying his me endpoint.
Result - successful
Attempts for 2nd call to - https://graph.microsoft.com/v1.0/me/revokeSignInSessions
Result - This time the API works fine.
This API has no issues if we make the request from fiddler composer.
Expected behavior
I think it should work every time when user attempts to call irrespective of whether its a first or second request.
[AB#5625](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5625)

**Comment by thewahome** [comment]
This issue seems to have self resolved
