### ISSUE TITLE
Basic Queries Failing Against v1.0 endpoint

### ISSUE THREAD

**Issue by luckerby** [microsoftgraph/microsoft-graph-explorer-v4#656]
Running the "GET my photo" builtin query results in a Bad Request - 400, with the response below:
{
    "error": {
        "code": "AuthenticationError",
        "message": "Error authenticating with resource",
        "innerError": {
            "date": "2020-07-30T10:17:31",
            "request-id": "096aea81-1290-4ade-89c5-9d94f1bb980f"
        }
    }

Switching from the default "v1.0" to the "beta" endpoint results in the query running successfully, and the photo retrieved correctly.
Using Windows 10, Chrome Version 83.0.4103.116 (Official Build) (64-bit).
The "v1.0" endpoint was definitely working in the past. Maybe there's a temporary issue affecting it ?
[AB#5624](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5624)

**Comment by ddyett** [comment]
not able to repro recently.
