### ISSUE TITLE
Create a new pipeline to support auto prod deployment

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#661]
A pipeline to move our code into content repo automatically.
[AB#5622](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5622)
- [x] #1604
- [x] #1521
- [x] #1522
- [x] #1523
- [x] #2289
- [x] #2339
- [x] #2340
- [x] #2341
- [x] #2463
- [x] #2464

**Comment by ddyett** [comment]
@thewahome what's the block on this?

**Comment by adhiambovivian** [comment]
@ddyett  this work requires moving the source code to ADO
