### ISSUE TITLE
When editing request url cursor keeps moving to the end

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#669]
1. Launch graph explorer
2. Enter a url like 'https://graph.microsoft.com/v1.0/me?$select'
3. scroll back with keyboard to try and replace v1.0 with beta

Result: as you hit backspace to delete the 0, the cursor moves to the end so you end up removing prior text

Expectation:  cursor should not be moving.

**Comment by michevnew** [comment]
I get similar behavior when pasting URIs as well, annoying...
