### ISSUE TITLE
Investigate: do we validate/sanitize user input into URL, headers, or request body fields

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#671]
Can history data be mucked with via an injected script in IndexDB? 
[AB#6252](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6252)

**Comment by thewahome** [comment]
> Can history data be mucked with via an injected script in IndexDB?
> [AB#6252](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6252)

@MIchaelMainer 

Being able to access/change data local to your own browser in your computer is does not pose a security threat. If another user was able to access data in the localStorage/indexeddb then that would be risky. However it is safe to say that indexeddb is safe. 

Would there be any use in trying to encrypt the data we store?

**Comment by thewahome** [comment]
We are taking advantage of React's built in [sanitisation](https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks). 

"By default, React DOM escapes any values embedded in JSX before rendering them. Thus it ensures that you can never inject anything that’s not explicitly written in your application. Everything is converted to a string before being rendered. This helps prevent XSS (cross-site-scripting) attacks."
