### ISSUE TITLE
Contextual Tip Information

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/microsoft-graph-explorer-v4#68]
Based on this [issue](https://github.com/microsoftgraph/microsoft-graph-explorer/issues/284) 
[AB#7513](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7513)

**Comment by bettirosengugi** [comment]
@jobala Can you provide more information on this issue?
