### ISSUE TITLE
Entering multiple '/' triggers HTTP requests to the back end. 

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#683]
**Describe the bug**
Entering multiple '/' triggers HTTP requests to the back end. 

**To Reproduce**
1. Open dev tools
2. Enter https://graph.microsoft.com/v1.0/me//
3. Notice two network calls are made

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#7485](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7485)

**Comment by ddyett** [comment]
is this graph explorer or the js sdk?

**Comment by thewahome** [comment]
> is this graph explorer or the js sdk?

On graph explorer in the autocomplete component

**Comment by ezkemboi** [comment]
@thewahome, I am trying to probably get some understanding of expected behavior on this issue. 
I have raised a PR that just terminates the process if more than one slash at the end of the URL is present. 
But, I am open to more discussion on what is expected e.g show msg, etc.
