### ISSUE TITLE
Add documentations and icons to suggestions

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#684]
**Is your feature request related to a problem? Please describe.**
Consider adding Documentation and special icons for entities, functions.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Similar to different colors and icons on VSCode
![image](https://user-images.githubusercontent.com/58787602/92480223-45dee480-f1ed-11ea-9a6b-79c889dc3521.png)

 
[AB#6251](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6251)

**Comment by RabebOthmani** [comment]
Work on the auto-complete experience planned for Q2.
