### ISSUE TITLE
Using unsupported host in query causes GE app to disappear

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#687]
Describe the bug
Using an unsupported host causes GE to disappear when I try to run the query. This requires me to reload the page to continue to use GE.

Running this query results in
[AB#6064](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6064)

**Comment by ElinorW** [comment]
I believe this has been fixed. 
The page no longer crashes and will instead return a response code.
Closing this issue.
