### ISSUE TITLE
Investigate and implement use of MSAL.js 2.0 which is now available

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#688]
The authentication library we use on Graph Explorer just released version 2.0 that has improvements. For this reason there is need to investigate how we can implement the new version and replace the old one and take up the process of implementing this. The materials are available here: 
1. https://developer.microsoft.com/en-us/microsoft-365/blogs/msal-js-2-0-supports-authorization-code-flow-is-now-generally-available/
2. https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser 
[AB#6235](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6235)

**Comment by ddyett** [comment]
investigating using token credential support here instead.

**Comment by MIchaelMainer** [comment]
We should check that token credential supports MSAL 2.0 Authorization Code flow with PKCE. We need that to support Microsoft Graph conditional access policy. We believe that the implicit auth flow does not support conditional access policy and will be a blocker for organizations that implement conditional access policy.

https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/373

**Comment by nikithauc** [comment]
https://github.com/Azure/azure-sdk-for-js/issues/13080 <- 
Token Credential support for Auth Code Flow with PKCE can be tracked h

**Comment by murdockcrc** [comment]
Looking for this one too, as we moved to msal-browser and AuthCode flow in December and cant build a dependency on the legacy Msal. Thx
