### ISSUE TITLE
Feedback Bar for samples with clickable link

### ISSUE THREAD

**Issue by Licantrop0** [microsoftgraph/microsoft-graph-explorer-v4#693]
We need a new type of Message Bar in graph explorer that allows requesting feedback to our customers for specific queries.
Overview: [Onboarding survey to Graph Explorer](https://microsoft-my.sharepoint-df.com/:w:/p/sanooran/ERs8P6XhlzRCoLSQpFfcqYQBxEy4saBV-r3RvjZHjJynxg?e=22B1ZD)

This is the first Pull request attempting at this, using the Tip bar: https://github.com/microsoftgraph/microsoft-graph-devx-content/pull/51

**Requirements for the new Feedback Message Bar**

1. Allow clickable URL formatting (with Markdown, HTML code, or a custom tag you decide). This is needed for opening the survey.
2. All the links will be opened by default in a new tab.
3. Show the feedback bar independently of the user login: it should be shown even with the demo tenant data.
4. The message bar should persist after the user clicks "Run query".
5. The message bar should dismiss only when:
  - The user changes a sample
  - The user clicks X to close the bar.
  - The user clicks the link to open the survey.
6. If the user clicked the link or dismissed the bar with the X, the Message bar *for that sample* should not appear anymore. This can be achieved by storing a LOCAL cookie with the id of the sample when the user clicks the link or dismiss the feedback bar:
  - If the cookie is present next time the user clicks the sample, the feedback bar will not be shown.
  - If the user clears their cache / cookies, then the feedback bar will be shown again, nothing related to the user data should be store server-side.

@thewahome @bettirosengugi
[AB#6062](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6062)

**Comment by sanana30** [comment]
hi @thewahome @MaggieKimani1 - any details on when this can be implemented? My team is very interested in this feature. Thanks!

CC: @bettirosengugi

**Comment by MaggieKimani1** [comment]
Hey @sanana30, sorry for the delay in reply.
I am currently working on this.

**Comment by Licantrop0** [comment]
@thewahome only the first and second requirement were satisfied with your PR.
Where are all the rest?

**Comment by bettirosengugi** [comment]
@Licantrop0 The goal was to make the feedback link clickable and open on an new tab. The tips message is used by other query samples to share information on how they can get the id described in the URL therefore we cannot modify it further to store user data. 
CC: @thewahome

**Comment by Licantrop0** [comment]
That's why we would need a new type of message bar that can satisfy all the requirements.
The fact that the tip bar is only displayed to logged users and disappears when the user press "run query" is a really bad experience.

**Comment by thewahome** [comment]
Reopening this so that we can track it. The issue that gets closed is issue #862
