### ISSUE TITLE
Can't select method other than GET

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/microsoft-graph-explorer-v4#700]
When building the request, it's not possible to select any other method than GET.

**To Reproduce**
1. Go to Graph Explorer
2. Click on GET
3. See error

**Expected behavior**
Be able to select any request method

**Screenshots**
![image](https://user-images.githubusercontent.com/11164679/93427318-eb651880-f8bd-11ea-9061-a652da741fbe.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 85
 
[AB#7487](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7487)

**Comment by thewahome** [comment]
This happens when you are not logged in. Once you log in, you will be able to make use of the other request methods

**Comment by waldekmastykarz** [comment]
Got it. It would be helpful if the UI make this clear.
