### ISSUE TITLE
Store Access Tokens In Cookies

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/microsoft-graph-explorer-v4#702]
Storing access tokens in local storage exposes the user to XSS attacks, instead we should store tokens in cookies. You can learn more [here](https://stackoverflow.com/a/54258744/9941680)
 
[AB#6248](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6248)

**Comment by thewahome** [comment]
We now acquire the token silently each time we intend to show it in the Auth tab. It is not stored anywhere. We are now safe :-)
