### ISSUE TITLE
Graph links in tip messages to populate the url address bar

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#705]
### Is your feature request related to a problem? Please describe.
A sample query may contain a tip message that describes what to do with the query. A common scenario is a query can have a **token** to display an item in the url that can be replaced eg `{message-id}` or `{task-id}`. A tip message is used here to tell the user what query to run in order to get the data to replace the **token** with.

The user then highlights the url in the tip message, copies it into the url editor and runs the query to get the data they can use to replace the **token**.

### Describe the solution you'd like
The ask here is that once a tip message is displayed, the url described in the message can be made clickable and once clicked, it should replace the url displayed on the url editor

### Describe alternatives you've considered
Leaving it as is and letting the user copy the link and paste it themselves
[AB#6125](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6125)

**Comment by ddyett** [comment]
can you describe the problem a little clearer.
