### ISSUE TITLE
Share button should store context of tab selected

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-explorer-v4#709]
If I run "my profile" sample and then select the Microsoft Graph Toolkit tab or Code Snippets tab. The Share button does not store that context. So sharing doesn't exactly share the view you're on. 
[AB#6247](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6247)

**Comment by RabebOthmani** [comment]
Hi @jthake-msft , the placement of the share button was confusing that's why we moved it near the query field.
