### ISSUE TITLE
Enable version suggestion (autocomplete) on the GE address bar

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#715]
At the moment, autocomplete only works after version selection, this feature request is to enable version selection as a suggestion in Graph Explorer, with the options at the moment being v1.0 and beta. when this is provided, we can remove the version selector on the UI, and increase the space for the address bar on Graph Explorer like in the screenshot below: 
![image](https://user-images.githubusercontent.com/4668452/94271361-33351100-ff4a-11ea-9587-271d4519a3a2.png)
 
[AB#6245](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6245)

**Comment by ddyett** [comment]
@bettirosengugi i'm not sure what this looks like. Are you saying that we only provide the host name in the address bar and the user always has to choose the version?

**Comment by bettirosengugi** [comment]
> @bettirosengugi i'm not sure what this looks like. Are you saying that we only provide the host name in the address bar and the user always has to choose the version?

Autocomplete only works after you type in the version, this feature request is to do 2 things:
1. Enable version selection in Autocomplete i.e. suggestions start after https://graph.microsoft.com and not https://graph.microsoft.com/v1.0/
2. When this is enabled remove the version selector from GE to create more space for the address bar.

**Comment by darrelmiller** [comment]
@ddyett  I would suggest just defaulting the URL to V1, just like we default the combobox to v1 today.  The point is, why have two ways to edit the same thing when the combobox takes up so much valuable space from the URL.
