### ISSUE TITLE
Autocomplete doesn't collapse onFocusOut

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#721]
**Describe the bug**
Autocomplete dropdown UI doesn't auto close when the address bar loses focus.

**To Reproduce**
1. Add a `/` in the URL bar
2. Click on any place else in the UI
3. See that the autocomplete UI doesn't close

The only way autocomplete closes is if I select an autocomplete option.

**Expected behavior**
When the URL bar loses focus, autocomplete dialog closes. 

**Screenshots**

![image](https://user-images.githubusercontent.com/8527305/95103608-a9273e00-06e9-11eb-8823-faccc1164a50.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browsers: Edge and Chrome

 
[AB#7463](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7463)

**Comment by thewahome** [comment]
Noted. You can also close by hitting escape
