### ISSUE TITLE
Autocomplete only triggers on `/`

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#722]
**Describe the bug**
Autocomplete is not resumeable once I type a character past `/`. So, let's say I autocomplete to `https://graph.microsoft.com/v1.0/me/calendar`, but realize I want to see `CalendarGroups` or `calendarview`, there doesn't appear to be a key chord to resume autocomplete. I suggest the following enhancements:

- resume autocomplete on `ctrl + space`. VS Code uses that bringing up a context menu. I believe that chord is used in other IDEs.
- each keystroke should result in a filtered view of autocomplete options. So, when I type `https://graph.microsoft.com/v1.0/me/c`, the only options I should see are `calendar`, `calendarview`, `calendargroups` `calendars`.

**To Reproduce**
1. Paste `https://graph.microsoft.com/v1.0/me/c` in the URL.
2. No autocomplete until I delete the trailing 'c' or I add a `/` character. 

**Expected behavior**
I get autocomplete based on all characters that are valid for OData URLs. For now, I'd be happy with alphabetic characters.

**Desktop (please complete the following information):**
 - Browser Chrome and Edge
 
[AB#6320](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6320)

**Comment by thewahome** [comment]
Adding a relation to #685
