### ISSUE TITLE
Autocomplete doesn't filter sensitive information

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#723]
**Describe the bug**
Autocomplete is required to make use of URL filtering. We send URLs in a wholesale manner. We need to 1) only send the URL pattern, 2) make sure the API does not log URLs in case we do send them.

**To Reproduce**
1. Open Fiddler, capture it all.
2. Enter the following in to the URL box `https://graph.microsoft.com/v1.0/users/CEO@contoso.com/`.
3. See us send URL data

![image](https://user-images.githubusercontent.com/8527305/95106734-bcd4a380-06ed-11eb-9d53-890ff3a7eeff.png)

**Expected behavior**
We only send the URL pattern, not the actual data

**Comment by ddyett** [comment]
@MIchaelMainer  the second point is definitely true I don't know that there is a requirement on the first part.   If that is the case then we have to change design here and/or update policy documents.  If we think there's a requirement here then we need to consult with the relevant contacts before we can move this.

Marking this blocking for now until we can have a resolution.

**Comment by thewahome** [comment]
This is fixed in #755
