### ISSUE TITLE
Autocomplete should cache URL patterns

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#724]
**Describe the bug**
Autocomplete doesn't cache the results for a URL pattern. I see it making repeat APIs calls for the same URL pattern. 

**To Reproduce**
1. Open Fiddler, capture
2. Type `https://graph.microsoft.com/v1.0/users/123/`, delete `123/`, the add `123/`.

**Expected behavior**
No new API call is made as we already downloaded the autocomplete suggestions for that URL pattern.
 
[AB#6318](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6318)

**Comment by thewahome** [comment]
Working on this together with #723
