### ISSUE TITLE
$whatif not working on Graph Explorer

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#729]
**Describe the bug**
$whatif does not work for Microsoft tenant in Graph Explorer
**To Reproduce**
1. Go to Graph Explorer while not logged in 
2. Paste this: https://graph.microsoft.com/v1.0/me?$whatif
3. This works
4. Try the same query while logged in Microsoft tenant
5. Fails.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thewahome** [comment]
The microsoft graph sdk version should fix this. We have tested $whatif with @nikithauc

**Comment by ddyett** [comment]
@thewahome is the linked pull request here correct?  Isn't the change needed here to pick up the next JS sdk version?

**Comment by thewahome** [comment]
> @thewahome is the linked pull request here correct?  Isn't the change needed here to pick up the next JS sdk version?

The linked pull request should bring in the latest JS sdk version.
