### ISSUE TITLE
Some queries are not showing the response preview when returning an error

### ISSUE THREAD

**Issue by Licantrop0** [microsoftgraph/microsoft-graph-explorer-v4#737]
1. Login with @Microsoft.com Account
2. Try [this query](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%2F000009ff-86bc-4d4e-bc71-9678ded3be28%2FtransitiveMembers%2F%2Fmicrosoft.graph.user%3F%24select%3Did%2CdisplayName&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
3. see that only the error bar is displayed, not the response content:
![image](https://user-images.githubusercontent.com/2388430/95925927-e174ef00-0d6f-11eb-9de9-38a9225ae3b8.png) 
[AB#7465](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7465)

**Comment by ddyett** [comment]
response body is returned from service so I would expect it to appear.

**Comment by thewahome** [comment]
Closing this as it is resolved in v4.12.0
