### ISSUE TITLE
Query Not working in Graph explorer, but ok in Postman

### ISSUE THREAD

**Issue by Licantrop0** [microsoftgraph/microsoft-graph-explorer-v4#738]
try running this query in graph explorer:

`https://graph.microsoft.com/beta/me?$expand=manager($levels=max;$select=displayName)&$count=true&$select=displayName`

then try in postman.

**Comment by thewahome** [comment]
Hi @Licantrop0, this issue fixed by [release v4.1.10](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/releases/tag/v4.1.10) and is live now
