### ISSUE TITLE
If pop ups are blocked, show the correct error message or use redirect authentication

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#753]
Some browsers block pop ups when trying to login to Graph Explorer. The error message displayed when authentication fails because of this is not descriptive enough to empower a user to resolve it. therefore the need to either:

1. Display a descriptive error message when this happens or
2. initiate a  redirect method to authenticate the user 
[AB#7469](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7469)

**Comment by ezkemboi** [comment]
@bettirosengugi I tried this in `Safari` and the error message is `Authentication failed - popup window_error`

Here is are some screenshots of some consoles I did to `reproduce what might be the cause` and `maybe a possible solution to the problem`. 

## Error on Safari and logs
 ![Screenshot 2020-11-09 at 20 11 25](https://user-images.githubusercontent.com/48981919/98574308-d22e8600-22c8-11eb-8274-922bc95f8de1.png)

## Possible lines of code to fix the issue

 ![Screenshot 2020-11-09 at 20 20 47](https://user-images.githubusercontent.com/48981919/98574517-1457c780-22c9-11eb-8f08-e6619760b27b.png)

**Comment by thewahome** [comment]
@bettirosengugi would you say that @ezkemboi has completed the task or should we also do the redirect action?

**Comment by bettirosengugi** [comment]
thanks @ezkemboi for helping with this.
