### ISSUE TITLE
Add the right error message to GET Org Branding endpoint signaling accept language header is needed

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#756]
If you run this query https://graph.microsoft.com/beta/organization/{org-id}/branding without adding Accept-language:default header, the call fails in Graph Explorer. 

Request: Add the right error message letting the user know the header is needed for it to run or add the header automatically whenever the query is typed on the address bar in Graph Explorer
 
[AB#7470](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7470)

**Comment by darrelmiller** [comment]
This is a badly designed API that should not return this 404 error when the Accept-Language is not provided.  However, Graph Explorer should not hide this bad design as that would not be help the user learn how to use the API.
