### ISSUE TITLE
feedback:  getOffice365ActiveUserDetail api does not work in graph explorer

### ISSUE THREAD

**Issue by StefanFried** [microsoftgraph/microsoft-graph-explorer-v4#779]
result is empty  (likely because it's returning  csv format) 
[AB#7476](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7476)

**Comment by ddyett** [comment]
@ElinorW @finsharp @thewahome can we push on getting this addressed.  Can you add more detail on what's causing the problem?

**Comment by thewahome** [comment]
This is related to #814

**Comment by finsharp** [comment]
Issue Reference: 
- https://www.chromestatus.com/feature/4614142321229824
- https://github.com/github/fetch/issues/137#issuecomment-168261010
