### ISSUE TITLE
Add a link to this github repo on aka.ms/ge

### ISSUE THREAD

**Issue by maliksahil** [microsoftgraph/microsoft-graph-explorer-v4#786]
**Is your feature request related to a problem? Please describe.**
If people run into issues or have feature requests for graph explorer, they should be easily able to find this repo and submit issues here. It may help to include a link to this repo on aka.ms/ge

**Describe the solution you'd like**
include a link to this repo on aka.ms/ge

**Describe alternatives you've considered**
Currently you have to google bing the repo, and you are taken to the old repo, then you click to get to the new repo, find issues tab. You do have links for facebook, twittter, teams, might as well add github too.

**Additional context**
 
[AB#7478](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7478)

**Comment by ddyett** [comment]
related to #771
