### ISSUE TITLE
The Url should be trimmed before being executed

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-explorer-v4#788]
**Describe the bug**
If a space is present in front of the URL GE will query `https://%20graph.microsoft.com/v1.0/me` instead of `https://graph.microsoft.com/v1.0/me`.

Inadvertently adding a space is common when you copy/paste things.

**To Reproduce**
1. Open GE
2. Add a space in front of the URL to query i.e ` https://graph.microsoft.com/v1.0/me` (note the space in front)
3. Run the query
4. the request fails

**Expected behavior**
GE to trim spaces on the URL so the request succeeds. 
[AB#7480](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7480)

**Comment by ElinorW** [comment]
Hey @baywet 
when I add a space before the GE query as such ' https://graph.microsoft.com/v1.0/me', the query runs just fine. Is this what you meant?

**Comment by baywet** [comment]
See the following screencap.

https://user-images.githubusercontent.com/7905502/145043134-8f1798fb-286e-4495-b558-e431b4a265a1.mp4
