### ISSUE TITLE
Need Admin Approval has been granted but Graph Explorer still won't connect

### ISSUE THREAD

**Issue by pagejustin** [microsoftgraph/microsoft-graph-explorer-v4#789]
**Describe the bug**
Graph Explorer does not work despite being granted Admin Access in Enterprise Applications within portal.azure.com. Specific users may even be assigned to the applications and they cannot sign in either.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Click on 'Sign-in to Graph Explorer'
3. Pop-up presents "Pick an account." Select organization's account.
4. User presented with Need Admin Approval
5. Verify Admin consent at Graph explorer (official site) | Permissions in the portal.azure.com
6. Verify Users in Graph explorer (official site) | Users and groups
7. Verify Enterprise Applications User settings in https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/UserSettings/menuId/
7. Entered ticket with Microsoft "120070924004860 - Issue with Graph Explorer"
8. Advised to report bug: "Hope you are doing great. Apologies for the long delay. I did some research and reached out to another engineer from Authentication team as well. We tried reproducing in both our labs. I recently got an another case with the same issue and wen I ran this question through my team , I was advised to ask you to raise a bug against the Graph Explorer and here is how you can do it."

**Expected behavior**
Sign into Graph Explorer and use

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windos
 - Browser Chrome, Edge(Chrome)
 - Version years 2020+

**Context
 - GCC client
 
[AB#7481](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7481)

**Comment by ddyett** [comment]
@bettirosengugi have we seen any other reports coming in around this?

**Comment by bettirosengugi** [comment]
> @bettirosengugi have we seen any other reports coming in around this?

Haven't seen this either, though its not clear if it's a login issue (user cannot login) or a permissions issue (user cannot consent to certain permissions) @pagejustin please clarify.

**Comment by pagejustin** [comment]
I can login. Our Global Admin has granted permissions for the organization. He has added me and 4 other people users of the application. None of us can use the application and are continually prompted with "Need Admin Approval." Within portal.azure.com -> Home->Enterprise Applications->Graph explorer (official site) | Permissions Type: delegated; Granted through: Admin consent; Granted by: An Administrator for all permissions. Self-service is not allowed. Again, we opened a ticket with Microsoft and their resolution was to ask us to put in a bug fix request.

**Comment by thewahome** [comment]
@pagejustin is this still a problem for you?

**Comment by thewahome** [comment]
Thanks for the prompt response @pagejustin
I'll be closing it coz it was quite niche. If anyone else encounters the same problem they'd be free to reopen this
