### ISSUE TITLE
Remove IDs from the url when fetching permissions

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#793]
**Is your feature request related to a problem? Please describe.**
A URL sent to the permissions endpoint could have user data. To re-enable telemetry on the devx API, we need to redact the information from the URL similar to work done in auto-complete.

**Describe the solution you'd like**
Sanitize the URL before sending it to the devx API

**Describe alternatives you've considered**
Current: Turn off telemetry in the devx api

**Additional context**
This may not fully allow turning on telemetry for the Devx API since more work may be needed there. But the blocker from Graph Explorer would be removed
 
[AB#7597](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7597)

**Comment by ddyett** [comment]
i thought this was done already?  If not we should work on this one shortly.
