### ISSUE TITLE
filter/search on profile feature in the Users API

### ISSUE THREAD

**Issue by aishwaryaumachandran** [microsoftgraph/microsoft-graph-explorer-v4#810]
**Is your feature request related to a problem? Please describe.**
It is related to an improvement on notes and profile feature of users
Currently the search/filter query does not allow us to build queries for users/../profile. With this feature if a user has certain interests to lookup someone, it would be a feature that would benefit certain integrations. 

eg. If a user searches for someone with Photography interests. With the filter/search the user's who have photography in their bio can be retrieved 
[AB#7768](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7768)

**Comment by ddyett** [comment]
this sounds like a feature request to the service APIs which we cannot assist with.  I would recommend posting on Microsoft QnA.
