### ISSUE TITLE
graph explorer contains an unecessary semi colon

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-explorer-v4#812]
Steps:
1. Open GE
2. Scroll to the bottom
(see screenshot attached)

after `#root > div > div > div.col-xs-12.col-sm-12.col-lg-9.col-md-8 > div:nth-child(3) > div`

![image](https://user-images.githubusercontent.com/7905502/105866158-b0889500-5fc1-11eb-8cae-371b060f36ec.png)
 
[AB#7789](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7789)

**Comment by ElinorW** [comment]
This was fixed on the PR linked above.
