### ISSUE TITLE
AuditLog.Read.All permissions cannot be added when selecting user's signInActivity

### ISSUE THREAD

**Issue by Licantrop0** [microsoftgraph/microsoft-graph-explorer-v4#821]
if you run this query:
https://graph.microsoft.com/beta/users?$select=displayname,userprincipalname,signInActivity

and then go to the Modify Permission Tab, there is no option to consent to AuditLog.Read.All 

![image](https://user-images.githubusercontent.com/2388430/106175075-8dd5b800-614a-11eb-83ba-5fb589f2a66d.png) 
[AB#7853](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7853)

**Comment by ElinorW** [comment]
@Licantrop0 At the moment the "Modify Permissions" tab is in preview and may not show all the permissions for some queries. 
For the time being, you could consent to the **AuditLog.Read.All** permission by clicking on the Settings icon located next to your profile and from the dropdown menu "Select Permissions" to search and view a list of all permissions.

**Comment by Licantrop0** [comment]
Thanks for the suggestion, it was not very intuitive.
Maybe a button "**Add other permissions**" within the Modify Permissions tab would have been more user friendly.

**Comment by ElinorW** [comment]
@Licantrop0 
This is a great suggestion. I will discuss it with the team
Thank you.
