### ISSUE TITLE
Try-it button opens a blank window in some concept topics in Microsoft Graph docs

### ISSUE THREAD

**Issue by angelgolfer-ms** [microsoftgraph/microsoft-graph-explorer-v4#843]
**Describe the bug**
Try-it button appears in some concept topics in Microsoft Graph docs but opens a blank window, like [enable online meeting in Outlook](https://docs.microsoft.com/en-us/graph/outlook-calendar-online-meetings), [share or delegate calendar](https://docs.microsoft.com/en-us/graph/outlook-share-or-delegate-calendar).

**To Reproduce**
1. Open this topic in a browser: https://docs.microsoft.com/en-us/graph/outlook-share-or-delegate-calendar
2. Scroll down to the first REST query example (GET https://graph.microsoft.com/beta/users/AlexW@contoso.OnMicrosoft.com/calendar/calendarPermissions).
3. Click the Try It button.
4. Wait for a minute to verify that nothing is going to be displayed in the right pane in the browser.

**Expected behavior**
If the snippet tool enables the try-it capability in a concept topic (inserts the ```msgraph-interactive tag) and inserts the try-it button for an example REST request, then clicking the button should open Graph Explorer side-by-side on the right pane in the browser.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 
 - Version 88.0.705.63 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
![Blank try-it pane in concept topic](https://user-images.githubusercontent.com/12191822/107622259-77c8fc80-6c0c-11eb-89a9-a6741c6909d0.jpg)

 
[AB#8114](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8114)

**Comment by thewahome** [comment]
Had a chat offline with @angelgolfer-ms 
The work from the team running the try-it experience from the `concept` docs would simply be to pass an empty list of permissions since the concept pages do not have a permissions block

**Comment by thewahome** [comment]
The experimental fix to make the permissions optional failed

**Comment by thewahome** [comment]
The docs team has agreed to tackle the problem and has created a work-item [here](https://ceapex.visualstudio.com/Engineering/_workitems/edit/435763). We will close this once they are done.
