### ISSUE TITLE
$metadata results not getting formatted by Monaco

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#858]
If you run this query on GE:
https://graph.microsoft.com/v1.0/$metadata

The results get returned unformatted as below:
![image](https://user-images.githubusercontent.com/4668452/108490953-6048de00-72b4-11eb-9e87-b6545949316d.png)
 
[AB#8215](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8215)

**Comment by ddyett** [comment]
test
