### ISSUE TITLE
Additional changes on the Adaptive cards tab

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#865]
The following changes were suggested to the Adaptive cards tab:
1. Change the name of the JSON Schema tab to **JSON template** (**small t)
2. Add a link to adaptive cards designer on the banner so the text is "Get started with adaptive cards on [Adaptive cards templating SDK](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk) and experiment on [Adaptive cards designer](https://www.adaptivecards.io/designer/)"
3. Show the code before the binding happens so developers can just copy and paste in their apps
4. Add a copy button on the code tab 
[AB#8311](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8311)

**Comment by thewahome** [comment]
Seems the copy button on the code tab already exists
![image](https://user-images.githubusercontent.com/58787602/109196788-33f9f980-77ad-11eb-958f-5ab2f95ade18.png)
