### ISSUE TITLE
Enable Graph Explorer to support sovereign/national clouds

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#868]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
 
[AB#8314](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8314)

**Comment by adhiambovivian** [comment]
Related to #614
