### ISSUE TITLE
Graph Explorer not showing error response

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#870]
**Describe the bug**
Graph Explorer is not showing an error response in the response preview. It is also showing the incorrect HTTP status code in the message bar. The actual response was a 200 with an error response body.

**Note:** this is a good test case for our client libraries. This is likely an issue in the JS client in its handling of error responses, @nikithauc . We should still make sure that Graph Explorer does the correct thing in showing the actual response and status code.

**To Reproduce**
1. Go to Graph Explorer with this [link](https://developer.microsoft.com/en-us/graph/graph-explorer?request=roleManagement%2Fdirectory%2FroleDefinitions%3F%24select%3DdisplayName&method=GET&version=beta&GraphUrl=https://graph.microsoft.com).
2. Sign in with a user that can get permissions to make that call.
3. Open Fiddler and filter capture for calls made to Microsoft Graph
4. Send the request.

**Expected behavior**
The request is sent, and the successful response is shown in the response preview pane.

**Actual**
The request is sent, the response preview  pane shows nothing, and the http status code in the message bar is 400.

![image](https://user-images.githubusercontent.com/8527305/109344297-5f1f3000-7823-11eb-81a5-48cd5b63fcd2.png)

Looking at Fiddler capture, we see the information in GE is contradicted by what is actually returned:

```http
HTTP/1.1 200 OK
[deleted response headers]

{"@odata.context":"https://graph.microsoft.com/beta/$metadata#roleManagement/directory/roleDefinitions(displayName)","value":[{"displayName":"Global Administrator"{
  "error": {
    "code": "InternalServerError",
    "message": "The entity instance value of type 'microsoft.graph.unifiedRoleDefinition' doesn't have a value for property 'id'. To compute an entity's metadata, its key and concurrency-token property values must be provided.",
    "innerError": {
      "date": "2021-02-26T18:44:45",
      "request-id": "51283cb4-246c-405c-b1d5-363d9eb32fa3",
      "client-request-id": "28a3cfb8-5cb3-4439-049e-0e9bfaa57686"
    }
  }
}
```

While the status code returned is a service bug and the error response info is not applicable to our clients, we should consider how we handle this in our JS client (and others) and Graph Explorer.  

 
[AB#8332](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8332)

**Comment by ElinorW** [comment]
Similar to #737

**Comment by nikithauc** [comment]
@MIchaelMainer  Is it valid to have a error response body with 200? Or is this a service issue?

**Comment by ElinorW** [comment]
Closing this issue as it seems to be resolved

**Comment by Lew1sX** [comment]
@ElinorW , do happen to know how this was resolved? as I'm seeing the exact same issue
