### ISSUE TITLE
Dark mode should be automatic

### ISSUE THREAD

**Issue by maliksahil** [microsoftgraph/microsoft-graph-explorer-v4#885]
It is hard to discover dark mode - you can pick it up automatically from the OS settings (the browser sends the headers)
 
[AB#8459](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8459)

**Comment by Onokaev** [comment]
Hi @maliksahil. This feature is now available

**Comment by Onokaev** [comment]
We will close this issue. In case of any other concerns, you can still comment on this issue or open another one. 
And thanks for the feature request :)
