### ISSUE TITLE
createDeviceLogCollectionRequest : bad request

### ISSUE THREAD

**Issue by damienvanrobaeys** [microsoftgraph/microsoft-graph-explorer-v4#886]
Hello,

**Context**
I'm trying to run the collect diagnostics device action using graph explorer.
See the [MS doc link](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-createdevicelogcollectionrequest?view=graph-rest-beta
).

**When it works ?**
If I run the action from the portal it works.
You can get the resource path and method using the developer mode.
This one is the following:
https://graph.microsoft.com/beta/deviceManagement/managedDevices('e5bb60c1-be49-44d6-be9a-888a412621b5')/createDeviceLogCollectionRequest

**The issue**
If I copy the same resource path to Graph Explorer with appropriate method, I have the below error:
"code": "BadRequest",
"message": "{  \"_version\": 3,  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 4436d647-461b-53d3-4480-86c16de89eab - Url: https://fef.amsub0202.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices%28%27e5bb60c1-be49-44d6-be9a-888a412621b5%27%29/microsoft.management.services.api.sendCustomNotificationToCompanyPortal?api-version=5020-12-30\",  \"CustomApiErrorPhrase\": \"\",  \"RetryAfter\": null,  \"ErrorSourceService\": \"\",  \"HttpHeaders\": \"{}\"}",

If I try using the Microsoft.Graph.intune i have the same issue.
However if I copy as powershell from the developer mode it works.

The token is not the same between intune portal and graph explorer.
It doesn't use the same client authentication.

- Value is 0 from Graph Explorer and Intune powershell module.
- Calue is 2 from the intune portal

**Reproduce the issue:**
1. Go to Graph explorer
2. Select **API Beta**
3. Select Method **POST**
4. In URI path add
https://graph.microsoft.com/beta/deviceManagement/managedDevices('type a device ID')/createDeviceLogCollectionRequest
5. Click on **Run query** 
[AB#8530](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8530)

**Comment by millicentachieng** [comment]
Please report issue in the [Microsoft Q&A forum](https://aka.ms/askgraph).
