### ISSUE TITLE
Unable to get Graph Explorer API token

### ISSUE THREAD

**Issue by IIrafail** [microsoftgraph/microsoft-graph-explorer-v4#887]
# Bug Report
Unable to get Graph Explorer API token

## Description
Looking at the instructions on the node.js sample page I followed the instructions on how to get the API access token but the `tokenPlease()` function is not defined
[Description of the bug or feature]

**Console Errors:** `tokenPlease() is not defined`

## Steps to Reproduce

1. Go to: developer.microsoft.com/en-us/graph/graph-explorer
2. Login 
3. Open dev console and type `tokenPlease()`
4. `tokenPlease is not defined`

I tried in the latest versions of both Firefox and Chrome 

 
[AB#8548](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8548)

**Comment by MIchaelMainer** [comment]
When a user signs in with a consumer account, the access token is not a JWT. We should still show the token but disable the link to jwt.ms as it can't decode the token. Consider the token opaque.

**Comment by thewahome** [comment]
Is there a direct way to know that it is a consumer account?

**Comment by IIrafail** [comment]
@IIrafail I am using a consumer account, could you please explain how I can get the token to use with my node.js application?

**Comment by IIrafail** [comment]
@MIchaelMainer I am using a consumer account. How can I get the api token to use with my node.js application?

**Comment by thewahome** [comment]
This should be available in the next update as it is fixed by #883
