### ISSUE TITLE
admin can't change permission i.e channel.send

### ISSUE THREAD

**Issue by dhamodar-adappt** [microsoftgraph/microsoft-graph-explorer-v4#891]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#8593](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8593)

**Comment by ElinorW** [comment]
Hey @dhamodar-adappt could you explain more about this issue? 
For example how we can reproduce the behaviour? what the expected behaviour is?

**Comment by thewahome** [comment]
Closing this as no information was added. The issue can be reopened once more info is provided
