### ISSUE TITLE
My Excel Files are not showing up /dating up

### ISSUE THREAD

**Issue by paulbijancoch** [microsoftgraph/microsoft-graph-explorer-v4#893]
**Describe the bug**
When creating a new Excel-Form in OneDrive it does not appear in the Graph Explorer properly.

**To Reproduce**
1. Create a new Excel File Form
2. Search in Graph Explorer (My Files, Recent, Search Items...)

**Expected behavior**
I wanted to see the files and copy its File-ID. 
[AB#8607](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8607)

**Comment by thewahome** [comment]
Hello @paulbijancoch!
You can try this:
- Get the list of items in your OneDrive using this query `https://graph.microsoft.com/v1.0/me/drive/root/children`
- You should find your document there unless it is in a folder
- If your file is in a folder, you get the `id` of the item and use this query. Replace `item-id` with the id you have picked up. `https://graph.microsoft.com/v1.0/me/drive/items/{item-id}/children
