### ISSUE TITLE
Some Beta permissions don't show in consent tab.

### ISSUE THREAD

**Issue by zemuldo** [microsoftgraph/microsoft-graph-explorer-v4#894]
**Describe the bug**
eDiscovery.Read.All and eDiscovery.ReadWrite.All do not show under permissions in compliance beta APIs thus leading to a 401 that seems to be a Graph issue. Until user selects them manually in permissions section.

**To Reproduce**
1. Go to Graph Explorer
2. Click on On samples queries, Select Compliance(beta)
3. Run List ediscovery cases
4. You get 401 even when all permissions in consents tab are consented to. Because eDiscovery.Read.All and eDiscovery.ReadWrite.All are missing

**Expected behavior**
eDiscovery.Read.All and eDiscovery.ReadWrite.All should show in consent tab and be included in the token.
I had to manually select them in the settings/permissions modal and consent to them.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [OSX 11.1]
 - Browser [Microsoft Edge  ]
 - Version [Version 89.0.774.54]

**Additional context**
None 
[AB#8612](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8612)

**Comment by thewahome** [comment]
The error status returned should be 403 and not 401. How do we escalate this? @darrelmiller / @irvinesunday / @bettirosengugi

**Comment by thewahome** [comment]
@zemuldo the modify permissions tab is still in preview. We are continually working to add more permissions to the urls

**Comment by thewahome** [comment]
Closing this since not all permissions are available yet
