### ISSUE TITLE
Graph explorer shows wrong data

### ISSUE THREAD

**Issue by piotrkot** [microsoftgraph/microsoft-graph-explorer-v4#896]
**Describe the bug**
I have a simple web application which enables to log in using oauth2 at microsoft.
The application requests scope "user.read" and retrieves "userPrincipalName" and "displayName". The information fetched from the application is not the same as in the graph explorer (https://graph.microsoft.com/v1.0/me).

**To Reproduce**
It is reproducible from the application, only.

**Expected behavior**
Expected is the data is the same.
 
[AB#8634](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8634)

**Comment by piotrkot** [comment]
Well, the issue could be in the https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token service which for scope "user.read" provides wrong access_token. The access_token which used in https://graph.microsoft.com/v1.0/me fetches wrong  "userPrincipalName" and "displayName" values.

**Comment by thewahome** [comment]
Hello @piotrkot what info do you get? is it possible to paste the difference here?
We call the `https://graph.microsoft.com/v1.0/me` endpoint to get user information. Do you call this too and get different information from what you get using Graph Explorer?
