### ISSUE TITLE
MS Graph Explorer Consent issue - AADSTS90015: Requested query string is too long.

### ISSUE THREAD

**Issue by jodeClarks** [microsoftgraph/microsoft-graph-explorer-v4#897]
**Describe the bug**
In Graph explorer, Modify Permissions (Preview). Toggle selection of all items and click consent I get an error message - AADSTS90015: Requested query string is too long.

**To Reproduce**
1. Login into Graph Explorer
2. Click on 'Modify Permissions (Preview)'
3. Click on 'Consent'
4. AADSTS90015: Requested query string is too long.

**Expected behavior**
Consent to the policy

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [89.0.774.54]

N/A-
**Smartphone (please complete the following information):**

**Additional context**
 
[AB#8637](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8637)

**Comment by ElinorW** [comment]
@jodeClarks 
At the moment, you can only consent to 128 permissions at a time.

**Comment by jodeClarks** [comment]
OK thank you for the information.

Jody Whitefield | IT Service Specialist | Computing
C. & J. Clark International Limited
E-Mail: Jody.Whitefield@Clarks.com<mailto:Jody.Whitefield@Clarks.com>
