### ISSUE TITLE
Use Powershell Variable in Search-AzGraph

### ISSUE THREAD

**Issue by RonnieQuan** [microsoftgraph/microsoft-graph-explorer-v4#898]
Do you have example to use Powershell Variable in Search-AzGraph?  I need to reference variable in the query string.

Thanks! 
[AB#8644](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8644)

**Comment by darrelmiller** [comment]
This PowerShell commandlet is for the Azure Resource Graph, not Microsoft Graph.  https://docs.microsoft.com/en-us/azure/governance/resource-graph/first-query-powershell#:~:text=The%20Azure%20Resource%20Graph%20module%20requires%20the%20following,The%20Resource%20Graph%20module%20for%20PowerShell%20is%20Az.ResourceGraph.
