### ISSUE TITLE
Graph Explorer crashes when you run sample query: POST send channel message

### ISSUE THREAD

**Issue by rabwill** [microsoftgraph/microsoft-graph-explorer-v4#899]
Graph Explorer crashes when you run sample query: POST send channel message

**To Reproduce**
1. Go to graph explorer
2. From the sample queries choose Microsoft Teams > POST send channel message
3. Run the query
4. The explorer crashes and shows nothing

**Expected behavior**
The query runs in the graph explorer and user can see the response/status of response

**Screenshots**
send channel message
![image](https://user-images.githubusercontent.com/20379311/111713040-8a34f680-889a-11eb-9449-74c05ce22ab1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 89.0.774.54 (Official build) (64-bit)

 
[AB#8665](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8665)

**Comment by ElinorW** [comment]
Similar behaviour experienced on issue #892
