### ISSUE TITLE
Access denied when fetching mails of organization users

### ISSUE THREAD

**Issue by rajat-008** [microsoftgraph/microsoft-graph-explorer-v4#900]
**Describe the bug**
Assume the organization is abc.onmicrosoft.com.
After having logged in as a user with Global Administrator and having granted all the required permissions, the following query-
"https://graph.microsoft.com/v1.0/users/some_user@abc.onmicrosoft.com/messages"
The following is the response-
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "Access is denied. Check credentials and try again.",
        "innerError": {
            "date": "2021-03-19T08:10:19",
            "request-id": "ffb0c7bd-8194-4fa4-afa4-22d1af483e2e",
            "client-request-id": "4195b1bc-7d86-9209-1c0b-a71396ccc5cb"
        }
    }
}

**Expected behavior**
Return the messages in the specified users' mailbox.

 
[AB#8670](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8670)

**Comment by ElinorW** [comment]
@rajat-008 
There are two scenarios where an app can get messages in another user's mail folder:

- If the app has application permissions, or,
- If the app has the appropriate delegated permissions from one user, and another user has shared a mail folder with that user, or, has given delegated access to that user

Graph explorer uses **delegated permissions** not application permissions

ref to docs: https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http

**Comment by rajat-008** [comment]
> @rajat-008 
> There are two scenarios where an app can get messages in another user's mail folder:
> 
> - If the app has application permissions, or,
> - If the app has the appropriate delegated permissions from one user, and another user has shared a mail folder with that user, or, has given delegated access to that user
> 
> Graph explorer uses **delegated permissions** not application permissions
> 
> ref to docs: https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http
> 
> 

Thank you. This clarifies a lot with regards to accessing other user's mailbox.
I feel mentioning this in the docs would be a great help for beginners like me.

**Comment by ElinorW** [comment]
@rajat-008 Welcome. 
I will pass on the feedback to the responsible team. Thanks
