### ISSUE TITLE
Immediate crash when selecting "Groups > all groups I belong to (direct or indirect membership) with count"

### ISSUE THREAD

**Issue by AlanMcBee** [microsoftgraph/microsoft-graph-explorer-v4#904]
**Describe the bug**
Clicking the sample query for "all groups I belong to (direct or indirect membership) with count" in the Groups area causes Graph Explorer to completely disappear, forcing a full page refresh to recover.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Sign in using work account
3. Scroll down to Groups and expand, then click "all groups I belong to (direct or indirect membership) with count"
4. Graph Explorer disappears, leaving only the page header and footer.

**Expected behavior**
Same output as you would get if you add "/memberOf" at the end of the URL (full URL should be "https://graph.microsoft.com/v1.0/me/memberOf") and click Run Query

**Screenshots**
![image](https://user-images.githubusercontent.com/37203424/112405331-4c3b3680-8ccf-11eb-89bf-931fa0bb8f7e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 19042.867
 - Browser: Edge (Dev Channel) Version 91.0.831.1 (Official build) dev (64-bit)

 
[AB#8726](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8726)

**Comment by ElinorW** [comment]
similar to #895
