### ISSUE TITLE
Unable to access Assignments using Graph APIs 

### ISSUE THREAD

**Issue by hemanthseshasai** [microsoftgraph/microsoft-graph-explorer-v4#906]
unable to get response form https://graph.microsoft.com/beta/education/classes/{1}/assignment since last night even though i have the consent for EduAssignments.ReadWrite. it is giving me access denied 403 error. any help would be much appreciated

hemanthAnnamraju-7740 asked · 21 hours agoActions

**Comment by hemanthseshasai** [comment]
i have all the required consents as well
![image](https://user-images.githubusercontent.com/81377583/112505099-59fec380-8d84-11eb-8049-fe75e9f4777a.png)

**Comment by millicentachieng** [comment]
Hello @hemanthseshasai

Thank you for reporting your concern. Unfortunately, we in the Graph Explorer team do not have any ownership of the APIs that are causing you issues. If you report this issue in the Microsoft Q&A forum, it will get routed to the appropriate team for them to triage.

https://aka.ms/askgraph
