### ISSUE TITLE
Add a banner for delta links similar to the one for nextlink property

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#913]
When there's a nextlink property, Graph Explorer adds a banner where the user can click and get the link pasted on the url bar. This feature request is to extend this functionality to delta links as well.  
[AB#8782](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8782)

**Comment by thewahome** [comment]
Are there instances where we would expect both or other links to be provided? This would inform whether the task at hand is straight forward or needs for us to rethink the placement of the links

**Comment by bettirosengugi** [comment]
@thewahome i'm afraid I dont understand your question.

**Comment by thewahome** [comment]
@bettirosengugi are there known Graph endpoints that can give us both the `@odata.nextLink` and the `@odata.deltaLink` properties?

**Comment by bettirosengugi** [comment]
at the moment, delta and nextlink are the only links I'm privy to, but will find out if there's more.

**Comment by thewahome** [comment]
@bettirosengugi what are the chances they can both be returned from one query?

**Comment by bettirosengugi** [comment]
@thewahome it's returned in the same query, see this link to docs: https://docs.microsoft.com/en-us/graph/delta-query-overview
