### ISSUE TITLE
Select permissions list has radio buttons instead of checkboxes

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#914]
**Describe the bug**
The Select permissions list should have checkboxes instead of radio buttons. When you select a group of permissions, the radio button and the blue tick disappears till you hover again on the group of permissions. This shouldn't be the experience. 

![image](https://user-images.githubusercontent.com/4668452/113002780-cc074c00-917a-11eb-80c6-8817138ed0e0.png)
 
[AB#8784](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8784)

**Comment by bettirosengugi** [comment]
@thewahome In design, multi-select is depicted by checkboxes while uni-select (I just made up this word ;) ) is depicted by radio buttons. 

Also when you select on the top level, you have to hover to see if the group of permissions is selected, and this is not the expected behaviour.

**Comment by Onokaev** [comment]
#1087
