### ISSUE TITLE
add a version number on Graph Explorer

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#931]
Just to the right of the product name, in medium-grey text, Segoe UI light, size 10. 

Justification:  

it needs to be above the fold; 

It needs to be next to the Product Name; 

It needs to remain persistent throughout the UI, and never move. (checking Version # is not task-dependent)  
[AB#9015](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9015)

**Comment by thewahome** [comment]
Placing this here for safekeeping:
https://stackoverflow.com/a/66966643/7035437
