### ISSUE TITLE
GET all Planner tasks for user does not work with another user from organization

### ISSUE THREAD

**Issue by niamai** [microsoftgraph/microsoft-graph-explorer-v4#933]
I need to get all the tasks assigned to a user in my organization. It only work with my own tasks, but not with a colleague.
I have admin rights and added an API in Azure AD with the action "https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}/planner/tasks" and added all permissions that looked fitting, and granted admin consent, as "Group.Read.All" seemed to not be enough. But it still doesn't work. When running in Graph Explorer, I get a "Forbidden - 403 - 427ms. You need to consent to the permissions on the Modify permissions (Preview) tab", but i already consented.

I want to build a PowerApp with an overview of all tasks of each member in my organization. For that pupose i wanted to the https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}/planner/tasks query in a custom connector, but there seems to be a problem with the permissions.

**Desktop:**
 - Windows 10
 - Chrome
 - Version 89
 
[AB#9058](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9058)

**Comment by thewahome** [comment]
Hello @niamai 
There are two scenarios where an app can get the tasks in another user's account

- If the app has application permissions, or,

- If the app has the appropriate delegated permissions from the one user

Graph explorer uses _delegated permissions_ not application permissions

You will find more details about application and delegated permssions in the documentation here: https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http

**Comment by thewahome** [comment]
Closing this as there was no response after the answer was provided
