### ISSUE TITLE
OneDrive for Business API - Cannot create folder

### ISSUE THREAD

**Issue by ghagnes** [microsoftgraph/microsoft-graph-explorer-v4#934]
I have tried to test the api on creating folder in OneDrive folders by using Graph Explorer.

Method:
Post https://graph.microsoft.com/v1.0/me/drive/items/{itemid}/children
Request Body:
{
    "name": "New 1",
    "folder": {},
    "@microsoft.graph.conflictBehavior": "rename"
}

Request Header:
![image](https://user-images.githubusercontent.com/82920659/115487929-35671000-a28c-11eb-8cb0-7a7a1caaf701.png)

Run Query:
![image](https://user-images.githubusercontent.com/82920659/115487964-4ca5fd80-a28c-11eb-8a2e-ff3adfa9c523.png)
It returns 400 Bad Request with code "invalidRequest".

I have tried to past the {itemid} to the Method:
Post https://graph.microsoft.com/v1.0/me/drive/items/01BTFZRxxxxxxxxxxxxxxxxx/children

It works!.

Would you please check the problem?
I am using Chrome on Windows 10

Thanks.
 
[AB#9096](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9096)

**Comment by thewahome** [comment]
Hi @ghagnes ,
This means that you have to paste the correct id in the {itemId} parameter. Which I see you have done

**Comment by thewahome** [comment]
Closing this as it has been answered. If not satisfactory, please feel free to reopen
