### ISSUE TITLE
unable to access Microsoft Graph Assignment API

### ISSUE THREAD

**Issue by hemanthseshasai** [microsoftgraph/microsoft-graph-explorer-v4#935]
I am having issues accessing Assignment under Education using Microsoft Graphs API giving access denied even though we have gave all the required permissions. noticed that Under Application permission it requires one of the these permissions 
![InkedCapture_LI](https://user-images.githubusercontent.com/81377583/116245485-e7a54880-a760-11eb-91b6-4bf38c638b4e.jpg)

. But under API Permission >  Application Permission  we actually have (EduAssignments.ReadBasic.All, EduAssignments.ReadWriteBasic.All, EduAssignments.Read.All, EduAssignments.ReadWrite.All)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/81377583/116244357-c4c66480-a75f-11eb-8d0b-15b070e25258.png)

 . I am not sure whether this the issue here. Please advise . Thanks 
[AB#9183](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9183)

**Comment by thewahome** [comment]
Hello @hemanthseshasai is this when you try to access using Graph Explorer or another application? Please confirm whether in the case of another application, that it uses Application permissions and not delegated permissions.


This is a link that describes the differences: https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http

**Comment by hemanthseshasai** [comment]
hello @thewahome  i am trying to use these api in a different application. i have given all the required permissions under application permissions it still says Access denied.

**Comment by hguryel** [comment]
> Hello @hemanthseshasai is this when you try to access using Graph Explorer or another application? Please confirm whether in the case of another application, that it uses Application permissions and not delegated permissions.
> 
> This is a link that describes the differences: https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http

Documentation states following permissions required; EduAssignments.ReadBasic, EduAssignments.ReadWriteBasic, EduAssignments.Read, EduAssignments.ReadWrite

But Azure Application - API Permissions under Application Consent, only provides permissions which ends with .All
EduAssignments.ReadBasic.All, EduAssignments.ReadWriteBasic.All, EduAssignments.Read.All, EduAssignments.ReadWrite.All

So there is some sort of discrepancy, but not sure who to contact or talk to to resolve.

**Comment by Onokaev** [comment]
Hey @hemanthseshasai. From Azure portal, it seems the permissions were updated.
![image](https://user-images.githubusercontent.com/45680252/176144854-6db31717-2f72-40f6-887c-70431fe66f20.png)

Are you still experiencing this issue?

**Comment by Onokaev** [comment]
Hey @hemanthseshasai. Can you confirm that your application is using application permissions and not delegated permissions? 
From Azure portal, the application permissions are the ones ending with the .All suffix. Delegated permissions on the other hand do not have this suffix.

For context, when an application is using application permissions, it does not require you to sign in to access resources in your tenant. (The app has to be registered in your tenant and you need to ensure that the application id you are using on application is the same one on Azure portal).

![image](https://user-images.githubusercontent.com/45680252/176149159-4afbed8c-b9b1-435a-acef-dc76abc55306.png)
