### ISSUE TITLE
Capture telemetry data for Graph Explorer preview

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#939]
We have Graph Explorer preview that we plan to use for experimentation, and it would be great to get usage and error telemetry data of it. The preview version of GE is hosted here: https://developer.microsoft.com/en-us/graph/graph-explorer/preview the telemetry data should be displayed on the same dashboard as the main Graph Explorer 
[AB#9282](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9282)

**Comment by millicentachieng** [comment]
This data is available on the GE Telemetry Power BI dashboard
