### ISSUE TITLE
Authentication failed - invalid client

### ISSUE THREAD

**Issue by jonketo** [microsoftgraph/microsoft-graph-explorer-v4#944]
**Describe the bug**
Sign in does not work.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Click on Sign In
3. Authenticate with Enterprise Account
4. Authentication Failed - invalid client error shown between request and response.

**Expected behavior**
I can sign in and send requests to my enterprise tenant.

**Desktop (please complete the following information):**
 - macOS Big Sur 11.2.3
 - Google Chrome Version 90.0.4430.93 (Official Build) (x86_64)

** Additional notes
Both Chrome and Safari failed. Can log in to other properties with Microsoft Accounts. Same credentials and different credentials.
 
[AB#9314](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9314)

**Comment by steamraven** [comment]
Same: Version 90.0.4430.93 (Official Build) (64-bit)
Using government enterprise tenant

**Comment by colonialfootsoldier** [comment]
Same Issue

**Comment by QuackersCoder** [comment]
experiencing same issue, multiple logins attempted, across multiple browsers (chrome, edge), private browsing, clearing cache, multiple tenants. All fail login and  get the same error

**Comment by ASDrew94** [comment]
Experiencing the same problem. 

Error happens with any tenant on different browsers, regardless of account's role.

AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: cbf211bd-205b-45f1-b919-85cbf5e11c00\r\nCorrelation ID: 6c6495ae-21b5-4b1a-bdbf-6c76a7b15390\r\nTimestamp: 2021-05-07 00:54:05Z

Somehow, this has also affected registered applications that query the GraphAPI as well.

Use this for daily production querying in SharePoint. Please revert to stable build.

**Comment by MIchaelMainer** [comment]
I was able to repro and now this has been resolved. Please try signing in again.
