### ISSUE TITLE
Microsoft Graph Explorer hangs using Microsoft Edge and Google Chrome but works with Firefox (in Private mode)

### ISSUE THREAD

**Issue by GenerAhl** [microsoftgraph/microsoft-graph-explorer-v4#945]
**Describe the bug**

I'm trying out the new expedited feature on Windows Updates as described in: [Deploy an expedited security update using the Windows Update for Business deployment service - Microsoft Graph | Microsoft Docs](https://docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update)

When I post the example query from the page, it hangs the Graph Explorer when using Microsoft Edge or Google Chrome. It works when using Firefox in Private mode (despite saying it isn't supported):

**Hangs**: "GET https://graph.microsoft.com/beta/admin/windows/updates/catalog/entries?$top=3&$filter=isof('microsoft.graph.windowsUpdates.qualityUpdateCatalogEntry') and microsoft.graph.windowsUpdates.qualityUpdateCatalogEntry/isExpeditable eq true&$orderby=releaseDateTime desc"

**To Reproduce**

Using Microsoft Edge, navigate to [Graph Explorer - Microsoft Graph](https://developer.microsoft.com/en-us/graph/graph-explorer)
On the top-left of the page, log on to your tenant with "enough privileges" to run queries. This is not a rights-issue so using a GA account is OK
Use the query above from the Docs article up top to query Graph for Windows Updates
Notice that the browser hangs (screenshot added below as "EdgeBug_1.png"
Repeat the process using Firefox successfully completes the query (screenshot added below as "EdgeBug_2.png")
It's tricky to use the F12/Dev tools as the browser hangs but I've fairly reliably discovered that it looks like the JS that hangs the Edge browser is calling this endpoint:
https://web.vortex.data.microsoft.com/collect/v1/t.js?ver='2.1'&name='Ms.Webi.PageAction'&time='2021-05-04T14:17:44.999Z'&os='Windows'&appId='JS:DevCenter'&-ver='1.0'&-impressionGuid='0b7676c5-f6b8-4025-871e-6af631579157'&-pageName='graph/graph-explorer'&-uri='https://developer.microsoft.com/en-us/graph/graph-explorer'&-pageTags='{"metaTags":{"ms.author":"O365devx@microsoft.com","ms.topic":"article","ms.suite":"Microsoft Graph","ms.technology":"microsoft graph","ms.pagename":"graph/graph-explorer"}}'&-contentVer='2.0'&-market='en-us'&-actionType='CL'&-behavior=0&-content='[{}]'&*baseType='Ms.Content.PageAction'&*timeToAction=2164762&*cookieEnabled=true&*isJs=true&*title='Graph Explorer - Microsoft Graph'&*isLoggedIn=false&*referrerUri='https://developer.microsoft.com/en-us/graph'&ext-javascript-ver='1.1'&ext-javascript-libVer='4.3.1'&ext-javascript-domain='developer.microsoft.com'&ext-javascript-userConsent=false&$mscomCookies=false

On Firefox that JS call responds really quickly.

Network timeline attached below as "EdgeBug_3.png"

**Expected behavior**

I would expect Graph Explorer to operate reliably on Microsoft Edge and at least be on-par with Firefox.

It looks like this is hanging because the page is making a network request via XMLHttpRequest (XHR) synchronously. That is, the entire page is waiting for this one network call to complete. This is strongly discouraged because it may cause apparent hangs like this one. Firefox no longer allows synchronous XHR because of this, but Chrome/Edge still support it for legacy reasons. I bet this is also why the site tells me Firefox is not supported.

I suspect that this is a site issue where the page or service trips up on the query and then hangs when the synchronous network call does not return.

**Screenshots**
Screenshot showing a successful query in Firefox Private mode
![image](https://user-images.githubusercontent.com/58516456/117724146-a3478d00-b1e3-11eb-81f3-808f332e3d54.png)

Screenshot showing Edge hanging on the same Graph Explorer query
![image](https://user-images.githubusercontent.com/58516456/117724325-e30e7480-b1e3-11eb-8674-f6c9a0a7930a.png)

Screenshot reference above (EdgeBug_1.png): 
![image](https://user-images.githubusercontent.com/58516456/117724583-413b5780-b1e4-11eb-8074-1df80a6aee93.png)

Screenshot reference above (EdgeBug_2.png): 
![image](https://user-images.githubusercontent.com/58516456/117724663-5d3ef900-b1e4-11eb-98d6-d4ddbba4295d.png)

Screenshot reference above (EdgeBug_3.png): 
![image](https://user-images.githubusercontent.com/58516456/117724701-6d56d880-b1e4-11eb-8b0b-0c0cc4360ea6.png)

**Desktop (please complete the following information):**
Operating system	Windows 10 OS Version 2009 (Build 19042.928)
Microsoft Edge	90.0.818.56 (Official build) (64-bit)
 
[AB#9365](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9365)

**Comment by adhiambovivian** [comment]
@millicentachieng  reach out to portal folks for this one. Thx

**Comment by millicentachieng** [comment]
@[GenerAhl](https://github.com/GenerAhl) This issue has been fixed. Thanks for your patience.
