### ISSUE TITLE
No option to consent to "AuditLog.Read.All" permission when running a query using beta api

### ISSUE THREAD

**Issue by msnnpatel** [microsoftgraph/microsoft-graph-explorer-v4#947]
**Describe the bug**
No option to consent to "AuditLog.Read.All" permission when running a query using beta api. However when using version 1.0 api, I saw option to consent to "AuditLog.Read.All" permission.

**To Reproduce**
1. Ensure your account doesn't already have "AuditLog.Read.All" permission under Graph Explorer app
2. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Run query 'https://graph.microsoft.com/beta/users?$select=displayName,userPrincipalName,signInActivity'
3. You will receive an error - Calling principal does not have required MSGraph permissions AuditLog.Read.All
4. However, there is no option under "Modify permissions (Preview)" Tab to be able to consent for "AuditLog.Read.All" permission.
5. As a workaround, I had to run another API query "https://graph.microsoft.com/v1.0/auditLogs/signIns/Object-Id". After that I saw option to consent under "Modify permissions (Preview)" Tab.

**Expected behavior**
There should be option to consent to "AuditLog.Read.All" permission when using beta api.

**Screenshots**

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
Support case was raised by customer to report this issue.
 
[AB#9461](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9461)

**Comment by ElinorW** [comment]
@msnnpatel 
Currently, with the **Modify permissions (Preview)** tab, some permissions may not be displayed. However, a list of all permissions exists. To view this:
1. Ensure you are **signed in** and navigate to the **More actions** button (located near your authentication details)
![image](https://user-images.githubusercontent.com/18407044/118458291-41b38100-b703-11eb-83e7-fd6123ebc4da.png)
2.  Select the **Select Permissions** menu option.
3. Search for the permission needed, select it and click **Consent**.
![image](https://user-images.githubusercontent.com/18407044/118458777-bf778c80-b703-11eb-84dd-639a9728d675.png)
