### ISSUE TITLE
Users cannot scroll horizontally on the response preview

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#957]
Once you run a query and get the response, if the response properties stretch too far to the right, there's no scroll bar to scroll horizontally which is bad user experience.  
[AB#9513](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9513)

**Comment by ElinorW** [comment]
Hey, @bettirosengugi Could you share an example of a query that displays such behavior?
From what I've seen, the information is wrapped inside the response area, therefore there would be no need to scroll horizontally

**Comment by thewahome** [comment]
A clearer definition of what is bad about the user experience here would help us triage this issue further

**Comment by bettirosengugi** [comment]
@ElinorW try this query: https://graph.microsoft.com/v1.0/servicePrincipals?$count=true&$search="displayName:teams"&$select=id,displayName

**Comment by ddyett** [comment]
i'm assuming here that the user gets all the information so P2.  If the user is not receiving information then P1.
