### ISSUE TITLE
Teams meeting link not generated when creating event using Graph explorer

### ISSUE THREAD

**Issue by pratikKataria** [microsoftgraph/microsoft-graph-explorer-v4#970]
Hello,

I am following the official document and as said if we want to create online Microsoft teams meeting then we have to pass the
following parameters like

"isOnlineMeeting": true,
"onlineMeetingProvider": "teamsForBusiness"

but when I create an event using this actually a skype link is generated.

**REQUEST**

`{
    "subject": "My event",
    "start": {
        "dateTime": "2021-05-30T17:48:08.394Z",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2021-06-06T17:48:08.394Z",
        "timeZone": "UTC"
    },
      "isOnlineMeeting": true,
        "onlineMeetingProvider": "teamsForBusiness"
}`

**Response**

`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('pratikkataria786%40outlook.com')/events/$entity",
    "@odata.etag": "W/\"cJXEB5PCtEOsrNBLpb88QQAAldDDtA==\"",
    "id": "AQMkADAwATNiZmYAZC0zMwA1ZS1hYzQ2LTAwAi0wMAoARgAAA62NIqs4UXZGhpEm4vkLgVsHAHCVxAeTwrRDrKwA0EulvzxBAAACAQ0AAABwlcQHk8K0Q6ysANBLpb88QQAAAJXPvt8AAAA=",
    "createdDateTime": "2021-05-30T17:48:22.5483101Z",
    "lastModifiedDateTime": "2021-05-30T17:48:24.155249Z",
    "changeKey": "cJXEB5PCtEOsrNBLpb88QQAAldDDtA==",
    "categories": [],
    "transactionId": null,
    "originalStartTimeZone": "UTC",
    "originalEndTimeZone": "UTC",
    "iCalUId": "040000008200E00074C5B7101A82E008000000004208DBFB7B55D7010000000000000000100000003A9C2487C6203F49BE575DDF7CD6A7A0",
    "reminderMinutesBeforeStart": 15,
    "isReminderOn": true,
    "hasAttachments": false,
    "subject": "My event",
    "bodyPreview": ".........................................................................................................................................Join online meetinghttps://join.skype.com/IAVJihdfJ7HF........................................................",
    "importance": "normal",
    "sensitivity": "normal",
    "isAllDay": false,
    "isCancelled": false,
    "isOrganizer": true,
    "responseRequested": true,
    "seriesMasterId": null,
    "showAs": "busy",
    "type": "singleInstance",
    "webLink": "https://outlook.live.com/owa/?itemid=AQMkADAwATNiZmYAZC0zMwA1ZS1hYzQ2LTAwAi0wMAoARgAAA62NIqs4UXZGhpEm4vkLgVsHAHCVxAeTwrRDrKwA0EulvzxBAAACAQ0AAABwlcQHk8K0Q6ysANBLpb88QQAAAJXPvt8AAAA%3D&exvsurl=1&path=/calendar/item",
    "onlineMeetingUrl": "https://join.skype.com/IAVJihdfJ7HF",
    "isOnlineMeeting": true,
    "onlineMeetingProvider": "skypeForConsumer",
    "allowNewTimeProposals": true,
    "isDraft": false,
    "hideAttendees": false,
    "recurrence": null,
    "responseStatus": {
        "response": "organizer",
        "time": "0001-01-01T00:00:00Z"
    },
    "body": {
        "contentType": "html",
        "content": "<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><meta name=\"Generator\" content=\"Microsoft Exchange Server\"><style></style></head><body><font size=\"2\"><span style=\"font-size:11pt;\"><div class=\"PlainText\"><br>.........................................................................................................................................<br>Join online meeting<br><a href=\"https://join.skype.com/IAVJihdfJ7HF\">https://join.skype.com/IAVJihdfJ7HF</a><br>.........................................................................................................................................<br></div></span></font></body></html>"
    },
    "start": {
        "dateTime": "2021-05-30T17:48:08.3940000",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2021-06-06T17:48:08.3940000",
        "timeZone": "UTC"
    },
    "location": {
        "displayName": "",
        "locationType": "default",
        "uniqueIdType": "unknown",
        "address": {},
        "coordinates": {}
    },
    "locations": [],
    "attendees": [],
    "organizer": {
        "emailAddress": {
            "name": "Pratik Kataria",
            "address": "pratikKataria786@outlook.com"
        }
    },
    "onlineMeeting": {
        "joinUrl": "https://join.skype.com/IAVJihdfJ7HF"
    }
}`

A small help will be appreciated and helpfull

Thank you in advance 
[AB#9640](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9640)

**Comment by thewahome** [comment]
Hello @pratikKataria 
It looks like you are using a personal account `...@outlook.com` where the meeting is created using **skype**. If you'd like to see how a Teams meeting is created, log in to Graph explorer with a work account.
