### ISSUE TITLE
Hint users to login when they are not getting results

### ISSUE THREAD

**Issue by kaevne** [microsoftgraph/microsoft-graph-explorer-v4#974]
**Is your feature request related to a problem? Please describe.**
Sometimes users will try APIs immediately and get no results.  It's not always clear that they can/need to login on the left-hand side to get "real" data.  Even though it says so on the sample account, there might be some UX optimizations that can be made to make this more intuitive.

**Describe the solution you'd like**
Maybe a hint when no results are received, or when requests are made to APIs outside of the sample's well-known set of responses.  "Hey you can login for real results."  
[AB#9661](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9661)

**Comment by ddyett** [comment]
Betti, do you for a plan on this.

**Comment by Onokaev** [comment]
![image](https://user-images.githubusercontent.com/45680252/143825315-1ebaa906-e02b-4648-8ef7-7124b743fb17.png)

This solves the issue
