### ISSUE TITLE
Graph Explorer not clearing user profile picture on sign out

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/microsoft-graph-explorer-v4#975]
Reported by @MIchaelMainer during the bug bash - I found that if I sign in with user1, then sign out, and then sign sign back in with a different user, the old profile pic is still being used.

Steps to reproduce -
1. Sign in to Graph Explorer with user1
2. Sign out of Graph Explorer using the Graph Explorer Sign Out button. Don't sign out using the identity UI (this might not make a difference.
3. Reopen Graph Explorer and sign in with user2.
4. See user1 profile photo when signed in as user2.

Result - incorrect user profile is shown.

 
[AB#9662](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9662)

**Comment by ddyett** [comment]
perceived security issue.
