### ISSUE TITLE
Url truncation with # character requires encoding

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#979]
**Describe the bug**
Graph Explorer should encode the # character (and likely other permissible characters) as it triggers GE to truncate the resource URL.

**To Reproduce**
1. Open Fiddler and start capturing traffic.
2. Run `GET https://graph.microsoft.com/v1.0/users/Nic#Von@chambele.onmicrosoft.com`
3. Observe `message": "Resource 'Nic' does not exist or one of its queried reference-property objects are not present.",`
4. Observe in Fiddler that the request URL was truncated to `https://graph.microsoft.com/v1.0/users/Nic`
5. Run `GET https://graph.microsoft.com/v1.0/users/Nic%23Von@chambele.onmicrosoft.com`
6. The response will now indicate it can't find the user Nic#Von@chambele.onmicrosoft.com
7. Look in Fiddler and observe that the full URL is sent.

This issue is also present for query parameters:
`https://graph.microsoft.com/v1.0/users?$search="Nic#Von@chambele.onmicrosoft.com"`
The problem here is that in this case, the service is not expecting the encoded character.

**Expected behavior**
URL is encoded and the request URL is not truncated.

cc @nikithauc  
[AB#9745](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9745)

**Comment by thewahome** [comment]
Will confirm whether this is related to #871 

I have noticed that we encode the URL when sending requests to the demo tenant, however we do not encode the URL when sending it through the javascript sdk. @nikithauc what is the risk of sending the encoded URL ?

**Comment by nikithauc** [comment]
@thewahome 

JS SDK does not handle the encoding and the application using the SDK should take care of the encoding.
Can you explain on what type of risk you are thinking about when sending the encoded URL? 

Adding to this issue: 
Recently, a customer reported an issue when encoding # in the URL.  # is encoded as %23
https://graph.microsoft.com/v1.0/users?$count=true&$search=%22displayName:LidiaH^1!%23@M365x283484.OnMicrosoft.com. 

I learnt that v1.0, you will have to double encode the string. this is a limitation of MS Graph. 

the letter # will be encoded as %2523
https://graph.microsoft.com/v1.0/users?$search="displayName:%2523"&$count=true.

**Comment by thewahome** [comment]
> Can you explain on what type of risk you are thinking about when sending the encoded URL?
I wanted to know whether there would be any risk if GE was to encode the string. Possibly if the SDK already encodes. But now it is clear that GE needs to encode the string.



> I learnt that v1.0, you will have to double encode the string. this is a limitation of MS Graph.

Do we double encode the whole URL or just the special # character?

**Comment by nikithauc** [comment]
@thewahome 

> Do we double encode the whole URL or just the special # character? 

Following is an example of # encoding in MGT - https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/1197/files
Only the character is being replaced here. 

This is the only use case that I am aware of. 

However, I would consider the following questions when working on this issue- 
1. What are the characters that require double encoding? 
2. Do we double encode the whole URL or just the special # character?
3. Do all workloads uniformly accept a double encoding URL string? Example -Multiple tests checking if replacing # with %2523 works for different cases. 

@bettirosengugi Do we have a documentation on encoding Graph URLs?
