### ISSUE TITLE
Some response headers are stripped off when you sign in

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#995]
**Describe the bug**

**To Reproduce**
1. Go to Graph Explorer while not signed in, and run a query
2. See the list of response headers listed on the response headers tab
3. Now sign in and run the same query, see the response headers list is shorter
4. that's the error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#9911](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9911)

**Comment by nikithauc** [comment]
@thewahome 

Can you please share the response with the headers that you are getting when you make a request to the Graph API  through the JS SDK?

**Comment by thewahome** [comment]
@nikithauc 

> Can you please share the response with the headers that you are getting when you make a request to the Graph API through the JS SDK?

The headers available are: `cache-control, client-request-id, content-type, request-id`. But I have investigated and found that this is by design.

**Comment by thewahome** [comment]
According to this article on [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers), there are headers that are exposed to the browser by default. They are listed in this article about [CORS-safelisted response header](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header)

> The Access-Control-Expose-Headers response header allows a server to indicate which response headers should be made available to scripts running in the browser, in response to a cross-origin request.

> A CORS-safelisted response header is an HTTP header in a CORS response that it is considered safe to expose to client scripts. Only safelisted response headers are made available to web pages.

The Graph API exposes less headers than the API we hit to get the demo data. This is the reason the headers are less when a user is logged in.

- Graph API exposed headers: 
`Access-Control-Expose-Headers: ETag, Location, Preference-Applied, Content-Range, request-id, client-request-id, ReadWriteConsistencyToken, SdkVersion, WWW-Authenticate`

- Proxy API exposed headers:
`Access-Control-Expose-Headers: Cache-Control, Content-Type, Content-Encoding, Vary, Access-Control-Allow-Origin, Access-Control-Expose-Headers, Strict-Transport-Security, request-id, client-request-id, x-ms-ags-diagnostic, x-ms-resource-unit, OData-Version, X-FE-DATA`

This means it would be possible to get all the response headers through an application that is not running in a browser
