### ISSUE TITLE
Security Alert query does not appear to honor filters

### ISSUE THREAD

**Issue by shawnzzzy** [microsoftgraph/microsoft-graph-explorer-v4#997]
**Describe the bug**
When performing a graph query to get security alerts from the Security and Compliance Center, filter does not appear to be honored.

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
2. Enter this into the query: **https://graph.microsoft.com/v1.0/security/alerts?$filter=Category eq 'ransomware'&$top=5**
3. Scroll down to view the results.
4. You will see that there are not just alerts generated that ransomware, but alerts of all category types.

**Expected behavior**
 I would expect that the results out only show alerts that have a category of ransomware as that is the category I have chosen to filter on. Please feel free to tell me if I am not performing this search correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/43176779/122102112-b3521e00-cdda-11eb-95af-bc760b52ceaa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 91
 
[AB#9918](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9918)

**Comment by millicentachieng** [comment]
Please report issue in the [Microsoft Q&A forum](https://aka.ms/askgraph).
